
<div class="comment" id="c_1713734418">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734418">1</a> by John C. Bland II
		posted on 7/29/2011 at 10:57 PM
		</div>
		<div class="comment_text"><p>The project pages are very responsive now. Good work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734431">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734431">2</a> by Raymond Camden
		posted on 7/29/2011 at 10:59 PM
		</div>
		<div class="comment_text"><p>Thanks. I could tweak it even more - but that would involve - you know - actual work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734432">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734432">3</a> by Nick Harvey
		posted on 7/29/2011 at 11:06 PM
		</div>
		<div class="comment_text"><p>Worth remembering too that the debug template is editable, and can be reprogrammed/augmented to provide the information in a more useful way.</p><p>One thing I like to do is summarize my query times for the whole page in a simple bar chart, that shows how all the queries look relative to one another. In fact I posted a quick post about exactly this a few days ago <a href="http://disq.us/url?url=http%3A%2F%2Fwww.bluemini.com%2F%3Flayout%3Dblog.item%26bumpid%3D650%3A36w0QnZmwhDkQZIzUYUFdbZD9vQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.bluemini.com/?layout=blog.item&amp;bumpid=650">http://www.bluemini.com/?la...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734433">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734433">4</a> by Raymond Camden
		posted on 7/29/2011 at 11:10 PM
		</div>
		<div class="comment_text"><p>Damn good example Nick. The debug template being editable (and you being allowed to write your own) is what allowed ColdFire to be built.</p></div>
	</div>
</div>
		