
<div class="comment" id="c_1713658364">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658364">1</a> by Joshua Curtiss
		posted on 10/19/2006 at 4:35 AM
		</div>
		<div class="comment_text"><p>Here's at least one person who didn't hear about it. Thanks for the link.</p></div>
	</div>
</div>
		