
<div class="comment" id="c_4861054410">
	<div>
		<img src="https://disqus.com/api/users/avatars/dylansather.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4861054410">1</a> by Dylan Sather
		posted on 4/4/2020 at 7:52 PM
		</div>
		<div class="comment_text"><p>Raymond, another great post. Small correction - you reference `$context` in a few places but I believe you mean `$checkpoint`.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4861090951">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4861090951">2</a> (In reply to <a href="#c_4861054410">#1</a>) by Raymond Camden
		posted on 4/4/2020 at 8:25 PM
		</div>
		<div class="comment_text"><p>Doh! Fixed (pushed to GitHub and will take about three minutes to show up). Thank you!</p></div>
	</div>
</div>
		