
<div class="comment" id="c_2535504900">
	<div>
		<img src="https://disqus.com/api/users/avatars/edm00se.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2535504900">1</a> by Eric McCormick
		posted on 2/25/2016 at 10:13 PM
		</div>
		<div class="comment_text"><p>A nice and simplistic approach. I may add it to my blog, thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2535509219">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2535509219">2</a> (In reply to <a href="#c_2535504900">#1</a>) by Raymond Camden
		posted on 2/25/2016 at 10:15 PM
		</div>
		<div class="comment_text"><p>You are most welcome.</p></div>
	</div>
</div>
		