
<div class="comment" id="c_1713734812">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734812">1</a> by John Farrar
		posted on 8/26/2011 at 10:10 PM
		</div>
		<div class="comment_text"><p>Sweet, nice to see more Custom Tag content used where it should be. There was a day we missed the target and used them too much. This is a great use case of the right way to do it and a great blog post. Keep up the awesomeness Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734815">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734815">2</a> by Jaana Gilbert
		posted on 8/26/2011 at 10:27 PM
		</div>
		<div class="comment_text"><p>I love it! Can't make a page creation any easier than that :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734816">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734816">3</a> by Connor Middleton
		posted on 8/27/2011 at 12:12 AM
		</div>
		<div class="comment_text"><p>This is pretty sweet Ray. I'll probably put this to use on a project I am just spooling up. Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734814">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734814">4</a> by David McGraw
		posted on 8/27/2011 at 12:26 AM
		</div>
		<div class="comment_text"><p>Interesting take, and cool routine.  Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734819">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734819">5</a> by Phillip Senn
		posted on 8/27/2011 at 5:43 AM
		</div>
		<div class="comment_text"><p>What could be next?  A Dreamweaver template?  Just kidding.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734820">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734820">6</a> by Misty
		posted on 1/31/2012 at 12:41 PM
		</div>
		<div class="comment_text"><p>Hi ray, Good post.</p><p>My Question here is</p><p>1. Can I cfinclude the templates in the pages - i think i can<br>2. Is the new way to write jquery mobile applications pertaining to their own attaibute usage like ui-hidden-theme classes or data-role="something"</p><p>3. silly question but let me ask -  can i add my application.cfm or application.cfc - i think i can</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734818">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734818">7</a> by Raymond Camden
		posted on 1/31/2012 at 5:35 PM
		</div>
		<div class="comment_text"><p>1) Um, well yeah, thats kinda the point. ;) You aren't cfincluding it though, you are using it as a custom tag.</p><p>2) No idea at all what you mean here.</p><p>3) Yes.</p></div>
	</div>
</div>
		