
<div class="comment" id="c_1713743076">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743076">1</a> by Mikel
		posted on 10/1/2012 at 3:47 PM
		</div>
		<div class="comment_text"><p>Thanks for coming to visit NC and for the great presentations!  I think I'll have to do some tinkering with websockets.  It seems like there is really a lot of potential there to make some really cool stuff!</p></div>
	</div>
</div>
		