
<div class="comment" id="c_1713661367">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661367">1</a> by Leif
		posted on 1/22/2007 at 9:40 PM
		</div>
		<div class="comment_text"><p>Although it might not be proper, I've put information like that into the Model. That way you can retrieve that string from anywhere.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661360">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661360">2</a> by Ben
		posted on 1/24/2007 at 8:33 PM
		</div>
		<div class="comment_text"><p>The docs recommend using Application.application.parameters. That way its accessible from anywhere.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661373">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661373">3</a> by Raymond Camden
		posted on 1/24/2007 at 8:39 PM
		</div>
		<div class="comment_text"><p>Thanks Ben. I knew there must have been _some_ global api for it.</p></div>
	</div>
</div>
		