
<div class="comment" id="c_2029448451">
	<div>
		<img src="https://disqus.com/api/users/avatars/bobclingan.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2029448451">1</a> by Bob Clingan
		posted on 5/17/2015 at 12:27 AM
		</div>
		<div class="comment_text"><p>I missed your ORA presentation and would like to check it out. When I go to the link you provided, I couldn't figure out how to view it.. am I missing something?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2030093818">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2030093818">2</a> (In reply to <a href="#c_2029448451">#1</a>) by Raymond Camden
		posted on 5/17/2015 at 1:39 PM
		</div>
		<div class="comment_text"><p>You are absolutely right. I'll ping my contact.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2031601927">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2031601927">3</a> (In reply to <a href="#c_2029448451">#1</a>) by Raymond Camden
		posted on 5/18/2015 at 10:59 AM
		</div>
		<div class="comment_text"><p>So you have to register on the site, go back to the URL, and ensure you shift+reload (I had to in Firefox). And then it should show up.</p></div>
	</div>
</div>
		