
<div class="comment" id="c_4981843419">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4981843419">1</a> by Ben
		posted on 7/6/2020 at 7:11 PM
		</div>
		<div class="comment_text"><p>Great article! Just in the example JS code, your API key "HERE_KEY", is exposed and others could use it without your permission - wondering if that was intentional/ok by you?</p></div>
	</div>
</div>
		
<div class="comment" id="c_4981846719">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4981846719">2</a> (In reply to <a href="#c_4981843419">#1</a>) by Raymond Camden
		posted on 7/6/2020 at 7:14 PM
		</div>
		<div class="comment_text"><p>Ah good catch. So I work for HERE and don't really care if my key gets out. Also, we let you limit a key to a domain, so it is safe to have a key in source and know it can't be abused.</p><p>However - that being said - Netlify makes it easy to setup and use environment variables, so it would be better if I had done that for the key.</p><p>Thank you!</p></div>
	</div>
</div>
		