
<div class="comment" id="c_1713614550">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614550">1</a> by Hilary Bridel
		posted on 4/13/2003 at 3:51 PM
		</div>
		<div class="comment_text"><p>Hi Ray,<br>The URL to your Blog zip file is incorrect.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614542">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614542">2</a> by Raymond Camden
		posted on 4/14/2003 at 12:27 AM
		</div>
		<div class="comment_text"><p>Fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614536">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614536">3</a> by Angelo McComis
		posted on 4/15/2003 at 9:38 PM
		</div>
		<div class="comment_text"><p>Hi Ray - Regarding the blog code, great stuff, except it''s not usable since it is distrubted sans application.cfm and the admin tool. Any word on when / if you''ll distribute those?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614546">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614546">4</a> by Raymond Camden
		posted on 4/15/2003 at 9:43 PM
		</div>
		<div class="comment_text"><p>The application.cfm just has stuff specific for the blog client - most of the work however is done in the CFC. Anyway, I''ll make sure the next zip contains the App.cfm file. As for the admin - my admin tool is meant to be used inside my main site admin - I''ll include it - but the formatting will be a bit off, stuff won''t be in context, etc.  You get the idea. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614537">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614537">5</a> by Angelo McComis
		posted on 4/15/2003 at 10:04 PM
		</div>
		<div class="comment_text"><p>Thanks, Ray.</p><p>Angelo</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614540">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614540">6</a> by Mike Kollen
		posted on 4/16/2003 at 1:49 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>I added my own Application.cfm pretty easily, then proceeded to create my own Admin.  Also, I incorporated the Ektron tool for adding HTML and images easily inline the browser. I would be happy to make this available for others to download.  I have written a custom tag for the calendar before on a couple of apps, but if you could make this available that would be cool.  I would like to see how you did you Admin as well, to compare notes.</p><p>My Intro. to MS SQL course used your .sql file for importing the blog tables.  I was showing how to import an external application table structure into their RDBD using the Query Analyzer. I also demoed blogging app. using CFCs.  It was a hit!  Do you mind if I give out to the class?</p><p>Regards,</p><p>Mike Kollen</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614533">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614533">7</a> by Raymond Camden
		posted on 4/16/2003 at 1:52 PM
		</div>
		<div class="comment_text"><p>I certainly don''t mind if you share, just remember that I do NOT consider myself a DBA - so my table structure may not be ''best practices.'' Certainly here I kinda did things rushed as well. But if it works for you, that''s great. :) Your admin sounds a lot more complex then mine, but I''ll definetely include it in the next zip. (The next zip will include a maxN type feature for getEntries.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614544">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614544">8</a> by Peter Tilbrook
		posted on 5/11/2003 at 6:45 AM
		</div>
		<div class="comment_text"><p>Site doesn''t fit in an 800x600 screen resolution. Makes it a bit difficult when your crappy hardware can''t cope.</p></div>
	</div>
</div>
		