
<div class="comment" id="c_1713664717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664717">1</a> by Anthony
		posted on 5/5/2007 at 12:44 AM
		</div>
		<div class="comment_text"><p>Below?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664722">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664722">2</a> by Raymond Camden
		posted on 5/5/2007 at 1:18 AM
		</div>
		<div class="comment_text"><p>Fixed. Sorry!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664723">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664723">3</a> by Ryan
		posted on 5/5/2007 at 3:03 AM
		</div>
		<div class="comment_text"><p>Great presentation, Ray! Started using Spry a few weeks ago myself and am really liking it. Now, I might just have to give this whole Model-Glue thing a looking in to!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664721">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664721">4</a> by Adam Ness
		posted on 5/5/2007 at 9:17 PM
		</div>
		<div class="comment_text"><p>I might be blind, but can you put a link to ColdFire up somewhere?  You demoed it and it looked really cool, but it wasn't working.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664724">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664724">5</a> by Raymond Camden
		posted on 5/5/2007 at 10:32 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fcoldfire.riaforge.org%3AttgthkBHkP8J3HrcB1YFu2h7MO4&amp;cuid=3321886" rel="nofollow noopener" title="http://coldfire.riaforge.org">http://coldfire.riaforge.org</a></p></div>
	</div>
</div>
		