
<div class="comment" id="c_1713668812">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668812">1</a> by Ben Nadel
		posted on 7/20/2007 at 5:28 PM
		</div>
		<div class="comment_text"><p>Nice! That's like some crazy Jedi mind tricks :)</p><p>It bothers me that this only works for .CFM pages, but still, very cool.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668802">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668802">2</a> by Dan G. Switzer, II
		posted on 7/20/2007 at 5:33 PM
		</div>
		<div class="comment_text"><p>Did you hear Paris Hilton started a new web site after getting out of Jail?</p><p>It's called <a href="http://disq.us/url?url=http%3A%2F%2FParisite.com%3AUeX-cSujf-z8SwgxR9eldq92Kcs&amp;cuid=3321886" rel="nofollow noopener" title="Parisite.com">Parisite.com</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668810">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668810">3</a> by Gary Gilbert
		posted on 7/20/2007 at 6:04 PM
		</div>
		<div class="comment_text"><p>It is amazing how many sites don't provide for a missing template handler or site wide errorhandling, as Ray says it isn't a big effort to include either, it's just plain laziness.</p><p>I have see quite a few websites that display ugly extensive errors when something a bit more end-user friendly should be displayed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668811">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668811">4</a> by duncan
		posted on 7/20/2007 at 6:22 PM
		</div>
		<div class="comment_text"><p>"It is amazing how many sites don't provide for a missing template handler or site wide errorhandling, as Ray says it isn't a big effort to include either, it's just plain laziness."</p><p>er, <br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.garyrgilbert.com%2Fparishiltonisfetch.cfm%3AjcMi2u4vGFW1mmmTS81hydnZCjU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.garyrgilbert.com/parishiltonisfetch.cfm">http://www.garyrgilbert.com...</a><br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Fparishiltonisfetch.cfm%3AHjrdTPLvKeyIZnieA0PNN13j1kw&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/parishiltonisfetch.cfm">http://www.coldfusionjedi.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668815">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668815">5</a> by Todd Rafferty
		posted on 7/20/2007 at 6:57 PM
		</div>
		<div class="comment_text"><p>@duncan: Zing!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668813">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668813">6</a> by Raymond Camden
		posted on 7/20/2007 at 7:13 PM
		</div>
		<div class="comment_text"><p>Heh, I'm as perfect as anyone else. As for my blog - it uses App.cfm, not App.cfc. BlogCFC 6 may be supporting both though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668814">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668814">7</a> by Geoff
		posted on 7/20/2007 at 10:02 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>You've got a 302 redirect in there still...<br>So you're saying "The parishiltonfetch.cfm page *does* exist, but is temporarily elsewhere" then you get the 404 for the "elsewhere" page...</p><p>Can you make the cflocation into a 301 redirect?</p><p>Or better still, can you not cfinclude your 404.cfm page directly from within onMissingTemplate? That way you'd avoid the "302 moved temporarily" redirect? - the 404 would then apply to "parishiltonfetch.cfm" not to "404.cfm?thepage=%2Fparishiltonfetch%2Ecfm"</p><p>Try this:<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.seoconsultants.com%2Ftools%2Fheaders%2F%3AIpJJ1zQSLe1tfs_3lWwNMqzQ-oQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.seoconsultants.com/tools/headers/">http://www.seoconsultants.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668818">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668818">8</a> by Raymond Camden
		posted on 7/20/2007 at 10:10 PM
		</div>
		<div class="comment_text"><p>Yep. ColdFusion 8 added the ability to add status headers to cflocation. I will do that right now. (But zip will be a bit later this week.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668816">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668816">9</a> by Geoff
		posted on 7/20/2007 at 10:34 PM
		</div>
		<div class="comment_text"><p>Sorry about this Ray - I reckon you need another change:</p><p>&lt;cfif not len(trim(url.thePage))&gt;<br>   &lt;cflocation url="index.cfm" addToken="false"&gt;<br>&lt;/cfif&gt;</p><p>should be:</p><p>&lt;cfif not len(trim(url.thePage))&gt;<br>   &lt;cfheader statuscode="404" statustext="Not Found"&gt;<br>   &lt;cfabort&gt;<br>&lt;/cfif&gt;</p><p>Just my 2 cents - can you tell I hate &lt;cflocation&gt; ?? ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668817">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668817">10</a> by Raymond Camden
		posted on 7/20/2007 at 10:36 PM
		</div>
		<div class="comment_text"><p>You can't add the text, just the code.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668819">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668819">11</a> by Raymond Camden
		posted on 7/20/2007 at 10:36 PM
		</div>
		<div class="comment_text"><p>Oh wait - you mean on the 404 page. That cflocation was meant to just stop people from hitting 404 directly. I think I'm ok with that. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668822">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668822">12</a> by errorik
		posted on 7/21/2007 at 1:19 AM
		</div>
		<div class="comment_text"><p>ColdFusion 404 handlers are only half the battle:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionbloggers.org%2Fparishiltonisfetch%2F%3AJEGqwBcoTcd04erqcG2L5Wbmo78&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionbloggers.org/parishiltonisfetch/">http://www.coldfusionblogge...</a></p><p>Nice default IIS page.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668829">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668829">13</a> by Raymond Camden
		posted on 7/21/2007 at 1:26 AM
		</div>
		<div class="comment_text"><p>You guys got too much time on your hands. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668821">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668821">14</a> by Geoff
		posted on 7/23/2007 at 5:35 PM
		</div>
		<div class="comment_text"><p>I've been playing with onMissingTemplate, and I reckon this would be better:</p><p>&lt;cffunction name="onMissingTemplate" returnType="boolean" output="true"&gt;<br>&lt;cfargument name="thePage" type="string" required="true" /&gt;<br>&lt;cfset somevariable=thepageyoutriedtoget /&gt;<br>&lt;cfinclude template="404.cfm" /&gt;<br>&lt;cfreturn true /&gt;<br>&lt;/cffunction&gt;</p><p>Using this cfinclude method, I'm not redirecting (302 or 301) then serving a 404, hence the 404 will apply to the page you tried to get, not to the 404.cfm page itself...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668826">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668826">15</a> by Raymond Camden
		posted on 7/23/2007 at 5:39 PM
		</div>
		<div class="comment_text"><p>I think you might be right. I'll see about updating the code this week.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668823">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668823">16</a> by Ben
		posted on 1/3/2008 at 2:34 AM
		</div>
		<div class="comment_text"><p>xss-able.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionbloggers.org%2F404.cfm%3Fthepage%3D%27%3Balert%28String.fromCharCode%2888%2C83%2C83%29%29%2F%2F%3Avnsi8Y3U_qjNz7n5lOyyJBEf6kI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionbloggers.org/404.cfm?thepage=';alert(String.fromCharCode(88,83,83))//">http://www.coldfusionblogge...</a>\';alert(String.fromCharCode(88,83,83))//%22;alert(String.fromCharCode(88,83,83))//\%22;alert(String.fromCharCode(88,83,83))//--%3E%3C/SCRIPT%3E%22%3E'%3E%3CSCRIPT%3Ealert(String.fromCharCode(88,83,83))%3C/SCRIPT%3E</p><p>Not a big problem, but should be fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668831">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668831">17</a> by Raymond Camden
		posted on 1/3/2008 at 2:38 AM
		</div>
		<div class="comment_text"><p>Wow, I tend to be pretty anal about that. Good catch. It is fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668824">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668824">18</a> by Edward Beckett
		posted on 4/14/2008 at 2:27 AM
		</div>
		<div class="comment_text"><p>Ray ... how's this look ...</p><p>  &lt;cffunction name="onMissingTemplate" returnType="boolean" output="true"&gt;<br>  &lt;cfargument name="targetPage" type="string" required="true" /&gt;<br>   &lt;cftry&gt;<br>     &lt;cflog type="error" text="Missing template: #Arguments.targetPage#"&gt;<br>      &lt;cfinclude template="404.cfm" /&gt;<br>    &lt;cfreturn true /&gt;<br>      &lt;cfcatch&gt;<br>        &lt;cfreturn false /&gt;<br>      &lt;/cfcatch&gt;<br>    &lt;/cftry&gt;<br>  &lt;/cffunction&gt;<br>&lt;/cfcomponent&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668828">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668828">19</a> by Raymond Camden
		posted on 4/14/2008 at 6:23 PM
		</div>
		<div class="comment_text"><p>Edward - are you asking how it looks in general? It seems fine to me. Not sure why you have a try catch though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668820">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668820">20</a> by Edward Beckett
		posted on 4/14/2008 at 8:09 PM
		</div>
		<div class="comment_text"><p>"Not sure why you have a try catch though ..."</p><p>I like pointless code :-&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668808">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668808">21</a> by Edward Beckett
		posted on 4/19/2008 at 4:06 PM
		</div>
		<div class="comment_text"><p>Okay ... now another problem exists ....</p><p>For some reason I am getting an error thrown by the onMissingTemplate function for my 404 page ... request was not of type boolean ... very strange ... here's what I came up with as a slight change to Geoff's code ...</p><p>  &lt;cffunction name="onMissingTemplate" returnType="void" output="true"&gt;<br>    &lt;cfargument name="targetPage" type="string" required="true" /&gt;<br>	    &lt;cflog type="error" text="Missing template: #Arguments.targetPage#"&gt;<br>    &lt;cfinclude template="404.cfm" /&gt;<br>  &lt;/cffunction&gt;</p><p>However, when I changed the retrunType to void ... there is no problem ...</p><p>Any reason why an error would be thrown from the return type being set as boolean?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668807">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668807">22</a> by Raymond Camden
		posted on 4/19/2008 at 4:20 PM
		</div>
		<div class="comment_text"><p>Well sure, Edward. If you ahd returnType="boolean" and you didn't do cfreturn true, then this error would occur. Your returntype has to match with how you end the func - whether it is App.cfc, any other CFC, or a tag based UDF.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668805">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668805">23</a> by Edward Beckett
		posted on 4/19/2008 at 6:09 PM
		</div>
		<div class="comment_text"><p>I shall be heading over to Amazon now ...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668835">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668835">24</a> by Raymond Camden
		posted on 4/19/2008 at 6:23 PM
		</div>
		<div class="comment_text"><p>Specifically on App.cfc, there are rules for what you should return. Look at my app.cfc template on the left. These rules apply to _how_ your app acts based on the return. So for example, if you return false in onRequestStart, you are basically aborting the request (I think it throws an error too - not sure).</p><p>So to be clear you have 2 things here:</p><p>a) First is the returnType must match rule, which applies _everywhere_<br>b) Second is the application behavior depeneding on what you do in the method</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668833">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668833">25</a> by Edward Beckett
		posted on 4/19/2008 at 6:43 PM
		</div>
		<div class="comment_text"><p>Thanks Ray!</p><p>One step forward ...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668834">26</a> by Johan
		posted on 4/27/2008 at 3:39 AM
		</div>
		<div class="comment_text"><p>Just a note about earlier code that used cflocation that the CF8 documentation states specifically that: To include the contents of a page in the onMissingTemplate function, use the cfinclude tag. Do not use any other method to include or redirect other page content, including tags and functions such as cflocation,<br>GetPageContext().forward(), and GetPageContext().include().</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668836">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668836">27</a> by Raymond Camden
		posted on 4/27/2008 at 5:03 PM
		</div>
		<div class="comment_text"><p>Thats interesting. As I said in reply to your other comment, I think this may be a mistake. The only reason I can see against doing a cflocate is to prevent accidental infinite looping by cflocating to a page that doesn't exist.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668837">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668837">28</a> by Johan
		posted on 4/27/2008 at 11:56 PM
		</div>
		<div class="comment_text"><p>Thanks Ray - sorry for the cross-post/comment. Agree on the endless loop. My testing seemed fine.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668838">29</a> by phive
		posted on 9/21/2008 at 8:17 PM
		</div>
		<div class="comment_text"><p>First time poster, long time reader ;-)</p><p>A recommended change would be to add a proceeding slash to the URL location:</p><p>&lt;cflocation url="/404.cfm?thepage=#urlEncodedFormat(arguments.thePage)#" addToken="false"&gt;</p><p>So should someone really go wrong and type in "<a href="http://disq.us/url?url=http%3A%2F%2Fwww.foo.com%2Ffolder%2Fwhat%2Fhuh.cfm%3AFhTD4QSK46OGV8kQuXN6t_GM0JU&amp;cuid=3321886" rel="nofollow noopener" title="www.foo.com/folder/what/huh.cfm">www.foo.com/folder/what/huh...</a>"; we'll redirect to the root file.</p><p>Thanks for your knowledge sharing, you've helped me out of a few jams in the past!</p><p>Phive.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668841">30</a> by Doug
		posted on 8/20/2009 at 5:29 PM
		</div>
		<div class="comment_text"><p>Interesting thing I discovered today on this issue:  If you don't use &lt;cfinclude&gt; or &lt;cflocation&gt; and have the onMissingTemplate method return false, CF will default to the 404 page you defined in the CFIDE administrator settings. Returning false means that the correct status of 404 will be sent in the http response headers.</p><p>Thus my onMissingTemplate simply has a &lt;cflog&gt; followed by &lt;cfreturn false /&gt;.   No more, no less.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668846">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668846">31</a> by Jose Galdamez
		posted on 9/16/2009 at 3:31 AM
		</div>
		<div class="comment_text"><p>How do you guys know which status code is being returned by the server?</p><p>I want to implement OnMissingTemplate(), but I don't want to return a 404. It looks like cfheader will take care of the status code for me, but I need to be able to test that it's working somehow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668842">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668842">32</a> by Raymond Camden
		posted on 9/16/2009 at 6:02 AM
		</div>
		<div class="comment_text"><p>Have you tested yourself - to see what the status is?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668844">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668844">33</a> by Jose Galdamez
		posted on 9/16/2009 at 6:38 AM
		</div>
		<div class="comment_text"><p>Never mind.</p><p>The Web Developer plug-in for Firefox has an option to View Response Headers under the Information menu. My quick test yields a "200 OK", which is pretty much what I was expecting. Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668849">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668849">34</a> by Jay Greer
		posted on 6/20/2010 at 8:51 PM
		</div>
		<div class="comment_text"><p>Little late to the party here but shouldn't you be sending a "404 not found" via cfheader before you cfinclude your missing template handler..? That way you avoid getting "200 OK" for a non-existent page... no?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668843">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668843">35</a> by Raymond Camden
		posted on 6/23/2010 at 1:34 AM
		</div>
		<div class="comment_text"><p>Sure - that would make sense.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668845">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668845">36</a> by Eric Belair
		posted on 8/29/2011 at 11:31 PM
		</div>
		<div class="comment_text"><p>How can I get my onMissingTemplate handler to catch Page Not Found errors that occur when the query string begins with an ampersand:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fmysite.com%2Findex.cfm%26x%3D1%3ATcdDWXwYCGDlAaATMoZ-4S1eytE&amp;cuid=3321886" rel="nofollow noopener" title="http://mysite.com/index.cfm&amp;x=1">http://mysite.com/index.cfm...</a></p><p>Even with a working onMissingTemplate handler, these are not caught. Is a Custom Error Handler in IIS the only solution?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668847">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668847">37</a> by Raymond Camden
		posted on 8/29/2011 at 11:33 PM
		</div>
		<div class="comment_text"><p>That's not a valid URL. URLs must have ? in them before anything after the file name.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668848">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668848">38</a> by Eric Belair
		posted on 8/29/2011 at 11:39 PM
		</div>
		<div class="comment_text"><p>Ok, I just thought there might be a way to catch it, since it throws a Page Not Found exception. Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668851">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668851">39</a> by Raymond Camden
		posted on 8/29/2011 at 11:43 PM
		</div>
		<div class="comment_text"><p>It might be web server dependent.</p></div>
	</div>
</div>
		