
<div class="comment" id="c_1713654822">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654822">1</a> by Nathan Dintenfass
		posted on 7/8/2006 at 1:54 AM
		</div>
		<div class="comment_text"><p>Have you thought about using Upcoming or something similar, so your calendar can be RSSified and such?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654833">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654833">2</a> by Raymond Camden
		posted on 7/8/2006 at 2:04 AM
		</div>
		<div class="comment_text"><p>I'm actually going to use Google Calendar, since I already have code to download and parse it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654831">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654831">3</a> by Teddy R Payne
		posted on 7/8/2006 at 2:33 AM
		</div>
		<div class="comment_text"><p>Ray,<br>Has any approached you for speaking in Atlanta?  I would definitely enjoy suggestion you to the board here for a fall speaker.  We can make sure to hit up Dave and Buster's for some steak rolls!</p><p>Cheers</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654834">4</a> by Derek P.
		posted on 7/8/2006 at 10:14 AM
		</div>
		<div class="comment_text"><p>BACFUG will always have you :)! Come visit the original Macromedia in lovely San Francisco California! Townsend street yay!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654829">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654829">5</a> by Raymond Camden
		posted on 7/8/2006 at 3:15 PM
		</div>
		<div class="comment_text"><p>Teddy, Derek, the offer was for remote speaking, unless you want to fly me up. ;) Shoot me an email though as it will be easier to talk that way.</p></div>
	</div>
</div>
		