
<div class="comment" id="c_1713709492">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709492">1</a> by Adam Tuttle
		posted on 10/31/2008 at 6:53 PM
		</div>
		<div class="comment_text"><p>PHP would have been much scarier!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709505">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709505">2</a> by Dave Hill
		posted on 10/31/2008 at 7:38 PM
		</div>
		<div class="comment_text"><p>Somewhere in a basement there could be someone carving a pumkin with the word....Fortran.... very scary!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709480">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709480">3</a> by Phillip Senn
		posted on 10/31/2008 at 10:30 PM
		</div>
		<div class="comment_text"><p>What?  No brackets?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709506">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709506">4</a> by Phillip Senn
		posted on 11/1/2008 at 5:51 AM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fjquery.com%2Fblog%2F2008%2F10%2F28%2Fjquery-pumpkin%3A5AVGBvOOBl2aOX4dGFQCCqbZBZw&amp;cuid=3321886" rel="nofollow noopener" title="http://jquery.com/blog/2008/10/28/jquery-pumpkin">http://jquery.com/blog/2008...</a></p></div>
	</div>
</div>
		