
<div class="comment" id="c_1713709987">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709987">1</a> by Dan Vega
		posted on 11/18/2008 at 10:27 PM
		</div>
		<div class="comment_text"><p>Finally another Anchor Steam fan, love it!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709972">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709972">2</a> by Rob Wilkerson
		posted on 11/19/2008 at 5:55 PM
		</div>
		<div class="comment_text"><p>Re: Anchor Steam</p><p>Very good beer that's _outstanding_ on draft. The only place I've ever seen it on draft is in SF, sadly.</p></div>
	</div>
</div>
		