
<div class="comment" id="c_1713620594">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620594">1</a> by Britt
		posted on 9/3/2005 at 3:07 AM
		</div>
		<div class="comment_text"><p>Don't know if you have a flash detection script going on, but when I get to the landing page, it gives me a prompt to upgrade to the newest flash player, or to view the html site.  Is the site supposed to forward you to the appropriate content? or make you choose?  I've got beta FP8 installed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620595">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620595">2</a> by Raymond Camden
		posted on 9/3/2005 at 5:23 AM
		</div>
		<div class="comment_text"><p>FP8 _should_ let you through. I uninstalled FP8 about a week ago, but it was working before. What browser were you using, IE or Firefox? Oh wait - was it Mozilla perhaps?</p></div>
	</div>
</div>
		