
<div class="comment" id="c_1713615054">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615054">1</a> by Ryan
		posted on 11/3/2003 at 9:23 PM
		</div>
		<div class="comment_text"><p>I experienced the same problem with Central installing and dying, but for my initial install on one computer.  I had to forcibly close the install via the application manager.  Not good.</p><p>I'm also slightly annoyed with the way Central disconnects (or appears to) my session in the Central Dev Chat application if I switch over to one of the other Central programs I have installed.  This is probably a function of how the Chat was coded, but may be a limitiation of version 1 of Central.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615053">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615053">2</a> by John Dowdell
		posted on 11/3/2003 at 10:02 PM
		</div>
		<div class="comment_text"><p>Sorry for the hassle, but good catch... could I ask you to drop a note to the &lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.macromedia.com%2Fsupport%2Femail%2Fwishform%2F%3F6213%3D32%3ArtPu2e6OYxqP5DBXkbVmKP6kddM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.macromedia.com/support/email/wishform/?6213=32">http://www.macromedia.com/s...</a>"&gt;feedback page&lt;/a&gt; to be sure this gets logged by the team, please? Thanks!</p><p>jd/mm</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615059">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615059">3</a> by Raymond Camden
		posted on 11/3/2003 at 10:08 PM
		</div>
		<div class="comment_text"><p>Done, and let me be the first to say, to bitch about a product and _not_ make a bug report is bad form! Sorry about that. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615061">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615061">4</a> by Ryan
		posted on 11/4/2003 at 4:52 AM
		</div>
		<div class="comment_text"><p>I just posted the two bugs above.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615060">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615060">5</a> by robby
		posted on 11/4/2003 at 5:30 AM
		</div>
		<div class="comment_text"><p>Just thought I would add a few for public consumption.<br>The ability for apps to resize (or central itself between tabbing apps) my window.</p><p>If I want it full screen, and choose another app I'd like to still have full screen. Not get the window jarred.</p><p>And a way to move the 'pods' into the main window (docking or similar) would be great as well, I like the app, it has a 'neat' factor. But I'd rather not deal with two windows/tabs to 'support' it.</p><p>And yeah I've sent all of the above into the wishform.</p><p>Robby</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615057">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615057">6</a> by mike chambers
		posted on 11/4/2003 at 11:20 PM
		</div>
		<div class="comment_text"><p>&gt;I'm also slightly annoyed with the way Central disconnects (or appears to) my session in the Central Dev Chat application if I switch over to one of the other Central programs I have installed. This is probably a function of how the Chat was coded, but may be a limitiation of version 1 of Central.</p><p>Yes, this is not an issue with Central but with how the app was built. The next version will keep you connected when you switch apps.</p><p>mike chambers</p><p>mesh@macromedia.com</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615066">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615066">7</a> by mike chambers
		posted on 11/4/2003 at 11:21 PM
		</div>
		<div class="comment_text"><p>&gt;And a way to move the 'pods' into the main window (docking or similar) would be great as well, I like the app, it has a 'neat' factor. But I'd rather not deal with two windows/tabs to 'support' it.</p><p>Yes. You can develop apps that would allow you to do this.</p><p>mike chambers</p><p>mesh@macromedia.com</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615065">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615065">8</a> by robby
		posted on 11/5/2003 at 3:43 AM
		</div>
		<div class="comment_text"><p>&gt;Yes. You can develop apps that would allow you to do this.</p><p>I was referring to the user experience. My windows, my control, one app, 'option' for one window vs managing two.</p></div>
	</div>
</div>
		