
<div class="comment" id="c_1713618720">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618720">1</a> by Peter Tilbrook
		posted on 6/14/2005 at 7:19 AM
		</div>
		<div class="comment_text"><p>LOL! Look at ICQ (I Seek You) - still in beta after years!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618721">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618721">2</a> by Ryan
		posted on 6/14/2005 at 11:29 AM
		</div>
		<div class="comment_text"><p>I suspect that the whole Beta thing has gotten taken over by marketing/sales departments to some extent.</p><p>For instance, Microsoft used to have betas, now they have CTP (community technology previews), etc.  I think MM has tried a similar tactic to hide the number of betas out there.  I'd much prefer if the makers would just make new betas more often and name them the same thing with a # or date after each to signify the sequence.  Why do we need Beta 1, beta 1 updates, updaters, fixes, CTP, etc.</p><p>So much for a naming convention.</p><p>As for the Gmail betas and such...well, it is a great way to get a product out, create FUD (fear, uncertainty, doubt) against your competitors without actually having to support the product since it isn't an 'official' release.  It also lets your marketing fiends claim it isn't feature complete/bug free whenever a journalist points out flaws.</p></div>
	</div>
</div>
		