
<div class="comment" id="c_5149859121">
	<div>
		<img src="https://disqus.com/api/users/avatars/stevestonebraker.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_5149859121">1</a> by Steve Stonebraker
		posted on 11/13/2020 at 5:01 AM
		</div>
		<div class="comment_text"><p>Hey Raymond, thanks for sharing this code.  This is exactly what I was looking for as I start my vue.js journey.  Also, congrats on the book!</p></div>
	</div>
</div>
		
<div class="comment" id="c_5150292543">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_5150292543">2</a> (In reply to <a href="#c_5149859121">#1</a>) by Raymond Camden
		posted on 11/13/2020 at 3:31 PM
		</div>
		<div class="comment_text"><p>Thank you!</p></div>
	</div>
</div>
		