
<div class="comment" id="c_1712240274">
	<div>
		<img src="https://disqus.com/api/users/avatars/photokandy.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1712240274">1</a> by Kerri Shotts
		posted on 11/25/2014 at 5:30 PM
		</div>
		<div class="comment_text"><p>Congrats on writing a book -- It's both wonderful and nerve-wracking at the same time! ;-) Good luck, and I hope it is very successful!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713748289">
	<div>
		<img src="https://disqus.com/api/users/avatars/rogerthegeek.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748289">2</a> by RogerTheGeek
		posted on 11/26/2014 at 3:16 PM
		</div>
		<div class="comment_text"><p>Good luck! Writing like that is a labor of love.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1725632806">
	<div>
		<img src="https://disqus.com/api/users/avatars/phillipsenn.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1725632806">3</a> by Phillip Senn
		posted on 12/4/2014 at 4:51 PM
		</div>
		<div class="comment_text"><p><a href="https://disq.us/url?url=https%3A%2F%2Fbitnami.com%2Fstack%2Fcordova%3AUlHD1L0naV93ZQNz8DwJsAIjL2k&amp;cuid=3321886" rel="nofollow noopener" title="https://bitnami.com/stack/cordova">https://bitnami.com/stack/c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1725783719">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1725783719">4</a> (In reply to <a href="#c_1725632806">#3</a>) by Raymond Camden
		posted on 12/4/2014 at 6:15 PM
		</div>
		<div class="comment_text"><p>Did you mean to type something with this?</p></div>
	</div>
</div>
		