
<div class="comment" id="c_1713658461">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658461">1</a> by Rob Brooks-Bilson
		posted on 10/22/2006 at 9:48 PM
		</div>
		<div class="comment_text"><p>Thanks Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658465">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658465">2</a> by Mark Drew
		posted on 10/22/2006 at 11:31 PM
		</div>
		<div class="comment_text"><p>Damn you all! I cant afford to go to Max this year (err... no corporate sponsor eh?) Hope you  have a great time!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658450">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658450">3</a> by Savvas
		posted on 10/23/2006 at 12:22 PM
		</div>
		<div class="comment_text"><p>Me too here in Greece..<br>I wish i was in Vegas now...Anyway i'll wait for the community's feedback..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658462">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658462">4</a> by quiksilv
		posted on 10/23/2006 at 2:23 PM
		</div>
		<div class="comment_text"><p>Hey Ray - try some Pictorial Ajaxitagging if you can ;)</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fadactio.com%2Fjournal%2F1194%3AaLb7Z90b4bXHEqXnx64sptrqU_g&amp;cuid=3321886" rel="nofollow noopener" title="http://adactio.com/journal/1194">http://adactio.com/journal/...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658467">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658467">5</a> by Josh Tynjala
		posted on 10/24/2006 at 2:17 AM
		</div>
		<div class="comment_text"><p>I brought my old school film camera, so my contributions won't be immediate, but I'll be sure to share once I get my rolls developed.</p></div>
	</div>
</div>
		