
<div class="comment" id="c_1713650714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650714">1</a> by Dave Carabetta
		posted on 3/8/2006 at 9:42 AM
		</div>
		<div class="comment_text"><p>Hey Ray. The URL should be <a href="http://disq.us/url?url=http%3A%2F%2Fwww.blogbeat.net%3ATo_LgkFPt4IBCHekaazhjcWcyb8&amp;cuid=3321886" rel="nofollow noopener" title="www.blogbeat.net">www.blogbeat.net</a>. I tried <a href="http://disq.us/url?url=http%3A%2F%2Fblogbeat.com%3AFPFsenBTsfPfVgv5m8do5lvseVo&amp;cuid=3321886" rel="nofollow noopener" title="blogbeat.com">blogbeat.com</a> but that's a dead link.</p><p>I just signed up for an account. My initial impression is that the site is a bit sluggish. Also, I clicked on the Dashboard link from the navigation at the bottom of a sub-page and I got an error. I then went straight to the Dashboard page via the "tab" link and the dashboard just doesn't load.</p><p>Oh well, I'll stick with it since it's free for a month and hope that they get their act together a bit. My initial impression is less than positive.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650716">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650716">2</a> by Raymond Camden
		posted on 3/8/2006 at 10:12 AM
		</div>
		<div class="comment_text"><p>Thanks - I fixed the URL. I've seen one or two errors myself, but I assume it's just them working on it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650715">3</a> by djuggler
		posted on 3/8/2006 at 10:21 PM
		</div>
		<div class="comment_text"><p>How do these compare against web hosting analyzers like webtrends? What's the lure to use Blogbeat instead of Webtrends (or similar)?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650707">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650707">4</a> by Raymond Camden
		posted on 3/8/2006 at 10:43 PM
		</div>
		<div class="comment_text"><p>I haven't used Web trends. Compred to Google Analytics, yes, it is "less" stats, but it is much more tuned for blog stats. It is much easier for me to hit blobeat and get a feel for my day compared to Analytics.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650712">5</a> by Ali Daniali
		posted on 3/9/2006 at 4:36 AM
		</div>
		<div class="comment_text"><p>I installed it on my site and really like the dashboard. The speed was just fine. I can't wait to see the results for the next month of usage.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650719">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650719">6</a> by Dave Shuck
		posted on 3/12/2006 at 9:33 AM
		</div>
		<div class="comment_text"><p>Ray, another one you should check out is MyBlogLog (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.mybloglog.com%2F%29%3AK38jy24YieYPn3eSuuk21JXI8E0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.mybloglog.com/)">http://www.mybloglog.com/)</a>.  I have used them for about 9 months and have been very happy.  They show your top inbound and outbound links and make it very easy to track what google searches are directing people to you.  Oh yeah... and it's free. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650720">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650720">7</a> by Tom Chiverton
		posted on 3/13/2006 at 9:04 PM
		</div>
		<div class="comment_text"><p>"you also get a list of all the clicks leaving your blog"<br>How do they manage that then ? You must have to rewrite all your links to point at a redirector on their site ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650717">8</a> by Raymond Camden
		posted on 3/13/2006 at 9:07 PM
		</div>
		<div class="comment_text"><p>Nope, I'm assuming they must have a click tracker event.</p></div>
	</div>
</div>
		