
<div class="comment" id="c_1713618701">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618701">1</a> by r0main
		posted on 6/6/2005 at 8:10 PM
		</div>
		<div class="comment_text"><p>Not so sure,<br>I think Flex and Flash is the first step...<br>see Zorn FAQ (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.macromedia.com%2Fsoftware%2Fflex%2Fproductinfo%2Ffaq%2F%23item-f15%29%3AvIetFdu_M3WrknPTqvu5sXasQ2c&amp;cuid=3321886" rel="nofollow noopener" title="http://www.macromedia.com/software/flex/productinfo/faq/#item-f15)">http://www.macromedia.com/s...</a>, the last sentence let me think if the Flash / Flex editor is good, they'll move CF dev as well !!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618700">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618700">2</a> by Steve Rittler
		posted on 6/6/2005 at 8:12 PM
		</div>
		<div class="comment_text"><p>Ray-<br>I see your point, but at the same time...i'm happy with CFEclipse and am not entirely sure what i'm missing.  I was a devout CFStudio user, got used to Dreamweaver (though still hate the startup time), and now i'm all about Eclipse.</p><p>What could MM add to CFEclipse that we don't already have?  Just curious...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618699">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618699">3</a> by Peter Tilbrook
		posted on 6/6/2005 at 8:16 PM
		</div>
		<div class="comment_text"><p>They've certainly gone pro Flash of late it seems. Check out the new Flash Platform portal at <a href="http://disq.us/url?url=http%3A%2F%2Fwww.macromedia.com%2Fplatform%2F%3AhMftN6RozIqMu53NlWdO_Hcfvw4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.macromedia.com/platform/">http://www.macromedia.com/p...</a></p><p>If only some decent books came out for integrating Flex and ColdFusion (and not just J2ee/.Net) I might be better inclined to spend more time with Flex.</p><p>I spent the effort to have the Flex deved running on the same port as MX7 but what now?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618698">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618698">4</a> by Raymond Camden
		posted on 6/6/2005 at 8:19 PM
		</div>
		<div class="comment_text"><p>Steve - please know that I'm not saying CFE is bad in anyway - but I'd just like to see MACR help support it. CFE is petty much a one man shop now so I'm sure _any_ support would be welcome. As for what could be done - perhaps help in the documentation area for future releases - perhaps adding in some of the features DWMX got in CFMX7, like toggling on debugging via the IDE and not the admin. I know Spike is still working on improving CFE - so obviously there are things left to do, even though it's better than HS+ _right now_. Does that make sense?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618697">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618697">5</a> by firebug
		posted on 6/6/2005 at 8:31 PM
		</div>
		<div class="comment_text"><p>hi,you are great and kind!thank you for you free blog software,but i do not know the css well.i want to change my blog look like yours.would you give me your css files of your blog.thank you!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618704">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618704">6</a> by Raymond Camden
		posted on 6/6/2005 at 8:35 PM
		</div>
		<div class="comment_text"><p>firebug - I got the design from Joe Rinehart. See the links at the very bottom of the blog.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618702">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618702">7</a> by Jim
		posted on 6/6/2005 at 8:39 PM
		</div>
		<div class="comment_text"><p>Good news - and it would be great if they supported CFEclipse in some form or fashion - either with manpower or financially.  Maybe they are going to test the waters with Zorn and see how that pans out first.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618703">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618703">8</a> by Steve Rittler
		posted on 6/6/2005 at 8:39 PM
		</div>
		<div class="comment_text"><p>Oh, no, I wasn't reading you that way at all!  I knew what you were getting at.</p><p>I was just digging in to figure out what features CFE could add that would make it better than it already is.  Gotta wonder though what would be in it for MM.  Their tools business brings in good money right now.  Flex Builder is an easy loss - since it's bundled with Flex (and it's pricetag!) there's no impact on their existing tools by fitting the functionality into another platform.</p><p>If MM did that officially for CF, as a hardcore CF  developer, would you ever buy another copy of Dreamweaver again?  I'd be tempted not to ~ and i'm sure i'm not alone in that assessment!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618711">9</a> by Raymond Camden
		posted on 6/6/2005 at 8:43 PM
		</div>
		<div class="comment_text"><p>First off - let me say I'm sorry when I said one man shop above - it's definitely more than one man - just not many. ;)</p><p>Steve: Heh, for a while there I recommended folks buy DW - just because you got HS+ with it and the price was less than what you used to pay for CFS. I think DW will ALWAYS have a huge audience. I think it is a great tool for the less hard-core developers out there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618707">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618707">10</a> by Ben Forta
		posted on 6/6/2005 at 8:56 PM
		</div>
		<div class="comment_text"><p>I agree with you Ray. I, for one, would love to see CF Eclipse become the rightful heir to ColdFusion Studio. &lt;said with a lump in my throat&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618709">11</a> by Raymond Camden
		posted on 6/6/2005 at 8:59 PM
		</div>
		<div class="comment_text"><p>"lump in throat" - heh - I still remember being so passionate about CFS/HS+ that I thought I would use it till the day I died.... ahh how times change. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618705">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618705">12</a> by Peter Tilbrook
		posted on 6/6/2005 at 9:14 PM
		</div>
		<div class="comment_text"><p>Sigh!</p><p>Even HomeSite+ has its limits.</p><p>Just tried creating a new "project" with 21,000+ files.</p><p>It died (or I gave up waiting for it to finish).</p><p>But so long as I have my Studio MX 2004 disk HomeSite+ will live on :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618706">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618706">13</a> by Mike Rankin
		posted on 6/6/2005 at 10:15 PM
		</div>
		<div class="comment_text"><p>I could see macr/adbe making a push to move more of its core developers to the flash platform.  It's a pretty compelling software stack if you can get your  brain around the timeline.  AS2.0 already feels pretty mature even if the components don't.  It reminds me of the early days of VB except web enabled.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618712">14</a> by M. Schopman
		posted on 6/8/2005 at 6:07 PM
		</div>
		<div class="comment_text"><p>The hold back on Eclipse is the lack of a good complete package. CFEclipse + CSS + XML + HTML/XHTML + Javascript. The last time I checked the web developer extension of Eclipse, I got about a dozen errors on startup with the latest stables.</p><p>The first one creating a package, one click to install with the mentioned features above is a clear winner :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618710">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618710">15</a> by Raymond Camden
		posted on 6/8/2005 at 6:11 PM
		</div>
		<div class="comment_text"><p>I have to agree with the one click/install type thing. I don't mind manually setting up stuff - but for many users Eclipse is still a bit too much. (Of course, sometimes you have to work to get results, so perhaps those people are just being lazy. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618708">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618708">16</a> by Rafael Torres
		posted on 6/8/2005 at 6:25 PM
		</div>
		<div class="comment_text"><p>As far as features that MACR could add to CFEclipse, I would love to see DW's excellent FTP support built into CFE. Current FTP support in Eclipse just doesn't cut it.</p></div>
	</div>
</div>
		