
<div class="comment" id="c_1713615023">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615023">1</a> by Chris Wigginton
		posted on 10/24/2003 at 11:43 PM
		</div>
		<div class="comment_text"><p>Ok Ray,</p><p>How about old TEXT based Muds!</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fmozart.atpnet.com%3AQnUntOG5WQVh4VqOx-8bZ9FdB-o&amp;cuid=3321886" rel="nofollow noopener" title="mozart.atpnet.com">mozart.atpnet.com</a> port 4500</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615022">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615022">2</a> by Raymond Camden
		posted on 10/27/2003 at 8:21 PM
		</div>
		<div class="comment_text"><p>Heh, I was a BIG mud player in college, even did a lot of development as well. LPC was a nice language, but I had the most fun when I built nice base classes. I still remember adding a basic concept of time to a mud, well, in my zone. It was pretty cool - my zone was the only one where the sun would rise and fall, church bells would ring out, etc. I also built a pretty nifty NPC class. It allowed you to easily add canned text responses to NPCs in games.</p></div>
	</div>
</div>
		