
<div class="comment" id="c_1713728626">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728626">1</a> by andy matthews
		posted on 1/3/2011 at 1:22 AM
		</div>
		<div class="comment_text"><p>Can't wait for you to check out the web app that I've been working on for the last month. Our modal usage is slick as a greased pig. Keep your eye open for the new <a href="http://disq.us/url?url=http%3A%2F%2Fgoba.mobi%3AGfI77tSRlXNnR8R10OFUn0QNAoQ&amp;cuid=3321886" rel="nofollow noopener" title="http://goba.mobi">http://goba.mobi</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728628">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728628">2</a> by James Moberg
		posted on 1/3/2011 at 9:27 PM
		</div>
		<div class="comment_text"><p>For simple inline editing like this on admin forms (w/o lots of validation), I've been using the Jeditable jQuery Plugin.<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.appelsiini.net%2Fprojects%2Fjeditable%3AEV1bzZICzOplG0CV7WGW9ITE1_M&amp;cuid=3321886" rel="nofollow noopener" title="http://www.appelsiini.net/projects/jeditable">http://www.appelsiini.net/p...</a></p><p>It creates editable form fields on-the-fly and posts the data to the server via ajax.  It requires a lot less code and only uses a uniquely coded ID and identifiable class per editable field.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728629">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728629">3</a> by Raymond Camden
		posted on 1/3/2011 at 9:29 PM
		</div>
		<div class="comment_text"><p>That's a slick little plugin - thanks for sharing it James.</p><p>Andy - be sure to let me know when it goes live!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728627">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728627">4</a> by James Moberg
		posted on 1/3/2011 at 9:32 PM
		</div>
		<div class="comment_text"><p>I've been using the CFJS jQuery library for DollarFormat.  It adds lots of CF-like functions to jQuery and the syntax is "$.{functionname()}" (ie, $.DollarFormat(price)). When you are using a CF IDE, the hints will provide you with insight into the javascript function (at least on HomeSite+.)<br><a href="http://disq.us/url?url=http%3A%2F%2Fcfjs.riaforge.org%2F%3AkV9B2ucEl5Ctl1tGUAJJRryKDoc&amp;cuid=3321886" rel="nofollow noopener" title="http://cfjs.riaforge.org/">http://cfjs.riaforge.org/</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728632">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728632">5</a> by Raymond Camden
		posted on 1/3/2011 at 9:37 PM
		</div>
		<div class="comment_text"><p>HomeSite+ - wow, now that Nadel has stopped using it I think you may be the last one around. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728630">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728630">6</a> by Phillip Senn
		posted on 1/3/2011 at 10:25 PM
		</div>
		<div class="comment_text"><p>Here's what I use when I want to load jQuery UI:</p><p>&amp;lt;cfparam name="url.Theme" default="smoothness"&gt;<br>&amp;lt;cfoutput&gt;<br>&amp;lt;link rel="stylesheet" href="<a href="http://disq.us/url?url=http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjqueryui%2F1%2Fthemes%2F%23url.Theme%23%2Fjquery-ui.css%3AsJ7NQkEGnUXqwCElXDDQ16bnGEY&amp;cuid=3321886" rel="nofollow noopener" title="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/#url.Theme#/jquery-ui.css">http://ajax.googleapis.com/...</a>" type="text/css" media="all" /&gt;<br>&amp;lt;/cfoutput&gt;<br>&amp;lt;script src="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.google.com%2Fjsapi%3Avbl28ruWWKTpp21RiJwKnS52-hc&amp;cuid=3321886" rel="nofollow noopener" title="http://www.google.com/jsapi">http://www.google.com/jsapi</a>"&gt;&amp;lt;/script&gt;<br>&amp;lt;script type="text/javascript"&gt;<br>google.load("jquery", "1");<br>google.load("jqueryui", "1");<br>&amp;lt;/script&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728631">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728631">7</a> by Raymond Camden
		posted on 1/3/2011 at 10:26 PM
		</div>
		<div class="comment_text"><p>Please don't post escaped code - we escape it already. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728637">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728637">8</a> by James Moberg
		posted on 1/4/2011 at 1:06 AM
		</div>
		<div class="comment_text"><p>I use AutoHotKey (Windows) to manage most of my custom hotkey/macros (and they work regardless of the editor I am using.)  I also have a lot of snippets and use Evernote to manage code samples.  I've tried to move to CFEclipe and Builder, but it just slowed me down compared to how I'm accustomed to programming.  (I have direct physical access to most of the servers I work with anyhow.)  I also disliked the various line number, line wrap and FTP issues I initially encountered and figured I just keep waiting and I haven't ever taken the time to reevaluate.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728636">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728636">9</a> by Alex Lovel
		posted on 1/4/2011 at 8:21 PM
		</div>
		<div class="comment_text"><p>Ray - can you expound a bit on this as to how you'd use tr and td to pass the data in via a click on an edit link?  For example:<br>&lt;tr&gt;<br>&lt;th&gt;Name&lt;/th&gt;<br>&lt;th&gt;Price&lt;/th&gt;<br>&lt;th&gt;Description&lt;/th&gt;<br>&lt;th&gt;&lt;/th&gt;<br>&lt;/tr&gt;<br>&lt;cfoutput query="getArt"&gt;<br>&lt;tr&gt;<br>&lt;td&gt;#name#&lt;/td&gt;<br>&lt;td&gt;#price#&lt;/td&gt;<br>&lt;td&gt;#description#&lt;/td&gt;<br>&lt;td&gt;&lt;a id="#artid# href=""&gt;edit&lt;/a&gt;&lt;/td&gt;<br>&lt;/tr&gt;<br>&lt;/cfoutput&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728634">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728634">10</a> by Raymond Camden
		posted on 1/4/2011 at 8:23 PM
		</div>
		<div class="comment_text"><p>Interesting - let me write up an example.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728635">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728635">11</a> by MikeG
		posted on 1/5/2011 at 1:42 AM
		</div>
		<div class="comment_text"><p>@phillip - Even the CDN is sometimes slow or unavailable and even blocked in some countries.  If you are using google.load or even a straight reference to the hosted js files for fallback you should also implement something like this.</p><p>if(typeof jQuery == ‘undefined’)<br>{<br>// load local version….<br>}<br><a href="http://disq.us/url?url=http%3A%2F%2Fbit.ly%2Fy8IMo%3AuSmqKYVcktseAxcz6-MRwEUk6mI&amp;cuid=3321886" rel="nofollow noopener" title="http://bit.ly/y8IMo">http://bit.ly/y8IMo</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728638">12</a> by Phillip Senn
		posted on 1/5/2011 at 3:55 AM
		</div>
		<div class="comment_text"><p>Thanks Mike.<br>Duly noted.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728639">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728639">13</a> by Raymond Camden
		posted on 1/5/2011 at 4:37 AM
		</div>
		<div class="comment_text"><p>Alex: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Findex.cfm%2F2011%2F1%2F4%2FQuick-follow-up-to-Modal-Dialog-Editing-post-with-jQuery-and-ColdFusion%3AYQPM13EdoUGwidT5NVByxoe0j8U&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/index.cfm/2011/1/4/Quick-follow-up-to-Modal-Dialog-Editing-post-with-jQuery-and-ColdFusion">http://www.coldfusionjedi.c...</a></p><p>Hope this helps.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728640">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728640">14</a> by Steve Logan
		posted on 1/5/2011 at 6:45 AM
		</div>
		<div class="comment_text"><p>Quick question - when you post the data with jquery:</p><p>$.post("artservice.cfc?method=saveart",</p><p>how can you access a CFC that's in a different directory that is not a sub directory of the current.</p><p>In this example let's say you had a CF mapping defined "art" and you could access those CFCs via cfinvoke or other methods using:  &lt;cfinvoke component="art.artists" method="qryArtists"&gt;?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728645">15</a> by Raymond Camden
		posted on 1/5/2011 at 9:18 AM
		</div>
		<div class="comment_text"><p>CF901 added the ability to hit CFC methods in CFCs available via CF mappings. But only via "their" stuff, like for example, cfdiv. It does not work via jQuery.</p><p>My answer is you don't want to do it. Period. If you want to run a CFC for Ajax stuff, put it under web root where it belongs.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728642">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728642">16</a> by Simon
		posted on 1/16/2011 at 7:14 AM
		</div>
		<div class="comment_text"><p>Thanks for the great help and guidance.</p><p>I wondering about using something similar - but instead of a modal or table, using a cfdiv to display the output - but I can't quite get the bind element to work. I'd like to have a list of items that when clicked update the content of a cfdiv</p><p>Thanks again - any advice appreciated.<br>Simon</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728641">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728641">17</a> by Raymond Camden
		posted on 1/16/2011 at 7:18 AM
		</div>
		<div class="comment_text"><p>I do not recommend mixing jQuery (or another js framework), with the built in CF AJAX UI items. In theory though what you want could be done by using jQuery to listen to the click even for the items and then fire ColdFusion.navigate to change the contents of the cfdiv. You wouldn't need bindings.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728643">18</a> by Simon
		posted on 1/16/2011 at 7:23 AM
		</div>
		<div class="comment_text"><p>Thanks for the (very) prompt reply Ray - and for the pointer.<br>Cheers<br>Simon</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728644">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728644">19</a> by Sebastiaan
		posted on 2/5/2011 at 1:46 PM
		</div>
		<div class="comment_text"><p>What's up with all the beards? Did I miss something?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728649">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728649">20</a> by andy matthews
		posted on 2/5/2011 at 6:33 PM
		</div>
		<div class="comment_text"><p>You sure did. It's the beardpocalypse. The aliens don't like beards in their exam rooms and they don't know human physiology well enough yet to realize that they can be shaved off. So they're only picking ppl for their probing that don't have beards.</p><p>Plus they look BAD. ASS.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728647">21</a> by Tim
		posted on 11/20/2012 at 2:01 AM
		</div>
		<div class="comment_text"><p>This is very cool, Ray!! Thanks for posting.</p><p>One question. I am working on a search tool, in a pop up such as this that will return a list of store locations based upon zip code entered. Submitting that to a cfc is fairly easy. What would be the easiest way to update the page with a returned query of results (will not be more than 3 rows)?</p><p>Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728648">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728648">22</a> by Raymond Camden
		posted on 11/20/2012 at 2:04 AM
		</div>
		<div class="comment_text"><p>Your question is kinda broad. You said already you can talk to a CFC and get results. So you get that part. If you are asking how to update the DOM, isn't that simple in jQuery? You take your result, generate html, and do something like $("#somediv").html(somestring)? Or am I missing something?</p></div>
	</div>
</div>
		