
<div class="comment" id="c_1713679183">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679183">1</a> by Andy Powell
		posted on 4/4/2008 at 9:04 PM
		</div>
		<div class="comment_text"><p>Have you looked at using the ROME Java libraries?  It's a  bit more complex, but it's what the CFFEED tag is built on.  CFFEED is, essentially, an abstraction of this library.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679182">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679182">2</a> by Raymond Camden
		posted on 4/4/2008 at 9:05 PM
		</div>
		<div class="comment_text"><p>Well my issue with cffeed is that I want it _simpler_. So for example, I get that RSS is complex. I get why the query returned from cffeed is huge. But - for 99% of usage out there, you want a few fields. I'd like to see cffeed have an option to return a much simpler query - one that 'munges' disparate but equal columns from Atom/RSS feeds.</p></div>
	</div>
</div>
		