
<div class="comment" id="c_1713745214">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713745214">1</a> by Michael Long
		posted on 3/18/2013 at 8:22 AM
		</div>
		<div class="comment_text"><p>"Local candidates preferred..." But no location given.</p><p>Just sayin'.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713745210">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713745210">2</a> by Jonathan Lee
		posted on 3/18/2013 at 7:14 PM
		</div>
		<div class="comment_text"><p>If you goto <a href="http://disq.us/url?url=http%3A%2F%2Fbib.com%3AyvRXZsp6VmkwGF99Mf3-dGiT9sY&amp;cuid=3321886" rel="nofollow noopener" title="bib.com">bib.com</a>, the location says "Huntersville, NC", so i'm assuming they're looking for someone within NC.</p></div>
	</div>
</div>
		