
<div class="comment" id="c_1713680320">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680320">1</a> by Ken Sykora
		posted on 4/24/2008 at 7:18 PM
		</div>
		<div class="comment_text"><p>For our last CF7 app, we used json.cfc (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.epiphantastic.com%2Fcfjson%2F%29%3ASn2hUOn06_4mVr--CqXlpXMRMCM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.epiphantastic.com/cfjson/)">http://www.epiphantastic.co...</a></p><p>Between that, and the prototype framework on the javascript side to actually parse the data into a javascript object, works like a charm. (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.prototypejs.org%2F%29%3A_y2Sb-MzqUdxe7Vfv9P8URigBbk&amp;cuid=3321886" rel="nofollow noopener" title="http://www.prototypejs.org/)">http://www.prototypejs.org/)</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680309">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680309">2</a> by Raymond Camden
		posted on 4/24/2008 at 7:23 PM
		</div>
		<div class="comment_text"><p>Um Ken - you do know that's the same CFC I pointed to - right? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680319">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680319">3</a> by Doug Laakso
		posted on 4/25/2008 at 4:17 AM
		</div>
		<div class="comment_text"><p>Another alternative is toJSON at <a href="http://disq.us/url?url=http%3A%2F%2Ftojson.riaforge.org%2Findex.cfm%3AffNqsrx6o9ee7yOF_zQWmVjWD5U&amp;cuid=3321886" rel="nofollow noopener" title="http://tojson.riaforge.org/index.cfm">http://tojson.riaforge.org/...</a></p></div>
	</div>
</div>
		