
<div class="comment" id="c_2206517371">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2206517371">1</a> (In reply to <a href="#c_2205843937">#0</a>) by Raymond Camden
		posted on 8/21/2015 at 10:08 AM
		</div>
		<div class="comment_text"><p>Nope. (Not as far as I know anyway.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_2830359036">
	<div>
		<img src="https://disqus.com/api/users/avatars/ishaiborovoy.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2830359036">2</a> by Ishai Borovoy
		posted on 8/10/2016 at 2:10 PM
		</div>
		<div class="comment_text"><p>Here is how to work combine MFP7.1 and Ionic2 <br><a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fmfpdev%2Fmfp71-with-ionic2%3AVnL5gU-ILtJj2a_6EG-S0S7rzuc&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/mfpdev/mfp71-with-ionic2">https://github.com/mfpdev/m...</a></p></div>
	</div>
</div>
		