
<div class="comment" id="c_1714080752">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080752">1</a> by Micah
		posted on 11/11/2013 at 6:18 AM
		</div>
		<div class="comment_text"><p>Thanks for putting this out there Ray and for what you have done.  I was adopted and have such a great respect for people who do so.<br>My wife and I have always had it in the back of our minds to do this but we now have two teenage daughters and im barely hanging on.  Plus financially it isn't feasible.</p><p>Thanks again for getting the word out.  You and your wife are purely awesome for adopting a few children.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080747">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080747">2</a> by Raymond Camden
		posted on 11/11/2013 at 6:24 AM
		</div>
		<div class="comment_text"><p>Thanks for the kind words. Honestly though - we are the lucky ones. The kids are awesome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080754">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080754">3</a> by Simon MacDonald
		posted on 11/11/2013 at 7:26 PM
		</div>
		<div class="comment_text"><p>Thanks for the reminder Ray. I'm so thankful for my adoptive parents for giving me such a wonderful childhood and never making me feel like I was anything other than their kid. Adoptive parents are awesome!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080751">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080751">4</a> by Jim
		posted on 11/13/2013 at 9:06 PM
		</div>
		<div class="comment_text"><p>We adopted 2 Russian children 1 1/2 years ago now.  I posted a message here about that at that time.  It was a transition for all of us at first but now everyone is doing great.  Their personalities are beginning to shine and all is good.  It's a shame that Russia shut down their adoptions to the U.S.  now 2-3 thousand more kids will languish in Russian orphanages each year.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080753">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080753">5</a> by Ding
		posted on 12/14/2013 at 1:52 PM
		</div>
		<div class="comment_text"><p>You are very kind, I respect you :) I am from China, just like the children in this video. Thank you for your warm heart.</p></div>
	</div>
</div>
		