
<div class="comment" id="c_1714080743">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080743">1</a> by MikeZ
		posted on 11/10/2013 at 9:21 PM
		</div>
		<div class="comment_text"><p>With most people it's just easier to link to this page: <a href="http://disq.us/url?url=http%3A%2F%2Fvz3.blur.com%2Fwork%2Fcinematics%3AfWUM9inPdsbYl-Ksp7W9OdLRd6A&amp;cuid=3321886" rel="nofollow noopener" title="http://vz3.blur.com/work/cinematics">http://vz3.blur.com/work/ci...</a> ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080730">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080730">2</a> by Raymond Camden
		posted on 11/10/2013 at 10:34 PM
		</div>
		<div class="comment_text"><p>Wasn't even aware of that - cool.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080745">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080745">3</a> by MikeZ
		posted on 11/10/2013 at 10:56 PM
		</div>
		<div class="comment_text"><p>Be sure to check out the "Films" section as well. <br>Every couple of years they produce a short film to demonstrate their role as a full-service company.<br>I'm not  sure why my favorite "Rock Fish" is no longer listed on their site, but a quick visit to <a href="http://disq.us/url?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZpO13RuLg3k%3AOn0kuYBpShCF7PGRnoZ6dhYH5ko&amp;cuid=3321886" rel="nofollow noopener" title="http://www.youtube.com/watch?v=ZpO13RuLg3k">http://www.youtube.com/watc...</a> will remedy that.</p></div>
	</div>
</div>
		