
<div class="comment" id="c_1714084344">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084344">1</a> by Pete Williamson
		posted on 11/10/2014 at 4:40 PM
		</div>
		<div class="comment_text"><p>I build websites for cars. I spent last week "debating" with my boss and the data manager over which word to use to describe air conditioning, sat nav etc.</p><p>I kept saying "features", they disagreed... seeing this makes me so happy:</p><p>var features = ["Air Conditioning", "Cruise Control", "Backup Camera", "Power Steering", "Internet", "Sat Radio", "4WD", "Moon Roof"];</p><p>Regarding your code, that's a lot of nested IFs... even for demo code isn't it nicer to use functions and callbacks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714084348">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084348">2</a> by Raymond Camden
		posted on 11/10/2014 at 5:08 PM
		</div>
		<div class="comment_text"><p>I thought about breaking it out into a function to randomly add features, etc, but, decided to just KISS. As it stands, *this* code won't be in the preso.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714084350">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084350">3</a> by Dan Kraus
		posted on 11/10/2014 at 10:11 PM
		</div>
		<div class="comment_text"><p>@Pete - I'm not in the car business, just a passing interest in them, but I think they're commonly referred to as "options" in the business. Ex - The GT trim comes with or without a moonroof. It's optional.  A "feature" would be something like  say power windows because it's standard in that trim. Every car in that trim has it.</p><p>So they end up being two different things. Some options are sometimes only available in certain trims too.</p><p>It's probably outside the scope of your demo, Ray, and it gets the point across already :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714084346">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084346">4</a> by Pete Williamson
		posted on 11/10/2014 at 10:41 PM
		</div>
		<div class="comment_text"><p>@Dan yeah you're right we use the word "option" for optional equipment, and I guess  that's what Ray was listing - I was thinking of the overall grouping for all options (or standards) of a type</p><p>E.g. feature: special paint, could be pearlescant paint, metallic paint, matte paint etc<br>or feature: leather seats, could be part leather, full leather, hand stitched leather etc</p><p>Anyway like you said, the demo is perfectly clear, and automotive terminology is an absolute nightmare.</p><p>@Ray you could add this to your MockData projects, give the random people more properties or just a different flavor of data</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714084349">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084349">5</a> by roger tubby
		posted on 11/10/2014 at 11:28 PM
		</div>
		<div class="comment_text"><p>And wouldn't it be nice to do this with just some mapping functions - no for() loops a-tall.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714084347">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714084347">6</a> by Raymond Camden
		posted on 11/11/2014 at 12:04 AM
		</div>
		<div class="comment_text"><p>Well, I could map over some of it, not all of it. :P</p></div>
	</div>
</div>
		