
<div class="comment" id="c_1713719283">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719283">1</a> by Brad Sevening
		posted on 10/27/2009 at 7:57 PM
		</div>
		<div class="comment_text"><p>Matt Kruse also has some tried and true JS Date libraries that I've used for a few years and have served me well.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.javascripttoolbox.com%2F%3AkGfqZJzE9xnmxqT8xQieSUEZIj0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.javascripttoolbox.com/">http://www.javascripttoolbo...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719289">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719289">2</a> by Bjarte Bore
		posted on 10/29/2009 at 12:57 PM
		</div>
		<div class="comment_text"><p>Another javascript date library: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.datejs.com%3A8v5Pp6PJO28hBxpW5M1tqPIrW7M&amp;cuid=3321886" rel="nofollow noopener" title="http://www.datejs.com">http://www.datejs.com</a></p></div>
	</div>
</div>
		