
<div class="comment" id="c_1713654095">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654095">1</a> by Ryan
		posted on 6/13/2006 at 11:09 PM
		</div>
		<div class="comment_text"><p>That is great news about the Cookbook!  A few months ago I submitted some code on looping with T-SQL to get added to the SQL section, however it never got published. Can I contact someone?</p><p>Ryan</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654101">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654101">2</a> by Raymond Camden
		posted on 6/13/2006 at 11:14 PM
		</div>
		<div class="comment_text"><p>Me. ;) I'm slowly going through old entries and pushing them to Jeremy. I'm putting more focus on CFML entries as I think they are more relevant, although I'm not going to ignore SQL questions.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654100">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654100">3</a> by Andrew
		posted on 6/14/2006 at 5:08 PM
		</div>
		<div class="comment_text"><p>Great site. One suggestion - perhaps the PDF file (the one I downloaded was "with comments") could have a table of contents.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654099">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654099">4</a> by Raymond Camden
		posted on 6/14/2006 at 5:28 PM
		</div>
		<div class="comment_text"><p>I would love to have that. Unfortunately, cfdocument doesn't support it. I may need to look at alternatives.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654102">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654102">5</a> by Andrew
		posted on 6/14/2006 at 5:37 PM
		</div>
		<div class="comment_text"><p>Now this is probably just my own ignorance here, but instead of a true ToC, perhaps just a listing of the "recipes" in the order they are presented. Not having the exact page number is not a big deal. If a solution is 3/4 of the way down the pseudo-ToC list, at least I'll know it's there. Given the mostly 1:1 ratio of page to recipe, this would certainly suffice for me - if it can be done. If not, no big deal - still an awesome resource!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654104">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654104">6</a> by Raymond Camden
		posted on 6/14/2006 at 5:44 PM
		</div>
		<div class="comment_text"><p>That I can do, and I agree, it would be helpful. I'll try and see if it can be done this week.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654103">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654103">7</a> by Ryan
		posted on 6/14/2006 at 6:22 PM
		</div>
		<div class="comment_text"><p>Ray,<br>I understand, CFML scripts should get higher priority in the ColdFusion Cookbook!</p><p>I like it, thanks for all your hard work.</p><p>Ryan</p></div>
	</div>
</div>
		