
<div class="comment" id="c_1713731978">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731978">1</a> by Mike Henke
		posted on 5/4/2011 at 6:44 PM
		</div>
		<div class="comment_text"><p>Does the Properties view work with the RDS Fileview view? With the Navigator View, if I also have the Properties view open and click on a file in the Navigator, I see info like editable, last modified, location, name, path, and size.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731970">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731970">2</a> by Raymond Camden
		posted on 5/4/2011 at 6:49 PM
		</div>
		<div class="comment_text"><p>No. I see options to rename or delete the file. (There are other options to - but these are the ones specific to the file you right click on.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731984">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731984">3</a> by Mike Henke
		posted on 5/4/2011 at 6:58 PM
		</div>
		<div class="comment_text"><p>Bummer. Here is screenshot of the navigator and properties views working together <a href="http://disq.us/url?url=http%3A%2F%2Fbit.ly%2FkCGKFc%3Ar1oMXPPYztqlvSfbYjblg-bIIro&amp;cuid=3321886" rel="nofollow noopener" title="http://bit.ly/kCGKFc">http://bit.ly/kCGKFc</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731982">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731982">4</a> by Raymond Camden
		posted on 5/4/2011 at 7:13 PM
		</div>
		<div class="comment_text"><p>Hey - how did you get the properties there? Oh - there is a Properties view! Nice - thanks man - you taught me something new. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731980">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731980">5</a> by Jim
		posted on 5/4/2011 at 7:23 PM
		</div>
		<div class="comment_text"><p>Nice! Thanks Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731986">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731986">6</a> by larry c lyons
		posted on 6/17/2011 at 6:48 PM
		</div>
		<div class="comment_text"><p>hey RAy, Is there any way to export this data? I'm going through a huge site right now and would love to be able to export this or the search view list to a spreadsheet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731981">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731981">7</a> by Raymond Camden
		posted on 6/17/2011 at 6:54 PM
		</div>
		<div class="comment_text"><p>Not that I know of, but it would be trivial to do in ColdFusion itself of course. I don't suppose you need an example of that, right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731985">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731985">8</a> by larry c lyons
		posted on 6/17/2011 at 6:57 PM
		</div>
		<div class="comment_text"><p>lol.</p><p>Actually for this PCI compliance project my boss was bugging me a bit because in Dreamweaver you can export search results. I was hoping that there was an easy way to do it in Builder, or for that matter Eclipse in general. I guess I'm just going to have to bite the bullet and look into writing and extension. Along with everything else I have to do. Who needs sleep anyhow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731979">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731979">9</a> by Raymond Camden
		posted on 6/17/2011 at 7:00 PM
		</div>
		<div class="comment_text"><p>Heh, an extension could be done to do this in like 5 minutes. Want to race? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731983">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731983">10</a> by larry c lyons
		posted on 6/17/2011 at 7:01 PM
		</div>
		<div class="comment_text"><p>Well given that I haven't tried writing an extension yet, I'll concede the race.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731989">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731989">11</a> by Raymond Camden
		posted on 6/17/2011 at 7:05 PM
		</div>
		<div class="comment_text"><p>Larry, you can start writing an extension right away. It's easy. I've got a recorded session on it actually. Give it a shot. I'll be more than happy to help you (via direct email). I think this could be a cool little extension.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731991">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731991">12</a> by larry c lyons
		posted on 6/17/2011 at 7:26 PM
		</div>
		<div class="comment_text"><p>At best I might be able to get started this weekend. But until we bet this PCI compliance stuff done I'm swamped.</p><p>Actually I've been meaning to learn how. I use a fair number of extensions already (appcfc, cfquickdocs, cflib, apptacular etc). But I've been meaning to write one that helps me set up the initial work on a new site.</p></div>
	</div>
</div>
		