
<div class="comment" id="c_1713684382">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684382">1</a> by shag
		posted on 7/15/2008 at 11:11 PM
		</div>
		<div class="comment_text"><p>the great jedi master has syntax errors?!? gasp...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684396">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684396">2</a> by Raymond Camden
		posted on 7/16/2008 at 2:14 AM
		</div>
		<div class="comment_text"><p>Many...</p></div>
	</div>
</div>
		