
<div class="comment" id="c_1713748172">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748172">1</a> by Troy Murray
		posted on 9/10/2013 at 6:13 PM
		</div>
		<div class="comment_text"><p>Sorry if I'm not seeing this, but do you have a repo of this code shared anywhere?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713748171">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748171">2</a> by Raymond Camden
		posted on 9/10/2013 at 6:42 PM
		</div>
		<div class="comment_text"><p>I do not - but here is a copy of the app.js. It is a bit messy as I was using it in multiple ways for the blog post.</p><p><a href="https://disq.us/url?url=https%3A%2F%2Fgist.github.com%2Fcfjedimaster%2F6510670%3Ap9eS9io68Kr5vra8YZyUy9Oul8k&amp;cuid=3321886" rel="nofollow noopener" title="https://gist.github.com/cfjedimaster/6510670">https://gist.github.com/cfj...</a></p></div>
	</div>
</div>
		