
<div class="comment" id="c_1713668502">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668502">1</a> by Randy
		posted on 7/16/2007 at 6:29 PM
		</div>
		<div class="comment_text"><p>I just figured this out over the weekend too.  I did not read the directions to thoroughly before setting up the snipex server, so it wasn't working correctly.  I ended up doing a search for the snipex server name  or something inside the workspace directly, deleted those files and to my suprise it was working when I restarted cfeclipse.  Pretty darn neat how it works.  I connected CFLib and it worked great too.</p><p>-Randy</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668486">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668486">2</a> by Mark Drew
		posted on 7/16/2007 at 7:31 PM
		</div>
		<div class="comment_text"><p>you dont need to restart Eclipse, you can just click the refresh snippets icon and it will do the same thing.</p><p>I have added (in the code, not a release yet) a dialog that asks you if you want to delete your snipex cache too when you click the refresh button... so that should help.</p><p>As a note, I have also started a snipex mailinglist over at google: <a href="http://disq.us/url?url=http%3A%2F%2Fgroups.google.com%2Fgroup%2Fcfeclipse-snipex%3AF7hIbbzGz_UK_kvja6MlUnJQ-hk&amp;cuid=3321886" rel="nofollow noopener" title="http://groups.google.com/group/cfeclipse-snipex">http://groups.google.com/gr...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713668500">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713668500">3</a> by Raymond Camden
		posted on 7/16/2007 at 7:34 PM
		</div>
		<div class="comment_text"><p>Nice, thanks for the clarification there. Certainly the 'restart eclipse' part was the slowest, so that makes things nicer!</p></div>
	</div>
</div>
		