
<div class="comment" id="c_1713735856">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735856">1</a> by Dan G. Switzer, II
		posted on 10/19/2011 at 5:48 PM
		</div>
		<div class="comment_text"><p>Gloss seems not quite ready for primetime. I'm seeing lots of issues with the searching. They definitely need to at least debounce their keypress events for searching. That would drastically reduce the calls to the server, which would help with load. I'm seeing tons of delays and weird behaviors due to the backlog of AJAX requests being filled--which debouncing would fix.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735844">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735844">2</a> by Mike Henke
		posted on 10/19/2011 at 6:53 PM
		</div>
		<div class="comment_text"><p>Thanks for the mention of the new podcast. We are going to give it a 3 episode try then re-evaluate. People can get the mp3 here <a href="http://disq.us/url?url=http%3A%2F%2Fcoldfusionshow-podcast.s3.amazonaws.com%2F111016-1.mp3%3A95vgrLghE02yRKwg_kLtqZ5w2xk&amp;cuid=3321886" rel="nofollow noopener" title="http://coldfusionshow-podcast.s3.amazonaws.com/111016-1.mp3">http://coldfusionshow-podca...</a> My site is a little confusing, with an auto generated audio file of blog posts. We'll get <a href="http://disq.us/url?url=http%3A%2F%2Fcoldfusionshow.com%3AZPhTvQitgvtogCUBGEgwCihrrrM&amp;cuid=3321886" rel="nofollow noopener" title="coldfusionshow.com">coldfusionshow.com</a> up and going soon.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735857">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735857">3</a> by roger tubby
		posted on 10/20/2011 at 3:18 AM
		</div>
		<div class="comment_text"><p>I think Gloss looks really good. I didn't have any problems with AJAX delays; perhaps they have been ameliorated. I was just in the process of building a little DataTables web page to display Ray's great CFLib (and export as a spreadsheet) but I may put this effort on hold and enjoy Gloss.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735859">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735859">4</a> by Aaron DeRenard
		posted on 10/20/2011 at 6:00 PM
		</div>
		<div class="comment_text"><p>I'm really glad to see cfgloss stuck with you... since I mentioned it way back in March.  I sure hope you have been using it all this time, and not just now rediscovering it.  :-P  <br>I use it all the time.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Findex.cfm%2F2011%2F3%2F23%2FNew-ColdFusion-Security-resource%23c130C18D1-C140-0974-0CE775E860E9D059%3AYZd5pL2ee4EOcIvjp6iiLOTNBto&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/index.cfm/2011/3/23/New-ColdFusion-Security-resource#c130C18D1-C140-0974-0CE775E860E9D059">http://www.coldfusionjedi.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735861">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735861">5</a> by existdissolve
		posted on 10/20/2011 at 8:22 PM
		</div>
		<div class="comment_text"><p>Thanks for posting about Gloss, Ray, and thanks everyone (here and on the Twitter) for the feedback.</p></div>
	</div>
</div>
		