
<div class="comment" id="c_1713667840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667840">1</a> by Ben Forta
		posted on 6/27/2007 at 7:01 PM
		</div>
		<div class="comment_text"><p>It's 100% ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667856">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667856">2</a> by Kyle Hayes
		posted on 6/27/2007 at 10:27 PM
		</div>
		<div class="comment_text"><p>Heh, you didn't sound too sure up there. :-P</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667855">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667855">3</a> by Ken Dunnington
		posted on 6/28/2007 at 1:00 AM
		</div>
		<div class="comment_text"><p>Now this makes me really curious what the separate editions of CF8 will include. My company is finally buying a new license of CF for internal projects, and I obviously want to get 8, but the uncertainty around editions and upgrade paths is frustrating, especially since we're doing a large equipment purchase, so holding off is difficult. Oh what I wouldn't give for a "pre-order now" button on the Adobe store! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667860">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667860">4</a> by Chris Leman
		posted on 6/28/2007 at 2:41 AM
		</div>
		<div class="comment_text"><p>I totally agree with Ken.  Pre-orders are a must unless you are planning to go OPEN-SOURCE! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667859">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667859">5</a> by Dale Fraser
		posted on 6/28/2007 at 5:28 AM
		</div>
		<div class="comment_text"><p>I have to agree,</p><p>I just ran a Survey here in australia on the cfaussie list, one of the questions was will you be upgrading to CF8</p><p>Yes	 75.4%<br>No	 3.3%<br>Unsure	 21.3%</p><p>Which is really good for CF8, but I think even though Adobe might not want to set a launch date yet, it's about time some pricing of editions was released, people need to plan and budget for these types of purchases</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667861">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667861">6</a> by Tim Smith
		posted on 6/28/2007 at 8:08 AM
		</div>
		<div class="comment_text"><p>I agree about the need for a known upgrade path (i.e. costs). I am delaying purchasing CF Enterprise versions as long as possible even investigating installing evaluation version for a production app to "buy some time". I have a new project going live August sadly we are not allowed to "enhance" to CF8:(  for this app because of the beta status but would love to CF8 available asap)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667858">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667858">7</a> by Daniel Budde II
		posted on 6/28/2007 at 8:08 PM
		</div>
		<div class="comment_text"><p>On Adobe's prerelease site there was a document outlining the differences in Enterprise and Standard.  This document listed that Gateways are now in Standard, but they are limited.  I have the PDF of the document, but I am unsure if the EULA allows me to pass it on or not.  I'm assuming NOT atm.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667845">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667845">8</a> by Jay
		posted on 6/28/2007 at 9:39 PM
		</div>
		<div class="comment_text"><p>I loved the whole Gateways thing in Cf7 but really struggled with some of the Java involved. I tried to follow a walkthrough and get a gateway to respond to incoming emails and stuff...i failed miserably...are we gonna see any more enhancements to the gateway stuff or is it just that it's not included in the standard version?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667857">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667857">9</a> by Raymond Camden
		posted on 7/1/2007 at 6:23 AM
		</div>
		<div class="comment_text"><p>Jay, are you asking if the _api_ is changing? If so - it isn't as far as I know. If you are really interested in _writing_ EGs, then I'd suggest just learning Java.</p></div>
	</div>
</div>
		