
<div class="comment" id="c_2681978119">
	<div>
		<img src="https://disqus.com/api/users/avatars/richardshergold.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2681978119">1</a> by Richard Shergold
		posted on 5/18/2016 at 12:58 PM
		</div>
		<div class="comment_text"><p>Ray, thanks for this.  I'm at the exact same stage as you.  Very happy with Ionic and loving Ionic 2 but also interested in NativeScript and what it can offer.  I think having both tools in the toolkit will be very handy.  I think it looks great - I particularly like the way it works so well with Angular 2.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2681981253">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2681981253">2</a> (In reply to <a href="#c_2681978119">#1</a>) by Raymond Camden
		posted on 5/18/2016 at 1:01 PM
		</div>
		<div class="comment_text"><p>Yeah I need to look into that next. (The Angular2 part I mean.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_2681987240">
	<div>
		<img src="https://disqus.com/api/users/avatars/richardshergold.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2681987240">3</a> (In reply to <a href="#c_2681981253">#2</a>) by Richard Shergold
		posted on 5/18/2016 at 1:05 PM
		</div>
		<div class="comment_text"><p>This is worth a watch <a href="https://disq.us/url?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Defk_oeI58hc%26feature%3Dyoutu.be%3AvxEO5AZ7AIXpfQmDo1dQuFq-Cz4&amp;cuid=3321886" rel="nofollow noopener" title="https://www.youtube.com/watch?v=efk_oeI58hc&amp;feature=youtu.be">https://www.youtube.com/wat...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_2687164728">
	<div>
		<img src="https://disqus.com/api/users/avatars/mark_chipman.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2687164728">4</a> by Mark Chipman
		posted on 5/20/2016 at 10:47 PM
		</div>
		<div class="comment_text"><p>Do you mind sharing the install issue you were having... I'm having install issues and wondering if they are similar?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2687340085">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2687340085">5</a> (In reply to <a href="#c_2687164728">#4</a>) by Raymond Camden
		posted on 5/21/2016 at 1:42 AM
		</div>
		<div class="comment_text"><p>I didn't have this env variable: ANDROID_HOME. What's odd is that it didn't impact Cordova at all. Then when I added it, I added it with a / at the end. I had to remove the / for it to work.</p></div>
	</div>
</div>
		