
<div class="comment" id="c_1713680618">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680618">1</a> by Tariq Ahmed
		posted on 5/3/2008 at 6:45 PM
		</div>
		<div class="comment_text"><p>Ya the movie has been doing really well on IMDB. 8.3 last I checked!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680637">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680637">2</a> by Luke Kilpatrick
		posted on 5/3/2008 at 10:48 PM
		</div>
		<div class="comment_text"><p>Ok, where is the picture??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680638">3</a> by Raymond Camden
		posted on 5/3/2008 at 10:50 PM
		</div>
		<div class="comment_text"><p>Ooops. I'll hook it up tonight.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680634">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680634">4</a> by Fernando Lopez
		posted on 5/4/2008 at 2:29 AM
		</div>
		<div class="comment_text"><p>Anybody knows where the Flickr group for cfobjective is? I have a couple pictures from the outing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680636">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680636">5</a> by patrick
		posted on 5/7/2008 at 6:54 AM
		</div>
		<div class="comment_text"><p>Iron Man was practically flawless as a super hero flick; it drops pretty obvious hints that would indicate a sequel as well... i'm thinking the next one should be equally great</p></div>
	</div>
</div>
		