
<div class="comment" id="c_1713681310">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681310">1</a> by James Edmunds
		posted on 5/30/2008 at 7:36 PM
		</div>
		<div class="comment_text"><p>The link for slidesx seems to be broken... and now you've made me curious to check it out! Thanks in advance...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681295">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681295">2</a> by Raymond Camden
		posted on 5/30/2008 at 7:42 PM
		</div>
		<div class="comment_text"><p>fixed. funny how urls don't work well w/o a protocol :)</p></div>
	</div>
</div>
		