
<div class="comment" id="c_1713685133">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685133">1</a> by Chris
		posted on 8/19/2008 at 9:51 AM
		</div>
		<div class="comment_text"><p>Hmmm, I don't know about those panel members...   I don't know i want to come to the "unconference" to listen to a bunch of noobs talk about cflooping through a list.</p><p>On another note Ray, are you keeping track of people who plan on attending the unconference?  Is there any unconference protocols I need to know?  Upside-down badges?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685136">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685136">2</a> by Raymond Camden
		posted on 8/19/2008 at 2:49 PM
		</div>
		<div class="comment_text"><p>There is nothing special needed to attend - you just walk in. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685138">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685138">3</a> by Brian Swartzfager
		posted on 8/19/2008 at 4:01 PM
		</div>
		<div class="comment_text"><p>A better answer would have been:  CF tattoos will be checked at the door.  :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685139">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685139">4</a> by Raymond Camden
		posted on 8/19/2008 at 4:14 PM
		</div>
		<div class="comment_text"><p>If Mark Drew was going, he would be lonely up there. ;) (Unless we switch to just a tattoo check, then I'm gold!)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685137">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685137">5</a> by Brian Swartzfager
		posted on 8/19/2008 at 4:20 PM
		</div>
		<div class="comment_text"><p>I'll bet Mark could handle being the only one up there, and you'd know he have some interesting answers for the audience.  :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685141">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685141">6</a> by tony of the weeg clan
		posted on 8/28/2008 at 6:07 PM
		</div>
		<div class="comment_text"><p>even tho the speaker list is weak, im going to come :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685140">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685140">7</a> by Raymond Camden
		posted on 8/28/2008 at 6:11 PM
		</div>
		<div class="comment_text"><p>I should add - Brian Meloche is going to be the host now, and will be recording it for a cfconversations podcast. For those who can't make it - you will still be able to hear it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685142">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685142">8</a> by Brian Swartzfager
		posted on 8/28/2008 at 6:28 PM
		</div>
		<div class="comment_text"><p>For those of us who probably won't make it to MAX, that's very good news.</p></div>
	</div>
</div>
		