
<div class="comment" id="c_1713717339">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713717339">1</a> by Dan Vega
		posted on 7/22/2009 at 6:41 PM
		</div>
		<div class="comment_text"><p>You know you have an open invite to sit in!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713717346">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713717346">2</a> by Raymond Camden
		posted on 7/22/2009 at 6:42 PM
		</div>
		<div class="comment_text"><p>Tuesday I hope to be drinking a beer by the pool. All day.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713717347">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713717347">3</a> by Phillip Senn
		posted on 7/28/2009 at 9:39 PM
		</div>
		<div class="comment_text"><p>D'oh!</p></div>
	</div>
</div>
		