
<div class="comment" id="c_1713650838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650838">1</a> by tony petruzzi
		posted on 3/16/2006 at 7:01 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Gotta ask this question. Why do you use CFLOCK as apposed to CFTRANSACTION?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650826">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650826">2</a> by Raymond Camden
		posted on 3/16/2006 at 7:06 PM
		</div>
		<div class="comment_text"><p>Hmm, good question. That would handle it as well. To be honest, I just didn't think of it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650841">3</a> by Ron Phillips
		posted on 3/16/2006 at 7:32 PM
		</div>
		<div class="comment_text"><p>I can't find the zip file?</p><p>I am enjoying this blow-by-blow style, by the way. So many times tutorials make it look like the author went straight to the bottom line, without all the false starts, do-overs, etc. that I usually run into.</p><p>Ron</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650840">4</a> by Raymond Camden
		posted on 3/16/2006 at 7:37 PM
		</div>
		<div class="comment_text"><p>Below the main entry text, above the big old ad, you will see some links, one is "Download". Click on that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650847">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650847">5</a> by tony of the weeg clan
		posted on 3/16/2006 at 8:03 PM
		</div>
		<div class="comment_text"><p>see im not crazy, that is just not an intuitive download link, there is nothing to tell you what you are downloading ray :)</p><p>tw</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650845">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650845">6</a> by Dave Carabetta
		posted on 3/17/2006 at 1:12 AM
		</div>
		<div class="comment_text"><p>Ray, is something missing from this last sentence?</p><p>"If you thought all these CFCs were overkill, you may want to check out "</p><p>Unless you're nicely asking me to "check out" of reading the series! ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650851">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650851">7</a> by Raymond Camden
		posted on 3/17/2006 at 1:18 AM
		</div>
		<div class="comment_text"><p>Oops. I was going to talk a bit about Reactor and completely forgot. I'm going to edit the entry to remote it for now. I wonder why this entyr got so few comments. People bored already? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650843">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650843">8</a> by Dave Carabetta
		posted on 3/17/2006 at 1:46 AM
		</div>
		<div class="comment_text"><p>Actually, I think some people just hate you ;) :</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.cbetta.com%2Fblog%2Findex.cfm%2F2006%2F3%2F16%2Fi-hate-ray-camden%3ADbAQmm7AwVImklMc5z3BaSbQJDI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.cbetta.com/blog/index.cfm/2006/3/16/i-hate-ray-camden">http://www.cbetta.com/blog/...</a></p><p>Honestly, this article got pushed down by your Network Troubles posting, so I might have missed this if not for my FeedDemon listing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650857">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650857">9</a> by Dave Carabetta
		posted on 3/17/2006 at 1:53 AM
		</div>
		<div class="comment_text"><p>OK, I should really sum up my thoughts before inflating your comments stats! One thing you might want to point out is that your use of the isValid() function in the User Bean implicitly makes this a CFMX 7-only application. That may trip up some people.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650842">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650842">10</a> by Raymond Camden
		posted on 3/17/2006 at 1:57 AM
		</div>
		<div class="comment_text"><p>Nice post there Dave. ;) In the next post I'll mention the CFMX7 code (if I remember).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650844">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650844">11</a> by Michael White
		posted on 3/17/2006 at 6:06 AM
		</div>
		<div class="comment_text"><p>today is the first day I'm actually working on this. I setup model glue (first part) and i'm walking through the second part and I just printed out the third part and downloaded the code... i'm just a little behind. You're a Model-Glue hero!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650846">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650846">12</a> by Jesse
		posted on 3/17/2006 at 9:40 AM
		</div>
		<div class="comment_text"><p>You mentioned an install.sql file when talking about the Users table, but I didn't see it in your zip file. Am I blind or is there another download besides <a href="http://disq.us/url?url=http%3A%2F%2Fwwwroot2.zip%3F%3AM3fgEIJxpTRklwv6g9nFGdB7Nq8&amp;cuid=3321886" rel="nofollow noopener" title="wwwroot2.zip?">wwwroot2.zip?</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650852">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650852">13</a> by Raymond Camden
		posted on 3/17/2006 at 4:44 PM
		</div>
		<div class="comment_text"><p>Yep. I did forget. It's in the zip attached to the fourth entry.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650849">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650849">14</a> by Tim Forcelle
		posted on 3/17/2006 at 8:33 PM
		</div>
		<div class="comment_text"><p>Wondering in the userDAO.cfc that in the queries checkUsername and insRec for the datasource you use #variables.dsn# and in the other queries in cfc you use #dsn# for the datasource.  Wondering if it will work both ways?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650854">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650854">15</a> by Tim Forcelle
		posted on 3/17/2006 at 8:37 PM
		</div>
		<div class="comment_text"><p>Also noticed that you do not have the name parameter for the delete and update queries.  Is this a typo and I should use name="delete" and name="update" or am I off the mark and not understanding something?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650848">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650848">16</a> by Raymond Camden
		posted on 3/17/2006 at 8:43 PM
		</div>
		<div class="comment_text"><p>It should definitely be all variables.dsn. That's a mistake on my part. Will correct it for entry 5.</p><p>You do not need to use the name property for cfquery if you aren't returning a query.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650850">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650850">17</a> by Michael White
		posted on 3/23/2006 at 7:16 AM
		</div>
		<div class="comment_text"><p>I've been away on other projects for a few days and I'm coming back to the model-glue thingy... I had to start over from the very beginning (memento effect, maybe i should get some tattoos) anyway, I know you said the model- stuff you did in this section is not specific to model glue but that cfc structure is WAY different than I do and I was wondering if you had some reference to help me understand why you do it that way and why it works. the Argument type="userBean" is a new way to handle creating a new record not to mention the invoke in the read method. (You're freaking me out, man!)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650828">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650828">18</a> by Trond Ulseth
		posted on 3/24/2006 at 6:39 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Great series!</p><p>I noticed the following:</p><p>In the DAO update and delete methods you use:</p><p>where id = &lt;cfqueryparam cfsqltype="cf_sql_int" value="#arguments.bean.getID()#"&gt;</p><p>In the bean however there is no getID() method, and also there is no id field in the db table you outlined.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650827">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650827">19</a> by Raymond Camden
		posted on 3/24/2006 at 7:04 PM
		</div>
		<div class="comment_text"><p>Bug! I'll fix it in the next release. The article is about 60% done. It's another big one (4 pages so far).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650834">20</a> by Scott Krebs
		posted on 3/25/2006 at 7:56 AM
		</div>
		<div class="comment_text"><p>Hi Ray,<br>Great stuff! Thanks for sharing.</p><p>For the cflock vs cftransaction mentioned above, perhaps bears mentioning in your final "things to maybe do differently" segment it would be worth mentioning that (if the DBMS being used supports it) replacing the code between the cflock tags with a stored procedure would be compelling in high-load situations. It couples your CF app more tightly with the DBMS, but the potential performance gains of offloading transactions like that one to the database engine should also be considered where it's appropriate. Just an .02, fire back if I'm wrong. :)</p><p>Thanks again, I have to ramp up on  MG in a very short time frame and I very much appreciate your insights.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650833">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650833">21</a> by Raymond Camden
		posted on 3/25/2006 at 7:08 PM
		</div>
		<div class="comment_text"><p>Scott, yeah, good point. I tend to not use SPs as much as I should. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650831">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650831">22</a> by sal
		posted on 5/4/2006 at 6:26 AM
		</div>
		<div class="comment_text"><p>Hello.<br>Just a quick simple cfc question. when you passed the userBean argument to the create(); in your userDAO.cfc, is that another method of inheriting the userBean.cfc rather than extending it?</p><p>thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650836">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650836">23</a> by Raymond Camden
		posted on 5/4/2006 at 5:28 PM
		</div>
		<div class="comment_text"><p>Sal. I'm not quite sure I get you. This has nothing to do with inheritance. The bean simply acts like "one record" of data. I pass it the DAO so that the DAO can persist the data to the db.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650835">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650835">24</a> by sal
		posted on 5/5/2006 at 9:29 AM
		</div>
		<div class="comment_text"><p>ahh I see. Thanks for the clarification!<br>any supurb docs on beans Ray??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650853">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650853">25</a> by Raymond Camden
		posted on 5/5/2006 at 3:22 PM
		</div>
		<div class="comment_text"><p>I'd check Joe Reinhart's blog. I don't have his URL handy, but he has some articles. And he is the creator Model-Glue.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650855">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650855">26</a> by sal
		posted on 5/5/2006 at 5:21 PM
		</div>
		<div class="comment_text"><p>right</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650856">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650856">27</a> by Trond Ulseth
		posted on 5/5/2006 at 10:33 PM
		</div>
		<div class="comment_text"><p>If you did not find it yet, or just for those coming by at a later time, here's the url to Joe's blog where he talks about beans:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fclearsoftware.net%2Findex.cfm%3Fmode%3Dentry%26entry%3D207096B8-E081-2BAC-697F878438AD8E6A%3AsYNLRHxGgZZkApdRrm6f4dvfkB8&amp;cuid=3321886" rel="nofollow noopener" title="http://clearsoftware.net/index.cfm?mode=entry&amp;entry=207096B8-E081-2BAC-697F878438AD8E6A">http://clearsoftware.net/in...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650859">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650859">28</a> by mike
		posted on 1/22/2007 at 10:08 PM
		</div>
		<div class="comment_text"><p>"I'm not going to spend a lot of time talking about how I set up the User model, since that could be a series to itself"</p><p>that would be awesome... or if you know if such a series exists, let us know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650858">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650858">29</a> by Raymond Camden
		posted on 1/23/2007 at 1:48 AM
		</div>
		<div class="comment_text"><p>I didn't even discuss how I do my model. To answer in a short blog comment, I typically have a Bean, DAO, and Gateway CFC to separate my model based on a domain (think "content area" like user, product, etc). Most of my apps follow this format.</p></div>
	</div>
</div>
		