
<div class="comment" id="c_1713675879">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675879">1</a> by Nick
		posted on 1/3/2008 at 8:34 PM
		</div>
		<div class="comment_text"><p>You know me, I would have gone a step farther and generated some ridiculous graph.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675886">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675886">2</a> by RobW
		posted on 1/3/2008 at 9:22 PM
		</div>
		<div class="comment_text"><p>Not enough posts about Lost, but you can make up for that in 28 days ;^)</p></div>
	</div>
</div>
		