
<div class="comment" id="c_1713709937">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709937">1</a> by todd sharp
		posted on 11/17/2008 at 10:39 PM
		</div>
		<div class="comment_text"><p>I hear they've already started on the mobile stuff....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709945">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709945">2</a> by todd sharp
		posted on 11/17/2008 at 11:01 PM
		</div>
		<div class="comment_text"><p>How are the chairs Ray? :D</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709946">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709946">3</a> by Edward Smith
		posted on 11/17/2008 at 11:07 PM
		</div>
		<div class="comment_text"><p>Cloudfusion?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709950">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709950">4</a> by Darrell
		posted on 11/17/2008 at 11:13 PM
		</div>
		<div class="comment_text"><p>Nice cameo in the mix there Ray - "Boggles the mind"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709951">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709951">5</a> by Scott P
		posted on 11/17/2008 at 11:29 PM
		</div>
		<div class="comment_text"><p>what - no arnold?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709956">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709956">6</a> by Mike Henke
		posted on 11/17/2008 at 11:39 PM
		</div>
		<div class="comment_text"><p>I am hoping Adobe announces a Amazon Machine Image (AMI) of ColdFusion like Railo's for Amazon Elastic Compute Cloud (Amazon EC2) with some type of price structure similiar to. <a href="http://disq.us/url?url=http%3A%2F%2Ftinyurl.com%2F59wk36%3AjuIFq7l_drMyBjNE2f3sIggSimY&amp;cuid=3321886" rel="nofollow noopener" title="http://tinyurl.com/59wk36">http://tinyurl.com/59wk36</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709958">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709958">7</a> by Jeff
		posted on 11/17/2008 at 11:50 PM
		</div>
		<div class="comment_text"><p>Wireless sucked last year too.. Wish I was there. Awaiting some updates Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709955">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709955">8</a> by Steve Gongage
		posted on 11/17/2008 at 11:50 PM
		</div>
		<div class="comment_text"><p>Yikes... nothing on ColdFusion huh?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709957">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709957">9</a> by Steve Gongage
		posted on 11/17/2008 at 11:52 PM
		</div>
		<div class="comment_text"><p>Oops... just noticed its still going on.  Ok, fingers crossing again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709938">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709938">10</a> by Bob
		posted on 11/17/2008 at 11:57 PM
		</div>
		<div class="comment_text"><p>@steve... its rumored that CF announcements will take place during the second keynote address tomorrow...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709940">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709940">11</a> by Raymond Camden
		posted on 11/18/2008 at 12:03 AM
		</div>
		<div class="comment_text"><p>CF will definitely be tomorrow, which is pretty standard. First day more high level, designer-y (I made that word up), the next day more product-y.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709941">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709941">12</a> by Mark Mazelin
		posted on 11/18/2008 at 12:17 AM
		</div>
		<div class="comment_text"><p>Ray -- thanks for sharing! I'll be watching your blog as I couldn't make MAX this year. Thanks for keeping us up-to-date!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709942">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709942">13</a> by Steve Gongage
		posted on 11/18/2008 at 12:35 AM
		</div>
		<div class="comment_text"><p>@Bob &amp; @Ray: Thanks for letting me know.  I am no longer depressed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709944">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709944">14</a> by Jake Munson
		posted on 11/18/2008 at 12:40 AM
		</div>
		<div class="comment_text"><p>"Kevin showed the iPhone and said they ARE working on it. I don't think that's news though, is it? I thought that was already out there?"</p><p>The rumor I heard is that Adobe has a Flash player ready for the iPhone, but Steve Jobs won't allow it into the app store.  Remember that "Flash is slow" comment from Mr. Jobs?  My guess is that "we ARE working on it" means that they are trying to find out how much money they have to pay Apple to get the Flash player into the <br>app store.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709949">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709949">15</a> by Mark Lapasa
		posted on 11/18/2008 at 12:47 AM
		</div>
		<div class="comment_text"><p>Great coverage so far. Thx!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709947">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709947">16</a> by Alirio Boquín
		posted on 11/18/2008 at 1:15 AM
		</div>
		<div class="comment_text"><p>Hi</p><p>Again thanks for sharing, your notes Raymond.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709952">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709952">17</a> by Derek
		posted on 11/18/2008 at 2:31 AM
		</div>
		<div class="comment_text"><p>I am hoping for a CF IDE announcement tomorrow!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709953">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709953">18</a> by Jonathan
		posted on 11/18/2008 at 5:41 AM
		</div>
		<div class="comment_text"><p>Two of the CF team were in the last session. someone asked what was new in 9. There will be announcements tomorrow...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713709954">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709954">19</a> by DanaK
		posted on 11/18/2008 at 9:48 PM
		</div>
		<div class="comment_text"><p>I'll be curious to see Adobe Wave some more. Mostly I want to see the differences with the products out there already. I have one on my iphone that pulls in all the major social platforms now (including facebook and twitter I believe?)</p></div>
	</div>
</div>
		