
<div class="comment" id="c_1713650136">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650136">1</a> by thinman
		posted on 2/15/2006 at 3:58 AM
		</div>
		<div class="comment_text"><p>Well said, oh Cranky One.  I agree.  Who wants to get busted gobbling up the boss's bandwidth when it's such a simple thing to NOT AUTOPLAY.  Except I'm the boss, and I'm ALWAYS pulling one over on myself. Wait. Oh, nevermind.  If I dont's want something to play, don't override me.  Why give me the choice?  I feel so USED.  Cheated.  MOCKED, even. Travesty!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650138">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650138">2</a> by Michael White
		posted on 2/15/2006 at 3:58 AM
		</div>
		<div class="comment_text"><p>I think they just didn't think it through. I'm sure the developer was thinking... I'll make this foolproof so the user doesn't sit there and wonder what to do.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650134">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650134">3</a> by Josh Tynjala
		posted on 2/15/2006 at 4:00 AM
		</div>
		<div class="comment_text"><p>I'm with you all the way. If I turn off auto-play, it better damn well not play until I press the play button!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650122">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650122">4</a> by Rob Cameron
		posted on 2/15/2006 at 4:31 AM
		</div>
		<div class="comment_text"><p>I didn't even know that turning off auto-play was an option!  Firefox gets better every day.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650137">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650137">5</a> by Raymond Camden
		posted on 2/15/2006 at 4:52 AM
		</div>
		<div class="comment_text"><p>Rob, that isn't a Firefox thing, but a Quicktime thing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650139">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650139">6</a> by PaulC
		posted on 2/15/2006 at 5:04 AM
		</div>
		<div class="comment_text"><p>As a rule, shouldn't user prefs override developer prefs? Isn't that the point of having user-defined preferences to begin with?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650140">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650140">7</a> by Matthew Wyant
		posted on 2/15/2006 at 5:22 AM
		</div>
		<div class="comment_text"><p>I don't know much about media files and the DOM, but could this be fixed with a Greasemonkey script? Anyone? Anyone?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650143">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650143">8</a> by Scott Stroz
		posted on 2/15/2006 at 7:31 AM
		</div>
		<div class="comment_text"><p>You can be cranky and have a valid point, they are not mutually exclusive ;-)</p></div>
	</div>
</div>
		