
<div class="comment" id="c_1713615584">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615584">1</a> by seancorfield
		posted on 4/12/2004 at 7:41 PM
		</div>
		<div class="comment_text"><p>I enjoyed your interview... Looking forward to chatting at the conference!</p></div>
	</div>
</div>
		