
<div class="comment" id="c_1713739154">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739154">1</a> by Don Vawter
		posted on 2/23/2012 at 8:39 PM
		</div>
		<div class="comment_text"><p>Now just add a handler for the onClose event to unsubscribe the user so the active users count remains accurate (or is this handled automatically?)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739166">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739166">2</a> by Evelin Varghese
		posted on 2/23/2012 at 9:54 PM
		</div>
		<div class="comment_text"><p>@Ray: <br>That was a good experiment to put another websocket call in message handler. :)<br>@Don: subscriber count is automatically calculated on subscribe and unsusbcribe.Also onclose event is fired on closing the WebSocket Connection.Not on unsubscribe.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739170">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739170">3</a> by Nuri Cevik
		posted on 2/27/2012 at 10:29 PM
		</div>
		<div class="comment_text"><p>Hi Ray, <a href="http://disq.us/url?url=http%3A%2F%2Fraymondcamden.com%2Fdemos%2F2012%2Ffeb%2F19%2Fchat%2F%3AZ5FVUhpZRwqShX_cNlXjaiDlPCo&amp;cuid=3321886" rel="nofollow noopener" title="http://raymondcamden.com/demos/2012/feb/19/chat/">http://raymondcamden.com/de...</a> throwing error</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739163">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739163">4</a> by Raymond Camden
		posted on 2/27/2012 at 10:30 PM
		</div>
		<div class="comment_text"><p>Hey Nuri - I had to remove CF10 from the server due to a bug with IIS (CF10 is in beta after all ;). I'll hopefully be up and running soon. If you want a copy of the code, let me know, I'll gladly put it up.</p></div>
	</div>
</div>
		