
<div class="comment" id="c_1713728989">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728989">1</a> by Matt W
		posted on 1/19/2011 at 7:50 PM
		</div>
		<div class="comment_text"><p>You could offer to present on HTML 3 and optimized table-based layouts and we would want to attend. Do it!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728971">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728971">2</a> by Raymond Camden
		posted on 1/19/2011 at 7:54 PM
		</div>
		<div class="comment_text"><p>Long live tables!</p></div>
	</div>
</div>
		