
<div class="comment" id="c_1713682655">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682655">1</a> by Terry Palmer
		posted on 7/9/2008 at 4:46 PM
		</div>
		<div class="comment_text"><p>Hey Ray.  Just wanted to drop a line about the cookie errors in the logs.  The option that worked for us was to set the setclientcookies to false in the cfapplication tag.  We were already on j2ee sessions and it was an easy change for us to make.  We no longer see the cookie errors in our logs.  So if that is a viable option for you, its a decent work around.  Jochem hit it on the head though.</p></div>
	</div>
</div>
		