
<div class="comment" id="c_1713666992">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666992">1</a> by Tom Chiverton
		posted on 6/13/2007 at 5:44 PM
		</div>
		<div class="comment_text"><p>Not to but the Teratech folks down, but CFUnited isn't the <br>"only conference of its kind that is run by developers" - there's CFDevCon (now in it's 2nd year) for instance, never mind Scotch On The Rocks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667066">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667066">2</a> by Kevin Roche
		posted on 6/13/2007 at 7:07 PM
		</div>
		<div class="comment_text"><p>Dates are 12th and 13th March 2008.</p></div>
	</div>
</div>
		