
<div class="comment" id="c_1713616189">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616189">1</a> by Critter
		posted on 9/10/2004 at 5:15 PM
		</div>
		<div class="comment_text"><p>danke sir.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616173">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616173">2</a> by Ben Forta
		posted on 9/10/2004 at 5:46 PM
		</div>
		<div class="comment_text"><p>See, if you stay with the old version like me then this is not even an issue. ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616170">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616170">3</a> by Critter
		posted on 9/10/2004 at 6:39 PM
		</div>
		<div class="comment_text"><p>ha, but /this/ version is /my/ old version!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616192">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616192">4</a> by Sean Corfield
		posted on 9/11/2004 at 7:58 AM
		</div>
		<div class="comment_text"><p>Yeah, I had to fix this locally. I also have a small fix to editor.cfm which allows you to do a bookmarklet that takes the current web page and turn it into a blog entry... basically just changing cfparam for title / body to default to URL params (and adding cfparams for those).</p></div>
	</div>
</div>
		