
<div class="comment" id="c_1713709924">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713709924">1</a> by James Edmunds
		posted on 11/16/2008 at 8:25 AM
		</div>
		<div class="comment_text"><p>Those of us who aren't making it to MAX are grateful that you will be keeping us all well informed!</p></div>
	</div>
</div>
		