
<div class="comment" id="c_1713711473">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711473">1</a> by Emanuel Costa
		posted on 1/15/2009 at 10:20 PM
		</div>
		<div class="comment_text"><p>Hi Ray, I went to your presentation and was really nice. I really liked the tip about coldfire and I am already using on CF 7 standard on windows without a problem. Do you know by any chance when we could have the exception information (or tab). I mean that information that shows on CF debug then we have try/catch and one exception is given. Please let me know. Thanks a lot! Look forward meeting you again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711487">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711487">2</a> by Raymond Camden
		posted on 1/15/2009 at 10:32 PM
		</div>
		<div class="comment_text"><p>Not sure. Let me ping Nathan.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711490">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711490">3</a> by Nathan Mische
		posted on 1/15/2009 at 10:39 PM
		</div>
		<div class="comment_text"><p>If the classic.cfm debugging template does it we should be able to do it with ColdFire. The only thing I'm concerned about is running out of real estate to put all of the ColdFusion sub tabs... I'll definitely look into it for the next release.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711491">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711491">4</a> by Emanuel Costa
		posted on 1/15/2009 at 10:45 PM
		</div>
		<div class="comment_text"><p>Cool Thanks!</p></div>
	</div>
</div>
		