
<div class="comment" id="c_3771394898">
	<div>
		<img src="https://disqus.com/api/users/avatars/dotnetkow.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3771394898">1</a> by Matt Netkow, Ionic Team
		posted on 2/22/2018 at 8:39 PM
		</div>
		<div class="comment_text"><p>It's great! excellent start, looking forward to more.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3771401643">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3771401643">2</a> (In reply to <a href="#c_3771394898">#1</a>) by Raymond Camden
		posted on 2/22/2018 at 8:43 PM
		</div>
		<div class="comment_text"><p>Thank you!</p></div>
	</div>
</div>
		