
<div class="comment" id="c_1713664852">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664852">1</a> by Peter Tilbrook
		posted on 5/6/2007 at 8:22 PM
		</div>
		<div class="comment_text"><p>Does not seem to be any danger of "NDA" at the moment.</p><p>So what exactly can I say/not for my interview next week?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664860">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664860">2</a> by Raymond Camden
		posted on 5/6/2007 at 8:25 PM
		</div>
		<div class="comment_text"><p>Everything I've heard Adobe say is that if you can point to it publicly (ie on a blog for example), then you can say it. But do NOT take my word for it. You need to ping Damon Cooper or Ben.</p></div>
	</div>
</div>
		