
<div class="comment" id="c_1713669787">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669787">1</a> by Robert Owen
		posted on 8/7/2007 at 4:40 PM
		</div>
		<div class="comment_text"><p>with great power, comes great responsibility</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669811">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669811">2</a> by DK
		posted on 8/7/2007 at 6:43 PM
		</div>
		<div class="comment_text"><p>Ray,<br> did you notice the valid XHTML and CSS links on the bottom of the bloggers site actually show that neither is valid?</p><p>I think using CF8 AJAX stuff will never allow your CSS to validate as it uses yui.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669809">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669809">3</a> by Raymond Camden
		posted on 8/7/2007 at 6:49 PM
		</div>
		<div class="comment_text"><p>Nope, didn't notice. I'll probably just remove the links as I see no need for them. (Not for validation in general, but on the site I mean.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669812">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669812">4</a> by James, F.E.
		posted on 8/7/2007 at 7:04 PM
		</div>
		<div class="comment_text"><p>That's great kid! Don't get cocky. - Han Solo ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669810">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669810">5</a> by Chris Jordan
		posted on 8/8/2007 at 3:07 AM
		</div>
		<div class="comment_text"><p>Ray, that's really cool! It must be nice to get letters like that. I have to agree with the author of that email. I really appreciate all that you and the other heavy hitter type folks do for the community. ;o)</p></div>
	</div>
</div>
		