
<div class="comment" id="c_1713651873">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651873">1</a> by Raymond Camden
		posted on 4/15/2006 at 8:00 PM
		</div>
		<div class="comment_text"><p>If I post a comment to my own entry does it make me insane?</p><p>Anyway, I'm playing the soundtrack online for my son (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.kameosoundtrack.com%3AtOVo2GnODUznlOOdqa4wDXMLSMA&amp;cuid=3321886" rel="nofollow noopener" title="www.kameosoundtrack.com">www.kameosoundtrack.com</a>). In the notes for the track, Ice Mountain Onslaught, the composer says this:</p><p>Designer "Can you come up with something big and icy"<br>Composer: "Sure, use this tune here, and I'll apply the 'Icy Filter' to it"</p><p>Freaking hilarious. I don't know why - but I don't imagine composer as having a sense of humour.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651878">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651878">2</a> by djuggler
		posted on 4/15/2006 at 8:07 PM
		</div>
		<div class="comment_text"><p>I saw the ability to download 360 demos and thought that pretty slick. Nintendo has done a similar thing with the &lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fblog.siliconholler.com%2F2006%2F04%2F14%2Fnintendo-ds-download-station-is-very-cool%2F%3AbzMX_fNd0CNcgRAOTl-OywpZqeY&amp;cuid=3321886" rel="nofollow noopener" title="http://blog.siliconholler.com/2006/04/14/nintendo-ds-download-station-is-very-cool/">http://blog.siliconholler.c...</a>"&gt;DS Download Station&lt;/a&gt;.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651892">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651892">3</a> by Brian Rinaldi
		posted on 4/16/2006 at 2:54 AM
		</div>
		<div class="comment_text"><p>Glad you finally got around to trying Kameo...told ya it wasn't kiddie. I beat it the other week and I now miss it :( I am not one to normally replay games much.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651884">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651884">4</a> by Peter Tilbrook
		posted on 4/16/2006 at 6:03 AM
		</div>
		<div class="comment_text"><p>Good to see the wishlist title is being enjoyed - especially by your son! Make me feel all warm and fuzzy inside!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651887">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651887">5</a> by Raymond Camden
		posted on 4/16/2006 at 8:18 AM
		</div>
		<div class="comment_text"><p>Heh, we actually stayed up past midnight last night to finish it. The ending was great.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651886">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651886">6</a> by [SteelValor]
		posted on 6/15/2006 at 6:36 PM
		</div>
		<div class="comment_text"><p>I just gamepassed Kameo and can say I'm sorry I hadn't played indepth earlier. A great game that will be added to my 2004 picks of the year.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651889">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651889">7</a> by Raymond Camden
		posted on 6/15/2006 at 6:41 PM
		</div>
		<div class="comment_text"><p>My son finished the game and actually lost his entire save when he turned the xbox off during a save. But he loves the game so much he is playing it again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651888">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651888">8</a> by [SteelValor]
		posted on 7/10/2006 at 8:56 PM
		</div>
		<div class="comment_text"><p>So I've been watching how much time you're putting into Kameo ... I'm calling Dr. Phil!!1</p><p>lol jk ... or am I?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651891">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651891">9</a> by Raymond Camden
		posted on 7/10/2006 at 9:01 PM
		</div>
		<div class="comment_text"><p>It is my son actually. He has finished the game twice now and is unlocking all the secrets.</p></div>
	</div>
</div>
		