
<div class="comment" id="c_1713738069">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738069">1</a> by Brad Wood
		posted on 2/28/2014 at 11:47 PM
		</div>
		<div class="comment_text"><p>Thanks for the older, but still useful post :)  I was getting server errors anytime I tried to hit the account but clearing cookies solved it.  I thought I'd throw that info out there in case anyone else trips across this page and is having the same issue. The "register..." link under "help" in CF Builder was sending me straight to the error page which is what led to my Googling.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3115073988">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_F4CxjkNH6o.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3115073988">2</a> by EP
		posted on 1/23/2017 at 5:14 PM
		</div>
		<div class="comment_text"><p>I've tried twice.  All I get is:<br>"Could not register your product at this time.  Try again later."</p></div>
	</div>
</div>
		
<div class="comment" id="c_3115107044">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3115107044">3</a> (In reply to <a href="#c_3115073988">#2</a>) by Raymond Camden
		posted on 1/23/2017 at 5:34 PM
		</div>
		<div class="comment_text"><p>Sorry - but this post is 5 years old now - things probably changed. Contact Adobe customer service - and good luck.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3115191959">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_F4CxjkNH6o.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3115191959">4</a> (In reply to <a href="#c_3115107044">#3</a>) by EP
		posted on 1/23/2017 at 6:19 PM
		</div>
		<div class="comment_text"><p>Thanks for the lighting quick response!</p><p>I can check w/my manager to see if he still has it.  That of course would be Mr. C. S. - someone you may remember from your FC days. :)</p><p>Now we'll see if his response time can match yours!  ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_3115299130">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3115299130">5</a> (In reply to <a href="#c_3115191959">#4</a>) by Raymond Camden
		posted on 1/23/2017 at 6:52 PM
		</div>
		<div class="comment_text"><p>Tell Chris I said hi. :)</p></div>
	</div>
</div>
		