
<div class="comment" id="c_1713713112">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713112">1</a> by Steve Withington
		posted on 2/18/2009 at 8:25 PM
		</div>
		<div class="comment_text"><p>what an interesting concept! it's enough to at least peak my interest anyway. hmm.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713133">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713133">2</a> by Jeff
		posted on 2/18/2009 at 11:38 PM
		</div>
		<div class="comment_text"><p>*political rant deleted</p><p>LOL! What an interesting concept. It would be nice if I could just take the music for free without having to give or take a dollar! That's too much responsibility, can't I just steal it instead?</p><p>*sigh*</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713132">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713132">3</a> by KC
		posted on 2/19/2009 at 9:55 AM
		</div>
		<div class="comment_text"><p>That is interesting..hopefully no one is taking advantage of this. By the way, they need some error handling on that site.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713137">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713137">4</a> by JC
		posted on 2/19/2009 at 8:15 PM
		</div>
		<div class="comment_text"><p>You don't have to pay, Jeff. They give you $1, or they give $1 to charity. You're choosing who one gets it.</p><p>Neat idea.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713138">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713138">5</a> by Jeff
		posted on 2/20/2009 at 9:07 PM
		</div>
		<div class="comment_text"><p>JC, it was a joke :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713136">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713136">6</a> by Nigel Leitch
		posted on 2/21/2009 at 5:00 PM
		</div>
		<div class="comment_text"><p>Officer Roseland are a cool band and I don't even get paid to say that, oh wait I do now :D<br>Seriously the songs "Spiders" and "we Want Your Money" are classy songs and the album is great.</p></div>
	</div>
</div>
		