
<div class="comment" id="c_3058013577">
	<div>
		<img src="https://disqus.com/api/users/avatars/dmastag.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3058013577">1</a> by Julian
		posted on 12/18/2016 at 5:34 PM
		</div>
		<div class="comment_text"><p>Have to disagree with you. CGI Leia was the one that looked out of place to me. I think its because Tarkin's scenes were in low light rooms while Leia was all bright (felt like watching the Polar Express).</p></div>
	</div>
</div>
		
<div class="comment" id="c_3058016708">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3058016708">2</a> (In reply to <a href="#c_3058013577">#1</a>) by Raymond Camden
		posted on 12/18/2016 at 5:37 PM
		</div>
		<div class="comment_text"><p>Interesting - yeah the lighting did make things different. I think for me the whole emotional aspect of the Leia scene also made me more forgiving.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3060984958">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3060984958">3</a> by Scott
		posted on 12/20/2016 at 3:26 PM
		</div>
		<div class="comment_text"><p>I agree watching Vader be Vader was awesome.  Makes me want a full movie of that to fully explore what he can do.  I would not have done the CGI actors - I'd have gone with recasting Tarkin and just showing Leia's profile instead of her face to get the point across.</p></div>
	</div>
</div>
		