
<div class="comment" id="c_1713623334">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623334">1</a> by todd
		posted on 12/11/2005 at 8:19 AM
		</div>
		<div class="comment_text"><p>think you forgot to close an &lt;em&gt; tag ray...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623332">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623332">2</a> by Raymond Camden
		posted on 12/11/2005 at 8:42 AM
		</div>
		<div class="comment_text"><p>Thanks, fixed.</p></div>
	</div>
</div>
		