
<div class="comment" id="c_1713616049">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616049">1</a> by Raymond Camden
		posted on 8/19/2004 at 12:50 AM
		</div>
		<div class="comment_text"><p>Woot, 2 down, 3 to go! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616046">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616046">2</a> by Sam Farmer
		posted on 8/19/2004 at 5:12 PM
		</div>
		<div class="comment_text"><p>I'll swap you a referal for a Roomba!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616047">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616047">3</a> by Bob Weston
		posted on 8/27/2004 at 2:04 AM
		</div>
		<div class="comment_text"><p>I signed up, so that should make 5!  Let me know if you get one! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616045">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616045">4</a> by Bob Weston
		posted on 8/27/2004 at 6:05 PM
		</div>
		<div class="comment_text"><p>I signed up, so that should make 5!  Let me know if you get one! :)</p></div>
	</div>
</div>
		