
<div class="comment" id="c_1713661199">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661199">1</a> by Steven Erat
		posted on 1/11/2007 at 8:47 AM
		</div>
		<div class="comment_text"><p>Between RIAForge, <a href="http://disq.us/url?url=http%3A%2F%2FCFLib.org%3AWOdcErJNG97LPvefvtc2ezLtDsI&amp;cuid=3321886" rel="nofollow noopener" title="CFLib.org">CFLib.org</a>, and other such sites, is there still a need for the ColdFusion Exchange?  I've seen very little mention of it in recent times.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.adobe.com%2Fcfusion%2Fexchange%2Findex.cfm%23view%3Dsn130%3ABlIG91hxthDjXIJNraLsSZCQNf0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.adobe.com/cfusion/exchange/index.cfm#view=sn130">http://www.adobe.com/cfusio...</a></p><p>The gallery was once dedicated to CFX tags and CF_Custom tags, but has widened in scope to be a vehicle for linking to ColdFusion-based software on other sites.</p><p>I know people are still uploading projects there, but has it's value been marginalized by other project repositories?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661206">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661206">2</a> by Raymond Camden
		posted on 1/11/2007 at 9:03 AM
		</div>
		<div class="comment_text"><p>Well, in theory it does have a place. I am going to (one day) update CFLib to support custom tags and CFCs, but only open source free ones. For those who want to sell their apps, the Exchange would work for them.</p><p>I must say though - when the Exchange went Flash, I stopped using it. It got too slow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661205">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661205">3</a> by Rey Bango
		posted on 1/11/2007 at 9:27 PM
		</div>
		<div class="comment_text"><p>I stopped using the exchange when they tried to turn it into a Spectra-based site. Thats what really killed the performance.</p></div>
	</div>
</div>
		