
<div class="comment" id="c_1713737794">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737794">1</a> by Tim Leach
		posted on 1/2/2012 at 5:25 AM
		</div>
		<div class="comment_text"><p>10 pushups? Is that total for the year, or at a time?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737797">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737797">2</a> by Raymond Camden
		posted on 1/2/2012 at 6:59 AM
		</div>
		<div class="comment_text"><p>Heh, per workout of course. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737798">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737798">3</a> by Ben Riordan
		posted on 1/2/2012 at 11:42 AM
		</div>
		<div class="comment_text"><p>@Ray - curious - do you already know a .NET language for win7 phone development or do you plant to learn one at that point as well?</p><p>I gave myself an intro to ASP.NET C# a few months ago. Visual studio installs so much stuff on your computer! Anyway I made my way back to ColdFusion but I do prefer script style components now. Hopefully the rest or majority of tags can be used as cfscript in Zues.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737780">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737780">4</a> by Ben Riordan
		posted on 1/2/2012 at 11:43 AM
		</div>
		<div class="comment_text"><p>Whoops *Zeus</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737799">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737799">5</a> by Adam Tuttle
		posted on 1/2/2012 at 6:11 PM
		</div>
		<div class="comment_text"><p>Looks like you did pretty well against your goals for last year, so congrats!</p><p>I think it's great that so many CF developers are pushing ourselves to learn new languages (Pyhton, Ruby, etc). There is nothing to fear: if you don't like it, you can always come back, and if you do, you can either start doing that or even just take a few things you liked about it and try to apply them to your CF work. I myself spent a good amount of time playing with Ruby this year, and read one of the Ruby training books (basically) cover to cover. And I still &lt;3 CFML.</p><p>Good luck with the goals for this year. If you figure out any secrets on the gut thing, do share. That'll be on my list, too. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737800">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737800">6</a> by Raymond Camden
		posted on 1/2/2012 at 7:46 PM
		</div>
		<div class="comment_text"><p>@Ben: Nope, don't know any .Net languages. Was going to use PhoneGap.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737801">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737801">7</a> by Brian Swartzfager
		posted on 1/2/2012 at 8:25 PM
		</div>
		<div class="comment_text"><p>You'll probably be able to write a native Android app fairly quickly, given some of the similarities with Flex when it comes to building views/activities with an XML-based syntax.  I haven't done any native Android coding in awhile, but I'd be glad to share what Android knowledge I remember or have documented if you want.</p><p>As for the push-up thing, I started one of those "do 100 pushups in X number of weeks" plans early last year.  I got pretty far until I realized that my form wasn't quite right (that when I did them properly, I wasn't nearly as far along) and I didn't feel like starting over.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737802">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737802">8</a> by Keith
		posted on 1/3/2012 at 3:42 AM
		</div>
		<div class="comment_text"><p>Why don't you give Scala a shot, instead of (or in addition to) Ruby and Python? It is the coolest language I have ever used and, since it compiles to JVM bytecode, you can also use it Android apps.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737803">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737803">9</a> by Raymond Camden
		posted on 1/3/2012 at 6:30 AM
		</div>
		<div class="comment_text"><p>I'll see about taking a look, Keith.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737805">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737805">10</a> by Duncan Nisbett
		posted on 1/3/2012 at 11:08 PM
		</div>
		<div class="comment_text"><p>Ray, for your pushups, try taking a look at the app called "100 Pushups" there's an iPhone and Android variants. It's a good app to get started on your goal.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737784">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737784">11</a> by Matt Busche
		posted on 1/5/2012 at 7:07 AM
		</div>
		<div class="comment_text"><p>There's also a website for the one hundred pushups program. I'd highly recommend it.</p></div>
	</div>
</div>
		