
<div class="comment" id="c_1713727310">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727310">1</a> by Matt Gifford
		posted on 11/2/2010 at 5:59 PM
		</div>
		<div class="comment_text"><p>I agree. If you build it, they will come.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727301">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727301">2</a> by jbuda
		posted on 11/2/2010 at 6:01 PM
		</div>
		<div class="comment_text"><p>Definitely.</p><p>Been making AIR apps for the desktop, next step will be for mobile devices. So would be interesting/helpful to have a user group based solely on this.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727311">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727311">3</a> by Raymond Camden
		posted on 11/2/2010 at 6:58 PM
		</div>
		<div class="comment_text"><p>I'm an idiot. I forgot to post the actual link. You can join now:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fgroups.google.com%2Fgroup%2Fadobe-air-for-devices%3AVgPOCuhKbepFN6tBk1mWYX3HZQs&amp;cuid=3321886" rel="nofollow noopener" title="http://groups.google.com/group/adobe-air-for-devices">http://groups.google.com/gr...</a></p></div>
	</div>
</div>
		