
<div class="comment" id="c_1713615647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615647">1</a> by Rob Brooks-Bilson
		posted on 5/20/2004 at 5:25 PM
		</div>
		<div class="comment_text"><p>One of the guys in my office is a big star wars fan:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.hanshootsfirst.org%2F%3ADhDxqLhyOcfttbx8J6H03FoTCYo&amp;cuid=3321886" rel="nofollow noopener" title="http://www.hanshootsfirst.org/">http://www.hanshootsfirst.org/</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615657">2</a> by Freddys
		posted on 5/20/2004 at 6:27 PM
		</div>
		<div class="comment_text"><p>Check out this commentary article that I came across while reading Slashdot:<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.msnbc.msn.com%2Fid%2F4980465%2F%3Aifff9MIbzM_-KGGZABDrxEhp8OQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.msnbc.msn.com/id/4980465/">http://www.msnbc.msn.com/id...</a></p><p>This guy was harsh!  Maybe I'm just easy to please, but I've liked them all so far, no complaints here.<br>-Freddys</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615656">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615656">3</a> by Rick Root
		posted on 5/24/2004 at 9:22 PM
		</div>
		<div class="comment_text"><p>Have you seen the supposed script summary that's running around?  It's fairly interested... I have it on my web site...</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.webworksllc.com%2Fstarwars3.php%3A6DDGhcBBWClKqMPTAmAVjNO8JBU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.webworksllc.com/starwars3.php">http://www.webworksllc.com/...</a></p><p>(yeah php, I know.. I do both)</p></div>
	</div>
</div>
		