
<div class="comment" id="c_1713674563">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713674563">1</a> by Ian
		posted on 11/27/2007 at 10:43 AM
		</div>
		<div class="comment_text"><p>We get shipments from Yellow Freight occasionally but never ship enough back out to use them otherwise.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713674576">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713674576">2</a> by bob
		posted on 11/27/2007 at 5:13 PM
		</div>
		<div class="comment_text"><p>so now for shipping you can go brown or yellow. There is a joke in there somewhere....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713674577">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713674577">3</a> by Ben B
		posted on 11/27/2007 at 6:29 PM
		</div>
		<div class="comment_text"><p>I've never sent or received anything via Yellow; but I've seen their trucks and have always wondered why they are painted ORANGE!</p></div>
	</div>
</div>
		