
<div class="comment" id="c_1713655392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655392">1</a> by jim collins
		posted on 7/25/2006 at 7:15 PM
		</div>
		<div class="comment_text"><p>A job "just writing coldfusion apps" probably would not allow you to live the lavish lifestyle to which you have become accustomed :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655414">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655414">2</a> by Raymond Camden
		posted on 7/25/2006 at 7:25 PM
		</div>
		<div class="comment_text"><p>True. I have determined that I need 4 million dollars, which isn't a lot. 4 million is 2.25 or so after taxes. The .25 would nuke my mortage and car loan.</p><p>The 2 million remaining would be invested in safer investments. If I can get 5-10%, I'm getting at least 100k before taxes in interest.</p><p>That would be enough to live off of. Now I just need to get the 4 million.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655417">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655417">3</a> by Dave Crawford
		posted on 7/25/2006 at 7:34 PM
		</div>
		<div class="comment_text"><p>I would be interested to see how you get the integration with SmarterMail working out. Particularly subscribing folks to the lists.  The web interface for SmarterMail is ok, but I have found that behind the scenes work with CF is quite a challange.</p><p>Dave</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655407">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655407">4</a> by Raymond Camden
		posted on 7/25/2006 at 7:39 PM
		</div>
		<div class="comment_text"><p>We only have ONE place where it is done, the cfczone list, and, if it can't work, it is no big deal. I say anyone not smart enough to send a "subscribe" message doesn't deserve to be on the list! ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655421">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655421">5</a> by Rob Brooks-Bilson
		posted on 7/25/2006 at 10:31 PM
		</div>
		<div class="comment_text"><p>We'll be able to get the list migrated, one way or the other ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655422">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655422">6</a> by Mike Groves
		posted on 7/26/2006 at 2:16 AM
		</div>
		<div class="comment_text"><p>is CFCDev a site?  If so I would be interested in looking at it/contributing.  Please email me the particulars.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655423">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655423">7</a> by fuzie
		posted on 7/26/2006 at 3:33 AM
		</div>
		<div class="comment_text"><p>You need to watch Firefly already.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655426">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655426">8</a> by fuzie
		posted on 7/26/2006 at 3:33 AM
		</div>
		<div class="comment_text"><p>That was meant for the Sin City thread.  :D  Damn pharmaceuticals.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655424">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655424">9</a> by Neil Bailey
		posted on 7/26/2006 at 4:16 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Any idea on how solid the SmarterMail server is?  I am also using MailEnable, and I am also not over thrilled with it.</p><p>Any recommendations as far as a replacement mail server would be greatly appreciated.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655427">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655427">10</a> by Raymond Camden
		posted on 7/26/2006 at 5:34 PM
		</div>
		<div class="comment_text"><p>Neil, I got multiple recommendations for it. I still haven't installed it. Yesterday was "Gotcha" day for my son so we went to Chucky Cheese, and then I prepped for my presentation tonight.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655428">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655428">11</a> by Raymond Camden
		posted on 7/26/2006 at 5:36 PM
		</div>
		<div class="comment_text"><p>Mike, CFCDev is the list. The site is <a href="http://disq.us/url?url=http%3A%2F%2Fcfczone.org%3AnCZjy6gdRbp2e8-aL4l3Yo06aHw&amp;cuid=3321886" rel="nofollow noopener" title="cfczone.org">cfczone.org</a>. The plan is to roll CFCZone into CFLib. But, as my readers know, I've been talking about it for two years and I'm still not done. I'd like to do it this fall once I finish the project I can't yet talk about.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655425">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655425">12</a> by Peter Bell
		posted on 7/26/2006 at 6:04 PM
		</div>
		<div class="comment_text"><p>Hi Neil,</p><p>I run smartermail. I ahve about 50-100 domains and a few thousand users and it has been rock solid. I have heard of other users with thousands of domains and tens or hundreds of thousands of user accounts on fairly modest boxes.</p><p>It is very popular with smaller web hosts who don't have a linux guy to configure a linux mail server and I'd recommend it 100%.</p><p>Best Wishes,<br>Peter</p></div>
	</div>
</div>
		