
<div class="comment" id="c_1713619239">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713619239">1</a> by Eric Dawson
		posted on 7/23/2005 at 8:21 AM
		</div>
		<div class="comment_text"><p>Do you need to get the DRK to get Harlan?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713619236">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713619236">2</a> by Raymond Camden
		posted on 7/23/2005 at 8:35 AM
		</div>
		<div class="comment_text"><p>Yes, it's just on the DRK for now.</p></div>
	</div>
</div>
		