
<div class="comment" id="c_1713616048">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616048">1</a> by Peter Tilbrook
		posted on 8/18/2004 at 7:10 AM
		</div>
		<div class="comment_text"><p>Would using J2EE session variables make any difference? I've found that since turning them on the session is terminated if ALL instances of the client used to login are closed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616044">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616044">2</a> by Raymond Camden
		posted on 8/18/2004 at 3:26 PM
		</div>
		<div class="comment_text"><p>Sorry, I'm not really sure.</p></div>
	</div>
</div>
		