
<div class="comment" id="c_1713651711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651711">1</a> by Scott Stroz
		posted on 4/11/2006 at 4:27 PM
		</div>
		<div class="comment_text"><p>I agree with letting your DB do what it was designed to do.  With few, and rare, exceptions, it will always be more efficient to write your SQL so that there is as little processing of data on the CF side as possible. (By efficient, I mean running the code,not necessarily writing it)</p><p>Also, and again, with few exceptions, SELECT * FROM... is bad, only query the data you need, nothing more.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651698">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651698">2</a> by John Barrett
		posted on 4/11/2006 at 4:47 PM
		</div>
		<div class="comment_text"><p>I will say that I agree with you on this. When I started learning coldfusion(about a year ago) I knew html only,and for the most part that got me really far. Css is something that I am still learning,and hope to really get one day.</p><p>I would also say that by reading the CF WACK book was a big help to me, but I learn so much by reading the cf-blogs,and asking questions on the mailing lists.</p><p>Also, the biggest problem I see with newbies(me included) is writting good SQL statements.</p><p>John</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651708">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651708">3</a> by Teddy Payne
		posted on 4/11/2006 at 6:03 PM
		</div>
		<div class="comment_text"><p>I started with ColdFusion on how to get the software installed and configure the administration features.  I learned how ColdFusion attached itself to a web server, how it interacts with mail, ftp, odbc/jdbc, location of error log files and where variables are stored.  I started at the engine and then focused on the bells and whistles.</p><p>When it came to abstraction that makes ColdFusion beautiful, knowing effectively how to combine tags and syntax together is a very worthy approach.</p><p>Ray hit it on the head with the idea of economy of code.  Reuse code, understand the abstraction of the CFML tags and know your toolset.  You can touch almost every tag in ColdFusion in about a month or two without too much problem, but knowing which tag one should use for a given algorithm is what CF'ers focus on continually.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651709">4</a> by Ed
		posted on 4/11/2006 at 7:48 PM
		</div>
		<div class="comment_text"><p>Re: SQL - buy a copy of Ben Forta's excellent SQL primer, Learn SQL In 10 Minutes (Sams). It covers most of your day-to-day needs, is reasonably priced, resonably generic and you'll keep coming back to it. It's the clearest and most concise SQL textbook I've read to date.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651715">5</a> by Lola Lee Beno
		posted on 4/11/2006 at 8:47 PM
		</div>
		<div class="comment_text"><p>Another suggestion I'll add is to get a good quality phrasebook for quick references - O'Reilly has good ones.  Also Developer's Library . . . I've recently discovered MySQL Phrasebook and i've found it very handly already in the one week that I've had it.  This one is geared more toward administration of MySQL.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651714">6</a> by PaulC
		posted on 4/12/2006 at 10:38 PM
		</div>
		<div class="comment_text"><p>I started with zero knowledge of any web application development using Kevin Schmidt's Macromedia ColdFusion MX: Training from the Source, it touches all the basics just enough to let you get what you need done. Highly recommended.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.amazon.com%2Fgp%2Fproduct%2F0321162242%2Fqid%3D1144866574%2Fsr%3D1-17%2Fref%3Dsr_1_17%2F102-5995827-3335310%3Fs%3Dbooks%26v%3Dglance%26n%3D283155%3ASu5pDt5eBbFzK5CYkLDEz7mVPCM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.amazon.com/gp/product/0321162242/qid=1144866574/sr=1-17/ref=sr_1_17/102-5995827-3335310?s=books&amp;v=glance&amp;n=283155">http://www.amazon.com/gp/pr...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651717">7</a> by Chris Phillips
		posted on 4/13/2006 at 1:00 AM
		</div>
		<div class="comment_text"><p>Sheesh! With all the AJAX buzz, no-one bothered to say Javascript.</p><p>I think developers should have at least a passable knowledge of the DOM and how to access/manipulate it with JS.</p><p>My 2 cents.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651720">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651720">8</a> by Raymond Camden
		posted on 4/13/2006 at 1:06 AM
		</div>
		<div class="comment_text"><p>Ah, good point Chris. I have no good reason for not mentioning it. I really don't use a lot of JS anymore. I got kinda burned by the whole cross platformthing back in the old days. ;) But you are right, it is something you should learn.</p></div>
	</div>
</div>
		