
<div class="comment" id="c_1713658835">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658835">1</a> by Mike Potter
		posted on 11/1/2006 at 1:35 AM
		</div>
		<div class="comment_text"><p>MAX jinx?  My computer shut down on me when I got home, and IS has been working on it for hours now to fix it.</p><p>Mike</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658853">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658853">2</a> by Phillip Senn
		posted on 11/1/2006 at 1:38 AM
		</div>
		<div class="comment_text"><p>WWYD?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658839">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658839">3</a> by todd
		posted on 11/1/2006 at 1:41 AM
		</div>
		<div class="comment_text"><p>I usually hop on the wireless scanner and find a neighbor with a strong signal....woops...did i just say that out loud?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658847">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658847">4</a> by Mike McConnell
		posted on 11/1/2006 at 2:01 AM
		</div>
		<div class="comment_text"><p>If you live in the typical subdivision (house on top of house on top of house), just bogart one of your neighbor's wireless connections ;)  I have at least 3 wireless networks (unsecured) within connection distance from my home office, not that I would ever really use them, and chances are pretty good that you do too.  It astonishes me that people still don't lock down their networks.</p><p>Also, I don't know if EATEL provides service out your way, but their new fiber network is awesome (phone, internet and cable TV packages).  I switched all my services to them (from Cox)and it's one of the smartest things I've done in a long time.  I consistently get down/up speeds of 5MBPS/1.5MBPS on my DSL service through them and they rarely go down (plus I talked them in to giving me a static address at no additional cost).</p><p>M. McConnell</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658849">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658849">5</a> by Raymond Camden
		posted on 11/1/2006 at 2:59 AM
		</div>
		<div class="comment_text"><p>Nope, I live in a neighborhood with mostly older folks. Lafayette DID vote to let the city provide fiber to the home, but BellSouth has been fighting it tooth and nail since they know the city will provide the services for half the cost.</p><p>Get this - before the election last year - they actually sponsored push polls - where the pollsters would call folks and tell them stuff like, "Did you know that if the city provides cable tv, you won't be able to watch religious programming due to separation of church and state?"</p><p>Anyway - now I'm off topic.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658840">6</a> by Brian Rinaldi
		posted on 11/1/2006 at 3:33 AM
		</div>
		<div class="comment_text"><p>I think it is the Cox/LG/Mini cabal...a conspiracy for sure ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658844">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658844">7</a> by todd sharp
		posted on 11/1/2006 at 3:50 AM
		</div>
		<div class="comment_text"><p>So that's why you don't like me Ray!  Because my company will own BellSouth after this Friday!</p><p>I've been meaning to ask you what is happening with that actually.  Is the city going through with it?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658841">8</a> by Phillip Senn
		posted on 11/1/2006 at 6:16 PM
		</div>
		<div class="comment_text"><p>Laughing out loud.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658848">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658848">9</a> by Raymond Camden
		posted on 11/1/2006 at 7:45 PM
		</div>
		<div class="comment_text"><p>Todd - we are still fighting lawsuits. It is truly sad.</p></div>
	</div>
</div>
		