
<div class="comment" id="c_1713681273">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681273">1</a> by Lola LB
		posted on 5/29/2008 at 2:26 PM
		</div>
		<div class="comment_text"><p>Someday, I'll actually get to MAX.  Not this year, though. :-P</p></div>
	</div>
</div>
		