
<div class="comment" id="c_1713729380">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729380">1</a> by Phillip Senn
		posted on 2/4/2011 at 2:38 AM
		</div>
		<div class="comment_text"><p>And lets not forget that Paris Hilton uses jQuery.</p><p>&lt;img src="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.PhillipSenn.com%2FIndex%2FImages%2Fparis-hilton-jquery.jpg%3AJXfk7aR4_8K0gGAbMOtLD60b71w&amp;cuid=3321886" rel="nofollow noopener" title="http://www.PhillipSenn.com/Index/Images/paris-hilton-jquery.jpg">http://www.PhillipSenn.com/...</a>"&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729391">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729391">2</a> by Sam Farmer
		posted on 2/4/2011 at 8:41 AM
		</div>
		<div class="comment_text"><p>Can I get a request in now to hear more about deferred and, especially, templates?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729394">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729394">3</a> by Raymond Camden
		posted on 2/4/2011 at 8:45 AM
		</div>
		<div class="comment_text"><p>Sure you can, but I'll forget. ;) Just come with the question. I'm not an expert on either but hopefully the rest of the panel is.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729393">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729393">4</a> by Mike Kear
		posted on 2/5/2011 at 6:32 PM
		</div>
		<div class="comment_text"><p>WIll there be any way to see a recording of this session?    That time is 0400 Wednesday here in Sydney and I have a prior commitment - my head will be firmly on my pillow after a late night Tuesday night.  I would still like to hear this discussion if it's possible.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729392">5</a> by Raymond Camden
		posted on 2/5/2011 at 7:10 PM
		</div>
		<div class="comment_text"><p>I'm pretty sure yes.</p></div>
	</div>
</div>
		