
<div class="comment" id="c_1713718117">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718117">1</a> by Mike Schierberl
		posted on 9/3/2009 at 5:13 AM
		</div>
		<div class="comment_text"><p>Committed the fix to svn, it will be part of the next release.</p></div>
	</div>
</div>
		