
<div class="comment" id="c_1713664378">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664378">1</a> by Chris
		posted on 4/25/2007 at 1:45 AM
		</div>
		<div class="comment_text"><p>Welcome to the world of Ubuntu!  I would suggest installing Ubuntu and then running Windows Virtual with VMWare.  It works great.  If you need any help, just send me an email.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664370">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664370">2</a> by Raymond Camden
		posted on 4/25/2007 at 1:54 AM
		</div>
		<div class="comment_text"><p>That was my goal. I was going to keep a 'real' Windows on a small partition for the last PC game I'm playing.</p><p>At this point I'm going to see if I can just get Ubuntu working and then migrate my Windows app. Believe it or not I can still see my files from Ubuntu (from the CD I'm using).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664379">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664379">3</a> by Dan Sorensen
		posted on 4/25/2007 at 2:08 AM
		</div>
		<div class="comment_text"><p>Unfortunately, most vendors don't include install media unless you specifically request it. Now they usually have a hidden 'recovery partition'. I usually request install media AND I pick up a fresh hard drive for any non-default OSes. I would prefer to use the factory hard drive, but it's just too hard to mess with Vendor installs and Microsoft anymore. :-P</p><p>Good luck, I hope the rest goes well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664381">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664381">4</a> by Nathan Strutz
		posted on 4/25/2007 at 2:28 AM
		</div>
		<div class="comment_text"><p>I knew I should have blogged this yesterday :)<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.dopefly.com%2Ftechblog%2Fentry.cfm%3Fentry%3D186%3ANvMu5ADT0VDqvGqajL-wcu0_1NE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.dopefly.com/techblog/entry.cfm?entry=186">http://www.dopefly.com/tech...</a></p><p>BTW, what's that "last" PC game you're playing?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664380">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664380">5</a> by Raymond Camden
		posted on 4/25/2007 at 2:33 AM
		</div>
		<div class="comment_text"><p>Nice. GParted is on the Ubuntu CD I have. I didn't try to resize there as I didn't know it was an option. Does it keep the data safe?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664384">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664384">6</a> by Nathan Strutz
		posted on 4/25/2007 at 2:42 AM
		</div>
		<div class="comment_text"><p>I can't validate the data dependency of GParted's data handling, but i will say it did a great job for me. I copied and pasted partitions, resized set boot flags, etc., and had absolutely no issues on any of the 3 HDDs I was playing with over the weekend.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664386">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664386">7</a> by Scott P
		posted on 4/25/2007 at 3:18 AM
		</div>
		<div class="comment_text"><p>Sounds like you just blew away your boot loader for XP.  If you are careful, you can get it all back without reinstalling.</p><p>Might give this a try:<br>GParted and click on your Windows partition. <br>In the Partition menu, click manage flags. <br>Make sure the boot check box is set.</p><p>Also - what does your menu.lst file in /boot/grub look like?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664395">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664395">8</a> by Justin Lewis
		posted on 4/25/2007 at 10:30 AM
		</div>
		<div class="comment_text"><p>Ubuntu had it's own snappy disk partitioner and even created a selection for windows in the grub bootloader. I tried to do the partition with a partition magic and it ended in tears....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664397">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664397">9</a> by Raymond Camden
		posted on 4/25/2007 at 5:34 PM
		</div>
		<div class="comment_text"><p>UGH. I got my Windows XP Media CDs (from a friend) and I even get a blue screen during install.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664393">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664393">10</a> by Raymond Camden
		posted on 4/25/2007 at 5:42 PM
		</div>
		<div class="comment_text"><p>Scott, the partition does have boot set. I have no idea what /boot/grub is. It doesn't seem to be a file.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664394">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664394">11</a> by Ken Dunnington
		posted on 4/25/2007 at 5:49 PM
		</div>
		<div class="comment_text"><p>Why not just get an external Firewire drive and run Ubuntu and Windows under Paralells on the Mac? ;) Ubuntu is a great distro, I hope you get this problem fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664396">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664396">12</a> by sethron
		posted on 4/25/2007 at 8:14 PM
		</div>
		<div class="comment_text"><p>I would suggest getting the VMWare player and the Ubuntu appliance image here <a href="http://disq.us/url?url=http%3A%2F%2Fwww.vmware.com%2Fvmtn%2Fappliances%2Fdirectory%2F693%3A51Nj3HfaMbEsvh35VDiECaFHdT0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.vmware.com/vmtn/appliances/directory/693">http://www.vmware.com/vmtn/...</a> for the Windows PC.</p><p>I have an old IBM ThinkPad T22 that I have installed Ubuntu 5.10 and have upgraded to 6.10 and also added Kubuntu and Xubuntu to it. VMWare server is installed and I have an instance of Windows XP Pro SP2 running inside of it, but I would not recommend that for games.</p><p>The VMWare player and the appliance running within Windows XP is very reliable. Your mileage may vary, with sound and video within the VM, but this is exactly what VMWare was meant to do.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664374">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664374">13</a> by Raymond Camden
		posted on 4/25/2007 at 10:12 PM
		</div>
		<div class="comment_text"><p>Just thought I'd add a note. I'm now running Ubuntu. Scott P gave me a LOT of help with my display, but I seem stuck at 1600x instead of 1920x. What is odd is that when I ran from the CD I was able to get the higher rez. Anyone else out there using Dell's 24 inch widescreen?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664373">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664373">14</a> by sethron
		posted on 4/25/2007 at 10:39 PM
		</div>
		<div class="comment_text"><p>You may have to double check your settings in the /etc/X11/xorg.conf file. Also, try the command posted here:<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.robgonda.com%2Fblog%2Findex.cfm%2F2006%2F10%2F19%2FUbuntu-Update%3AMSKmcIK30Wlz7tdV3dpRUeyfSQU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.robgonda.com/blog/index.cfm/2006/10/19/Ubuntu-Update">http://www.robgonda.com/blo...</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664375">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664375">15</a> by Raymond Camden
		posted on 4/25/2007 at 11:30 PM
		</div>
		<div class="comment_text"><p>No go. I've tried the reconfigure a few times now. It just won't go over 1600x. The more I use it now the more I want to get it fixed. I may blog it just to draw in some traffic.</p></div>
	</div>
</div>
		