
<div class="comment" id="c_1714082961">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082961">1</a> by Dana K
		posted on 5/15/2014 at 5:46 PM
		</div>
		<div class="comment_text"><p>I'm glad they coordinated the release date with this on a much improved timeframe from last version!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082962">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082962">2</a> by ayhan
		posted on 5/15/2014 at 6:09 PM
		</div>
		<div class="comment_text"><p>Adobe doesn't show coldfusion under products. Checked all products! Not even under web development!! Why are they still keeping? maybe they should sell to some company who can care!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082963">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082963">3</a> by Raymond Camden
		posted on 5/15/2014 at 6:13 PM
		</div>
		<div class="comment_text"><p>This (the prominence on the home page) has been the same for many years. Yeah it sucks, but honestly, it hasn't "killed" CF yet and as we just released 2 major updates w/ 12 on the way, I'd not be too concerned about it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082964">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082964">4</a> by ayhan
		posted on 5/15/2014 at 7:01 PM
		</div>
		<div class="comment_text"><p>i know it hasn't killed. Just it really sucks that nobody gives s**t</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082965">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082965">5</a> by Daniel Mejia
		posted on 6/25/2014 at 5:00 AM
		</div>
		<div class="comment_text"><p>Back on topic. Pete suggests to install coldfusion on a separate partition and in a custom folder name (section 2.2). Then in section 2.11 he suggests to make the physical path of the cf admin site on another partition within the sites folder, ie: d:/sites/cfadmin-web/.</p><p>However, the files for the admin site are installed in {cf-root}/cfusion/wwwroot/CFIDE. So I attempted to move the entire CFIDE to my new cfadmin folder under my sites partition.</p><p>Ofcourse, now my admin site is throwing a 500.19 "Cannot read configuration file". Which is attempting to reference the web.config file under the {cf-root}/cfusion/wwwroot/CFIDE.</p><p>So this guide is missing instructions on this part. What do I do?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082967">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082967">6</a> by Raymond Camden
		posted on 6/25/2014 at 6:28 AM
		</div>
		<div class="comment_text"><p>Not to pawn you off, but did you try asking Pete?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082966">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082966">7</a> by Daniel Mejia
		posted on 6/25/2014 at 8:03 AM
		</div>
		<div class="comment_text"><p>I did, but I also want to get the answers on the only blog post I found regarding this guide. I'm positive someone else will be searching too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082972">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082972">8</a> by Lee
		posted on 8/6/2014 at 8:58 PM
		</div>
		<div class="comment_text"><p>I'm having the same issue as Daniel Mejia.  It's like the guide is missing some steps or something.  Was hoping to see someone else having a similar problem and found a solution, or that the CF11 Lockdown guide would have been updated by now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082973">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082973">9</a> by Raymond Camden
		posted on 8/6/2014 at 9:13 PM
		</div>
		<div class="comment_text"><p>@Lee: I've reach out to Pete.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082974">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082974">10</a> by Lee
		posted on 8/6/2014 at 9:27 PM
		</div>
		<div class="comment_text"><p>@Raymond:  I tried to contact him through his website, but I was getting an error on his contact form.  So I sent him a message through his company, so I don't know if he'll get to it or not.  Thanks a lot of reaching out to him since you probably have a  better means of communicating with him.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082977">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082977">11</a> by Pete Freitag
		posted on 8/6/2014 at 9:53 PM
		</div>
		<div class="comment_text"><p>@Daniel - never move the /CFIDE folder, your copy of CFIDE will never be updated with security hotfixes / patches when you run the ColdFusion updater.</p><p>The /CFIDE IIS virtual directory gets created automatically when you run the web server configuration tool (step 2.13), as long as you configure all sites or each site manually.</p><p>For the permissions error you are getting it sounds like you didn't add read file system permissions to {cf-root}/cfusion/wwwroot/CFIDE for the IIS application pool identity user &amp; IUSR (step 2.5).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082978">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082978">12</a> by WsuApe
		posted on 9/19/2014 at 8:35 PM
		</div>
		<div class="comment_text"><p>The lockdown guide does not seem correct in listing steps to create the separate cfadmin webiste.   I created the site with the security cert but, cant get anything to pull up as the site just throws errors.  Do I need to create a virtual mapping to CFIDE from within that site?  Can someone list some detailed steps here?</p></div>
	</div>
</div>
		