
<div class="comment" id="c_1713674155">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713674155">1</a> by Brian Kotek
		posted on 11/8/2007 at 10:56 PM
		</div>
		<div class="comment_text"><p>Ray, any idea if this is something people on CF8 need to consider, or are these changes already part of the CF8 version of JRun (CF8 already runs on Vista for example)?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713674140">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713674140">2</a> by Andy Allan
		posted on 11/8/2007 at 11:45 PM
		</div>
		<div class="comment_text"><p>Brian, you don't need this updater if you're already on CF8. This Updater brings JRun4 Updater 6 installs into line with CF8.</p></div>
	</div>
</div>
		