
<div class="comment" id="c_1713728180">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728180">1</a> by CJ
		posted on 12/5/2010 at 3:48 AM
		</div>
		<div class="comment_text"><p>This is a very cool little project; I definitely like this kind of stuff!</p><p>Out of curiosity, is the servermonitor API's also available on the non-enterprise version of CF server?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728164">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728164">2</a> by Ben Nadel
		posted on 12/5/2010 at 8:43 PM
		</div>
		<div class="comment_text"><p>Ha ha, simply awesome :D ... and what a sweet game that was! That's back when video games were simple enough for me to understand.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728181">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728181">3</a> by Raymond Camden
		posted on 12/5/2010 at 11:07 PM
		</div>
		<div class="comment_text"><p>@CJ: No, it is Enterprise only. I believe FusionReactor can provide similar results and I believe it has an API.</p><p>@Ben: Thanks - one day I need to make a -useful- mobile app. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728182">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728182">4</a> by Jarod Knoten
		posted on 12/5/2010 at 11:53 PM
		</div>
		<div class="comment_text"><p>This is great! On server crash does Ganon appear and start laughing ominously in 8 bits?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728177">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728177">5</a> by Raymond Camden
		posted on 12/5/2010 at 11:59 PM
		</div>
		<div class="comment_text"><p>Heh I had forgotten about that. Wasn't that only in the second Zelda?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728183">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728183">6</a> by Jarod Knoten
		posted on 12/6/2010 at 12:05 AM
		</div>
		<div class="comment_text"><p>Ya, second Zelda only, but ill bet a server crash would make me feel exactly the same way I did after a death due to a misguided side scroll jump.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728184">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728184">7</a> by Grant Eagon
		posted on 12/6/2010 at 5:02 AM
		</div>
		<div class="comment_text"><p>So so awesome Ray! Can we download this somewhere and use it for our servers? Woot for Zelda!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728169">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728169">8</a> by Raymond Camden
		posted on 12/6/2010 at 5:26 PM
		</div>
		<div class="comment_text"><p>I included the zip of the AIR project. The CFC is in code above. That should be it, right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728167">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728167">9</a> by Yaron Kohn
		posted on 12/6/2010 at 5:59 PM
		</div>
		<div class="comment_text"><p>Is that Ray Forta? Great Job as usual.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728166">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728166">10</a> by Raymond Camden
		posted on 12/6/2010 at 6:03 PM
		</div>
		<div class="comment_text"><p>I'm going for Epic Beard-ness.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728168">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728168">11</a> by Doug
		posted on 12/6/2010 at 6:20 PM
		</div>
		<div class="comment_text"><p>Wow Ray, it's been a while since I've seen you and your beard has become really glorious!  WTG</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728170">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728170">12</a> by Doug
		posted on 12/6/2010 at 6:23 PM
		</div>
		<div class="comment_text"><p>Oh and Jared: I think a server crash would give more of a sense of panic than Ganon ever did.  BTW I hated Z2.  That final fight was such a pain and then if you died you had to start over that whole section again.</p><p>(though obsession lead me to finally beat the game on an emulator when I was in college.  Jeez, maybe that's why my sophomore year grades weren't so hot?)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728172">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728172">13</a> by Ernest E. Breau Jr.
		posted on 12/6/2010 at 6:40 PM
		</div>
		<div class="comment_text"><p>You can also use this, which works on BlueDragon as well.<br>&lt;Cfset runtime = CreateObject("java","java.lang.Runtime").getRuntime()&gt;<br>&lt;cfset fm = runtime.freememory()/&gt;<br>&lt;Cfset fm = int((fm/1024)/1024)/&gt;<br>&lt;cfset usedmem = 1270-fm/&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728171">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728171">14</a> by Raymond Camden
		posted on 12/6/2010 at 7:24 PM
		</div>
		<div class="comment_text"><p>@Doug: My grades took a hit when I discovered MUDs. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728175">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728175">15</a> by John Allen
		posted on 12/6/2010 at 10:13 PM
		</div>
		<div class="comment_text"><p>Awesome. Totally awesome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728176">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728176">16</a> by Aaron West
		posted on 12/6/2010 at 11:08 PM
		</div>
		<div class="comment_text"><p>I don't know which is better, the Zelda-style health meter or your beard.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728174">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728174">17</a> by Raymond Camden
		posted on 12/6/2010 at 11:11 PM
		</div>
		<div class="comment_text"><p>Any questions/observations about the code are welcome. My beard is boring. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728248">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728248">18</a> by andy matthews
		posted on 12/7/2010 at 3:56 AM
		</div>
		<div class="comment_text"><p>Epic beard is E.P.I.C!</p></div>
	</div>
</div>
		