
<div class="comment" id="c_1713617874">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617874">1</a> by Oguz Demirkapi
		posted on 4/6/2005 at 9:20 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>What about sorting of Conferences and Forums?</p><p>As an example, how can I decide which forum must listed before?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617873">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617873">2</a> by Ray Camden
		posted on 4/6/2005 at 9:34 PM
		</div>
		<div class="comment_text"><p>Patiences. :) It will happen.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617878">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617878">3</a> by q
		posted on 4/7/2005 at 7:56 PM
		</div>
		<div class="comment_text"><p>test</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617880">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617880">4</a> by q
		posted on 4/7/2005 at 7:56 PM
		</div>
		<div class="comment_text"><p>test2</p></div>
	</div>
</div>
		