
<div class="comment" id="c_1713664016">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664016">1</a> by Pete
		posted on 4/12/2007 at 3:36 PM
		</div>
		<div class="comment_text"><p>This raises the question of what will happen to Sun, too.    They never mention when a pregnant woman begins to have problems, but I'd be surprised if they didn't bring it up before the end of the season.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664010">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664010">2</a> by Ken Auenson
		posted on 4/12/2007 at 3:49 PM
		</div>
		<div class="comment_text"><p>I was surprised by the belief that Juliette has in the Others and their "power".<br>This is a spoiler...  I am *very* confused by the supposed ability for Ben to "heal" cancer in someone who isn't even on the island (Juliette's sister)...  <br>Anyone have any explainations for that?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664012">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664012">3</a> by Jonathan
		posted on 4/12/2007 at 4:37 PM
		</div>
		<div class="comment_text"><p>last two episodes have restored my faith in this show.</p><p>The Australians chick didn't die when pregnant. her symptoms were faked in the episode. So Sun might not be in danger either. The whole Juliette really surprised me. I was totally fooled.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664015">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664015">4</a> by Ryan Pieszak
		posted on 4/12/2007 at 4:51 PM
		</div>
		<div class="comment_text"><p>I think Ken brings up a really good point.  If Ben has the means to heal somebody that isn't on the island, he appears to be the key, not the island.</p><p>And when everybody finds out that Juliette isn't being honest, there goes their faith in Jack.  Then the leadership power will switch to Sawyer and Sayid, and I'm not sure I trust them with that power.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664005">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664005">5</a> by Daniel Roberts
		posted on 4/12/2007 at 5:41 PM
		</div>
		<div class="comment_text"><p>"The Australians chick didn't die when pregnant. her symptoms were faked in the episode."</p><p>Yeah. Earlier in the episode Juliette said something about how the problems start at conception. None of the women from the plane crash have become pregnant, that we know of,  while on the island. Maybe they were just comparing blood samples of Claire to the other pregnant women in their testing--not trying help her.</p><p>About Ben and curing cancer. There is definitely something fishy. It is possible he faked the data for Juliette's sister's cancer returning to convince her to stay. They then show her years later and the sister is fine.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664014">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664014">6</a> by Jeff Smallwood
		posted on 4/12/2007 at 6:12 PM
		</div>
		<div class="comment_text"><p>I agree with you Daniel, I too thought that the cancer returning was a lie, right from the start. He just happened to have the data and present it to her at a critical point in her first 6 months on the island. That lie gives him the ability to magically cure her.</p><p>Another thing, I see a shake-up in the works involving Russo, possibly before Juliette joins back with the others. Ever since Sawyer, Sayid, Kate and Locke all found Jack, I've been wondering were Russo wandered off to. I find it convenient that the writers just let her walk away so easily. Almost like they want us to forget she was there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663995">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663995">7</a> by Max Hamby
		posted on 4/12/2007 at 6:18 PM
		</div>
		<div class="comment_text"><p>@Ryan - Right now, Sayid is the only one that seems to have his head screwed on straight. He's asking the important questions and knows why they need the answers. They are are under attack from the Others... I know I'd be tring to find out everything I could about the people trying to kill me.</p><p>I never trusted Juliette for a minute... Let Sayid do what he's got to do... she'll talk.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664004">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664004">8</a> by Ryan Pieszak
		posted on 4/12/2007 at 6:39 PM
		</div>
		<div class="comment_text"><p>@Max - I agree that right now Sayid appears to be the right person to lead, but that's only because Jack is temporarily clouded.  I don't trust Sayid's leadership abilities.  History has shown that Jack is the only person that  can keep a level head and be the leader that everyone trusts.</p><p>I'm sure this was part of the thought process when Ben was contriving this plan: weaken them by removing their faith in their leader.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664008">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664008">9</a> by Ken Dunnington
		posted on 4/12/2007 at 7:09 PM
		</div>
		<div class="comment_text"><p>Ray, why do you say Juliette is more evil (eviler?) than Ben? I agree that she's definitely not good for the Losties, but I think her motivation is getting home. We saw that at the time of the plane crash, she was still desperate to go home, and felt that her task to figure out the pregnancy issue was impossible, and obviously Claire helped prove it wasn't, so it seems to me that Juliette is now focused on doing whatever it takes to complete her task so that she can go home. Selfish and dangerous, yes, but evil? I'm not so sure.</p><p>Of course, if she could muster more than one facial expression it might be easier to discern. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664013">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664013">10</a> by Raymond Camden
		posted on 4/12/2007 at 7:27 PM
		</div>
		<div class="comment_text"><p>Ken - it is just my gut. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664007">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664007">11</a> by Ryan Pieszak
		posted on 4/12/2007 at 7:57 PM
		</div>
		<div class="comment_text"><p>"Of course, if she could muster more than one facial expression it might be easier to discern."</p><p>Good call!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664017">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664017">12</a> by Damon Gentry
		posted on 4/12/2007 at 8:35 PM
		</div>
		<div class="comment_text"><p>I'm an avid fan of PVP Online.  Today's strip was priceless:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.pvponline.com%2Farticle%2F3257%2Fwed-apr-11%3AD3sfppseIPDUc1uTd-eePbkjNDc&amp;cuid=3321886" rel="nofollow noopener" title="http://www.pvponline.com/article/3257/wed-apr-11">http://www.pvponline.com/ar...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663997">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663997">13</a> by Daniel Roberts
		posted on 4/12/2007 at 9:01 PM
		</div>
		<div class="comment_text"><p>hey, I like that facial expression :-D WOW!</p><p>Would this facial expression help? <a href="http://disq.us/url?url=http%3A%2F%2Ftinyurl.com%2F2k7po6%3AONuR-o9vAknSSNShH4SiWhwUZoc&amp;cuid=3321886" rel="nofollow noopener" title="http://tinyurl.com/2k7po6">http://tinyurl.com/2k7po6</a></p><p>I'm going to call it now and predict that Jack will eventually kill Juliette.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664000">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664000">14</a> by Rick Root
		posted on 4/12/2007 at 10:17 PM
		</div>
		<div class="comment_text"><p>This may have been mentioend, but I don't THINK we "know" that juliette is more evil than Ben.</p><p>In fact, given the ending - which caught me off guard - I don't know WHAT to think of her.  She obviously doesn't get along with Ben, and Jack is probably right about one thing - she wants off the island.</p><p>It became clear in the final minute of the show that she's lying to the castaways about being "left behind" by the others.</p><p>But even KNOWING that, I have a suspicion that she's in it for herself only.</p><p>In otherwords.. Ben thinks she's doing what she's told, but I think she's got her own motivations.</p><p>And that's the best part about this plot twist.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663998">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663998">15</a> by Scott Sroz
		posted on 4/16/2007 at 5:20 PM
		</div>
		<div class="comment_text"><p>I missed the episode due to a DVR screw up and was able to watch it this weekend.  I have several comments:</p><p>1. I think this is the best episode since season 1.</p><p>2. How does it benefit the Others to have her in the camp? Its not like the Others don't know where the camp is?</p><p>3. Where are the Others going for a week?  Yet another island or encampment?</p><p>4. I am not convinced that Juliette is entirely behind Ben's plan (whatever it may be).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663999">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663999">16</a> by yagiz
		posted on 4/29/2007 at 3:46 AM
		</div>
		<div class="comment_text"><p>Hey guys I'll be watching the comments and i have some clue that can enlighten your thoughts... Did anyone see that on the report that Ben gave Juliette about her sister's(RAchel)cancer gender side was MALE!!! I'm not sure what to think about it right know but it's pretty obvious that Rachel is a male... Check on the timeline 19:34 of episode 16...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664001">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664001">17</a> by Ryan Pieszak
		posted on 5/8/2007 at 12:13 AM
		</div>
		<div class="comment_text"><p>Ray, why no Lost recaps lately?  I look forward to the analysis and friendly banter on the blog/comments.</p><p>I've been too busy to watch lately, but I have them DVR'd, so I'll catch up this week.</p><p>In case anybody is interested...<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.cnn.com%2F2007%2FSHOWBIZ%2FTV%2F05%2F07%2Ftelevision.lost.reut%2Findex.html%3AiPPDOogL_wuNG8AC43rJq9LaNCs&amp;cuid=3321886" rel="nofollow noopener" title="http://www.cnn.com/2007/SHOWBIZ/TV/05/07/television.lost.reut/index.html">http://www.cnn.com/2007/SHO...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664002">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664002">18</a> by Raymond Camden
		posted on 5/8/2007 at 12:16 AM
		</div>
		<div class="comment_text"><p>Busy - and while I'm liking the more recent episodes, I'm kinda bummed by the show now. I'll do a recap this week I think though as it looks to be worth the time to write a blog entry. ;)</p><p>Also - I'm planning on launching <a href="http://disq.us/url?url=http%3A%2F%2Fgeekthetube.com%3AWhlWpVJPHuca0uFg_01OHwgwLDc&amp;cuid=3321886" rel="nofollow noopener" title="geekthetube.com">geekthetube.com</a> sometime just for these TV posts. (Although I may cross post for a while.)</p></div>
	</div>
</div>
		