
<div class="comment" id="c_1713724492">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724492">1</a> by Josh
		posted on 5/19/2010 at 9:11 PM
		</div>
		<div class="comment_text"><p>Have you ever looked at Portcullis?(<a href="http://disq.us/url?url=http%3A%2F%2Fportcullis.riaforge.org%2F%29%3AqaZNXQMiZVA7cSTlTKS4iFS9u9E&amp;cuid=3321886" rel="nofollow noopener" title="http://portcullis.riaforge.org/)">http://portcullis.riaforge....</a>.  It's a SQL injection and XSS filter.  I use it and it seems to work pretty well.  Filters all form, url, and cookie variables.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713724513">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724513">2</a> by Raymond Camden
		posted on 5/19/2010 at 9:27 PM
		</div>
		<div class="comment_text"><p>No, I've not. I tend to prefer to do things more obvious - directly on the page. Of course, it leads to mistakes like those corrected by Procheckup.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713724494">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724494">3</a> by Mavelar
		posted on 6/12/2010 at 12:43 AM
		</div>
		<div class="comment_text"><p>Hey Raymond, what if I want to update those specific files. I have my blog cfc customized.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713724495">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724495">4</a> by Raymond Camden
		posted on 6/12/2010 at 12:48 AM
		</div>
		<div class="comment_text"><p>Check the readme.txt file. It always details exactly what files changed in what release.</p></div>
	</div>
</div>
		