
<div class="comment" id="c_1713616390">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616390">1</a> by Joel
		posted on 10/26/2004 at 4:38 PM
		</div>
		<div class="comment_text"><p>Ray, Is that session on Monday free if you did not sign up for the "all-day" event?  It would be nice to get to see it if possible.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616393">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616393">2</a> by Raymond Camden
		posted on 10/26/2004 at 4:52 PM
		</div>
		<div class="comment_text"><p>The Community Suite is 100% free as it is an "unofficial" event. There -should- be a URL but I don't think it is ready yet. Monitor <a href="http://disq.us/url?url=http%3A%2F%2Fwww.houseoffusion.com%3A1J3LJjIFPsPWUcCHcGWR7YmwH84&amp;cuid=3321886" rel="nofollow noopener" title="www.houseoffusion.com">www.houseoffusion.com</a> for more info.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616392">3</a> by ErikG
		posted on 10/26/2004 at 10:34 PM
		</div>
		<div class="comment_text"><p>I arrive in New Orleans at 1:42pm - so I am SOL on catching your preso.  But I should be at the Birds of a Feather group - as I was in SLC when it was unofficial.</p></div>
	</div>
</div>
		