
<div class="comment" id="c_1713726139">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726139">1</a> by Sooraj
		posted on 8/27/2010 at 12:11 PM
		</div>
		<div class="comment_text"><p>Hi Ray,<br>         Nice plugin, nice demo...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726129">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726129">2</a> by Gary Funk
		posted on 8/27/2010 at 4:57 PM
		</div>
		<div class="comment_text"><p>Nice. Very nice. You just earned another nice toy. Now to find something you don't have.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726140">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726140">3</a> by todd sharp
		posted on 8/27/2010 at 5:51 PM
		</div>
		<div class="comment_text"><p>Just a heads up FWIW - if you're trying to implement this method with a large number of select elements that contain a lot of options it will be very slow in Internet Exploder.  Like everything else I guess, but this particular technique was so bad that I had to remove it from an app at work where IE is the standard browser...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726141">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726141">4</a> by Christian Clark
		posted on 8/27/2010 at 6:42 PM
		</div>
		<div class="comment_text"><p>Would it be easy to amend the code to disable the previously used options rather than hiding them totally?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726147">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726147">5</a> by Raymond Camden
		posted on 8/27/2010 at 7:01 PM
		</div>
		<div class="comment_text"><p>HTML option tags support a disabled property. You can try that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726145">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726145">6</a> by Brian
		posted on 8/27/2010 at 8:23 PM
		</div>
		<div class="comment_text"><p>Firebug doesn't keep up when you're looking at the HTML for this...  after playing with the menus (and watching the state changes), I changed Beer to "Select One" -- Firebug only reflected the changes to option value attributes, but not the displayed value.  I had to click the drop down for ColdFusion to verify that, yes, in fact the options display DID change.  weird.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726144">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726144">7</a> by Raymond Camden
		posted on 8/27/2010 at 8:26 PM
		</div>
		<div class="comment_text"><p>To be clear, you are saying something is odd with Firebug. Not my code. Right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726146">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726146">8</a> by Brian
		posted on 8/27/2010 at 8:30 PM
		</div>
		<div class="comment_text"><p>Yup... definitely Firebug.  Your code is fine...</p></div>
	</div>
</div>
		