
<div class="comment" id="c_1713729301">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729301">1</a> by Shaun McCran
		posted on 1/31/2011 at 2:03 AM
		</div>
		<div class="comment_text"><p>Woo! I did something very similar just now: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.mccran.co.uk%2Findex.cfm%2F2011%2F1%2F30%2FUsing-ColdFusion-to-see-Java-server-values%3AcsHbG-YAGn3pYh99Wmll38PzxQU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.mccran.co.uk/index.cfm/2011/1/30/Using-ColdFusion-to-see-Java-server-values">http://www.mccran.co.uk/ind...</a>, needed to find the jvm bersion on the server to confirm why my compiled app wouldn't run. (was getting a 'Unsupported major.minor version 49.0') java error.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729304">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729304">2</a> by Steve Keator
		posted on 1/31/2011 at 6:25 PM
		</div>
		<div class="comment_text"><p>Interesting.  Got a lot of cool information from this running on my local machine.  Anyone know of any way to use something similar to this to see how much memory jRun is eating up?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729302">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729302">3</a> by Raymond Camden
		posted on 1/31/2011 at 7:25 PM
		</div>
		<div class="comment_text"><p>JVM memory is much easier. Give me a minute and I'll hunt up the URL.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729303">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729303">4</a> by Raymond Camden
		posted on 1/31/2011 at 7:26 PM
		</div>
		<div class="comment_text"><p>java.lang.Runtime has it: <a href="http://disq.us/url?url=http%3A%2F%2Fdownload.oracle.com%2Fjavase%2F1.5.0%2Fdocs%2Fapi%2Fjava%2Flang%2FRuntime.html%3AemlgVctchKjWo8tztTfxSPyorFw&amp;cuid=3321886" rel="nofollow noopener" title="http://download.oracle.com/javase/1.5.0/docs/api/java/lang/Runtime.html">http://download.oracle.com/...</a></p><p>You can also get it via the Admin API. I've used it in a few demos.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729306">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729306">5</a> by todd sharp
		posted on 1/31/2011 at 9:03 PM
		</div>
		<div class="comment_text"><p>I'm not sure people even remember that .NET integration exists, but if you really wanted to you could get similar information via .NET:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.anujgakhar.com%2F2008%2F01%2F30%2Fgetting-system-info-with-coldfusion-8-and-net%2F%3AU5Crlx5IO34MDRdT_tqcvItFT4c&amp;cuid=3321886" rel="nofollow noopener" title="http://www.anujgakhar.com/2008/01/30/getting-system-info-with-coldfusion-8-and-net/">http://www.anujgakhar.com/2...</a></p><p>I haven't tested it because quite frankly my .net install seems to be broken and I'm not going to bother fixing it (since this would probably be the only thing I'll ever use it for).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729308">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729308">6</a> by Raymond Camden
		posted on 1/31/2011 at 9:12 PM
		</div>
		<div class="comment_text"><p>People still use .Net?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729309">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729309">7</a> by todd sharp
		posted on 1/31/2011 at 9:38 PM
		</div>
		<div class="comment_text"><p>Ask Scott.  I believe he's wrangling some as we speak.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729307">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729307">8</a> by Randy Jacoy
		posted on 1/31/2011 at 10:52 PM
		</div>
		<div class="comment_text"><p>Does anyone know how to programmatically get the ColdFusion Update Level (patching level)?  I am able to obtain most all of the other information from the CF Information page but I can't find the patching level.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729310">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729310">9</a> by Raymond Camden
		posted on 2/1/2011 at 3:27 AM
		</div>
		<div class="comment_text"><p>I believe the updates are JAR files in standard locations. You could check those directories.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729314">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729314">10</a> by Randy Jacoy
		posted on 2/1/2011 at 4:11 AM
		</div>
		<div class="comment_text"><p>Ah good point; I could just look in &lt;cf install root&gt;\lib\updates.  I guess I was overthinking it.  Thank you!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729313">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729313">11</a> by spartan2276
		posted on 5/23/2012 at 9:30 PM
		</div>
		<div class="comment_text"><p>Is it possible to get remote servers memory usage?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729325">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729325">12</a> by Randy Jacoy
		posted on 5/23/2012 at 9:55 PM
		</div>
		<div class="comment_text"><p>I assume you are talking about the actual operating system memory use and not ColdFusion memory use.  Try this:</p><p>&lt;cfset mf = createObject("java", "java.lang.management.ManagementFactory")&gt;<br>&lt;cfset osbean = mf.getOperatingSystemMXBean()&gt;</p><p>&lt;cfoutput&gt;<br>&lt;cfset freeMemory = osbean.getFreePhysicalMemorySize() / 1024 / 1024&gt;<br>&lt;cfset totalMemory = osbean.getTotalPhysicalMemorySize() / 1024 / 1024&gt;</p><p>Total Physical Memory: #NumberFormat(Round(totalMemory#))MB<br>Free Physical Memory:#NumberFormat(Round(freeMemory))#MB<br>&lt;/cfoutput&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729328">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729328">13</a> by Raymond Camden
		posted on 5/23/2012 at 11:39 PM
		</div>
		<div class="comment_text"><p>Also - ColdFusion 10 added native functions for this.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729326">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729326">14</a> by spartan2276
		posted on 5/23/2012 at 11:56 PM
		</div>
		<div class="comment_text"><p>@Randy Jacoy,</p><p>Thanks but it gives me the same results. I get an accurate total memory count of what is on the actual server, but not the actual free memory count of the actual OS which is what I want, I need to use CF to get the actual OS server not CF server</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729329">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729329">15</a> by spartan2276
		posted on 5/23/2012 at 11:58 PM
		</div>
		<div class="comment_text"><p>I need to get info display on a web page, something like the CF server monitor does but not using flex.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729327">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729327">16</a> by Raymond Camden
		posted on 5/24/2012 at 1:05 AM
		</div>
		<div class="comment_text"><p>Use Ajax then.</p></div>
	</div>
</div>
		