
<div class="comment" id="c_1713730015">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730015">1</a> by Lola LB
		posted on 2/23/2011 at 10:29 PM
		</div>
		<div class="comment_text"><p>I guess I should get around to padding out my "About Me" a bit more.  As for "contact me" . . . you've got a point.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730017">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730017">2</a> by Lola LB
		posted on 2/23/2011 at 10:30 PM
		</div>
		<div class="comment_text"><p>And BTW, how did you add the FB "like" button?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713729997">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713729997">3</a> by Raymond Camden
		posted on 2/23/2011 at 10:33 PM
		</div>
		<div class="comment_text"><p>It's just some JS. View source on it. I believe I googled for FB's guide.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730011">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730011">4</a> by Aaron West
		posted on 2/23/2011 at 11:39 PM
		</div>
		<div class="comment_text"><p>Ray, I agree. It's really frustrating to wind up on a nice blog post and want to contact the author and not be able to. Or, to want to write a comment and address the author by name and not be able to find their name. Just moments ago I came across another CF blog I hadn't seen before and it took me 5 mins to find the name of the owner.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730018">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730018">5</a> by Ryan Vikander
		posted on 2/23/2011 at 11:46 PM
		</div>
		<div class="comment_text"><p>The subscribe to comments is handy but it would be nice if I could only subscribe to comments that pertain to my comment. Otherwise if it's a popular blog entry I get flooded with useless comments. Or if I could subscribe to the blogger's comments.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730010">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730010">6</a> by Anonymous
		posted on 2/23/2011 at 11:59 PM
		</div>
		<div class="comment_text"><p>My reason to be anonymous is to annoy the people who don't like people being anonymous. ;)</p><p>(Well, it's more that whenever someone mentions this I think "I really should get around to doing that", and then moments later I've forgotton about it, until the next time someone brings up the subject. This time I'll actually make an effort to remember and add an "About The Author" section. Promise!)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730014">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730014">7</a> by Simon Romanski
		posted on 2/24/2011 at 12:08 AM
		</div>
		<div class="comment_text"><p>What's a blog? Must be another one of those internets fads!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730012">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730012">8</a> by Raymond Camden
		posted on 2/24/2011 at 12:10 AM
		</div>
		<div class="comment_text"><p>A blog is the long form of a tweet. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730013">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730013">9</a> by Cliff
		posted on 2/24/2011 at 5:49 PM
		</div>
		<div class="comment_text"><p>OK, so then what's a Tweet?  :)</p><p>Seriously, I have no idea what Twitter's purpose is.  I've visited the site a few times and find lot's of cryptic, short comments that all appear random and unrelated.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730019">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730019">10</a> by Raymond Camden
		posted on 2/24/2011 at 5:50 PM
		</div>
		<div class="comment_text"><p>Twitter is mainly like bar chatter. Fun, social, _sometimes_ relevant, but casual.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730021">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730021">11</a> by Adam Tuttle
		posted on 2/25/2011 at 1:59 AM
		</div>
		<div class="comment_text"><p>Twitter's sole purpose is, if I understand it correctly, to show off your beard in your avatar. I only follow @cfjedimaster and @commadelimited though, so maybe I'm not seeing the big picture.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730020">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730020">12</a> by Raymond Camden
		posted on 2/25/2011 at 3:41 AM
		</div>
		<div class="comment_text"><p>The big picture is just more of my beard.</p></div>
	</div>
</div>
		