
<div class="comment" id="c_1713659276">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659276">1</a> by Jen
		posted on 11/16/2006 at 6:26 AM
		</div>
		<div class="comment_text"><p>Great presentation, Ray! Was that a MAX water bottle? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659282">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659282">2</a> by Raymond Camden
		posted on 11/16/2006 at 6:52 AM
		</div>
		<div class="comment_text"><p>Wow, it was. How did you recognize that? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659283">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659283">3</a> by Chris
		posted on 11/16/2006 at 5:02 PM
		</div>
		<div class="comment_text"><p>Woah! I missed the show! :(<br>Just can't wait to see the recorded files...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659285">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659285">4</a> by Raymond Camden
		posted on 11/16/2006 at 5:11 PM
		</div>
		<div class="comment_text"><p>When I get the recording url I'll post it along with the zip.</p></div>
	</div>
</div>
		