
<div class="comment" id="c_1713615082">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615082">1</a> by Peter Tilbrook
		posted on 11/7/2003 at 12:44 AM
		</div>
		<div class="comment_text"><p>Dang! Doesn't work under Studio 5 but have MX 6 at work and MX 2004 at home so...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615081">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615081">2</a> by Rob Brooks-Bilson
		posted on 11/7/2003 at 12:53 AM
		</div>
		<div class="comment_text"><p>If Macromedia would just include CVS (or any SCC support for that matter) support in DWMX, maybe I could make the switch.  Well, that and the ability to publish to more than one server ala Homesite+'s projects...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615080">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615080">3</a> by Andy Jarrett
		posted on 11/7/2003 at 4:04 PM
		</div>
		<div class="comment_text"><p>Thank you soooo much for the HS+5.5 snippet variable s! DOH! should of gone through the book, just used the web as a reference.</p><p>The one reason though im sticking with HS+ for a default IDE is speed of loading in general. I still find it a quicker enviroment to work in (and my PC should easily be able to handle anything), DWMX just tends to be that little (annoyingly) bit more slower. Oh and the file viewer. Actually if MM had this like HS+ then i think id swap.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615084">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615084">4</a> by Bartee
		posted on 11/13/2003 at 5:05 PM
		</div>
		<div class="comment_text"><p>Great idea,  Looked at the book online and do NOT see the list of variables available.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Flivedocs.macromedia.com%2Fcoldfusion%2F5.0%2FUsing_ColdFusion_Studio%2Fcreate7.htm%231106633%3A-Side7SsUtJ68iy4x_YJDBbCWAU&amp;cuid=3321886" rel="nofollow noopener" title="http://livedocs.macromedia.com/coldfusion/5.0/Using_ColdFusion_Studio/create7.htm#1106633">http://livedocs.macromedia....</a></p><p>Any Ideas...</p><p>And thx for your blog time... it is a now on my daily read list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615085">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615085">5</a> by Raymond Camden
		posted on 11/13/2003 at 5:13 PM
		</div>
		<div class="comment_text"><p>Bartee, the link above is to the CF 5.0 docs concerning CF Studio 5, therefore they are out of date. You need to look in the docs for HS+ itself.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615086">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615086">6</a> by Steve Ray
		posted on 11/15/2003 at 1:47 AM
		</div>
		<div class="comment_text"><p>This is the exact same stuff that MM has included in their CF Studio wizards for years. If you ever look at any of those .wml files in the wizards folders, you'll see those vars in there. Works the same, from what you're describing. Launch the wizard, you get a prompt, fill it in, and as the files get created, your info gets plugged in.</p><p>I can't believe that MM didn't put SCC support into DWMX2004. That's a stunning omission.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615083">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615083">7</a> by Jeff Wilkinson
		posted on 12/2/2003 at 11:43 PM
		</div>
		<div class="comment_text"><p>A couple of additional features of the homesite snippet variables:</p><p>&lt;p&gt;- You can embed your own variables into the snippet text. When you insert the snippet you are prompted for the values. They take the same form as VTML variables: $${VARNAME}.</p><p>&lt;p&gt;- You may also include a list of values for the variable like so: $${COLOR:Blue,Red,Green}.</p><p>&lt;p&gt;BTW, the predefined snippet vars are listed in <br>Andy Jarrett's blog &lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.andyjarrett.cfdeveloper.co.uk%2Findex.cfm%3Ffuseaction%3Dfuseblog.ShowComments%26ArticleID%3D20031120032225%3A9Yq6HuoMlttqQa9EMPQV50lfJSA&amp;cuid=3321886" rel="nofollow noopener" title="http://www.andyjarrett.cfdeveloper.co.uk/index.cfm?fuseaction=fuseblog.ShowComments&amp;ArticleID=20031120032225">http://www.andyjarrett.cfde...</a>"&gt;here&lt;/a&gt;.</p></div>
	</div>
</div>
		