
<div class="comment" id="c_1713616007">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616007">1</a> by Craig M. Rosenblum
		posted on 7/29/2004 at 10:55 PM
		</div>
		<div class="comment_text"><p>Definitely the old dark knight batman, Christian Bale, bringing out the dark psycho feeling....</p><p>I still remember him from Lord of the Rings, but anyways. I still loved Batman Forever the best, but ce sera...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616016">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616016">2</a> by Raymond Camden
		posted on 7/29/2004 at 11:19 PM
		</div>
		<div class="comment_text"><p>He was??? As who?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616021">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616021">3</a> by Andy Jarrett
		posted on 7/30/2004 at 12:05 AM
		</div>
		<div class="comment_text"><p>Cheers for that Ray, but Craig, no, sorry the first and second batman were still the darkest and best :o)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616022">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616022">4</a> by Jacob
		posted on 7/30/2004 at 2:04 PM
		</div>
		<div class="comment_text"><p>I agree -- first and second Batman were the best.  The rest were too "Disney".  The dark and mysterious works better.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616019">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616019">5</a> by Sung J. Woo
		posted on 8/18/2004 at 4:11 AM
		</div>
		<div class="comment_text"><p>Gunkata!  Equilibrium was cheesy, but it was a very good kinda cheesy.  Bale will be an excellent Batman, I agree.  He's a good actor.  If you haven't checked out American Psycho, I'd highly recommend it.  It's a bit gruesome, but he's very funny (in a dark way, of course).</p></div>
	</div>
</div>
		