
<div class="comment" id="c_1787842442">
	<div>
		<img src="https://disqus.com/api/users/avatars/geirman.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1787842442">1</a> by Chris Geirman
		posted on 1/12/2015 at 2:44 AM
		</div>
		<div class="comment_text"><p>I always forget I can call CFCs this way... api.cfc?method=dostuff&amp;input=foo</p></div>
	</div>
</div>
		
<div class="comment" id="c_1787895687">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1787895687">2</a> (In reply to <a href="#c_1787842442">#1</a>) by Raymond Camden
		posted on 1/12/2015 at 3:41 AM
		</div>
		<div class="comment_text"><p>This is probably - imo - one of the best features of ColdFusion.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3389858503">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3389858503">3</a> by Adm Che
		posted on 6/28/2017 at 3:22 PM
		</div>
		<div class="comment_text"><p>"The code on this page disabled back and forward caching". Have you seen this and if so, is there a fix? I'm using ColdFusion 11 and IE 11</p></div>
	</div>
</div>
		
<div class="comment" id="c_3389974225">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3389974225">4</a> (In reply to <a href="#c_3389858503">#3</a>) by Raymond Camden
		posted on 6/28/2017 at 4:22 PM
		</div>
		<div class="comment_text"><p>Does that have something to do with this blog post?</p></div>
	</div>
</div>
		
<div class="comment" id="c_3897190902">
	<div>
		<img src="https://disqus.com/api/users/avatars/eselkay.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3897190902">5</a> by EsElKay
		posted on 5/12/2018 at 7:01 AM
		</div>
		<div class="comment_text"><p>I know this info is ancient history but some of us are just now getting up to speed with jQuery and CF. Between <a href="http://disq.us/url?url=http%3A%2F%2Flearn.jquery.com%2Fusing-jquery-core%2Fdata-methods%2F%3AnXRP6SrUO8-r2at7V-48BqIdGV0&amp;cuid=3321886" rel="nofollow noopener" title="http://learn.jquery.com/using-jquery-core/data-methods/">http://learn.jquery.com/usi...</a> and this demo the light just came on. I can't wait to see where this learning leads me.</p><p>I thought you might like to know that your work years ago is still bearing fruit.</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_3897475549">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3897475549">6</a> (In reply to <a href="#c_3897190902">#5</a>) by Raymond Camden
		posted on 5/12/2018 at 2:03 PM
		</div>
		<div class="comment_text"><p>Thank you for letting me know. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4597317803">
	<div>
		<img src="https://disqus.com/api/users/avatars/halidayek.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4597317803">7</a> by Halid AYÇİÇEK
		posted on 8/30/2019 at 7:12 AM
		</div>
		<div class="comment_text"><p>ColdFusion!<br>$.ajax({<br>			type:"GET",<br>			url:"/rest/api/uts/send/",<br>			cache:false,<br>			data:GetData,<br>			dataType:"json",<br>			success: function() {</p><p>                             json format please help how do I fetch sql data here</p><p>			}</p><p>		});</p></div>
	</div>
</div>
		
<div class="comment" id="c_4597791523">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4597791523">8</a> (In reply to <a href="#c_4597317803">#7</a>) by Raymond Camden
		posted on 8/30/2019 at 4:21 PM
		</div>
		<div class="comment_text"><p>If you don't know how to write CFCs, I'd start there. Please check the docs.</p></div>
	</div>
</div>
		