
<div class="comment" id="c_1713741793">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713741793">1</a> by Sameer
		posted on 6/20/2012 at 10:39 PM
		</div>
		<div class="comment_text"><p>Wow! That's a super cool app!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713741814">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713741814">2</a> by Ben Dalton
		posted on 6/21/2012 at 12:53 AM
		</div>
		<div class="comment_text"><p>This was a fun project. I enjoyed playing with websockets for pushing real-time data updates to the client from the server. Client-Client communication is interesting and has quite a few use cases, Server-client data "pushing" has a TON of interesting uses.</p><p>It would actually be very easy to adjust an existing CF application to broadcast a notification when data has been updated and trigger a refresh event in an "AJAX" front end. This would prevent polling and allow people to have always-up-to-date data sets in a rich-client situation.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713741812">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713741812">3</a> by PaulH
		posted on 6/21/2012 at 3:45 AM
		</div>
		<div class="comment_text"><p>very slick.</p></div>
	</div>
</div>
		