
<div class="comment" id="c_1713665239">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665239">1</a> by Kyle Hayes
		posted on 5/15/2007 at 9:23 PM
		</div>
		<div class="comment_text"><p>Type -36 error (I/O Errors (bummers)</p><p>This file is having difficulty while either reading from the drive or writing to the drive. The file<br>may have been improperly written data to the drive or the hard drive or disk may be damaged.<br>This is almost always indicative of a media error (hard error on the disk). Sometimes (rarely) it is transient.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665218">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665218">2</a> by Sean
		posted on 5/15/2007 at 9:54 PM
		</div>
		<div class="comment_text"><p>"Macs don't get those cryptic error messages" - Justin Long (aka the Mac guy from the I'm a Mac, I'm a PC ads)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665240">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665240">3</a> by Greg Nilsen
		posted on 5/15/2007 at 10:24 PM
		</div>
		<div class="comment_text"><p>Actually, Sean, I think he's right.  Instead of giving you cryptic error messages, they give you a cryptic error TYPE which you can then look up to find out how screwed you are!</p><p>There are lies, damned lies, statistics, and advertising...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665222">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665222">4</a> by Max Hamby
		posted on 5/15/2007 at 10:31 PM
		</div>
		<div class="comment_text"><p>Well, to be fair... Windows will give you a cyptic error type AND cryptic error message that you can look up to see how screwed you are.</p><p>Personally, couldn't care less what I'm working on (I've worked on both).... its all computers and computers friggin' rock!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665224">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665224">5</a> by Elliott Sprehn
		posted on 5/15/2007 at 11:23 PM
		</div>
		<div class="comment_text"><p>They're rare, but OS X does have some cryptic error messages. If you know what you're doing though OS X is a dream compared to Windows to debug the problems.</p><p>If you check out the console and the system logs (/Applications/Utilities/<a href="http://disq.us/url?url=http%3A%2F%2FConsole.app%3AuXYH7HC9K1TkbTyEpYy3mBqWg7o&amp;cuid=3321886" rel="nofollow noopener" title="Console.app">Console.app</a>) you can learn a lot about what your system is doing at any point in time and what might have gone wrong.</p><p>Chances are the problems that caused your transfer to fail are in the console.log :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665220">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665220">6</a> by Louis Galipeau
		posted on 5/15/2007 at 11:26 PM
		</div>
		<div class="comment_text"><p>Yes computers friggin' rock, 'cept Windows can't do FUSE or any other nifty Linux/BSD stuff that Macs seem to be getting better at.</p><p>and Vista is going nowhere...</p><p>= end rant =</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665221">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665221">7</a> by dave
		posted on 5/16/2007 at 2:05 AM
		</div>
		<div class="comment_text"><p>what do u mean "vista is going nowhere.."</p><p>For gods sakes didnt you notice Vista got new sounds!!!!<br>I dunno how m$ did it but they got those new sounds in there, a monumental feat for them.....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665223">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665223">8</a> by Sean Corfield
		posted on 5/16/2007 at 8:10 AM
		</div>
		<div class="comment_text"><p>For another mirthful message from Macs:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fcorfield.org%2Fentry%2FApple_Mail_say_wha%3AnH_KMLaQAglXunfXgKK5Ec5Waes&amp;cuid=3321886" rel="nofollow noopener" title="http://corfield.org/entry/Apple_Mail_say_wha">http://corfield.org/entry/A...</a></p></div>
	</div>
</div>
		