
<div class="comment" id="c_1713743743">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743743">1</a> by Ryan
		posted on 11/6/2012 at 1:42 AM
		</div>
		<div class="comment_text"><p>Ray,<br>I am curious what made you/your wife decide to use a google based survey application versus a) Soundings b) Surveymonkey (probably limited to the 100 free respondants)?</p><p>I downloaded Soundings a few days ago and am contemplating using it versus the free version of Surveymonkey to offer a small survey to 2 different groups I am in and wondered why you picked the Google one.<br>Ryan</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743754">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743754">2</a> by Raymond Camden
		posted on 11/6/2012 at 1:44 AM
		</div>
		<div class="comment_text"><p>It was quicker to set up. I didn't have Soundings installed on my own server. I like how Google handles questions too - much quicker to edit. Something for me to consider if I ever get time to work on Soundings again.</p></div>
	</div>
</div>
		