
<div class="comment" id="c_1713664641">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664641">1</a> by DK
		posted on 5/2/2007 at 9:06 PM
		</div>
		<div class="comment_text"><p>holy mother of easy living we can use ++ soon! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664656">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664656">2</a> by Sean Corfield
		posted on 5/3/2007 at 2:51 AM
		</div>
		<div class="comment_text"><p>Also check out my writeup of Ben's preso at BACFUG, with more details and some code samples:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fcorfield.org%2Fentry%2FBen_on_Scorpio_at_BACFUG%3AqMFmwUn0bNoc40pFJRIe1H7mcp8&amp;cuid=3321886" rel="nofollow noopener" title="http://corfield.org/entry/Ben_on_Scorpio_at_BACFUG">http://corfield.org/entry/B...</a></p><p>I'll be speaking at cf.Objective() (and CFUNITED) about the new AJAX functionality in Scorpio, going into lots of detail!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664654">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664654">3</a> by Raymond Camden
		posted on 5/3/2007 at 5:27 AM
		</div>
		<div class="comment_text"><p>Yeah, but at the same time as me, so I hope you don't mind when I delete your comment... ;)</p></div>
	</div>
</div>
		