
<div class="comment" id="c_1713722189">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722189">1</a> by Tony Nelson
		posted on 2/26/2010 at 9:15 AM
		</div>
		<div class="comment_text"><p>Interesting stuff, although I have to admit my favorite part was seeing all the tweets from @fart_robot in your example. Gotta love Twitter...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722192">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722192">2</a> by Grant Copley
		posted on 2/26/2010 at 9:18 AM
		</div>
		<div class="comment_text"><p>Nice idea!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722194">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722194">3</a> by Pedro Morin
		posted on 2/26/2010 at 7:44 PM
		</div>
		<div class="comment_text"><p>Always thinking of cool stuff to blog about, thanks Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722193">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722193">4</a> by PaulH
		posted on 2/27/2010 at 10:55 PM
		</div>
		<div class="comment_text"><p>you probably should do one for bing's xlate service:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.microsofttranslator.com%2FDefault.aspx%3AmHX28gwFJ_Jpi7ZZQQP17mEe23I&amp;cuid=3321886" rel="nofollow noopener" title="http://www.microsofttranslator.com/Default.aspx">http://www.microsofttransla...</a></p><p>then while you're at it, one for my daughter's cat.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722197">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722197">5</a> by Raymond Camden
		posted on 2/27/2010 at 10:58 PM
		</div>
		<div class="comment_text"><p>Thanks Paul. Bing has some very interesting services. I've looked at them a bit but I don't think I've done a blog entry on them.</p><p>I hope the cat remark was just a joke. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722195">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722195">6</a> by PaulH
		posted on 2/27/2010 at 11:08 PM
		</div>
		<div class="comment_text"><p>oh no, i mean if you going to get gibberish translations, why not get really *good* make-no-mistake-about-it gibberish ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722196">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722196">7</a> by Raymond Camden
		posted on 2/27/2010 at 11:28 PM
		</div>
		<div class="comment_text"><p>Heh, I was WAITING for you to chime in here. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722198">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722198">8</a> by Ben Nadel
		posted on 3/2/2010 at 5:01 AM
		</div>
		<div class="comment_text"><p>Very cool :)</p></div>
	</div>
</div>
		