
<div class="comment" id="c_3713095473">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3713095473">1</a> by Robert Zehnder
		posted on 1/17/2018 at 9:33 PM
		</div>
		<div class="comment_text"><p>Honestly that is pretty cool, I would have totally over complicated it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3713137958">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3713137958">2</a> (In reply to <a href="#c_3713095473">#1</a>) by Raymond Camden
		posted on 1/17/2018 at 9:55 PM
		</div>
		<div class="comment_text"><p>Thanks. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_3716385394">
	<div>
		<img src="https://disqus.com/api/users/avatars/phillipsenn.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3716385394">3</a> by Phillip Senn
		posted on 1/19/2018 at 8:34 PM
		</div>
		<div class="comment_text"><p>You are a JavaScript Ninja. Master said "When you can scrape the data from my website, it will be time for you to leave".</p></div>
	</div>
</div>
		
<div class="comment" id="c_3717369017">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3717369017">4</a> (In reply to <a href="#c_3716385394">#3</a>) by Raymond Camden
		posted on 1/20/2018 at 2:03 PM
		</div>
		<div class="comment_text"><p>Hah :)</p></div>
	</div>
</div>
		