
<div class="comment" id="c_1713649187">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649187">1</a> by Malcolm Hawker
		posted on 1/17/2006 at 4:51 AM
		</div>
		<div class="comment_text"><p>Ray, that extension is a beautiful thing :)</p><p>and works great :))</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649195">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649195">2</a> by The Rabid CF Developer
		posted on 1/17/2006 at 4:55 AM
		</div>
		<div class="comment_text"><p>You da man, Ray !</p><p>You just keep making my life easier and easier and easier...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649196">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649196">3</a> by Brett Liotta
		posted on 1/17/2006 at 5:11 AM
		</div>
		<div class="comment_text"><p>very cool Ray.</p><p>Can I use this outside the CF Administrator?  B/c our host doesn't allow us direct access to the Administrator.  But we do have access to the mail directory paths and all the .cfmail files.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649197">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649197">4</a> by Brian Rinaldi
		posted on 1/17/2006 at 5:25 AM
		</div>
		<div class="comment_text"><p>Very cool. I added it to the open-source project list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649198">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649198">5</a> by tony of the weeg clan
		posted on 1/17/2006 at 9:51 AM
		</div>
		<div class="comment_text"><p>nigga you is crazy!</p><p>nice idea though.</p><p>havent implemented yet, but the intro alone has now compelled moi!</p><p>adios<br>tw</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649202">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649202">6</a> by Frank Gerritse
		posted on 1/17/2006 at 3:50 PM
		</div>
		<div class="comment_text"><p>have implemented right away, It works great thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649200">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649200">7</a> by Sana Ullah
		posted on 1/17/2006 at 4:36 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>I think your code is really cool, we can check our bounce mails and your code exposed alot thing we can do very easily.</p><p>Thanks for your great code.</p><p>Thanks</p><p>Sana</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649199">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649199">8</a> by Phillip Senn
		posted on 1/17/2006 at 6:57 PM
		</div>
		<div class="comment_text"><p>You had me at &lt;cfmail&gt;.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649204">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649204">9</a> by tony of the weeg clan
		posted on 1/17/2006 at 7:02 PM
		</div>
		<div class="comment_text"><p>i absolutely KNEW this post would garner responses like this, that was funny as hell phillip, thanks for the smile this marnin'</p><p>tw</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649206">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649206">10</a> by ross
		posted on 1/17/2006 at 7:49 PM
		</div>
		<div class="comment_text"><p>Ohmigawd.  w00t!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649201">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649201">11</a> by Raymond Camden
		posted on 1/17/2006 at 8:10 PM
		</div>
		<div class="comment_text"><p>Brett, yes. Just put the files anywhere - although you may want to add password protection to it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649203">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649203">12</a> by Robo
		posted on 1/17/2006 at 9:01 PM
		</div>
		<div class="comment_text"><p>Can this be used on CF MX6.1?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649205">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649205">13</a> by Raymond Camden
		posted on 1/17/2006 at 9:06 PM
		</div>
		<div class="comment_text"><p>Robo - yes. It should work just fine. Probably even in CF5.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649208">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649208">14</a> by Raymond Camden
		posted on 1/17/2006 at 9:18 PM
		</div>
		<div class="comment_text"><p>Oops - I forgot that I used App.cfc. Phillip Duba sent me an app.cfm version. I'll proably switch to that later. Anyway - for those of you on 6.X, you will need to rewrite the app.cfc. But it shouldn't take long.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649210">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649210">15</a> by Brett Liotta
		posted on 1/19/2006 at 9:25 AM
		</div>
		<div class="comment_text"><p>Hey Ray, can you explain the "or 1" thing below?  I've never seen this shorthand.</p><p>isDefined("url.reinit") or 1</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649207">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649207">16</a> by tony of the weeg clan
		posted on 1/19/2006 at 9:32 AM
		</div>
		<div class="comment_text"><p>isnt 1 = yes = on = a positive thereby always boolean for yes, 1, on etc...</p><p>so basically its going to happen either way, whatever follows.  so then, i ask, whats the point of checking for the existence?</p><p>its not a bitwise or operation, so i dont think its that.</p><p>must be like 1 or 1 really, since the isDefined("") returns 1 if its true.</p><p>right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649188">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649188">17</a> by Raymond Camden
		posted on 1/19/2006 at 11:19 AM
		</div>
		<div class="comment_text"><p>Brett, it is a mistake. :) It is my way of telling to app to reinit on every request. I do this when I'm developing something. In this case, I simply forgot to turn it off! I'll update the app tomorrow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649190">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649190">18</a> by Brett Liotta
		posted on 1/19/2006 at 11:27 AM
		</div>
		<div class="comment_text"><p>lol.  that's pretty funny.  you know I was thinking maybe it's just an override b/c he didn't feel like commenting out the cfif lines.  but that was after I posted.  heh, that's a good one.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649209">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649209">19</a> by Brett Liotta
		posted on 1/19/2006 at 11:51 AM
		</div>
		<div class="comment_text"><p>Ray, can you explain this?  why do you tell cf to ignore the runtime.abortexception?</p><p>&lt;cfif structKeyExists(arguments.exception, "rootCause") and structKeyExists(arguments.exception.rootCause, "type") and arguments.exception.rootCause.type is "coldfusion.runtime.AbortException"&gt;<br>      &lt;cfreturn&gt;<br>&lt;/cfif&gt;</p><p>Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649212">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649212">20</a> by Raymond Camden
		posted on 1/19/2006 at 7:18 PM
		</div>
		<div class="comment_text"><p>There is a bug where cflocation (or cfabort, I always forget) will fire onError. That code is there to make it ignore it.</p><p>FYI - I'll be updating the zip today to use APp.cfm. Someone sent me the conversion already so it won't take long. This will let the app work with CF6. (And CF5 I'm sure.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649211">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649211">21</a> by Sung
		posted on 2/9/2006 at 1:22 AM
		</div>
		<div class="comment_text"><p>Ray, you are the man.  This is so simple and beautiful.  Thanks a bunch.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649213">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649213">22</a> by David Lakein
		posted on 2/14/2006 at 8:35 AM
		</div>
		<div class="comment_text"><p>Just checked it out; looks awesome!</p><p>The one thing I have besides this for managing the spool is a text-mode file manager with built-in fast viewer (Far) - but this is loads easier.</p><p>One huge addition would be to extract the relevant line(s) from mail.log (and mailsent.log for 6/7) for that spool filename to get the exact error. Would be version-specific, and requires searching through 1-2 potentially big logfiles that may be locked, so may be more trouble than it's worth, unless it's possible to read those without locking.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649214">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649214">23</a> by Abovethesky
		posted on 1/15/2010 at 2:45 PM
		</div>
		<div class="comment_text"><p>Please does anyone know how to configure cfmail to send delivery notification to an email address? i'm trying to monitor the emails i send out such that a response should be sent to my address when the email is delivered, i should get a notification.<br>Thanks.</p></div>
	</div>
</div>
		