
<div class="comment" id="c_1713748323">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748323">1</a> by S P Technolab
		posted on 8/27/2013 at 2:30 PM
		</div>
		<div class="comment_text"><p>Thanks for sharing this info with us..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713748322">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748322">2</a> by Maxime Robert
		posted on 9/4/2013 at 4:05 PM
		</div>
		<div class="comment_text"><p>Very useful !<br>But I'm surprised this isn't fixed yet, as well as the other bug pointed out in <a href="http://disq.us/url?url=http%3A%2F%2Fwww.raymondcamden.com%2Findex.cfm%2F2013%2F8%2F15%2FUsing-the-PhoneGap-CLI-on-Windows-Watch-out-for-this-bug%3AyY9w_Z-8DKm-tcV5e0x9a2Y5ilo&amp;cuid=3321886" rel="nofollow noopener" title="http://www.raymondcamden.com/index.cfm/2013/8/15/Using-the-PhoneGap-CLI-on-Windows-Watch-out-for-this-bug">http://www.raymondcamden.co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713748325">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713748325">3</a> by Raymond Camden
		posted on 9/4/2013 at 5:49 PM
		</div>
		<div class="comment_text"><p>Maxime: Yeah, I'm trying to track down when the next release will be. Will post when I know.</p></div>
	</div>
</div>
		