
<div class="comment" id="c_1713711461">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711461">1</a> by BA
		posted on 1/10/2009 at 9:16 AM
		</div>
		<div class="comment_text"><p>I wish I could help but I haven't moved up to CF 7 yet :)</p><p>BA<br><a href="http://disq.us/url?url=http%3A%2F%2Fnobosh.com%3Aj4XGlUyyeHCH8Oekgr5P3SJGGks&amp;cuid=3321886" rel="nofollow noopener" title="http://nobosh.com">http://nobosh.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711462">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711462">2</a> by Gurpreet
		posted on 7/4/2010 at 11:34 AM
		</div>
		<div class="comment_text"><p>How do i bind an additional parametr like:</p><p>&lt;cfdiv bindOnLoad="False" bind="url:checkuser.cfm?email_addr={email_addr},sting=1" ID="theDiv1" style="color:red;"/&gt;</p><p>checkuser.cfm is a file which have two queries, one it matches the username and that is matched when no sting=1 is passed, now in the same file, i have called the &lt;cfif isdefined('url.string') and url.sting IS 1&gt;<br>query to match the email goes here<br>&lt;/cfif&gt;</p><p>but it returning empty results! i mean displays nothing in firebug</p><p>i think i am doing something horribly wrong</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711463">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711463">3</a> by Gurpreet
		posted on 7/4/2010 at 12:15 PM
		</div>
		<div class="comment_text"><p>solvedi it!</p><p>used &amp; instead of ,</p></div>
	</div>
</div>
		