
<div class="comment" id="c_1713743122">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743122">1</a> by Phillip Senn
		posted on 10/9/2012 at 7:05 PM
		</div>
		<div class="comment_text"><p>Maybe one day one of the code names for ColdFusion will be Cobra.</p></div>
	</div>
</div>
		