
<div class="comment" id="c_1714081466">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081466">1</a> by Cutter
		posted on 1/16/2014 at 8:36 PM
		</div>
		<div class="comment_text"><p>Wow! That is flippin' awesome! This could be a lot of fun...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081477">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081477">2</a> by Jaana Gilbert
		posted on 1/18/2014 at 9:57 PM
		</div>
		<div class="comment_text"><p>That is quite impressive!! They make it seem so easy hehe. I need to give this a try for sure.<br>Thanks for posting the movie!</p></div>
	</div>
</div>
		