
<div class="comment" id="c_1713743903">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743903">1</a> by Mikel
		posted on 11/22/2012 at 7:45 PM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving to you and yours as well!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743892">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743892">2</a> by Simon MacDonald
		posted on 11/22/2012 at 10:28 PM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving! I get to head down to the lounge to watch some NFL football while I work. One of the better days in the year for a Canadian working for an American company. All the football I can watch and none of the distractions.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743907">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743907">3</a> by Ristef
		posted on 11/23/2012 at 1:54 PM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving to you Raymond !</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743902">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743902">4</a> by Phillip Senn
		posted on 11/30/2012 at 2:05 AM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving! (Going through my inbox)</p></div>
	</div>
</div>
		