
<div class="comment" id="c_1713663644">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663644">1</a> by Chad
		posted on 3/28/2007 at 4:23 PM
		</div>
		<div class="comment_text"><p>Does this mean the end of CFJUG?</p><p>How about doing FlexJUG?  I am really starting to dig Flex and need more examples and training.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663634">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663634">2</a> by Sid Wing
		posted on 3/29/2007 at 1:23 AM
		</div>
		<div class="comment_text"><p>Let me echo Chad question (about CFJUG) and suggestion (about FlexJUG). I am neck deep in an enterprise-level flex app and could really use some Jedi-level examples/training/info.  GOOD training materials for Flex are still really sparse.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663647">3</a> by Raymond Camden
		posted on 3/29/2007 at 1:31 AM
		</div>
		<div class="comment_text"><p>My CFJUG is very different. First, its just me (grin), and, um, well thats it. ;) So no, this won't impact it.</p><p>I'll be happy to do both a Flex and Apollo meeting once I get a bit more used to them. I'm not quite a Jedi yet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663657">4</a> by chad gray
		posted on 3/29/2007 at 1:46 AM
		</div>
		<div class="comment_text"><p>I dont know if we are looking for a Jedi on flex/apollo, but more of a place to talk about it.</p><p>The technology and language is so new to a lot of people that have been doing CF work that i think they can benefit from more talks and presentations.</p><p>Adobe has done a wonderful job in giving examples and test code, but i think all of us could benifit from more sharing of code/insight like CFTalk did for me when i started programming in CF many o' years ago.</p><p>Action script i use to make fun of about 2 years ago.  Now it powers Flex and i need to catch up!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663645">5</a> by Raymond Camden
		posted on 3/29/2007 at 3:09 AM
		</div>
		<div class="comment_text"><p>Well if you are looking for a 'cf-talk' for apollo, there -is- a yahoo group that is getting used quite a bit.</p></div>
	</div>
</div>
		