
<div class="comment" id="c_1822511692">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1822511692">1</a> by Joel
		posted on 1/29/2015 at 12:04 AM
		</div>
		<div class="comment_text"><p>Not sure I like your "5 stylesheets" answer. If all five were local, I'd keep them separate in the code-base, and use a bundling tool to combine them into a single file for deployment, to minimize HTTP requests and speed up load time. Alternatively, "framework" CSS like Bootstrap may be best loaded from a CDN, since it increases the chances that your user already has the CSS in their cache and doesn't have to download it at all.</p><p>Also I can't imagine a real-world application where Bootstrap is enough, and doesn't require any application-specific CSS at all. Even my toy learning apps tend to have their own CSS (and little-to-no inline style attributes).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1822769639">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1822769639">2</a> (In reply to <a href="#c_1822511692">#1</a>) by Raymond Camden
		posted on 1/29/2015 at 2:04 AM
		</div>
		<div class="comment_text"><p>Joel, first off, thank you. I've only done two of these, but this is my first disagreement. I'm hoping for more of them. :)</p><p>So to your first part, isn't that what I said? Or did you not agree with my saying I'd keep "frameworks" like Bootstrap out? I think we agree *except* for that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1824999177">
	<div>
		<img src="https://disqus.com/api/users/avatars/geirman.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1824999177">3</a> by Chris Geirman
		posted on 1/30/2015 at 4:54 AM
		</div>
		<div class="comment_text"><p>I loved VSS actually. It just made sense to me. My last client used perforce (ug!). I highly recommend the Git Pro book! Very easy to get through and will very quickly ramp up your skillz! If you'd rather not buy the book, you can read it online free... <a href="http://disq.us/url?url=http%3A%2F%2Fgit-scm.com%2Fdocumentation%3AGSYC_7va_GjmgT2Zw3M8MsB6H-U&amp;cuid=3321886" rel="nofollow noopener" title="http://git-scm.com/documentation">http://git-scm.com/document...</a></p></div>
	</div>
</div>
		