
<div class="comment" id="c_1713744733">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744733">1</a> by Jeromy French
		posted on 2/26/2013 at 7:59 PM
		</div>
		<div class="comment_text"><p>Totally agree. I wasn't aware of &lt;dl&gt;/&lt;dt&gt;/&lt;dd&gt; until I noticed it in Bootstrap's CSS documentation!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744732">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744732">2</a> by Pete
		posted on 2/28/2013 at 1:49 PM
		</div>
		<div class="comment_text"><p>I use <a href="http://disq.us/url?url=http%3A%2F%2Fteamtreehouse.com%3ACk9Gf_dmrITgI0JIx7E3cCJqauQ&amp;cuid=3321886" rel="nofollow noopener" title="teamtreehouse.com">teamtreehouse.com</a> videos to go back and cover the basics every now and again to remind of of things like the blockquote and address tags - I rarely use things like that. I usually pick up something basic I'd missed or forgotten about with each course I do.</p><p>Ian Devlin's post on the link was useful too, I didn't realise there were so many rel attributes. I will start using those.</p><p>I think the main problem is most of what I've learnt has been from copying example code and hacking away at things till they work - instead of reading the docs first.</p></div>
	</div>
</div>
		