
<div class="comment" id="c_1713671644">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671644">1</a> by Shane Zehnder
		posted on 9/12/2007 at 7:12 AM
		</div>
		<div class="comment_text"><p>The database explorer is my new favorite tool.  Very nice work.</p><p>Thanks for releasing it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671631">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671631">2</a> by O?uz Demirkap?
		posted on 9/12/2007 at 8:16 AM
		</div>
		<div class="comment_text"><p>Thanks Ray!!!</p><p>I love the PDFUtils which would be really popular.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671643">3</a> by Dale Fraser
		posted on 9/12/2007 at 8:24 AM
		</div>
		<div class="comment_text"><p>That DB Explorer is way cool. I'll be busy recommending improvements :) on RiaForge</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671646">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671646">4</a> by Andy Sandefer
		posted on 9/12/2007 at 7:29 PM
		</div>
		<div class="comment_text"><p>I got a sneak peak at the Database Explorer during the Best of Scorpio contest and I was immediately impressed with this very useful tool.  I know that everyone who didn't win 1st and 2nd ultimately tied for 3rd in the contest but I actually voted this entry as my 2nd favorite.  Nice work Ray - and thanks a lot for making it available for public use!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671648">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671648">5</a> by Raymond Camden
		posted on 9/12/2007 at 7:46 PM
		</div>
		<div class="comment_text"><p>I came in 3rd and got a sweet little IPod Shuffle. It's so small I could probably eat it. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671630">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671630">6</a> by Shane Zehnder
		posted on 9/12/2007 at 9:36 PM
		</div>
		<div class="comment_text"><p>I've seen the iPod Shuffles.  I'd lose that in about 2 minutes flat.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671641">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671641">7</a> by nick tong
		posted on 9/19/2007 at 5:05 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Are there any plans for the DBE to allow inline editing?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671638">8</a> by Raymond Camden
		posted on 9/19/2007 at 7:23 PM
		</div>
		<div class="comment_text"><p>Inline editing? Of what?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671637">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671637">9</a> by nick tong
		posted on 9/19/2007 at 7:32 PM
		</div>
		<div class="comment_text"><p>Sorry - to be more clear. The returned data from queries. So one could click a field and edit the data. smiler to <a href="http://disq.us/url?url=http%3A%2F%2Ftutorial401.easycfm.com%2F%3AVX_A9VOqYcKZWluFz9ZSwOjNM2c&amp;cuid=3321886" rel="nofollow noopener" title="http://tutorial401.easycfm.com/">http://tutorial401.easycfm....</a> ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671636">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671636">10</a> by Raymond Camden
		posted on 9/19/2007 at 7:37 PM
		</div>
		<div class="comment_text"><p>Hmmm. Could be interesting. The issue would be writing code that could generically accept updates. It's possible using cfdbinfo of course.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671640">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671640">11</a> by nick tong
		posted on 9/19/2007 at 8:21 PM
		</div>
		<div class="comment_text"><p>I'd be happy to contribute - ping me if you want any input.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713671642">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713671642">12</a> by Ed Sullows
		posted on 9/24/2007 at 7:15 PM
		</div>
		<div class="comment_text"><p>Inline editing would very much help - i know i could use it for a few clients.</p></div>
	</div>
</div>
		