
<div class="comment" id="c_1713730875">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730875">1</a> by Brice
		posted on 3/22/2011 at 6:12 PM
		</div>
		<div class="comment_text"><p>Thanks Ray.  This is a good idea for people to implement on their sites.<br>Mango Blog offers this up by default, for those who use Mango as their blog framework.  Example:<br>Normal:  /blog/feeds/rss.cfm<br>Category:  /blog/feeds/rss.cfm/category/coldfusion</p></div>
	</div>
</div>
		