
<div class="comment" id="c_3490692953">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_afj5HcLEXF.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3490692953">1</a> by Chris
		posted on 8/28/2017 at 2:22 PM
		</div>
		<div class="comment_text"><p>What happened to <a href="http://disq.us/url?url=http%3A%2F%2Fdeveloperria.com%3F%3A-BMWVSTgAHQpHuGstXJPbLp2qss&amp;cuid=3321886" rel="nofollow noopener" title="developerria.com?">developerria.com?</a> It seems to redirect to <a href="http://disq.us/url?url=http%3A%2F%2Fadobe.io%3AqJu_TmiSML5F_QpumLZjx7LMwT0&amp;cuid=3321886" rel="nofollow noopener" title="adobe.io">adobe.io</a> and I can't any of the original articles there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3490741571">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3490741571">2</a> (In reply to <a href="#c_3490692953">#1</a>) by Raymond Camden
		posted on 8/28/2017 at 2:53 PM
		</div>
		<div class="comment_text"><p>No idea - sorry.</p></div>
	</div>
</div>
		