
<div class="comment" id="c_1713662940">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662940">1</a> by Jay McConathy
		posted on 3/9/2007 at 9:12 PM
		</div>
		<div class="comment_text"><p>I like the look of that. I definately think it will be useful</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662938">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662938">2</a> by John Ramon
		posted on 3/9/2007 at 9:16 PM
		</div>
		<div class="comment_text"><p>Nice Ray, sounds like a great tool, I'm first in line to be a Beta or Alpha tester hehe.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662928">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662928">3</a> by Nick Tong
		posted on 3/9/2007 at 9:16 PM
		</div>
		<div class="comment_text"><p>This looks great Ray, well done to you both. If you need beta testers please let me know.  I find the data sources on the 3rd screen shot quite amusing... sorry is that childish... ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662919">4</a> by Mike Elston
		posted on 3/9/2007 at 9:16 PM
		</div>
		<div class="comment_text"><p>Very nice! Just make sure it is Mac OS X Compatable.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662937">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662937">5</a> by Danlance
		posted on 3/9/2007 at 9:17 PM
		</div>
		<div class="comment_text"><p>Very nice...</p><p>What needs to be enabled on the server / in the application in the terms of debugging settings?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662935">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662935">6</a> by Raymond Camden
		posted on 3/9/2007 at 9:20 PM
		</div>
		<div class="comment_text"><p>Nick - what are you - 2 years old? ;)</p><p>Danlance - You turn on debugging, select coldfire as the template, and that's it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662943">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662943">7</a> by Raymond Camden
		posted on 3/9/2007 at 9:21 PM
		</div>
		<div class="comment_text"><p>Elston - I demonstrated this at CFUNITED/Express... on my Mac.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662942">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662942">8</a> by Joe Danziger
		posted on 3/9/2007 at 9:21 PM
		</div>
		<div class="comment_text"><p>This is great!!!!!  Firebug is the ultimate debugging tool and having CF debugging available as well would make it just awesome.  Especially love how you've made it even better than the standard stuff by reconverting the cfqueryparam variables.  Great work Ray and Adam!!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662939">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662939">9</a> by Shlomy Gantz
		posted on 3/9/2007 at 9:24 PM
		</div>
		<div class="comment_text"><p>Awsome</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662927">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662927">10</a> by Jeremy Prevost
		posted on 3/9/2007 at 9:29 PM
		</div>
		<div class="comment_text"><p>Is it ready yet? It's been like over 15 minutes! Come on already :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662933">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662933">11</a> by Marcos Placona
		posted on 3/9/2007 at 9:36 PM
		</div>
		<div class="comment_text"><p>That's brilliant Ray. I can't wait for it to be released. Here's one more beta tester if you need.</p><p>Cheers</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662931">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662931">12</a> by Ryan Arneson
		posted on 3/9/2007 at 9:44 PM
		</div>
		<div class="comment_text"><p>Count me in for beta testing, this looks amazing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662930">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662930">13</a> by Michael Dinowitz
		posted on 3/9/2007 at 9:45 PM
		</div>
		<div class="comment_text"><p>I'd have to argue that the web developer toolbar is the best, but firebug is right up there with it.</p><p>Now about that beta testing. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662932">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662932">14</a> by Rich Kroll
		posted on 3/9/2007 at 9:53 PM
		</div>
		<div class="comment_text"><p>Amazing work Ray!  Add +1 to the list of beta / alpha testers ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662947">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662947">15</a> by Frederic Fortier
		posted on 3/9/2007 at 10:00 PM
		</div>
		<div class="comment_text"><p>How is it going to function with fusebox and AJAX?</p><p>In Fusebox 5 you have to disable query execution time.. since the fusebox cfc's are clogging the debug parsing time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662948">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662948">16</a> by Raymond Camden
		posted on 3/9/2007 at 10:04 PM
		</div>
		<div class="comment_text"><p>AJAX: Good question. Let's say you load foo.cfm, and foo.cfm does an ajax call to goo.cfm. RIght now ColdFire shows the _main_ debug info, which is foo.cfm. Adam has said he thinks hew can make it support N sets of data per request, so we may have all soon. This will be HUGE as right now you can't do debugging with ajax since it adds crap to the output stream. Since ColdFire is all header based, this would not be an issue.</p><p>Fusebox: Well, as I said, we should be adding a filter. This will let you drill down to specific entries. It was not intended to remove entries, but you could do that to focus on non-fusebox stuff.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662949">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662949">17</a> by jonese
		posted on 3/9/2007 at 10:05 PM
		</div>
		<div class="comment_text"><p>bring it on! we've got a few sites we've built in the past where we had to turn off debugging output cause it mucked with JS or CSS or something else.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662950">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662950">18</a> by Jim Prist
		posted on 3/9/2007 at 10:19 PM
		</div>
		<div class="comment_text"><p>This looks great!  I always have Firebug open so this would be really convenient!!</p><p>Release it to the masses!!! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662951">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662951">19</a> by Nick Walters
		posted on 3/9/2007 at 10:20 PM
		</div>
		<div class="comment_text"><p>Very cool. We love FireBug here, these days you really just can't work without it. This extension onto it would be great. Count me in for testing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662952">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662952">20</a> by Richard Davies
		posted on 3/9/2007 at 10:24 PM
		</div>
		<div class="comment_text"><p>Wow! I'm so excited---I can hardly wait to try this. I love Firebug and this would only add to its usefulness. Thank you for taking on this project!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662953">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662953">21</a> by Sam Curren
		posted on 3/9/2007 at 10:25 PM
		</div>
		<div class="comment_text"><p>Awesome! You just made my friday.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662954">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662954">22</a> by Frederic Fortier
		posted on 3/9/2007 at 10:37 PM
		</div>
		<div class="comment_text"><p>Well if you guys can make the AJAX integration. That is just going to be awesome.. but it still will be without it :-)</p><p>Thanks a lot.</p><p>Good work!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662958">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662958">23</a> by Sam Farmer
		posted on 3/9/2007 at 10:40 PM
		</div>
		<div class="comment_text"><p>This sounds awesome.</p><p>When displaying queries could it parse the real values in and not the ? when using cfqueryparam?</p><p>AJAX support would be amazing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662957">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662957">24</a> by Raymond Camden
		posted on 3/9/2007 at 10:46 PM
		</div>
		<div class="comment_text"><p>Sam, I think you missed some of my text in the entry. The code does replace the ? from cfqueryparam. A lot of ColdFire comes from the old Starfish.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662959">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662959">25</a> by Scott Krebs
		posted on 3/9/2007 at 10:47 PM
		</div>
		<div class="comment_text"><p>This is really sweet. What a fantastic idea... Thank you Ray!</p><p>&gt;support N sets of data per request</p><p>Will it support -gag- frames and allow viewing the debug info of each frame in the current set? I'm personally not a frames-lover (or even liker) but I've got to support some legacy apps that make extensive use of them (they were so cool in 1998! ;). It's tough to get debugging info out of very small frames and this would make life so much easier.</p><p>If frames support isn't planned and this sounds like a feature request on a piece of software that isn't even released yet, then my apologies for that. I'm really looking forward to something to squash the CSS positioning headaches with debug info once and for all. Woohoo!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662956">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662956">26</a> by Raymond Camden
		posted on 3/9/2007 at 10:50 PM
		</div>
		<div class="comment_text"><p>Frederic - no promises. But - at a bare minimum - you can have debug turned on and it won't _break_ AJAX requests</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662961">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662961">27</a> by Raymond Camden
		posted on 3/9/2007 at 10:53 PM
		</div>
		<div class="comment_text"><p>Scott, I believe this is all related to the AJAX stuff. Ie, if one URL has N sets of data than it should work. Should. Again - this is Adam's area here so I don't want to over promise.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662962">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662962">28</a> by Ken Dunnington
		posted on 3/9/2007 at 10:58 PM
		</div>
		<div class="comment_text"><p>This is fantastic! I'm working on a project now that suffers from the "CSS Ate My Debugging" syndrome :) Firebug is incredible, and this will only add to its indispensability. If this is an unofficial beta signup page, count me in! Would love to see an extension to ModelGlue that made its debug output available too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662965">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662965">29</a> by Raymond Camden
		posted on 3/9/2007 at 11:01 PM
		</div>
		<div class="comment_text"><p>There may be some confusion. When I asked if people would be interested, I didn't mean in the beta, but in the product as a whole. Ie, "Does this make sense?".</p><p>There won't be a beta sign up or anything, I'll just post the bits to my blog. It will open to all.</p><p>Oh wait - no - um - the beta is available to anyone who visits the wishlist! Or gets me a good import beer! There we go! ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662964">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662964">30</a> by David Stockton
		posted on 3/9/2007 at 11:09 PM
		</div>
		<div class="comment_text"><p>This is a top idea!</p><p>Well done!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662967">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662967">31</a> by Don
		posted on 3/9/2007 at 11:09 PM
		</div>
		<div class="comment_text"><p>This would be perfect for remote servers that do not have debug turned on like on <a href="http://disq.us/url?url=http%3A%2F%2Fjodohost.com%3AelQOTF2WB1Y9LgKfmYZhegC8RCA&amp;cuid=3321886" rel="nofollow noopener" title="jodohost.com">jodohost.com</a>.  It is maddening not being able to see debug when I write such sloppy code.<br>This would save me hours of frustration!!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662963">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662963">32</a> by John Ramon
		posted on 3/9/2007 at 11:14 PM
		</div>
		<div class="comment_text"><p>Don, the best solution is to download a Developer Version of ColdFusion and run locally.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662966">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662966">33</a> by jeff
		posted on 3/9/2007 at 11:17 PM
		</div>
		<div class="comment_text"><p>Fantastic!  What about variables?  I didn't see anything in the screenshots.  Also, assuming variable dump will be included, would there be any way to add in my own scope as I've done in existing debug?</p><p>Very cool idea Ray!  Thanks for all your hard work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662971">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662971">34</a> by Joel Cox
		posted on 3/9/2007 at 11:23 PM
		</div>
		<div class="comment_text"><p>A big woot! I use Firebug all the time, this makes it even more useful. Good job.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662968">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662968">35</a> by Brian Swartzfager
		posted on 3/9/2007 at 11:35 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>That looks really cool!  Kudos to you and Adam for coming up with this.  I look forward to hearing more about it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662972">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662972">36</a> by Kurt Bonent
		posted on 3/9/2007 at 11:40 PM
		</div>
		<div class="comment_text"><p>Brilliant!!!  I can't wait for ColdFire's release.  I've been doing a lot of sites with CSS layouts so this will be a huge help!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662970">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662970">37</a> by Roy Martin
		posted on 3/9/2007 at 11:43 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Once you get this wrapped up let me know because it would be the ideal thing to port the ModelGlue debugging info into this.</p><p>- Roy</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662969">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662969">38</a> by Justice
		posted on 3/9/2007 at 11:45 PM
		</div>
		<div class="comment_text"><p>I dont know where I might fit into this, but if you need any help feel free to hollar. =) This looks awesome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662973">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662973">39</a> by Mark Mazelin
		posted on 3/9/2007 at 11:57 PM
		</div>
		<div class="comment_text"><p>Late to the party, but looks like a promising tool. By the way, for Michael Dinowitz, I use a combination of Web Developer and FireBug--they each have their strengths. I love the ability of FireBug to integrate through such an extensible interface. Pretty awesome Ray!</p><p>Mark</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662974">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662974">40</a> by DK
		posted on 3/9/2007 at 11:58 PM
		</div>
		<div class="comment_text"><p>This looks like it will be a great addition to the toolboxes. I love firebug more everyday especially with some of these css challenged sites I've had to help on. Thanks as always :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662975">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662975">41</a> by Jeff Wilkinson
		posted on 3/10/2007 at 12:03 AM
		</div>
		<div class="comment_text"><p>very cool.  I've just begun to learn of the beauty that is firebug, so to find out there is similar support for php and now CF is great.</p><p>So, how about ASP now?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662978">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662978">42</a> by Michael Brennan-White
		posted on 3/10/2007 at 12:04 AM
		</div>
		<div class="comment_text"><p>I am definitely looking forward to using this.</p><p>I love Firebug and often thought it would be great if I could do CF with it as well.</p><p>Michael</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662977">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662977">43</a> by Raymond Camden
		posted on 3/10/2007 at 12:11 AM
		</div>
		<div class="comment_text"><p>Lots of stuff here. Nice.</p><p>So first off - I didn't consider it for ModelGlue. It _may_ be something to consider. We could make ColdFire extensible, where if it finds a header of the form coldfire_XXXX, then it tries to parse XXX. It would only support simple datasets, but, it could be possible. Definitely a 2.0 thing. ;)</p><p>Jeff - I'll do an ASP one when they pry the CF from my cold, dead, hands. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662981">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662981">44</a> by Scott P
		posted on 3/10/2007 at 12:21 AM
		</div>
		<div class="comment_text"><p>I just want a R2D2 mailbox...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662983">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662983">45</a> by Raymond Camden
		posted on 3/10/2007 at 12:28 AM
		</div>
		<div class="comment_text"><p>I just want Starbuck back...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662980">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662980">46</a> by Mike
		posted on 3/10/2007 at 12:57 AM
		</div>
		<div class="comment_text"><p>tes</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662982">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662982">47</a> by Alfio
		posted on 3/10/2007 at 12:58 AM
		</div>
		<div class="comment_text"><p>Definitely looks cool and useful. Wouldn't mind giving it a spin when it is completed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662979">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662979">48</a> by desd
		posted on 3/10/2007 at 12:59 AM
		</div>
		<div class="comment_text"><p>dsa</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662985">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662985">49</a> by Sid Wing
		posted on 3/10/2007 at 1:16 AM
		</div>
		<div class="comment_text"><p>AHA! So THAT is where that CF tab in Firebug came from in your demo to the NZ Folks!  Sneaky! Very Sneaky!  But also WAY cool!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662987">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662987">50</a> by Adam Fortuna
		posted on 3/10/2007 at 1:39 AM
		</div>
		<div class="comment_text"><p>Looks great! Definitely would use this.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662986">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662986">51</a> by Sean Corfield
		posted on 3/10/2007 at 3:19 AM
		</div>
		<div class="comment_text"><p>This would certainly get me to install FireBug. Looks awesome Ray. When can we have it? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662990">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662990">52</a> by Sam Clement
		posted on 3/10/2007 at 4:00 AM
		</div>
		<div class="comment_text"><p>Brilliannttt!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662993">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662993">53</a> by Raymond Camden
		posted on 3/10/2007 at 4:12 AM
		</div>
		<div class="comment_text"><p>As an FYI, I just added Total Execution Time and CFTRACE support on the server side. Next will be CFTIMER, EXCEPTIONS.</p><p>And not to get too wild.... but RDS is really just HTTP calls. If you look at Dreamweaver, it just does HTTP calls to get data. It is possible to enable RDS support via the plugin to let you browse DBs, and even see source code for files. Now mind you - I'm just talking wildly here so take this with a gigantic grain of salt.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662992">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662992">54</a> by Jaana Gilbert
		posted on 3/10/2007 at 5:45 AM
		</div>
		<div class="comment_text"><p>That is awesome! Count me in for beta testing!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662991">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662991">55</a> by Matt
		posted on 3/10/2007 at 7:12 AM
		</div>
		<div class="comment_text"><p>How can we help?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662989">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662989">56</a> by Raymond Camden
		posted on 3/10/2007 at 8:17 AM
		</div>
		<div class="comment_text"><p>Matt, it will be hosted at RIAForge, which means that you will be able to log issues and help us debug.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662996">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662996">57</a> by Jay Greer
		posted on 3/10/2007 at 12:31 PM
		</div>
		<div class="comment_text"><p>To borrow a phrase...</p><p>"Insanely Great!"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662994">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662994">58</a> by Richard Tugwell
		posted on 3/10/2007 at 1:46 PM
		</div>
		<div class="comment_text"><p>Wow - 55 replies in 8 hours. I think that answers your question Ray</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662995">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662995">59</a> by William from Lagos
		posted on 3/10/2007 at 11:35 PM
		</div>
		<div class="comment_text"><p>Great stuff. I just started getting used to this Firebug thingie.</p><p>How can I sign up to be notified when it becomes available?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662997">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662997">60</a> by William from Lagos
		posted on 3/10/2007 at 11:35 PM
		</div>
		<div class="comment_text"><p>Great stuff. I just started getting used to this Firebug thingie.</p><p>How can I sign up to be notified when it becomes available?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662999">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662999">61</a> by Ken Dunnington
		posted on 3/11/2007 at 12:20 AM
		</div>
		<div class="comment_text"><p>"Oh wait - no - um - the beta is available to anyone who visits the wishlist! Or gets me a good import beer! There we go! ;)" - LOL! If I make it to cf.Objective I'll try to sneak some homebrew on the plane, does that count? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662998">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662998">62</a> by Raymond Camden
		posted on 3/11/2007 at 12:43 AM
		</div>
		<div class="comment_text"><p>I've had a few more repeats on this so I'll say it again. You do not need to sign up. I'll be posting the bits when they are ready (which should be very soon). So... stop asking how to get the bits. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663003">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663003">63</a> by Sam Farmer
		posted on 3/11/2007 at 1:02 AM
		</div>
		<div class="comment_text"><p>@Ray -- Great stuff about the cfqueryparam being replaced.  Thats my bad for not actually reading the whole entry.  Damn reading....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663005">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663005">64</a> by Raymond Camden
		posted on 3/11/2007 at 1:16 AM
		</div>
		<div class="comment_text"><p>Sam: Yeah, the feature isn't perfect. Like for example, if you had name = &lt;cfqueryparam ...&gt;, you will see name = foo, where in reality it should be name = 'foo', but I figure people can deal.</p><p>Again - a lot of this was already done in Starfish - I'm just using the old code with some new updates.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663002">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663002">65</a> by Alexander
		posted on 3/11/2007 at 7:20 AM
		</div>
		<div class="comment_text"><p>PLEASE tell me this is coming out soon! It might be a dream come true for me, honestly, you know exactly what some people just need!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663008">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663008">66</a> by David Harris
		posted on 3/11/2007 at 7:55 AM
		</div>
		<div class="comment_text"><p>I remember you pointed that out when I said "Hey, Look, PHP!" when you did the Spry presentation to the Auckland CFUG.</p><p>I'm looking forward to it being ready!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663006">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663006">67</a> by Anand Paleja`
		posted on 3/12/2007 at 4:59 PM
		</div>
		<div class="comment_text"><p>Is it ready yet? jk! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663011">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663011">68</a> by Paul Glover
		posted on 3/12/2007 at 9:30 PM
		</div>
		<div class="comment_text"><p>Looks *very* useful! Will be installing it as soon as it's available.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663010">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663010">69</a> by Jeremy Prevost
		posted on 3/13/2007 at 1:01 AM
		</div>
		<div class="comment_text"><p>@ Ray: way off topic, but you started it :)<br>I want Starbuck back too! What the heck were they thinking? That said, I want Cylons back too! Season 3=yawn (with a few exceptions).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663012">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663012">70</a> by Brandner
		posted on 3/13/2007 at 1:49 AM
		</div>
		<div class="comment_text"><p>Awesome, can't wait!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663015">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663015">71</a> by Trond Ulseth
		posted on 3/13/2007 at 12:46 PM
		</div>
		<div class="comment_text"><p>hmm...what to say that's not said already?</p><p>Awesome, cool, rocking, miindblowing - please apply the one(s) that are not already used.</p><p>I'm using Firebug all the time, and I won't be using it any less once this get out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663014">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663014">72</a> by Dave Konopka
		posted on 3/15/2007 at 5:07 PM
		</div>
		<div class="comment_text"><p>This rocks. Unfortunately my work development environment is all done on a shared CF web server. So I can't hook up the ColdFire.cfm to debugging without affecting everyone else.</p><p>But it's an awesome tool.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663019">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663019">73</a> by Tak
		posted on 5/8/2007 at 5:34 PM
		</div>
		<div class="comment_text"><p>Looks like a great tool, Ray!</p><p>I wouldn't mind Alpha/Beta testing it!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663018">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663018">74</a> by Raymond Camden
		posted on 5/8/2007 at 5:39 PM
		</div>
		<div class="comment_text"><p>It has been out for a few months now. :) Still considering it 'beta' though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663021">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663021">75</a> by JOZEPH
		posted on 12/31/2007 at 5:14 AM
		</div>
		<div class="comment_text"><p>Unfortunately my work development environment is all done on a shared CF web server<br>yes.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663016">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663016">76</a> by SEO
		posted on 1/22/2008 at 2:48 AM
		</div>
		<div class="comment_text"><p>If this is an unofficial beta signup page, count me in! Would love to see an extension to ModelGlue that made its debug output available too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663020">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663020">77</a> by Raymond Camden
		posted on 1/22/2008 at 2:52 AM
		</div>
		<div class="comment_text"><p>It was released sometime ago. <a href="http://disq.us/url?url=http%3A%2F%2Fcoldfire.riaforge.org%3AttgthkBHkP8J3HrcB1YFu2h7MO4&amp;cuid=3321886" rel="nofollow noopener" title="http://coldfire.riaforge.org">http://coldfire.riaforge.org</a></p></div>
	</div>
</div>
		