
<div class="comment" id="c_1714079787">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079787">1</a> by Dinesh
		posted on 9/3/2013 at 9:35 PM
		</div>
		<div class="comment_text"><p>Well personally I do not think it will affect me in any way (you don't post India job anyway), but if there isn't any particular issue, you should continue with it. Such is your standing and following in community that prospective employers (and most of them already complain that there aren't any cf developers), find it easier to send the job to you and get better notice/responses. Bigger companies pay big bucks and get moe experienced, bigger developers. Small companies can't pay that much money, not to candidate nor to recruiters. Hence who is at loss? Upcoming developers. And then we talk about making the community large!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079812">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079812">2</a> by Andrew Scott
		posted on 9/4/2013 at 8:41 AM
		</div>
		<div class="comment_text"><p>Personally I think Blogs are not the place to put Jobs, twitter and other macro services I can understand. But a blog about a job that can sit there months or even years after the job has come and gone, just seems wrong to me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079813">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079813">3</a> by Matt W
		posted on 9/4/2013 at 12:52 PM
		</div>
		<div class="comment_text"><p>Please consider referring the employer to the CF jobs email list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079817">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079817">4</a> by Raymond Camden
		posted on 9/4/2013 at 1:59 PM
		</div>
		<div class="comment_text"><p>@MattW: Good idea.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079816">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079816">5</a> by Richard Hughes
		posted on 9/5/2013 at 6:23 PM
		</div>
		<div class="comment_text"><p>What is the link for the CF Jobs e-mail list?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079818">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079818">6</a> by Raymond Camden
		posted on 9/5/2013 at 6:36 PM
		</div>
		<div class="comment_text"><p>Here ya go: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.houseoffusion.com%2Fgroups%2Fcf-jobs%2F%3AWnqOiPyhtcl2XZMHysYlarHfkS4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.houseoffusion.com/groups/cf-jobs/">http://www.houseoffusion.co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079815">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079815">7</a> by Gary
		posted on 9/6/2013 at 5:02 AM
		</div>
		<div class="comment_text"><p>Ray,<br>I can look at houseoffusion should I need to but I do not remember ever seeing anything current there.</p><p>For all you do, I definitely wouldn't criticize you for not posting them. No way, no how.</p><p>Yet I think there are a good thing and they add to your site. It seems simple enough to post them and they're easily ignored just like any topic.</p><p>So you have two full votes for reconsidering and only one against!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079821">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079821">8</a> by Gary
		posted on 9/6/2013 at 5:15 AM
		</div>
		<div class="comment_text"><p>Not to pile on or show undue lack of empathy :) but</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fhouseoffusion.com%2Fgroups%2Fcf-jobs%2F%3Ait9aJunTaD2HY4MB7ctwfOInbEg&amp;cuid=3321886" rel="nofollow noopener" title="houseoffusion.com/groups/cf-jobs/">houseoffusion.com/groups/cf...</a> just threw this from JRun :</p><p>503 <br>Request timed out waiting to execute</p><p>(it finally came up)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079814">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079814">9</a> by prabakaran
		posted on 9/6/2013 at 3:04 PM
		</div>
		<div class="comment_text"><p>hey...what happened to you....?<br>i m your unknown friend from INDIA....<br>its not a good idea man...help others...its my kind request...<br>post jobs to help job seekers....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079820">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079820">10</a> by Raymond Camden
		posted on 9/6/2013 at 3:06 PM
		</div>
		<div class="comment_text"><p>Err, what makes you think something happened to me?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714079819">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714079819">11</a> by prabakaran
		posted on 9/11/2013 at 11:51 AM
		</div>
		<div class="comment_text"><p>hmmm, that u have decided to no longer post job openings on your blog.</p></div>
	</div>
</div>
		