
<div class="comment" id="c_1713664645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664645">1</a> by Raymond Camden
		posted on 5/3/2007 at 6:40 PM
		</div>
		<div class="comment_text"><p>Wow, that didn't take long. My flight was canceled and I'm back home now. I will (supposedly) be leaving at 11:50, but right now there are severe storms.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664659">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664659">2</a> by Kyle
		posted on 5/3/2007 at 11:38 PM
		</div>
		<div class="comment_text"><p>Ha. I have seen few people who have as many travel issues as you do. All the more reason to buy your own private jet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664661">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664661">3</a> by Nick
		posted on 5/4/2007 at 1:09 AM
		</div>
		<div class="comment_text"><p>Is there somewhere that we can download your travel itineraries? I'd be nice to know when to avoid, at all costs, traveling.</p><p>HAHA, sorry about your bad luck.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664660">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664660">4</a> by Sean Corfield
		posted on 5/4/2007 at 9:23 AM
		</div>
		<div class="comment_text"><p>You have the worst travel kharma of anyone I've ever met! I sure hope you make it here on time!</p></div>
	</div>
</div>
		