
<div class="comment" id="c_1713656796">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656796">1</a> by Damon Cooper
		posted on 8/25/2006 at 10:10 PM
		</div>
		<div class="comment_text"><p>Rahul is actually part of the Adobe website development team, not the CF team, fyi.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656791">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656791">2</a> by Raymond Camden
		posted on 8/25/2006 at 10:15 PM
		</div>
		<div class="comment_text"><p>Already fixed. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656801">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656801">3</a> by Sean Corfield
		posted on 8/26/2006 at 7:49 AM
		</div>
		<div class="comment_text"><p>Not quite fixed: Ashwin is a member of the CF product team, Rahul is a member of the Web Design and Technology Group (to give my old team their current full name!).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656802">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656802">4</a> by Raymond Camden
		posted on 8/26/2006 at 4:52 PM
		</div>
		<div class="comment_text"><p>I had forgotten to change the title. Is everyone happy now?? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656797">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656797">5</a> by Sean Corfield
		posted on 8/27/2006 at 12:13 AM
		</div>
		<div class="comment_text"><p>No, you still say Ashwin is a member of web team - he is not. He is a member of the CF product team.</p><p>:)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656798">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656798">6</a> by Raymond Camden
		posted on 8/27/2006 at 2:14 AM
		</div>
		<div class="comment_text"><p>Ok, I nuked Ashwin. I think this is the most edited entry on my blog. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656805">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656805">7</a> by Rahul Narula
		posted on 8/27/2006 at 9:03 AM
		</div>
		<div class="comment_text"><p>hehehe! I didnt noticed so many comments to my introductory post.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656800">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656800">8</a> by Ashwin Mathew
		posted on 8/27/2006 at 11:36 AM
		</div>
		<div class="comment_text"><p>&lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fblogs.sanmathi.org%2Fashwin%2F2006%2F08%2F27%2Fi-was-nuked-by-ray-camden%3AmVANf1z__YbmrLmtVPUFZ09b_pQ&amp;cuid=3321886" rel="nofollow noopener" title="http://blogs.sanmathi.org/ashwin/2006/08/27/i-was-nuked-by-ray-camden">http://blogs.sanmathi.org/a...</a>"&gt;<br>I was nuked by Ray Camden&lt;/a&gt; ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656803">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656803">9</a> by Raymond Camden
		posted on 8/27/2006 at 4:40 PM
		</div>
		<div class="comment_text"><p>Heh, to be fair, I did tell people about your blog a few weeks ago. I swear, I'm never mentioning someone elses blog again. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656799">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656799">10</a> by Ashwin Mathew
		posted on 8/27/2006 at 6:35 PM
		</div>
		<div class="comment_text"><p>Awww, c'mon, this is fun - imagine how many more people would love to get nuked by you? Verily, 'tis a rare privilege to be nuked by the Jedi Master hisself! ;)</p><p>But seriously, thanks for the mention back when I'd just started blogging.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656806">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656806">11</a> by Rahul Narula
		posted on 8/27/2006 at 7:23 PM
		</div>
		<div class="comment_text"><p>I agree with Ashwin. Mention from Jedimaster himself helps to get more into community.</p><p>Thanks again Ray :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656808">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656808">12</a> by Raymond Camden
		posted on 8/27/2006 at 8:39 PM
		</div>
		<div class="comment_text"><p>From now on - all blog mentions will be called Nukes. :)</p><p>And Rahul, no problem at all. Every new CF blogger out there just helps spread the gospel.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656807">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656807">13</a> by test
		posted on 9/15/2006 at 11:56 PM
		</div>
		<div class="comment_text"><p>test</p></div>
	</div>
</div>
		