
<div class="comment" id="c_1713736861">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736861">1</a> by Kevin Penny
		posted on 11/19/2011 at 3:40 AM
		</div>
		<div class="comment_text"><p>Thanks Ray - <br>You could also create multiple 'pages' that have each form displayed on them, so everything is downloaded all at once immediately, then the form 'post' just essentially hides the 'page' you're on and then displays the next 'page' (which contains the next form) and so on.  Then on the last form, you actually do a final POST of all the forms (sure jquery has some good multi form serializing of the data) and it becomes a '2' request/response process vs. 5, which slow network users may enjoy...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736858">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736858">2</a> by Raymond Camden
		posted on 11/19/2011 at 6:50 AM
		</div>
		<div class="comment_text"><p>Yep, that would work well too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736859">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736859">3</a> by Raymond Camden
		posted on 12/19/2011 at 3:23 AM
		</div>
		<div class="comment_text"><p>Sorry - I don't know PHP. I'm sure working with Form data must be simple though.</p></div>
	</div>
</div>
		