
<div class="comment" id="c_1713744522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744522">1</a> by Raymond Camden
		posted on 2/1/2013 at 3:58 AM
		</div>
		<div class="comment_text"><p>By the way - I'm thinking of taking the preso and turning it into a blog post so it could be read/downloaded/etc.</p></div>
	</div>
</div>
		