
<div class="comment" id="c_1713677351">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677351">1</a> by Don Quist
		posted on 2/24/2008 at 4:27 AM
		</div>
		<div class="comment_text"><p>Thank you Ray, I've been meaning to make a facebook app and this is very easy to understand basic walk-through</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677373">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677373">2</a> by Raul Riera
		posted on 2/24/2008 at 7:35 AM
		</div>
		<div class="comment_text"><p>This is pretty good info. Thanks. I wonder how far can someone go with this. I will have to dig more into the FBML</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677358">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677358">3</a> by Dmitry Yakhnov
		posted on 2/25/2008 at 8:48 AM
		</div>
		<div class="comment_text"><p>One more thing to be aware of:<br>FB has 7 secs timeout for any request to your server, so your application has to be really quick with good hosting close to FB =)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677354">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677354">4</a> by Raymond Camden
		posted on 2/25/2008 at 9:00 AM
		</div>
		<div class="comment_text"><p>Yes, but I use ColdFusion, and 7 seconds would be an eternity for CF. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677353">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677353">5</a> by Dmitry Yakhnov
		posted on 2/25/2008 at 11:42 AM
		</div>
		<div class="comment_text"><p>Don't forget that any REST call (getting user info, list of friends, any other data) will be made to FB server within these 7 secs, so add XML round trip time and FB processing time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677352">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677352">6</a> by MrBuzzy
		posted on 2/25/2008 at 12:22 PM
		</div>
		<div class="comment_text"><p>Shameless plug, check out <a href="http://disq.us/url?url=http%3A%2F%2Fcoldface.org%3ACjoqfUZKw3u5QT-qOfvIoMLTU4I&amp;cuid=3321886" rel="nofollow noopener" title="http://coldface.org">http://coldface.org</a> or at least <a href="http://disq.us/url?url=http%3A%2F%2Fapps.facebook.com%2Fcoldface-exmaple-app%2F%3APwu56HL7b2fy6S3MBZNtBoem6Qo&amp;cuid=3321886" rel="nofollow noopener" title="http://apps.facebook.com/coldface-exmaple-app/">http://apps.facebook.com/co...</a> I invite anyone in the CF community to get involved. Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677361">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677361">7</a> by MrBuzzy
		posted on 2/25/2008 at 12:23 PM
		</div>
		<div class="comment_text"><p>Oops I meant <a href="http://disq.us/url?url=http%3A%2F%2Fapps.facebook.com%2Fcoldface-example-app%2F%3AEN-lKWGlcONejoN8Y3hh3EHy69M&amp;cuid=3321886" rel="nofollow noopener" title="http://apps.facebook.com/coldface-example-app/">http://apps.facebook.com/co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677355">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677355">8</a> by Lola LB
		posted on 2/26/2008 at 1:15 AM
		</div>
		<div class="comment_text"><p>Please . . . tell your client to go easy on the invites . . . make it hard for one to automatically send invite to every single person that you're linked with.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677356">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677356">9</a> by Don Li
		posted on 4/9/2008 at 6:26 PM
		</div>
		<div class="comment_text"><p>A slightly different requirement about FB interface.  What if I want to extract a few msg from my FB inbox.  How do we go about that?</p><p>Thks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677374">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677374">10</a> by Raymond Camden
		posted on 4/9/2008 at 8:47 PM
		</div>
		<div class="comment_text"><p>Don, I'd check their docs to see if they support it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677375">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677375">11</a> by MrBuzzy
		posted on 4/10/2008 at 12:21 AM
		</div>
		<div class="comment_text"><p>The application I've posted above exercises all known Facebook API methods. There's nothing in there to get access to your FB inbox.<br>Cheers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677378">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677378">12</a> by Adrian Lynch
		posted on 4/25/2008 at 6:56 PM
		</div>
		<div class="comment_text"><p>This is a damn sight better explanation of the basics than Facebook's own documentation!</p><p>Thanks Ray.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677377">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677377">13</a> by Raymond Camden
		posted on 4/25/2008 at 7:02 PM
		</div>
		<div class="comment_text"><p>Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677381">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677381">14</a> by Mosey
		posted on 4/28/2008 at 6:42 PM
		</div>
		<div class="comment_text"><p>Am I the only one that loads this Facebook FBML Starter Kit, changes the stuff and gets no authorisation every single time?</p><p>It seems to be checking a form, but that form is always blank (cfdump) as well as the application.FBMLClient which shows me less info than I expected when I dump it.</p><p>I am guessing this is one of those "simple" things I need a line of code, or a correction or something and things will be lickity splitity. Anyone have advice on this? (CF8 btw)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677380">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677380">15</a> by Raymond Camden
		posted on 4/28/2008 at 6:49 PM
		</div>
		<div class="comment_text"><p>Can you be a bit more clear? No authorisation?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677379">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677379">16</a> by Mosey
		posted on 4/28/2008 at 7:02 PM
		</div>
		<div class="comment_text"><p>Invokes lines 10 to 14 on fb_post.cfm</p><p>       &lt;cfif not application.FBMLClient.AuthenticatePost(form, 'SIG_FB')&gt;<br>               &lt;h1&gt;Authorisation error&lt;/h1&gt;<br>               &lt;p&gt; You are not authorised to view this page.&lt;/p&gt;<br>               &lt;cfabort&gt;<br>       &lt;/cfif&gt;</p><p>So something in the form isn't there, I do a cfdump of #form#  and I<br>get a blank struct.</p><p>Feels like something isn't initialized, but I am pretty sure that is solid (callbacks and keys and whatnot).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677386">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677386">17</a> by Mosey
		posted on 4/28/2008 at 7:08 PM
		</div>
		<div class="comment_text"><p>HA! solved it.</p><p>I had been using another API: Cory Johnson's which require an iframe. So of course, no post.</p><p>I re-read the code and thought "this looks like FMBL native" so I changed the app over and YAY!.</p><p>So, note to self, this needs the FMBL setting and won't work on iframe.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677383">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677383">18</a> by Mark
		posted on 6/18/2008 at 8:53 AM
		</div>
		<div class="comment_text"><p>Have you got the photoTag feature working?</p><p>I want to use CF to add photoTag features for graduation photos.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677385">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677385">19</a> by MrBuzzy
		posted on 6/18/2008 at 2:27 PM
		</div>
		<div class="comment_text"><p>You can use the rest API to upload photos. I've done it succesfully in ColdFace <a href="http://disq.us/url?url=http%3A%2F%2Fcoldface.org%2F%3ACu-A7534ZuGDaw5evZYUok084Bw&amp;cuid=3321886" rel="nofollow noopener" title="http://coldface.org/">http://coldface.org/</a> I think you can tag or at least give the photo comments when you upload it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677382">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677382">20</a> by jorge
		posted on 6/19/2008 at 6:55 PM
		</div>
		<div class="comment_text"><p>Great explanation!.<br>Thanks a lot.<br>Kinds,<br>Jorge</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677384">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677384">21</a> by Jeff
		posted on 7/12/2008 at 4:44 AM
		</div>
		<div class="comment_text"><p>I keep getting this everytime.  Any ideas?</p><p>Errors while loading page from application</p><p>Received HTTP error code 405 while loading <a href="http://disq.us/url?url=http%3A%2F%2Fwww.thewarp.org%2Ffacebook%2Fcfm_template%3Ax-YycmbntZ02noGFgE09aux2OXI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.thewarp.org/facebook/cfm_template">http://www.thewarp.org/face...</a></p><p>There are still a few kinks Facebook and the makers of Actionscript are trying to iron out. We appreciate your patience as we try to fix these issues. Your problem has been logged - if it persists, please come back in a few days. Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677387">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677387">22</a> by Jeff
		posted on 7/12/2008 at 4:58 AM
		</div>
		<div class="comment_text"><p>Found the solution.</p><p>You have to specify index.cfm in the callback URL:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.thewarp.org%2Ffacebook%2Fcfm_template%2Findex.cfm%3Asegj3zB5BzdgKuZY7rb2xwD6ozM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.thewarp.org/facebook/cfm_template/index.cfm">http://www.thewarp.org/face...</a></p><p>I think that it assumes that it is a PHP page.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677388">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677388">23</a> by Alexander
		posted on 9/18/2008 at 11:20 PM
		</div>
		<div class="comment_text"><p>If it wasn't for this article, who knows...</p><p>I'm using the provided cf test app but whenever i click on "Go to application" nothing happens.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fapps.facebook.com%2Ftasosbotisfacts%2F%3AxuumwUtJry2ai1Bt2umJBz2R8O0&amp;cuid=3321886" rel="nofollow noopener" title="http://apps.facebook.com/tasosbotisfacts/">http://apps.facebook.com/ta...</a></p><p>Any idea? help?</p><p>Thanks,<br>Alexander</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677389">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677389">24</a> by Raymond Camden
		posted on 9/18/2008 at 11:24 PM
		</div>
		<div class="comment_text"><p>Heh, it's funny someone just read this. I'm actually working on a new version of this article. I don't know if i can talk about where/when, but I'm in the process of updating it.</p><p>So one thing I'd suggest is, do some heavy logging on the CF side to ensure you are seeing the HTTP requests come in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677394">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677394">25</a> by Alexander
		posted on 9/18/2008 at 11:35 PM
		</div>
		<div class="comment_text"><p>Great - without pressuring, hope we see something soon! Logging seems like the best trick, so to make this comment a bit useful this is how i plan to log:<br>&lt;cfdocument format="pDF" overwrite="yes" filename="thefile.pdf"&gt;<br>&lt;cfdump var="#form#"/&gt;<br>&lt;cfdump var="#cgi#"/&gt;<br>&lt;cfdump var="#url#"/&gt;<br>&lt;/cfdocument&gt;<br>and for errors:<br>&lt;cftry&gt;<br>&lt;cfcatch type="any"&gt;<br>&lt;cfdocument format="pDF" overwrite="yes" filename="errordebug.pdf"&gt;<br>&lt;cfdump var="#cfcatch#"/&gt;<br>&lt;/cfdocument&gt;<br>&lt;/cfcatch&gt;<br>&lt;/cftry&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677390">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677390">26</a> by Raymond Camden
		posted on 9/18/2008 at 11:40 PM
		</div>
		<div class="comment_text"><p>Oh god no - you don't want to use pdf for logging. I'd use cfdump's new file based logging ability.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677392">27</a> by Alexander
		posted on 9/18/2008 at 11:53 PM
		</div>
		<div class="comment_text"><p>Too late :), but indeed a better way.</p><p>&lt;cfif not StructKeyExists(form, "fb_sig_user") or not StructKeyExists(form, "fb_sig_session_key")&gt;</p><p>this seems to always validate as there is no fb_sig_user nor fb_sig_session_key, therefore always redirects here: <a href="http://disq.us/url?url=http%3A%2F%2Fapps.facebook.com%2Ftasosbotisfacts%2F%3AxuumwUtJry2ai1Bt2umJBz2R8O0&amp;cuid=3321886" rel="nofollow noopener" title="http://apps.facebook.com/tasosbotisfacts/">http://apps.facebook.com/ta...</a></p><p>In the form parameters i see FB_SIG_ADDED is 0. How can i get to the page where it shows you the facebook terms and the "Allow" button?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677395">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677395">28</a> by Raymond Camden
		posted on 9/19/2008 at 12:07 AM
		</div>
		<div class="comment_text"><p>Um, if I remember right, the first hit on your app will prompt the user. If you already have the app added to your account, remove it, and hit it again. I went to your URL and I see that msyelf.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677393">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677393">29</a> by Francesco
		posted on 8/1/2009 at 7:55 AM
		</div>
		<div class="comment_text"><p>What if I will use a cfform with related select?</p><p>I notice that never work...why?</p><p>this is the code:<br>&lt;cfform action="agriturismo.cfm" name="ricerca"&gt;<br>        	&lt;cfselect name="regione" value="22" /&gt;<br>            &lt;cfselect name="provincia" /&gt;<br>            &lt;label&gt;<br>            &lt;cfinput type="submit" name="Submit" style="width:50px; float:right; margin-right:8px" id="button2" value="Invia"&gt;<br>            &lt;/label&gt;<br>  &lt;/cfform&gt;</p><p>Why I get error? it depends on the binding of component?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677396">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677396">30</a> by Francesco
		posted on 8/1/2009 at 7:56 AM
		</div>
		<div class="comment_text"><p>sorry, the exact code is:</p><p>&lt;cfform action="../ricerca-geografica-agriturismo.cfm" name="ricerca"&gt;<br>        	&lt;cfselect name="regione" bind="cfc:select.getRegioni()" bindonload="true" /&gt;<br>            &lt;cfselect name="provincia" bind="cfc:select.getProvince({regione})" /&gt;<br>            &lt;label&gt;<br>            &lt;cfinput type="submit" name="Submit" style="width:50px; float:right; margin-right:8px" id="button2" value="Invia"&gt;<br>            &lt;/label&gt;<br>  &lt;/cfform&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677397">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677397">31</a> by Raymond Camden
		posted on 8/2/2009 at 12:09 AM
		</div>
		<div class="comment_text"><p>CFFORM spits out a lot of JavaScript that runs via your server, and would not work as a FB application.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677398">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677398">32</a> by Francesco
		posted on 8/2/2009 at 8:56 PM
		</div>
		<div class="comment_text"><p>what you suggest?</p><p>better not use javascript on facebok applcation?</p><p>also if i try with a normal ajax script I will get error?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677399">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677399">33</a> by Raymond Camden
		posted on 8/2/2009 at 9:40 PM
		</div>
		<div class="comment_text"><p>I'd suggest reading the Facebook docs, as it details what types of JavaScript features are allowed and which are not. Ajax in general is going to be a bit tricky. I mean, do not forget that when you write a FB app, it is NOT being served from your server per se, but via FB as a proxy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677400">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677400">34</a> by Chris Bowyer
		posted on 3/30/2013 at 9:54 PM
		</div>
		<div class="comment_text"><p>There is currently an issue with the text not wrapping etc. on this page.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677401">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677401">35</a> by Raymond Camden
		posted on 3/30/2013 at 11:41 PM
		</div>
		<div class="comment_text"><p>Thanks, I was missing a closing &lt;/code&gt; block.</p></div>
	</div>
</div>
		