
<div class="comment" id="c_1713666494">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666494">1</a> by Richard Chappell
		posted on 6/7/2007 at 2:25 AM
		</div>
		<div class="comment_text"><p>Cool new domain name, Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666481">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666481">2</a> by John Ramon
		posted on 6/7/2007 at 2:32 AM
		</div>
		<div class="comment_text"><p>Now that your rocking 8 I expect more examples =)</p><p>J/K - nice name.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666502">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666502">3</a> by Raymond Camden
		posted on 6/7/2007 at 2:36 AM
		</div>
		<div class="comment_text"><p>I've got my RSS Search UDF done. Will be posting it tonight.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666506">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666506">4</a> by Chad
		posted on 6/7/2007 at 2:38 AM
		</div>
		<div class="comment_text"><p>Ray, the email notification was from your <a href="http://disq.us/url?url=http%3A%2F%2Fcamdenfamily.com%3AwTisx5fv2XwC3bFwuiKCun0fT3w&amp;cuid=3321886" rel="nofollow noopener" title="camdenfamily.com">camdenfamily.com</a> email address.  Not sure if that was on purpose, just thought i would let you know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666496">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666496">5</a> by Robert Owen
		posted on 6/7/2007 at 2:40 AM
		</div>
		<div class="comment_text"><p>Wow.. Is this on a different server as well? Seems faster.. Maybe its just the cool new name! ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666497">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666497">6</a> by Raymond Camden
		posted on 6/7/2007 at 3:14 AM
		</div>
		<div class="comment_text"><p>@Chad - I'm not going to change my email address. I will add an alias eventually (ray@coldfusionjedi.com).</p><p>@Robert - The old server was - well - old. And CF7. So you have  big updates. I may be moving to a whole new machine as well, for a bit more speed as well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666503">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666503">7</a> by Kyle Hayes
		posted on 6/7/2007 at 4:45 AM
		</div>
		<div class="comment_text"><p>Hey Ray, the little icons below the post are not showing up, such as:<br>"<a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Fimages%2Fcomment.gif%3AVc-vUEscA17fX6BMLH59ecHT024&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/images/comment.gif">http://www.coldfusionjedi.c...</a>"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666498">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666498">8</a> by Christopher Wigginton
		posted on 6/7/2007 at 5:08 AM
		</div>
		<div class="comment_text"><p>Lucas, don't you mean Adobe?  I hope you get to keep it.</p><p>Adobe's lawyers climbed all over deconcept regarding the FlashObject project, forcing Geoff into renaming it to SWFObject, Trademark dilution and all that...</p><p>Check out Item of 1 of the following URL.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.adobe.com%2Fmisc%2Ftrade.html%3A2Cl473BpVzaR1zzEeP-i1izvwqc&amp;cuid=3321886" rel="nofollow noopener" title="http://www.adobe.com/misc/trade.html">http://www.adobe.com/misc/t...</a></p><p><a href="http://disq.us/url?url=http%3A%2F%2Fblog.deconcept.com%2F2006%2F04%2F21%2Fflashobject-to-become-swfobject%2F%3AqaVI7PJBZHCg0xB5q-sSroyEKkQ&amp;cuid=3321886" rel="nofollow noopener" title="http://blog.deconcept.com/2006/04/21/flashobject-to-become-swfobject/">http://blog.deconcept.com/2...</a></p><p>Sorry for the Buzz Kill</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666500">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666500">9</a> by Raymond Camden
		posted on 6/7/2007 at 5:12 AM
		</div>
		<div class="comment_text"><p>I'm not too terribly worried about it. I'd raise quite a stink if there was a complaint.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666504">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666504">10</a> by Raymond Camden
		posted on 6/7/2007 at 5:23 AM
		</div>
		<div class="comment_text"><p>Kyle, thanks, fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666507">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666507">11</a> by CF Oh no he didn&amp;apost
		posted on 6/7/2007 at 5:25 AM
		</div>
		<div class="comment_text"><p>I wouldn't worry about the buzz kill.  Apparently its business as usual with Coldfusion marketing.  If we didn't stick cf in front of everything there wouldn't be any marketing at all.  Unless you count the preaching to the choir method.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666501">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666501">12</a> by Martin
		posted on 6/7/2007 at 1:20 PM
		</div>
		<div class="comment_text"><p>SO....ASK A JEDI....</p><p>How is it you are able to run a production environment on a technology that hasn't been ("officially") released yet? Can I do it too?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666505">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666505">13</a> by Raymond Camden
		posted on 6/7/2007 at 3:15 PM
		</div>
		<div class="comment_text"><p>Martin, I asked before I went live. I believe you would need to do the same.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666492">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666492">14</a> by Steve Walker
		posted on 6/7/2007 at 5:28 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>I know others have mentioned it, but I will ask it directly.  Is CF8 really this much more efficient?  Your site is loading at least 10x faster.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666491">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666491">15</a> by Raymond Camden
		posted on 6/7/2007 at 5:34 PM
		</div>
		<div class="comment_text"><p>Yes. And remember my site has a bunch of crap on it (sorry guys, got to pay the bills). I don't want to say the number I know - because I don't know if it is "official" or not, but CF8 is incredibly faster than CF7.</p><p>Let me share a story - and if you are an old reader - you know I like to repeat my stories so forgive me if you heard this one before.</p><p>The first time I ran RIAForge locally under CF8, I thought it was broken. Why? Because it loaded so fast.</p><p>I thought - surely I must be seeing the error template. There is NO way the site ran that fast.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666493">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666493">16</a> by Robert Owen
		posted on 6/7/2007 at 5:38 PM
		</div>
		<div class="comment_text"><p>Interesting thing here Ray.. I get comment emails from this post but only from you... Its kinda weird only getting your part of the comments.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666509">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666509">17</a> by Raymond Camden
		posted on 6/7/2007 at 5:55 PM
		</div>
		<div class="comment_text"><p>Poopies. Must be a mail server validation thing as it tries to send mail from an "outside" address. Ok, I'm going to set the commentsfrom property to me for now. (Thank god BlogCFC supports that.) I'll post a test from an outside email addy in a sec, please tell me if you get it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666511">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666511">18</a> by Raymond Camden
		posted on 6/7/2007 at 5:56 PM
		</div>
		<div class="comment_text"><p>This comment from rcamden@gmail.com. Your email should say from ray@camdenfamily.com though.</p><p>Let me know if it comes through.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666510">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666510">19</a> by John Ramon
		posted on 6/7/2007 at 6:16 PM
		</div>
		<div class="comment_text"><p>Came though fine Ray.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666515">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666515">20</a> by Raymond Camden
		posted on 6/7/2007 at 6:19 PM
		</div>
		<div class="comment_text"><p>Nice. So now I need to move <a href="http://disq.us/url?url=http%3A%2F%2Fray.camdenfamily.com%3Anr8Wfzs5RNhu5OZT_80z8UhvscU&amp;cuid=3321886" rel="nofollow noopener" title="ray.camdenfamily.com">ray.camdenfamily.com</a>, <a href="http://disq.us/url?url=http%3A%2F%2Fwww.camdenfamily.com%3APzxtKga0XjP3AjcvKoLDIW2duCI&amp;cuid=3321886" rel="nofollow noopener" title="www.camdenfamily.com">www.camdenfamily.com</a>, and lastly the mail over. As I'm moving to a new new box soon though I may wait.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666512">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666512">21</a> by Sammy Larbi
		posted on 6/7/2007 at 6:28 PM
		</div>
		<div class="comment_text"><p>Congrats on the new setup.  I thought it was funny that "my site has a bunch of crap" had one of those pop-up content link ads linked in it (though would have been better if the whole phrase was linked) =).</p><p>In any case, go with the story that it's not "Jedi" but ColdFusionJEdi with Edi short for edition.  Didn't work for the "GoOgle" lady, but who knows - you may get a nicer judge?!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666516">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666516">22</a> by Frank Hipolito
		posted on 6/7/2007 at 9:01 PM
		</div>
		<div class="comment_text"><p>If not you can always get <a href="http://disq.us/url?url=http%3A%2F%2FColdFusionSith.com%3A9a8ltUiXoiHFEzF12mrJTdf7ka4&amp;cuid=3321886" rel="nofollow noopener" title="ColdFusionSith.com">ColdFusionSith.com</a></p><p>Lot's of cool stuff you can do using the dark side of ColdFusion!</p><p>I'm not sure if you've ever seen this, but it's funny as hell. Star Wars ! What really happened after the Deathstar blew up.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DrfP90uJ12eQ%3AYMESlccVf6NdHPsxyGkvO-mPjs4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.youtube.com/watch?v=rfP90uJ12eQ">http://www.youtube.com/watc...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666514">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666514">23</a> by Frank Hipolito
		posted on 6/7/2007 at 9:22 PM
		</div>
		<div class="comment_text"><p>Hey won't the name change effect your search engine stuff?<br>Right off the bat the one thing I see is Technorati.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Ftechnorati.com%2Fblogs%2Fray.camdenfamily.com%3Freactions%3AoKm91k1oNbwBW84HprWx14OKzpY&amp;cuid=3321886" rel="nofollow noopener" title="http://technorati.com/blogs/ray.camdenfamily.com?reactions">http://technorati.com/blogs...</a><br>Authority: 278<br>Rank: 13,921</p><p><a href="http://disq.us/url?url=http%3A%2F%2Ftechnorati.com%2Fblogs%2Fwww.coldfusionjedi.com%3Freactions%3A88lnEbTUx_C9bMhLpay__R9VVKA&amp;cuid=3321886" rel="nofollow noopener" title="http://technorati.com/blogs/www.coldfusionjedi.com?reactions">http://technorati.com/blogs...</a><br>Authority: 1 <br>Rank: 2,152,785</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666513">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666513">24</a> by Raymond Camden
		posted on 6/7/2007 at 9:59 PM
		</div>
		<div class="comment_text"><p>Frank, yes, but frankly, I really needed a better URL. If my earnings take a dip, well, I'll survive. And folks will still be able to find me as my old address will continue to work forever.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666517">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666517">25</a> by Raymond Camden
		posted on 6/7/2007 at 10:08 PM
		</div>
		<div class="comment_text"><p>I've seen that video like 200 times. And it never stops being funny. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666519">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666519">26</a> by Dale Fraser
		posted on 6/8/2007 at 3:40 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Not sure if this is related to new site or not. But</p><p>NEW: Geek the Tube</p><p>link doesn't work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666518">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666518">27</a> by Robert Owen
		posted on 6/8/2007 at 4:19 AM
		</div>
		<div class="comment_text"><p>The url it is giving is this: http://www.coldfusionjedi/forums</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666520">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666520">28</a> by Raymond Camden
		posted on 6/8/2007 at 5:05 AM
		</div>
		<div class="comment_text"><p>Fixed. Thanks guys. Silly typo on my part. But - um - I blame Bush. And Clinton. And global warming.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666522">29</a> by vignesh
		posted on 1/3/2008 at 8:53 AM
		</div>
		<div class="comment_text"><p>Is it possible to develop  image processing algorithms in coldfusion ?..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666524">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666524">30</a> by Raymond Camden
		posted on 1/3/2008 at 7:23 PM
		</div>
		<div class="comment_text"><p>Yes, CF8 has image processing.</p></div>
	</div>
</div>
		