
<div class="comment" id="c_1713659621">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659621">1</a> by Scott P
		posted on 11/26/2006 at 11:46 PM
		</div>
		<div class="comment_text"><p>very cool kind sir.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659640">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659640">2</a> by Jacob Munson
		posted on 11/27/2006 at 6:03 AM
		</div>
		<div class="comment_text"><p>I signed up for a Gravatar a couple of months ago, and have yet to get a reply email.  I wish some other company would replace them as the popular one, because I think the idea is great, but their service is terrible.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659636">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659636">3</a> by Dave Anderson
		posted on 11/27/2006 at 6:58 AM
		</div>
		<div class="comment_text"><p>Ray Camden, you are the hardest working man in Cold Fusion development. But I get why you would code while you were sick. It takes your mind off feeling miserable. Get well soon.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659639">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659639">4</a> by Mingo Hagen
		posted on 11/27/2006 at 6:15 PM
		</div>
		<div class="comment_text"><p>Hey Ray, You know you are the man, right?!<br>I do have a quick bug/typo fix for ya:</p><p>&lt;cfcontent type="images/png"</p><p>should be:</p><p>&lt;cfcontent type="image/png"</p><p>Also, I was sick as well this weekend and I've opted for the couch-tv-soup recovery strategy... I must say I like yours better, I'll do that next time.</p><p>Mingo.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659635">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659635">5</a> by Raymond Camden
		posted on 11/27/2006 at 7:21 PM
		</div>
		<div class="comment_text"><p>Dang it. That will take forever to fix! ;)</p><p>Fixed. I don't have SVN turned on or a readme, but the fix is in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659638">6</a> by Lance
		posted on 11/27/2006 at 7:31 PM
		</div>
		<div class="comment_text"><p>Must have been something in the water...I was sick this weekend, too (still am, actually).</p><p>Thanks, Ray.  I agree Gravatar is great, but slow!!!  Hopefully this will help.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659637">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659637">7</a> by Lance
		posted on 11/29/2006 at 9:28 PM
		</div>
		<div class="comment_text"><p>Ray--will you be implementing this into the next release of BlogCFC?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659641">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659641">8</a> by Raymond Camden
		posted on 11/29/2006 at 9:30 PM
		</div>
		<div class="comment_text"><p>I'm not sure. Right now I'm building it as a separate service. Sure - I could roll it in - but I'd also want an easy way for folks to NOT use it if they want to make the service box wide and use it for other things like Galleon.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659643">9</a> by Loren Strand
		posted on 2/15/2012 at 2:32 AM
		</div>
		<div class="comment_text"><p>Ray, any changes in your thoughts on using Gravatar now that we are a few years past the original blog post?  Has speed improved?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659645">10</a> by Raymond Camden
		posted on 2/15/2012 at 2:37 AM
		</div>
		<div class="comment_text"><p>I use Gravatar here. Seem slow to you? Not doing any caching at all. (Well, of Gravatar - I use other caching elsewhere...)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659646">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659646">11</a> by Loren Strand
		posted on 2/15/2012 at 5:38 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Load times look good to me.  I peeked at <a href="http://disq.us/url?url=http%3A%2F%2Ftools.pingdom.com%3AiqyULV-bjeqKH_FtI7W_Bbzbp4Q&amp;cuid=3321886" rel="nofollow noopener" title="tools.pingdom.com">tools.pingdom.com</a> for this page.  52 requests, 376.6Kb and loaded in Firefox 10 in 749ms.  Gravatar calls were around 30 ms, one with 143ms wait time.</p><p>Have you thought about implementing the Gravatar hovercard feature?  I saw some code in jQuery at their site for Wordpress implementations.  Perhaps you could craft a nice CF version?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659619">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659619">12</a> by Raymond Camden
		posted on 2/15/2012 at 5:45 PM
		</div>
		<div class="comment_text"><p>Cool, I didn't even know that was an option. Although they don't share the code for the hovercard, not that I see.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659620">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659620">13</a> by Loren Strand
		posted on 2/15/2012 at 7:28 PM
		</div>
		<div class="comment_text"><p>Check out this page <a href="http://disq.us/url?url=http%3A%2F%2Fen.gravatar.com%2Fsite%2Fimplement%2Fprofiles%2F%3AupROVNeSULrJxNkHXbGMwu25Ik0&amp;cuid=3321886" rel="nofollow noopener" title="http://en.gravatar.com/site/implement/profiles/">http://en.gravatar.com/site...</a> for hovercard implementation.  Sparse.  Scroll to header "Data Formats." I see PHP and JSON there.  I haven't dabbled in those.  Maybe you can create a component based on code there for the ColdFusion community.</p><p>Perhaps submitting such code to support@gravatar.com and they could add it to the page for implementation of hovercards for CF?</p></div>
	</div>
</div>
		