
<div class="comment" id="c_1713652919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652919">1</a> by Mark Drew
		posted on 5/15/2006 at 9:38 PM
		</div>
		<div class="comment_text"><p>Maybe by jumping right in and doing all these changes its good, do it all at once, then dont change for another few years?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652930">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652930">2</a> by Phillip Senn
		posted on 5/15/2006 at 9:52 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>I know nothing of the new culture you're going into.<br>But in my culture, what I've found is that a new hire will try to impress everyone with their ability, while the other employees are looking at their stability.<br>Can we work with this guy or is he going to change something without anyone knowing anything about it?</p><p>I'm sure they're already impressed with your ability.  For the first x number of days, make sure you show them that you're someone they can work with.</p><p>Technology will change.  The people that you will work with will (by and large) stay the same.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652932">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652932">3</a> by Gary Funk
		posted on 5/15/2006 at 10:00 PM
		</div>
		<div class="comment_text"><p>Interesting Ray,</p><p>"I also told my wife to "have her way" with my office."</p><p>I was with you until the 'my office.' Congratulations on the new notebook. Sounds like you will be having some fun.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652927">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652927">4</a> by Jim
		posted on 5/15/2006 at 10:13 PM
		</div>
		<div class="comment_text"><p>Have they delivered your Swingline stapler yet?</p><p>Jim</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652928">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652928">5</a> by Raymond Camden
		posted on 5/15/2006 at 10:17 PM
		</div>
		<div class="comment_text"><p>You know, its funny. I was thinking a few weeks ago that I needed a stapler. (Seriously.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652929">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652929">6</a> by Kyle Hayes
		posted on 5/15/2006 at 11:11 PM
		</div>
		<div class="comment_text"><p>Congratulations on your new MacBook Pro!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652925">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652925">7</a> by charlie griefer
		posted on 5/15/2006 at 11:39 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.thinkgeek.com%2Fhomeoffice%2Fgear%2F61b7%2F%3AZFAtotw7yT1CeO9QzoFiR2ebFkg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.thinkgeek.com/homeoffice/gear/61b7/">http://www.thinkgeek.com/ho...</a></p><p>:)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652926">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652926">8</a> by Scott Stroz
		posted on 5/15/2006 at 11:40 PM
		</div>
		<div class="comment_text"><p>Could?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652933">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652933">9</a> by Raymond Camden
		posted on 5/15/2006 at 11:42 PM
		</div>
		<div class="comment_text"><p>You know what I really need? And should do a separate blog post on. A better way to handle the 10 million cables I have. And this is with just ONE dang pc in my office.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652935">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652935">10</a> by Scott Stroz
		posted on 5/15/2006 at 11:48 PM
		</div>
		<div class="comment_text"><p>Ball bearings...its all ball bearings these days.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652936">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652936">11</a> by Alan
		posted on 5/15/2006 at 11:56 PM
		</div>
		<div class="comment_text"><p>Ray, I sent this link to the only-est Mac user in my office.<br>You may have already seen it, the TechRepublic story about how "Apple flaws put both Macs and PCs at risk"</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fct.techrepublic.com.com%2Fclicks%3Ft%3D2319670-4067be28cf929d04b5633056cb8f842c-bf%26s%3D5%26fs%3D0%3AUCiJtuQDpOO-J-d54w5JJumrUDg&amp;cuid=3321886" rel="nofollow noopener" title="http://ct.techrepublic.com.com/clicks?t=2319670-4067be28cf929d04b5633056cb8f842c-bf&amp;s=5&amp;fs=0">http://ct.techrepublic.com....</a></p><p>Al</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652934">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652934">12</a> by Tom Spillar
		posted on 5/16/2006 at 2:14 AM
		</div>
		<div class="comment_text"><p>Good Luck! Change is great.</p><p>Now that you are there maybe you can influence them to change their website.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652942">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652942">13</a> by tof
		posted on 5/16/2006 at 3:47 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Please don't forget the new cover-sheet on your TPS reports</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652938">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652938">14</a> by PaulC
		posted on 5/16/2006 at 4:33 AM
		</div>
		<div class="comment_text"><p>Hmm...I notice they do a bit of e-Learning related stuff there. I've been dreaming of a ColdFusion based LMS for years...chop chop!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652939">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652939">15</a> by Nick Tong
		posted on 5/16/2006 at 4:51 PM
		</div>
		<div class="comment_text"><p>change is always good.  Just noticed the new macbook: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.apple.com%2Fmacbook%2Fmacbook.html%3AVykiV7AygjaO5QZwsJoFudhO9GQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.apple.com/macbook/macbook.html">http://www.apple.com/macboo...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652937">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652937">16</a> by tony weeg
		posted on 5/16/2006 at 8:37 PM
		</div>
		<div class="comment_text"><p>you may have mentioned this, but is this still at the home office? or are you now in a cubicle?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652940">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652940">17</a> by Raymond Camden
		posted on 5/16/2006 at 9:05 PM
		</div>
		<div class="comment_text"><p>Still in the home office, which is actually being redone now so I'm actually kicked out of it for a good 2 weeks. (But the end result will make it worth the while.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652941">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652941">18</a> by Ali
		posted on 5/16/2006 at 9:21 PM
		</div>
		<div class="comment_text"><p>Congrats!<br>I think I'm the exact opposite, in that my life is a series of changes.  Although, I myself may not invite it, it seems that a lot of times when I don't initiate it, the events around me are causing a constant change.</p><p>I'm not a gambler though, and don't take huge risks, I'm a simple guy.  Just seems like my life's constantly changing.</p><p>So here's to change, and to your new adventures.<br>I raise my glass of root beer...cheers!<br>Ali</p></div>
	</div>
</div>
		