
<div class="comment" id="c_1713657763">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657763">1</a> by John Ramon
		posted on 9/26/2006 at 7:12 AM
		</div>
		<div class="comment_text"><p>Great example of a real world use, all I can say is I hope mine is some day ranked 14th. hehe Thanks Ray</p><p>PS thanks for the insight on the calendar problem I got it working.</p></div>
	</div>
</div>
		