
<div class="comment" id="c_1713618569">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618569">1</a> by mani
		posted on 5/24/2005 at 2:40 AM
		</div>
		<div class="comment_text"><p>For some reason this type of behavior can really get under your skin. I had a minor disagreement with another poster on one of the largest social Flash mailing lists, and out of the blue he sent me a violently threatening obscene offlist mail.<br>Instead of the support of the other members, i found that the weirdest kind of schoolyard bullying began - and straight away i realized that there was no point trying to fight it.<br>Best to just let this kind of thing go - people often enjoy the freedom of a different kind of power in the semi-anonimous world of the web. For myself, the worst part was a sudden ENORMOUS increase in spam that i received from this guy's part of the world. Otherwise, leaving that list was the best decision i made in a while.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618571">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618571">2</a> by Raymond Camden
		posted on 5/24/2005 at 2:47 AM
		</div>
		<div class="comment_text"><p>What I don't get is why this person would flame me twice in two years. It's like a real low key flamer. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618568">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618568">3</a> by Jennifer Larkin
		posted on 5/24/2005 at 2:55 AM
		</div>
		<div class="comment_text"><p>Well, if you did have an alternate personality, you would pick a fun name for him like Angus McLaren. It's Raymond's kilt-wearing personality. I can see him now. He's quite cranky.</p><p>If you start out with ad hominem attacks, you just have issues. Everybody's software has bugs.</p><p>I would think that some people whose bad code I've posted would flame me but nooooooooo.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618573">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618573">4</a> by Jeremy Fuksa
		posted on 5/24/2005 at 3:07 AM
		</div>
		<div class="comment_text"><p>I had someone flame one of my blog posts the other day...  presumably because it was off-topic from Macromedia technologies.</p><p>For one thing, from the very beginning, I made it clear on MXNA that my posts were going to be more design related and less development related.  And, plenty of people post off-topic material to their blogs.  Do they also get chastised by the MXNA readership?</p><p>Ultimately, my response to the flame is that if you don't want to read off-topic posts on MXNA, don't click my links.</p><p>Some people...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618572">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618572">5</a> by scott janousek
		posted on 5/24/2005 at 3:41 AM
		</div>
		<div class="comment_text"><p>secret window was one demented movie ...</p><p>I was disappointed I figured it out in the first 20-30 minutes of the movie though ...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618574">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618574">6</a> by booty man
		posted on 5/24/2005 at 3:47 AM
		</div>
		<div class="comment_text"><p>I'd be cranky too if i had to wear that dang dress.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618575">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618575">7</a> by Jennifer Larkin
		posted on 5/24/2005 at 3:51 AM
		</div>
		<div class="comment_text"><p>I had that problem with Secret Window too. Very shortly into the movie I turned to my date and said "I think I've seen this movie before." But he didn't figure it out until later. I think foreshadowing is a bit too subtle for him.</p><p>He still gets creeped out by the thought of corn. :D</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618577">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618577">8</a> by Douglas Knudsen
		posted on 5/24/2005 at 4:50 AM
		</div>
		<div class="comment_text"><p>regardless of kilt wearing flame throwing moody alternate personalaities, your blog looks, feels, and smells, an infinite percentage better.  woohoo!</p><p>DK</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618579">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618579">9</a> by Doug Hughes
		posted on 5/24/2005 at 6:36 AM
		</div>
		<div class="comment_text"><p>What's weird about this isn't the flame on the content or anything, but their fixation on your driving abilities.  What gives?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618580">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618580">10</a> by Critter
		posted on 5/24/2005 at 8:54 AM
		</div>
		<div class="comment_text"><p>first i would just go after his family.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618578">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618578">11</a> by barry.b
		posted on 5/24/2005 at 9:04 AM
		</div>
		<div class="comment_text"><p>just a thought:</p><p>are you able to do a search for all of this persons comments - both good and bad?</p><p>it might be the ratio isn't 0 to 2  - it might be 100:2 and we just remember the bad...</p><p>I freely admit that sometimes I forget the impersonality of text base communication and may come across heavy handed unintentionally (not in this case admittedly - I read the reply and drew a similar conclusion). I've even applolgised to people *in case* what I wrote could be misconstrued as rude of offencive.</p><p>just a thought.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618583">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618583">12</a> by felix
		posted on 5/24/2005 at 5:56 PM
		</div>
		<div class="comment_text"><p>Thanks! I wont need to see 'Secret Window' now (not like I was planning to anyway).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618582">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618582">13</a> by Raymond Camden
		posted on 5/24/2005 at 6:18 PM
		</div>
		<div class="comment_text"><p>I searched - but he only posted twice. That's why I find it so odd. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618585">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618585">14</a> by Rick
		posted on 5/24/2005 at 8:59 PM
		</div>
		<div class="comment_text"><p>I bet it's a friend of Ray's just being obnoxious. =)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618588">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618588">15</a> by Mike Rankin
		posted on 5/24/2005 at 9:46 PM
		</div>
		<div class="comment_text"><p>Man, if that's the worst flame you've gotten, you're not trying hard enough.</p><p>Try posting some right-wing propaganda with some poor grammer on /. and prepare to be nuked.  Sometimes the whole thread will completely leave the original topic.  It's like watching a train wreck.  It's horrible, but you keep looking anyway.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618587">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618587">16</a> by Raymond Camden
		posted on 5/24/2005 at 9:49 PM
		</div>
		<div class="comment_text"><p>I should post my feelings on copyright then. I know I'm in the minority there. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618584">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618584">17</a> by PaulC
		posted on 5/25/2005 at 2:15 AM
		</div>
		<div class="comment_text"><p>It's obvious flaming isn't a problem, but maybe it's worth adding a ban comments by IP feature to BlogCFC. Most forum apps have something like that.</p><p>I'd do it myself, but I'll flame myself and let you know I suck.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618586">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618586">18</a> by barry.b
		posted on 5/25/2005 at 4:29 AM
		</div>
		<div class="comment_text"><p>Bah, a pox on all their houses!</p><p>Don't be dispondant, Ray. We all appreciate your thoughts, work and community spirit even if this one malcontent doesn't...</p><p>...but can't please all of the people all of the time...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618589">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618589">19</a> by mike
		posted on 5/25/2005 at 1:48 PM
		</div>
		<div class="comment_text"><p>The fact that he refers to your driving (in the older post) is either just a childish insult or suggests that he knows you in person - ever dented somebodys shiny new motor?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618591">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618591">20</a> by malcolm
		posted on 5/25/2005 at 3:46 PM
		</div>
		<div class="comment_text"><p>I once had someone flame me....  and then I found out later it was my wife messing with my head :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618592">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618592">21</a> by Ken
		posted on 5/26/2005 at 1:51 AM
		</div>
		<div class="comment_text"><p>If he doesn't like your blog, why does he come back, people can be really stupid sometimes.</p><p>Anyway, my job has forced me to move to .NET with our development, so I have not been as tied into the CF community as I was for a long time, but I still read your blog b/c it has such valuable info.  The dude just needs to get a life, keep up the great work.</p></div>
	</div>
</div>
		