
<div class="comment" id="c_1713651300">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651300">1</a> by jimjay
		posted on 4/3/2006 at 5:42 PM
		</div>
		<div class="comment_text"><p>If anyone is looking for an example, here's the LiveDocs link:<br><a href="http://disq.us/url?url=http%3A%2F%2Flivedocs.macromedia.com%2Fcoldfusion%2F7%2Fhtmldocs%2F00001059.htm%3APNKb5YMHjjgPVsLB4k6haH46IlQ&amp;cuid=3321886" rel="nofollow noopener" title="http://livedocs.macromedia.com/coldfusion/7/htmldocs/00001059.htm">http://livedocs.macromedia....</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651303">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651303">2</a> by Joe Rinehart
		posted on 4/3/2006 at 6:14 PM
		</div>
		<div class="comment_text"><p>"Rabid", "King Camden"?  You crack me up.</p><p>Thanks for posting this, we've got a few new hires coming on in the next few weeks who'll be getting a copy...</p><p>I like the new style on comments, btw.</p><p>-Joe</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651305">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651305">3</a> by Phillip Senn
		posted on 4/3/2006 at 6:28 PM
		</div>
		<div class="comment_text"><p>Joshua</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651306">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651306">4</a> by James Buckingham
		posted on 10/22/2007 at 5:28 PM
		</div>
		<div class="comment_text"><p>Hi Raymond,</p><p>Was just linked to this pdf from another blog but I'm getting a page not found. Do you know where I can find it?</p><p>Cheers,<br>James</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651304">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651304">5</a> by Raymond Camden
		posted on 10/22/2007 at 5:29 PM
		</div>
		<div class="comment_text"><p>Check out the pod in the upper right hand corner of this blog. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713651301">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713651301">6</a> by James Buckingham
		posted on 10/22/2007 at 5:30 PM
		</div>
		<div class="comment_text"><p>Not 2 seconds after I post that comment I find it in the CFC Resources :-)</p><p>Cheers,<br>James</p></div>
	</div>
</div>
		