
<div class="comment" id="c_1713616229">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616229">1</a> by Sean Corfield
		posted on 9/27/2004 at 12:42 AM
		</div>
		<div class="comment_text"><p>Tony Weeg is about the only person I can think of from NavTrak...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616230">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616230">2</a> by Leif Wells
		posted on 9/27/2004 at 2:26 AM
		</div>
		<div class="comment_text"><p>I'm just glad it isn't me. ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616228">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616228">3</a> by tony weeg
		posted on 9/28/2004 at 3:43 PM
		</div>
		<div class="comment_text"><p>hi ray.</p><p>someone does run your blog on one of our servers here, we lost a raid drive on that server, and something got mucked up...either way, we are backup, im not sure if this is fixed, but if you could confirm, let me know...thanks!</p><p>anyhew, i was away @ a golf tournament and didnt realize this was an issue.</p><p>sorry dude.</p><p>tw</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616231">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616231">4</a> by Raymond Camden
		posted on 9/28/2004 at 4:00 PM
		</div>
		<div class="comment_text"><p>Thanks Tony for taking a look at this.</p></div>
	</div>
</div>
		