
<div class="comment" id="c_1713684299">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684299">1</a> by Gary Funk
		posted on 7/11/2008 at 9:56 PM
		</div>
		<div class="comment_text"><p>All I can say is, "I love my HTC Tilt."</p><p>Congratulations on the hits Ray. It's good to see the rest of the world find you.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684310">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684310">2</a> by Raymond Camden
		posted on 7/11/2008 at 9:57 PM
		</div>
		<div class="comment_text"><p>HTC?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684308">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684308">3</a> by Gary Funk
		posted on 7/11/2008 at 10:02 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fhtc.com%3A0cv5wPC2t6W0YuNCW3JF_PdLnJw&amp;cuid=3321886" rel="nofollow noopener" title="htc.com">htc.com</a></p><p>The make some of the BEST phones in the world.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684307">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684307">4</a> by Sid Wing
		posted on 7/11/2008 at 10:12 PM
		</div>
		<div class="comment_text"><p>Computerworld article isn't hurting your hits ratio either there, Ray.  Gotta love "major updates" and how they can KILL the update server and it's bandwidth.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684311">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684311">5</a> by Mat Evans
		posted on 7/12/2008 at 12:20 AM
		</div>
		<div class="comment_text"><p>hehe, who need slashdot when you have apple?!</p><p>i still love them tho, couldn't live with out my macbook.</p><p>comment count is crazy on that thread!<br>you can actually see it goin up!</p></div>
	</div>
</div>
		