
<div class="comment" id="c_1713649709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649709">1</a> by jim collins
		posted on 1/28/2006 at 10:42 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Felementk.com%2Fcatalog.asp%3Fdisplay%3DDetails%26b%3Delementk%26r%3DProgramming%2Band%2BWeb%2BDevelopment%3ALGzDLLxSwPsx0s0YA1pnWtyZ19A&amp;cuid=3321886" rel="nofollow noopener" title="http://elementk.com/catalog.asp?display=Details&amp;b=elementk&amp;r=Programming+and+Web+Development">http://elementk.com/catalog...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649717">2</a> by Scott Slone
		posted on 1/28/2006 at 10:57 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2FLynda.com%3ATPz3dgmgOqHT_7X_Z6RS4XU4CiE&amp;cuid=3321886" rel="nofollow noopener" title="Lynda.com">Lynda.com</a> used to have a fairly robust library of training. Some web, some cd-based.<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.lynda.com%3ABiCYT10cKC4PzyWnvFopu2BhKwY&amp;cuid=3321886" rel="nofollow noopener" title="http://www.lynda.com">http://www.lynda.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649719">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649719">3</a> by Scott Slone
		posted on 1/28/2006 at 11:03 PM
		</div>
		<div class="comment_text"><p>Also, a quick google of "coldfusion online training" generated a fair amount of results.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649720">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649720">4</a> by Raymond Camden
		posted on 1/28/2006 at 11:08 PM
		</div>
		<div class="comment_text"><p>Heh, it was too early in the morning for me to think of Googling for it. ;) What I'd love to hear, though, is people who can speak from experience.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649724">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649724">5</a> by Phillip Senn
		posted on 1/29/2006 at 2:48 AM
		</div>
		<div class="comment_text"><p>I've taken the <a href="http://disq.us/url?url=http%3A%2F%2FLynda.com%3ATPz3dgmgOqHT_7X_Z6RS4XU4CiE&amp;cuid=3321886" rel="nofollow noopener" title="Lynda.com">Lynda.com</a> ColdFusion course taught by Joey Lott.  He is also a CommunityMX contributor.<br>I HIGHLY recommend it.  Although it's getting a bit dated, in terms of fundamentals, I could easily see it being a requirement for "core competencies".  One of his examples is creating a shopping cart application.<br>You can go to <a href="http://disq.us/url?url=http%3A%2F%2Fwww.lynda.com%2Ffreepass%2Fcs2%3AGFajQk79MFAuPi5BYEn2l6dYDo0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.lynda.com/freepass/cs2">http://www.lynda.com/freepa...</a> for a free 1-day pass.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649723">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649723">6</a> by Peter Tilbrook
		posted on 1/29/2006 at 5:29 AM
		</div>
		<div class="comment_text"><p>I second Scotty! <a href="http://disq.us/url?url=http%3A%2F%2FLynda.com%3ATPz3dgmgOqHT_7X_Z6RS4XU4CiE&amp;cuid=3321886" rel="nofollow noopener" title="Lynda.com">Lynda.com</a> have great tutorials covering a huge range of subjects.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649727">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649727">7</a> by Joe Danziger
		posted on 1/30/2006 at 7:20 PM
		</div>
		<div class="comment_text"><p>I would have him ask around to see if he has access to "SmartForce".  All Army people have access to it, it provides online training in all sorts of technical areas.  I'm not sure about Flex, but I know there is ColdFusion.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649725">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649725">8</a> by Kris Brixon
		posted on 1/30/2006 at 7:35 PM
		</div>
		<div class="comment_text"><p>Try VTC <a href="http://disq.us/url?url=http%3A%2F%2Fwww.vtc.com%2F%3AMgJIdpfL_0NGSwS2Ve9gAEiPwes&amp;cuid=3321886" rel="nofollow noopener" title="http://www.vtc.com/">http://www.vtc.com/</a> Their ColdFusion training for MX is very CFC heavy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649726">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649726">9</a> by Russell Youngblood
		posted on 1/30/2006 at 10:54 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2FLynda.com%3ATPz3dgmgOqHT_7X_Z6RS4XU4CiE&amp;cuid=3321886" rel="nofollow noopener" title="Lynda.com">Lynda.com</a> is definately the best choice for eLearning with a pre-recorded session. However, if you need online learning with a live Authorized instructor, we offer live eLearning sessions with Breeze or GoToMeeting. With this blended learning method you have the advantage of distance learning with a live Macromedia Authorized instructor to train and assist.</p><p>Russell Youngblood<br>Director of Training <br>ryoungblood@ledet.com<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.ledet.com%3APtsS7eTQyoV7Rlr-9sPVXfl5q0Q&amp;cuid=3321886" rel="nofollow noopener" title="http://www.ledet.com">http://www.ledet.com</a><br>Authorized Adobe/Macromedia Training</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649710">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649710">10</a> by PaulC
		posted on 1/31/2006 at 12:46 AM
		</div>
		<div class="comment_text"><p>(Sorry for the confusion Ray.)</p><p>Let me know if you need any assistance with SCORM tracking. If it's a Defense Dept. project, it's very likely they want a packaged SCO to run in their LMS, since they paid for the SCORM standard to be developed. A course that requires it's own server is generally frowned upon in e-Learning.</p><p>I've got a lot of experience with it and a handy AS2.0 class to simplify tracking I'd be willing to share.</p><p>If it's technical training with lots of screencaps and whatnot, I'd recommend Captivate.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649712">11</a> by Davy Mac
		posted on 5/11/2006 at 4:57 PM
		</div>
		<div class="comment_text"><p>Hi Paul C. I develop elearning in Flash and would be most interested to find out more about your AS2.o class for tracking.</p><p>Could you tell me more?</p><p>Davy</p></div>
	</div>
</div>
		