
<div class="comment" id="c_1713620935">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620935">1</a> by Scott Stroz
		posted on 9/23/2005 at 6:16 PM
		</div>
		<div class="comment_text"><p>iPod Nano = junk....I think not ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620937">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620937">2</a> by Raymond Camden
		posted on 9/23/2005 at 6:18 PM
		</div>
		<div class="comment_text"><p>True. The more I see it the more I lust over it.</p><p>So, did you sign up? Did ya? Did ya? If you don't, I'll ban your IP from viewing my blog! I'll tell your kids Santa isn't real! I'll squash small kittens with my big feet!</p><p>Errr, or maybe not. That sounds like a lot of work. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620940">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620940">3</a> by Chris
		posted on 9/23/2005 at 6:49 PM
		</div>
		<div class="comment_text"><p>Hooked you up Ray - if you get one, how about helping some readers hit the magic #5? ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620942">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620942">4</a> by drisgill.com
		posted on 9/23/2005 at 8:14 PM
		</div>
		<div class="comment_text"><p>I hooked you up too... least I can do for the free blog software. But of course now I need to get five people. Once Ray has his five, use mine instead ;)</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fipodnanos.freepay.com%2F%3Fr%3D22720109%3ATLzDQnIK5jXu3Qcz4Zyy6U-cvgA&amp;cuid=3321886" rel="nofollow noopener" title="http://ipodnanos.freepay.com/?r=22720109">http://ipodnanos.freepay.co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620945">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620945">5</a> by Raymond Camden
		posted on 9/23/2005 at 8:20 PM
		</div>
		<div class="comment_text"><p>Not a bad idea. I promise that when I get my 5 done, I'll add a comment so folks don't "waste" a referal on me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620944">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620944">6</a> by drisgill.com
		posted on 9/26/2005 at 7:38 PM
		</div>
		<div class="comment_text"><p>The Rhapsody thing is actually pretty cool... if it was 99cents a month i would consider keeping it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620943">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620943">7</a> by Raymond Camden
		posted on 9/26/2005 at 9:40 PM
		</div>
		<div class="comment_text"><p>It's just 99 cents for the first month. I believe it is 9.99 after that. To be honest, I'd rather buy satellite(sp) radio instead if I were to pay 10 bucks a month for music. I _do_ like Rhapsody in general though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620946">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620946">8</a> by Justin
		posted on 9/27/2005 at 10:26 PM
		</div>
		<div class="comment_text"><p>&lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.freemacmini.com%2F%3Fr%3D153050%3A-Hm_Pav7ht5vR7g9ZO40Q8OM26E&amp;cuid=3321886" rel="nofollow noopener" title="http://www.freemacmini.com/?r=153050">http://www.freemacmini.com/...</a>"&gt;<a href="http://disq.us/url?url=http%3A%2F%2Fwww.freemacmini.com%2F%3Fr%3D153050%3C%2Fa%3E%3Ab5aosY7Zl7jC2HfTOqZ8Ija7WA4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.freemacmini.com/?r=153050</a>">http://www.freemacmini.com/...</a> - if anyone still needs a free mac mini...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620947">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620947">9</a> by Nick Tong
		posted on 12/15/2005 at 6:25 PM
		</div>
		<div class="comment_text"><p>hey Ray - look what you can do with your iPods these days - no need to upgrade again ;)</p><p>Okay maybe for a bigger hard drive.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.succor.co.uk%2Findex.cfm%2F2005%2F12%2F15%2Flinix-on-your-iPod%3ADz8CxYX7v41jZLUCUabGzkrH0nA&amp;cuid=3321886" rel="nofollow noopener" title="http://www.succor.co.uk/index.cfm/2005/12/15/linix-on-your-iPod">http://www.succor.co.uk/ind...</a></p></div>
	</div>
</div>
		