
<div class="comment" id="c_1713737342">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737342">1</a> by Mike
		posted on 12/16/2011 at 1:53 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>I caught the last couple of mins of your presentation yesterday and thought it was a really good intro to JQM, seems there are a lot of misconceptions of what JQM is and isn't.</p><p>on the last question in your post are you referring to a .net person returning html as in a webapp or in a mobile (phonegap) type app?</p><p>I'm assuming you are talking about a mobile web app and not a mobile app correct?</p><p>I have always thought if it was going to be in say phonegap you would then be returning JSON or something like that and parsing vs mobile web app that is run on the server.</p><p>Anyhow just a questions.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737347">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737347">2</a> by Raymond Camden
		posted on 12/16/2011 at 2:00 AM
		</div>
		<div class="comment_text"><p>So in general, yes, if you mean a PhoneGap app hitting .Net (or ColdFusion), your CF/.Net should return data in a nice package (like JSON) that you then interpret on the PhoneGap side. You don't have to do that - you could return HTML fragments too.</p><p>Technically - it IS possible to push the user immediately to an offsite page. So the PhoneGap goes from (local)index.html to (remote)some.html. This works - and even still allows device hardware APIs. My old boss Greg Wilson did this once in PhoneGap. (But I don't think he blogged it.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737345">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737345">3</a> by Woody Pewitt
		posted on 12/16/2011 at 2:33 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Thanks so much for the presentation I got my first site using jQuery Mobile up last night. I look froward to doing much more with it soon!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737344">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737344">4</a> by Raymond Camden
		posted on 12/16/2011 at 2:34 AM
		</div>
		<div class="comment_text"><p>Glad you liked it, Woody!</p></div>
	</div>
</div>
		