
<div class="comment" id="c_1713684774">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684774">1</a> by Chris
		posted on 8/7/2008 at 4:14 PM
		</div>
		<div class="comment_text"><p>I know you are new to Flex, but I would love to see another presentation on Flex, Coldfusion, and Livecycle.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684790">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684790">2</a> by Lola LB
		posted on 8/7/2008 at 4:30 PM
		</div>
		<div class="comment_text"><p>Hmm . . . how about CFCs?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684797">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684797">3</a> by Steve Withington
		posted on 8/7/2008 at 4:32 PM
		</div>
		<div class="comment_text"><p>Would you be able to share anything you've been working on at Broadchoice?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684791">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684791">4</a> by Dan Vega
		posted on 8/7/2008 at 5:24 PM
		</div>
		<div class="comment_text"><p>Well that is my birthday so we could devote an hour to talking about me? HA!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684794">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684794">5</a> by marc esher
		posted on 8/7/2008 at 5:39 PM
		</div>
		<div class="comment_text"><p>i'd like to see a step-by-step investigation into a performance or memory problem in a real CF App. Take the problem, use the tools we have available to us (server monitor, java profilers, whatever) and use it as a case study in this kind of problem solving.</p><p>the presentations i've seen on this topic have been fairly general and have never gone completely from problem to solution.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684792">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684792">6</a> by Brian
		posted on 8/7/2008 at 5:55 PM
		</div>
		<div class="comment_text"><p>I second Lola and vote for CFC's.  You did a presentation at MAX in 2005 on Application.cfc.  How about updating that for CF8?  Or maybe focus on remote calls and web services.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684796">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684796">7</a> by Ryan McIlmoyl
		posted on 8/7/2008 at 6:12 PM
		</div>
		<div class="comment_text"><p>I know it's not one of your usual topics, but I'd love to see more information about unit testing being put forth to the CF community.  I think there's still a lot of developers out there who see it as more work than it's worth.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684793">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684793">8</a> by Raymond Camden
		posted on 8/7/2008 at 7:18 PM
		</div>
		<div class="comment_text"><p>I'm thinking CFCs or Unit Testing. CFCs would have to be a best practices type one though as my normal CFC preso is 3 hours long or so.</p><p>Unit Testing would be nice. It's something I've never presented on, and frankly, I'm new to it. So that adds the extra layer of me being scared to death of royally screwing up, which just adds to your enjoyment. However - I need to check with Charlie as I believe they recently had one... lets see. Bill Shelton did DB pattern for UT. Well, that's not exactly UT 101. I'll chew on this a bit.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684798">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684798">9</a> by David Sammons
		posted on 8/7/2008 at 7:34 PM
		</div>
		<div class="comment_text"><p>I agree with the other who have suggested a topic on CFCs.  I would specifically like to get more information on kind of a 'best practices' in structuring your applications in regard to CFCs.  I've been using the DAO/Gateway/Service model.  Is that the best??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684795">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684795">10</a> by Robert Myers
		posted on 8/7/2008 at 8:49 PM
		</div>
		<div class="comment_text"><p>Java for Coldfusion developers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684799">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684799">11</a> by Raymond Camden
		posted on 8/7/2008 at 9:00 PM
		</div>
		<div class="comment_text"><p>@Robert: I don't know Java. :) Well I can read it, but I don't "know" it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684789">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684789">12</a> by Esmeralda
		posted on 8/7/2008 at 9:50 PM
		</div>
		<div class="comment_text"><p>I also say CFC's - and perhaps binding using them.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684804">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684804">13</a> by Phillip Senn
		posted on 8/7/2008 at 11:17 PM
		</div>
		<div class="comment_text"><p>I wouldn't mind some discussion as to why so many top ColdFusion developers are being hired by Broadchoice.<br>What do they see in the company?<br>Is Broadchoice something that an 'average' developer could sign up for and become a reseller?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684802">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684802">14</a> by Raymond Camden
		posted on 8/7/2008 at 11:22 PM
		</div>
		<div class="comment_text"><p>@PSenn - It's the free energy drinks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684803">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684803">15</a> by shakti
		posted on 8/8/2008 at 1:54 AM
		</div>
		<div class="comment_text"><p>another vote for CFCs. mainly about best practices and how to not overuse them, i think i kinda do :)<br>also something about hw far can u take the OOP approach using CFCs would be gr8....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684801">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684801">16</a> by Jared Shields
		posted on 8/8/2008 at 3:40 AM
		</div>
		<div class="comment_text"><p>How about... 'usable' or 'useful' uses of Event Gateways... (from a low or high level perspective)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684806">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684806">17</a> by Alan Barlow
		posted on 8/8/2008 at 4:50 AM
		</div>
		<div class="comment_text"><p>Information relating to scale, server configuration, security, maintenance in regards to delivering SaaS-based applications would be greatly appreciated.</p><p>Also, if you want to broaden the brief more then perhaps cover the pro's/con's of individual codebase/database deployment per customer vs. shared codebase/individual database per customer vs. shared codebase/shared database per customer.</p><p>Thanks!<br>Alan Barlow<br>CTO, <a href="http://disq.us/url?url=http%3A%2F%2FProWorkflow.com%3A4q4CG95kp41oByTGUoVdZtqMe8Q&amp;cuid=3321886" rel="nofollow noopener" title="ProWorkflow.com">ProWorkflow.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684807">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684807">18</a> by John Barrett
		posted on 8/10/2008 at 9:50 AM
		</div>
		<div class="comment_text"><p>I would like to add another vote for cfcs. Especially referring to Application.cfc<br>just a thought,..</p></div>
	</div>
</div>
		