
<div class="comment" id="c_1713661390">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661390">1</a> by Teddy R Payne
		posted on 1/23/2007 at 12:02 AM
		</div>
		<div class="comment_text"><p>This is becoming more of a prevalent experience that I am noticing.  I have spoken with people, read emails or blog posts about features they would like to have in CFEclipse.  More than half the time the feature already exists.  I have only heard a few legitimate gripes about CFEclipse:</p><p>1) Large file handling<br>2) Enhanced search and replace (I don't like this feature)<br>3) File view multiple times for the same file that synchronizes for larger files</p><p>In the Flex Builder world, I keep hearing people wanting to see code behind and the visual stage at the same time, but that has nothing to do with CFEclipse.</p><p>Cheers,<br>Teddy</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661402">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661402">2</a> by Dan Skaggs
		posted on 1/23/2007 at 12:22 AM
		</div>
		<div class="comment_text"><p>Amen to the heartburn with Syscon's autoplaying video!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661403">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661403">3</a> by MikeR
		posted on 1/23/2007 at 12:52 AM
		</div>
		<div class="comment_text"><p>Funny, I don't see any autoplaying video at SysCon.</p><p>(After adding a simple filter to Firefox's AdBlock plus, that is.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661406">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661406">4</a> by Josen Ruiseco
		posted on 1/23/2007 at 1:04 AM
		</div>
		<div class="comment_text"><p>You're absolutely right.</p><p>That Sys-Con video ad is lame...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661410">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661410">5</a> by Justice
		posted on 1/23/2007 at 1:12 AM
		</div>
		<div class="comment_text"><p>just to point out (I am sure you know, but others might not) that when you use file view, you loose the built in revision history you get with project view.  That sucker has saved my butt more times than I can count =)</p><p>Chris</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661405">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661405">6</a> by Justice
		posted on 1/23/2007 at 1:13 AM
		</div>
		<div class="comment_text"><p>dangit, where is edit comment.  You dont really loose the built in rev history, you just lose it. =)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661407">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661407">7</a> by Raymond Camden
		posted on 1/23/2007 at 1:22 AM
		</div>
		<div class="comment_text"><p>Justice - you aren't allowed to make a mistake. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661414">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661414">8</a> by Tom K
		posted on 1/23/2007 at 1:28 AM
		</div>
		<div class="comment_text"><p>A file view that doesn't display file date and file size just doesn't work for me. When that's available, I'll finaly switch to CFeclipse!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661411">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661411">9</a> by Raymond Camden
		posted on 1/23/2007 at 1:36 AM
		</div>
		<div class="comment_text"><p>Tom, that is a good idea. I'll mention it to Mark. But here is an idea - why not use Aptana's file view for browsing and CFE for CF dev?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661412">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661412">10</a> by Tommy Gunn
		posted on 1/23/2007 at 2:02 AM
		</div>
		<div class="comment_text"><p>Thank you for boycotting sys-con. That has got to be THE biggest steaming pile on the internet. It's almost unbelievable that they do that, the video, the div popups, all the ads, it's crazy the amount of ads!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661409">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661409">11</a> by Dan
		posted on 1/23/2007 at 2:04 AM
		</div>
		<div class="comment_text"><p>I knew about this but I have to totally agree with you on the Sys-Con site. Every time I end up on that site and that tv ad starts running I get very annoyed. I understand that a company may need to make money with banner ads but auto playing any type of music or video is just annoying!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661415">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661415">12</a> by Raymond Camden
		posted on 1/23/2007 at 2:07 AM
		</div>
		<div class="comment_text"><p>To be fair - I'm pro-ad. Look at my site. (And click. Oops, forget I said that. ;)</p><p>I'm VERY opposed to ANY video/audio playing automatically. I don't care if it is an ad or not. I almost always have music on and when some stupid ad/animation starts playing, it just bugs me.</p><p>And while I'm ranting (grin), why the heck do a lot of Flash devs refuse to put a simple pause button on their Flash video? I mean - lord forbid I want to stop the video so I can quickly do work and do restart in a minute.</p><p>&lt;/rant&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661389">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661389">13</a> by Jason
		posted on 1/23/2007 at 3:15 AM
		</div>
		<div class="comment_text"><p>@MikeR</p><p>care to share that filter?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661391">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661391">14</a> by MikeR
		posted on 1/23/2007 at 3:36 AM
		</div>
		<div class="comment_text"><p>@Jason,</p><p>OK, after you install adblock plus:<br>    <a href="http://disq.us/url?url=http%3A%2F%2Fadblockplus.org%2Fen%2F%3Ac5VvqUmQeKDpSW4UhkB-jkjn9MA&amp;cuid=3321886" rel="nofollow noopener" title="http://adblockplus.org/en/">http://adblockplus.org/en/</a></p><p>Then add the filter rules:<br><a href="http://disq.us/url?url=http%3A%2F%2Fres.sys-con.com%2Fvideo%2Fcommercials%2F%2A%3A4e9I3OKxiQQYcFETk4YDdiVEGRc&amp;cuid=3321886" rel="nofollow noopener" title="http://res.sys-con.com/video/commercials/*">http://res.sys-con.com/vide...</a><br>and<br><a href="http://disq.us/url?url=http%3A%2F%2Fbanners.sys-con.com%2F%2A%3ACygc20rZRmpegFX_l2zV1qTPfx8&amp;cuid=3321886" rel="nofollow noopener" title="http://banners.sys-con.com/*">http://banners.sys-con.com/*</a></p><p>Note that adblock (with filter set G) already stops 13 other annoyances with syscon.</p><p>Bonus:  It also stops Raymond's Google ads!  (Sorry Raymond.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661392">15</a> by Jason
		posted on 1/23/2007 at 3:56 AM
		</div>
		<div class="comment_text"><p>thanks...got tired of those syscon ads.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661396">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661396">16</a> by Scott P
		posted on 1/23/2007 at 5:36 AM
		</div>
		<div class="comment_text"><p>Espn does that video autoplay stuff also....</p><p>Speaking of file view, do you know of a way to create a new file somewhere other than a project?  Would love to create new empty file on ftp server (or local drives) but I can't seem to figure that one out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661394">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661394">17</a> by Rey Bango
		posted on 1/23/2007 at 8:42 PM
		</div>
		<div class="comment_text"><p>The file view is really nice but the FTP implementation left something to be desired. On some FTP servers, my files were always in read-only mode which basically rendered CFE useless for FTP-based development. The same servers worked perfectly in CF Studio so I stuck with the old reliable. Rob Gonda pointed me over to WebDrive which works very nicely to get around this. It maps a drive letter on your PC to an FTP server. Very cool.</p><p>I agree with you Ray, its crazy that the Eclipse team has put so little effort into file-based access. Not everyone will be using a version control system and working in a project-based workbench. Even the FTP plugins aren't that great. Its the only thing thats holding me back from truly embracing CFE. I don't want to make everything a project. On many occasions, I simply want to open a file on an FTP server and work with it. Until CFE can "effectively" do that, I'll stick with CF Studi.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661395">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661395">18</a> by Ryan
		posted on 1/24/2007 at 12:02 AM
		</div>
		<div class="comment_text"><p>Agree on Eclipse FTP being buggy... if you wait too long in between saves, you'll get java errors when you try to save.  Then the file will no longer have that unsaved indicator, but really it didn't save it.  You need to click on a directory, which will automatically reestablish the connection (imagine that).  Then you can hit save again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661393">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661393">19</a> by Larry C. Lyons
		posted on 1/24/2007 at 12:03 AM
		</div>
		<div class="comment_text"><p>The ftp synchronizer is another plus with Aptana. Much better than other implementations of ftp in eclipse.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661397">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661397">20</a> by Tom K
		posted on 1/25/2007 at 11:48 AM
		</div>
		<div class="comment_text"><p>Finaly got around to trying Aptana, to see if anyone developing IDE's based on Eclipse can do file view in a useful manner. Aptana was a decent editor, but its file view function isn't ready for prime time.</p><p>Just opening up a new folder containing 30-40 files took 10+ seconds to render the entire list of file names. Then to see the file date and file size you had to right click each file, select 'properties' and read the information in a pretty 3-line pop-up window. So if you want to see last-saved date of 20 files, that's 20 icons you have to right click!</p><p>Sorry. That's not my idea of file view. All we need is what CF Studio could do 7+ years ago; show a 3 column, column sortable, list of names, sizes and dates, one folder at a time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661399">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661399">21</a> by G Fay
		posted on 4/26/2007 at 7:56 PM
		</div>
		<div class="comment_text"><p>Does anyone know how to turn on DATE (modified) and or attributes for the file explorer in eclipse ...</p><p>As for nifty plugins, the EPIC (perl) has a really nice regex tool!</p><p>G</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661398">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661398">22</a> by Patrick
		posted on 10/1/2008 at 11:27 PM
		</div>
		<div class="comment_text"><p>File Explorer View will not display directories for me. Worked fine for me in Win XP. I am on Vista Ultimate now though....any suggestions? Thx.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661401">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661401">23</a> by bucabay
		posted on 6/11/2009 at 12:53 AM
		</div>
		<div class="comment_text"><p>I've been creating a project and setting the location to the directory and want to use as the root for the file viewing.</p></div>
	</div>
</div>
		