
<div class="comment" id="c_3289137123">
	<div>
		<img src="https://disqus.com/api/users/avatars/antoniogallo.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3289137123">1</a> by Antonio Gallo
		posted on 5/4/2017 at 9:44 PM
		</div>
		<div class="comment_text"><p>is ionic2 considered "stable" by someone? O.o</p></div>
	</div>
</div>
		
<div class="comment" id="c_3289140385">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3289140385">2</a> (In reply to <a href="#c_3289137123">#1</a>) by Raymond Camden
		posted on 5/4/2017 at 9:47 PM
		</div>
		<div class="comment_text"><p>You mean me? Sure. I love it. I even have a course on it coming out from Lynda (well, not "course", it's more a intro to it).</p></div>
	</div>
</div>
		
<div class="comment" id="c_3289311768">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_uC8iW86l6S.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3289311768">3</a> by Gary F
		posted on 5/5/2017 at 12:18 AM
		</div>
		<div class="comment_text"><p>Ray, could you tell me if the book assume the reader is already familiar with the previous version of Ionic and also Angular? If someone has only known jQuery Mobile + PGB and wants to migrate, is this a suitable book? Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3290205051">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3290205051">4</a> (In reply to <a href="#c_3289311768">#3</a>) by Raymond Camden
		posted on 5/5/2017 at 3:37 PM
		</div>
		<div class="comment_text"><p>You do not need to be familiar with either Ionic 1 or Angular 1. I think you should be fine.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3290231744">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_uC8iW86l6S.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3290231744">5</a> (In reply to <a href="#c_3290205051">#4</a>) by Gary F
		posted on 5/5/2017 at 3:54 PM
		</div>
		<div class="comment_text"><p>Cool, thanks Ray.(Mumbles to self: I wonder why computer books have dull and irrelevant cover artwork? Could have at least use a photo or drawing of a happy person holding a mobile, smiling at how wonderful their new app is! Hmm, it's probably cost related reason.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_3290234261">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3290234261">6</a> (In reply to <a href="#c_3290231744">#5</a>) by Raymond Camden
		posted on 5/5/2017 at 3:56 PM
		</div>
		<div class="comment_text"><p>Actually, *all* ORA books follow a theme of using interesting animals. I like it. :)</p></div>
	</div>
</div>
		