
<div class="comment" id="c_1713716413">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716413">1</a> by David Ogletree
		posted on 6/30/2009 at 12:48 AM
		</div>
		<div class="comment_text"><p>I think it would be a good idea to have a session on search marketing and how to use coldfusion to implement and improve search marketing including pay per click, search engine optimization, product feeds, and social networking api integration.</p><p>I have worked with a few coldfusion websites to help them with their seo in the past.  I an not a dedicated CF programmer but I know how to get in and tweak CF websites to work better with search marketing.  It would be good to have a panel with experts in twitter, and facebook api's, as well as people that have used it to create search engine friendly websites.  With pay per click coldfusion websites can be set up to do multivariate landing page testing using coldfusion.</p><p>I am available for any time slot to speak on search engine friendly web design and how that relates to CF</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716420">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716420">2</a> by Michael Dinowitz
		posted on 6/30/2009 at 3:59 AM
		</div>
		<div class="comment_text"><p>Put me down next to David. I could take up the entire unconference with SEO related stuff with another day's worth after that. :)</p><p>Actually, you can put me down for just about anything in CF or Google. Hell, just my basic HTML for search engines would be worth a listen. How many people scorn the basics and miss all that it can do?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716421">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716421">3</a> by Dan Wilson
		posted on 7/2/2009 at 4:46 PM
		</div>
		<div class="comment_text"><p>You can count me in for a slot or two. I might like to do a session on client side performance. I'll also do one on Model-Glue 3.1 (yes it'll be out then)</p><p>I'm not yet sure of what times would be good, and don't even know the general Max schedule. I'll try to go figure it out.</p><p>DW</p></div>
	</div>
</div>
		