
<div class="comment" id="c_1713676776">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676776">1</a> by Todd Rafferty
		posted on 1/31/2008 at 6:13 PM
		</div>
		<div class="comment_text"><p>You dropped the 'k' in your link.  <a href="http://disq.us/url?url=http%3A%2F%2FGeethetubes.com%3AcRS9Lw0iw5BtTuvd2d183AYzskA&amp;cuid=3321886" rel="nofollow noopener" title="Geethetubes.com">Geethetubes.com</a> doesn't exist. ;)  Honestly, I had been avoiding lost, but recently I just resubscribed to Netflix and saw Lost there, so I threw in disc 1 season 1 for giggles.  Watched 2 episodes last night and now I'm going to have to get the whole damn thing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676789">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676789">2</a> by Raymond Camden
		posted on 1/31/2008 at 7:04 PM
		</div>
		<div class="comment_text"><p>Fixed, thanks. FYI, season 3 has some low points, but don't stop watching. Half way through it _really_ picks up and the ending is amazing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676793">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676793">3</a> by Todd Rafferty
		posted on 1/31/2008 at 7:05 PM
		</div>
		<div class="comment_text"><p>No worries.  BSG had some low points and I didn't stop watching.  I plan on watching this the whole way through.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676792">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676792">4</a> by RobW
		posted on 1/31/2008 at 7:23 PM
		</div>
		<div class="comment_text"><p>Here it comes, the "Beginning of the End". Hopefully the writers' strike will get ironed out in time to complete the other 8 episodes for this season. But from the spoilers I've read so far, things are about to get even weirder on the island.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676795">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676795">5</a> by Sam Robbins
		posted on 1/31/2008 at 7:29 PM
		</div>
		<div class="comment_text"><p>Yeah I can't wait! The end of season three has to be my best tv viewing experience ever.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676797">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676797">6</a> by Raymond Camden
		posted on 1/31/2008 at 7:33 PM
		</div>
		<div class="comment_text"><p>Hmm. I'm not sure "best" is right. It was darn, darn, darn good. When I think best... I think....</p><p>Ending to Six Feet Under (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWWdYMuo3_B4%29%3ABYrJ8NQsK-qjTvNfNs5WHJYJYXY&amp;cuid=3321886" rel="nofollow noopener" title="http://www.youtube.com/watch?v=WWdYMuo3_B4)">http://www.youtube.com/watc...</a></p><p>Parts of BSG s2 - specifically the human resistance part, which frankly did not get enough attention (I mean come on, they basically said it was ok to use suicide bombers, how did Fox News miss this?)</p><p>And from Lost - I think some of the best scenes so far have been Locke's history, of course, I have personal reasons for that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676796">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676796">7</a> by Adam
		posted on 1/31/2008 at 8:05 PM
		</div>
		<div class="comment_text"><p>wow, you guys are doing better than me, I lost interest mid way through season 2 when it started feeling like 1 step forward 2 steps back all the time, giving you one little bit of info then throwing in 10 new random events. Only watched a few of s3 but I guess I might pick it up again if it looks like it's ever going to end, what I want is for them to wrap it up and explain some stuff not just string it out into another twin-peaks/xfiles never-ending story. Think this will actually happen?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676798">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676798">8</a> by Raymond Camden
		posted on 1/31/2008 at 8:12 PM
		</div>
		<div class="comment_text"><p>You raise an interesting point. Should Lost "wrap up". I'm of two minds on this. First - some of the best stories do NOT answer all the questions. They leave it up to you to decide. Now certainly Lost could not end right now, but I don't think they need to answer everything for me.</p><p>The flip side of course is the geek part of me which wants to know each and every single detail. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676801">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676801">9</a> by RobW
		posted on 1/31/2008 at 9:33 PM
		</div>
		<div class="comment_text"><p>If you watch this <a href="http://disq.us/url?url=http%3A%2F%2Fwww.ted.com%2Findex.php%2Ftalks%2Fview%2Fid%2F205%3AU4Nkp03kREXOYaLjRoTwroJCZbc&amp;cuid=3321886" rel="nofollow noopener" title="http://www.ted.com/index.php/talks/view/id/205">http://www.ted.com/index.ph...</a> video of JJ Abrams speaking about "the mystery box", it would give you the idea that some of Lost's mysteries will always be mysteries. But since Cuse &amp; Lindelof have gotten a committment out of ABC for a specific number of episodes, it give one hope that at least a satisfying ending will eventually be reached. Probably not everyone will be happy with the ending, but it will have a finite ending, rather than dragging on extra seasons with more and more filler material.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676803">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676803">10</a> by Adam
		posted on 1/31/2008 at 10:43 PM
		</div>
		<div class="comment_text"><p>hmm, just seems like a cop-out and to cheapen the whole story telling process if at any time he can throw in a unicycling whalrus playing bagpipes (or a polar bear, or a horse, or a cloud monster or...), then never need to explain or even reference it again.... "it's a mystery, wooooo" (waves fingers enigmatically and makes ghost noises)... no, it's you desperately trying to pad out what could have been an amazing one season story into an ongoing paycheck :)</p></div>
	</div>
</div>
		