
<div class="comment" id="c_1713655756">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655756">1</a> by Bastian Konetzny
		posted on 8/1/2006 at 6:48 PM
		</div>
		<div class="comment_text"><p>So why are you extending the deadline if i'm winning anyway? ;)</p></div>
	</div>
</div>
		