
<div class="comment" id="c_1713662472">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662472">1</a> by Sam
		posted on 2/21/2007 at 8:18 PM
		</div>
		<div class="comment_text"><p>Well, at least you are within 4 hour driving distance of Houston!</p><p>Ours (Houston) will be right in the middle of finals, but I'm going to see if I can't make some time for it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662467">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662467">2</a> by Ryan Everhart
		posted on 2/21/2007 at 9:03 PM
		</div>
		<div class="comment_text"><p>Anyone else notice that the Adobe Labs site is PHP???  That ain't right!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662473">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662473">3</a> by James Edmunds
		posted on 2/21/2007 at 10:20 PM
		</div>
		<div class="comment_text"><p>ROAD TRIP? Ray, does our local UG own a luxury tour bus? I can't seem to remember just right now whether it does or not!</p></div>
	</div>
</div>
		