
<div class="comment" id="c_1713731957">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731957">1</a> by Steve &amp;aposCutter&amp;apos Blades
		posted on 5/3/2011 at 3:21 PM
		</div>
		<div class="comment_text"><p>It's FlashBuilder 4.5, right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731962">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731962">2</a> by Raymond Camden
		posted on 5/3/2011 at 3:24 PM
		</div>
		<div class="comment_text"><p>Doh. You are right. Editing now. Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731964">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731964">3</a> by Ben Riordan
		posted on 5/4/2011 at 2:53 AM
		</div>
		<div class="comment_text"><p>Even CFB2 uses Aptana 1? Why not upgrade Aptana in CFB2?</p><p>~ Ben</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713731965">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713731965">4</a> by Raymond Camden
		posted on 5/4/2011 at 4:56 AM
		</div>
		<div class="comment_text"><p>I asked about that, but apparently it would have been difficult. It is - probably - the only real disappointing thing about CFB2 to me.</p></div>
	</div>
</div>
		