
<div class="comment" id="c_1713680906">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680906">1</a> by David O Malley
		posted on 5/13/2008 at 5:47 PM
		</div>
		<div class="comment_text"><p>Sorry Ray - the URL for the connect meeting is:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fadobechats.adobe.acrobat.com%2Fcfugitives%2F%3AWG1nXg9YXCx5UYWbJe9TGt7yL4E&amp;cuid=3321886" rel="nofollow noopener" title="http://adobechats.adobe.acrobat.com/cfugitives/">http://adobechats.adobe.acr...</a></p><p>Open to all.</p><p>Cheers,</p><p>Davo</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680913">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680913">2</a> by Rick Smith
		posted on 5/13/2008 at 7:56 PM
		</div>
		<div class="comment_text"><p>I'm presenting [for my first time] tonight on CFCs in St. Louis, but no Adobe Connect.  Good luck tonight on your presentation (you're always a good speaker :)).</p></div>
	</div>
</div>
		