
<div class="comment" id="c_1713747723">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713747723">1</a> by Marcin
		posted on 7/19/2013 at 3:43 PM
		</div>
		<div class="comment_text"><p>Heh, you're game fronting up at a CocoaHeads to speak about PhoneGap!</p><p>At my local CocoaHeads there was already enough heckling when someone spoke about AppCode vs Xcode :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713747735">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713747735">2</a> by Raymond Camden
		posted on 7/19/2013 at 8:08 PM
		</div>
		<div class="comment_text"><p>I didn't even think about that. Um.... maybe I need to rethink this. ;)</p></div>
	</div>
</div>
		