
<div class="comment" id="c_1713728344">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728344">1</a> by Brian Rinaldi
		posted on 12/15/2010 at 8:03 PM
		</div>
		<div class="comment_text"><p>The next step would be to update the ANT task to generate more than just an Android version. In theory at least, you could get it to generate a Playbook and iOS version as well based upon user choices.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713728346">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728346">2</a> by Raymond Camden
		posted on 12/15/2010 at 8:07 PM
		</div>
		<div class="comment_text"><p>Yep, if you look at Terry's blog post he does just that. (Well, for Playbook.) I removed it intentionally to simplify things.</p></div>
	</div>
</div>
		