
<div class="comment" id="c_1713724247">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724247">1</a> by Simon
		posted on 5/7/2010 at 11:24 PM
		</div>
		<div class="comment_text"><p>Hey hey go Dave and you managed to cram this into the schedule as well as the podcasts nice one :o)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713724253">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724253">2</a> by Dave Ferguson
		posted on 5/14/2010 at 7:35 PM
		</div>
		<div class="comment_text"><p>I have made a bunch of changes to the extension since Ray did this review.  Some issues have been corrected and new functions have been added. Check out the new version of the extension here.  <a href="http://disq.us/url?url=http%3A%2F%2Fbase64imageconverter.riaforge.org%2F%3AqRO8yXXhl0LJnFg3odnR7CfYU5Y&amp;cuid=3321886" rel="nofollow noopener" title="http://base64imageconverter.riaforge.org/">http://base64imageconverter...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713724255">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713724255">3</a> by Eric Belair
		posted on 5/18/2010 at 5:39 PM
		</div>
		<div class="comment_text"><p>I wish I had read this post when it came out...this extension would have been very useful to me on my last project. I'm definitely going to try it out though....</p></div>
	</div>
</div>
		