
<div class="comment" id="c_1713681518">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681518">1</a> by Todd Rafferty
		posted on 6/5/2008 at 6:27 PM
		</div>
		<div class="comment_text"><p>For those looking to listen to this for spry/jquery tips and such, it's not mentioned until time marker 1:00:00 or so and it's not so much as tips as comparisons to CF's baked in stuff.  Ray pretty much sticks with CF8's new ajax tags throughout the presentation.</p><p>BTW Ray, the cflib preview you did in the video is awesome.  The site looks great!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681525">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681525">2</a> by Raymond Camden
		posted on 6/5/2008 at 6:33 PM
		</div>
		<div class="comment_text"><p>Were folks expecting more spry/jquery tips? If so - sorry. There is a lot to cover just w/n the CF8 stuff.</p><p>My announcement re: cfunited, which will be more formally done later today, is that after I do my CF8 Ajax preso (which is this preso), I'm also doing a "part 2", where I can spend more time on using CF8 with Ajax. For example, using returnFormat=json, etc.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681529">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681529">3</a> by Todd Rafferty
		posted on 6/5/2008 at 6:43 PM
		</div>
		<div class="comment_text"><p>You mentioned on twitter that you'd be talking about spry/jquery.  That's why I brought it up, but now that I look at twitter again, I see that I disregarded or didn't see this ( <a href="http://disq.us/url?url=http%3A%2F%2Ftwitter.com%2Fcfjedimaster%2Fstatuses%2F826841982%3AHBYxBRKDMUkWaw86xnxsTlSzwoc&amp;cuid=3321886" rel="nofollow noopener" title="http://twitter.com/cfjedimaster/statuses/826841982">http://twitter.com/cfjedima...</a> ).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681527">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681527">4</a> by Raymond Camden
		posted on 6/5/2008 at 6:46 PM
		</div>
		<div class="comment_text"><p>Ahh. Well I feel a bit better now. ;) I try to be very clear about what I'm talking about so folks don't go away disappointed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681523">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681523">5</a> by Todd Rafferty
		posted on 6/5/2008 at 6:53 PM
		</div>
		<div class="comment_text"><p>It's hard to be clear in 140 characters, but yes... I just wasn't paying attention and apparently only caught half the conversation.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681522">6</a> by David Harris
		posted on 6/5/2008 at 11:46 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Thanks again for the presso.<br>We love the code examples etc.<br>Great show &amp; tell!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681534">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681534">7</a> by Matt Hall-Smith
		posted on 6/6/2008 at 12:10 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Many thanks for your time in presenting last night. It was a pleasure to see new ways to do old stuff and we all look forward to the new and improved cflib.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681524">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681524">8</a> by Shama
		posted on 6/6/2008 at 12:44 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Thanks for taking the time to present to us last night. The CF Ajax stuff was a lot of fun.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681526">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681526">9</a> by Josh Hand
		posted on 6/6/2008 at 1:14 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Thanks for your presentation last night was very informative and the code examples were easy to follow.</p></div>
	</div>
</div>
		