
<div class="comment" id="c_1713623317">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623317">1</a> by Scott Stroz
		posted on 12/9/2005 at 3:27 AM
		</div>
		<div class="comment_text"><p>Yep - you'll be on another list somewhere ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623316">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623316">2</a> by John Farrar
		posted on 12/9/2005 at 3:54 AM
		</div>
		<div class="comment_text"><p>Well... bottom line is that component level repair went out years ago. Now it's a matter of replacing major assemblies like mother boards or hard drives and the like. How long should that take... if you hit the bench, it doesn't take long. Unscrew... unplug... replace... return. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623318">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623318">3</a> by Raymond Camden
		posted on 12/9/2005 at 4:01 AM
		</div>
		<div class="comment_text"><p>Oh yeah, I know, but again with the holidays, I'm impressed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623322">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623322">4</a> by Mark W. Breneman
		posted on 12/9/2005 at 4:04 AM
		</div>
		<div class="comment_text"><p>Ray, have you ever looked into moding your xbox? I had more fun researching / soft moding my xbox not to mention all of the cool things you can do with the XBOX after it is moded. Oh, and I know I have spent more time using my XBOX for other things, than I have spent paying games. I even saw someone install blue dragon  Coldfusion server on a moded XBOX.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623321">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623321">5</a> by Mark W. Breneman
		posted on 12/9/2005 at 4:06 AM
		</div>
		<div class="comment_text"><p>Sorry, the reason I ask about moding, is you can make a back up of your hard disk or even swap it out for a larger one.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623319">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623319">6</a> by Raymond Camden
		posted on 12/9/2005 at 4:11 AM
		</div>
		<div class="comment_text"><p>No - I'm a hardware noob. I despise opening up hardware. Always have. I think it's because my hands are big and I'm clumsy. I always tense up when I do hardware work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623320">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623320">7</a> by cmd19872002
		posted on 1/8/2006 at 5:31 AM
		</div>
		<div class="comment_text"><p>Ya, you can do sooo much more with a modded xbox :P. I personaly mod xboxes all the time, a hard drive replace is pretty easy and quick if you have a mod chip laying around (to back up the orignal hard drive if it works at all yet, put in a new drive thats not locked, format it, and load the info back on the drive.) Its not as simple as it sounds though, just geting the mod chip in and flashing is some times more than most people can handle (all the research and info you have to read). You can update the hard drive to a bigger one and still beable to take the mod chip out/ turn it off aslong as you lock it with the right code.</p><p>If you want any more info, email me at: ps2fixer@gmail.com or post, but i will probley loose this link lol.</p><p>cmd19872002</p></div>
	</div>
</div>
		