
<div class="comment" id="c_1713659078">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659078">1</a> by Phillip Senn
		posted on 11/14/2006 at 1:16 AM
		</div>
		<div class="comment_text"><p>Impressive.<br>Obiwan has taught you well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659126">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659126">2</a> by Shigeru
		posted on 11/14/2006 at 8:15 AM
		</div>
		<div class="comment_text"><p>BTW this "code view" includes latest BlogCFC ??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659123">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659123">3</a> by Raymond Camden
		posted on 11/14/2006 at 8:17 AM
		</div>
		<div class="comment_text"><p>It will be, yes.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659128">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659128">4</a> by Stephen Moretti
		posted on 11/14/2006 at 2:54 PM
		</div>
		<div class="comment_text"><p>A word of caution about the code view...</p><p>There is something very weird going on.  In the &lt;!--- generate key from arguments ---&gt; section, I am seeing "keykey" in the cfsets, one in red and one in blue, rather than just plain "key" and in the query I'm seeing where "11 = 1" rather than "1=1". Again, one is red the other is blue.</p><p>The contents of plain view is fine though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659127">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659127">5</a> by Raymond Camden
		posted on 11/14/2006 at 5:20 PM
		</div>
		<div class="comment_text"><p>I see that Stephan. I'll ping the author. Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659125">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659125">6</a> by Shigeru
		posted on 11/14/2006 at 9:27 PM
		</div>
		<div class="comment_text"><p>About new code view.<br>What about MXML and ActionScript3 ??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713659124">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713659124">7</a> by Raymond Camden
		posted on 11/14/2006 at 9:32 PM
		</div>
		<div class="comment_text"><p>The client doesn't support those languages yet. But it could be added.</p></div>
	</div>
</div>
		