
<div class="comment" id="c_1713614538">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614538">1</a> by Geoff Bowers
		posted on 4/29/2003 at 1:23 AM
		</div>
		<div class="comment_text"><p>Sad to see you leave the back of the old beast, mate.  Spectra had some great innovations in it''s day -- secretive "grouse" meetings, new techno-babble, and more.  But Spectra''s pretty much come to the end.</p><p>&lt;plug&gt;If you ever hunker after a bit of Spectra-esque development(the good bits -- not the bad bits ;) -- you might try FarCry Opensource (<a href="http://disq.us/url?url=http%3A%2F%2Ffarcry.daemon.com.au%2F%3C%2Fplug%3E%3Apb0K1Gx12ax-bvP4c5xEd-T_Xps&amp;cuid=3321886" rel="nofollow noopener" title="http://farcry.daemon.com.au/</plug>">http://farcry.daemon.com.au...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614552">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614552">2</a> by Raymond Camden
		posted on 4/29/2003 at 4:01 PM
		</div>
		<div class="comment_text"><p>Or our products, Mindseye Element. But I may be a bit biased. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614539">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614539">3</a> by Raymond Camden
		posted on 4/29/2003 at 4:02 PM
		</div>
		<div class="comment_text"><p>Of course, products == product.</p></div>
	</div>
</div>
		