
<div class="comment" id="c_1713736965">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736965">1</a> by Peter Schmidt
		posted on 11/24/2011 at 9:30 PM
		</div>
		<div class="comment_text"><p>And a Happy Thanksgiving to you and yours</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736984">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736984">2</a> by Alirio Boquin A.
		posted on 11/24/2011 at 10:18 PM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving my friend</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736967">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736967">3</a> by Ian Finch
		posted on 11/25/2011 at 12:30 AM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving to you and your family, Ray, from one of the worldwide members of your community here in London. Thanks for the year-round inspiration!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736968">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736968">4</a> by shiva
		posted on 11/25/2011 at 9:34 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>I would like to take this opportunity to thank you in the thanks giving day.</p><p>Whenever i turned on my PC, i will first visit the coldfusion JEDI for gathering information about CFML with great example!</p><p>We would like to thank you for enhancing our skills in CFML. You man done a great effort.</p><p>Once again thanks Ray!</p><p>Shiva</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736970">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736970">5</a> by Shawn Bowman
		posted on 11/25/2011 at 9:46 AM
		</div>
		<div class="comment_text"><p>Happy Turkey Day to you and yours good sir.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736969">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736969">6</a> by SteveOfSP
		posted on 11/28/2011 at 10:38 PM
		</div>
		<div class="comment_text"><p>Yes, Ray, a blog is a community.  And this is one of the nicest I visit.</p><p>Belated Happy T'Day</p></div>
	</div>
</div>
		