
<div class="comment" id="c_1713615763">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615763">1</a> by Chris Brandt
		posted on 6/11/2004 at 8:48 PM
		</div>
		<div class="comment_text"><p>Cue track 10 from the 'Office Space' soundtrack (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.amazon.com%2Fexec%2Fobidos%2Ftg%2Fdetail%2F-%2FB00000I5M4%2Fqid%3D1086979305%2Fsr%3D8-2%2Fref%3Dpd_ka_2%2F104-5223302-6789518%3Fv%3Dglance%26s%3Dmusic%26n%3D507846%29%3Ap3XzcqTdlkhYVB-bnPBfC6Dftm4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.amazon.com/exec/obidos/tg/detail/-/B00000I5M4/qid=1086979305/sr=8-2/ref=pd_ka_2/104-5223302-6789518?v=glance&amp;s=music&amp;n=507846)">http://www.amazon.com/exec/...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615769">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615769">2</a> by Steve Nelson
		posted on 6/11/2004 at 9:40 PM
		</div>
		<div class="comment_text"><p>Man that's the story of my life. The last couple years i've just gotten in the habit of throwing away my printer the second I can't clean it within a minute or two. Then i run down to best buy and pick up a new one for $50-100. The price of a new one is less than an hour of consulting. Not worth the effort to continuously messing with it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615772">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615772">3</a> by Jeff Garza
		posted on 6/11/2004 at 9:55 PM
		</div>
		<div class="comment_text"><p>Get a printer that doesn't require those awful multi-color tanks that cost more than the printer itself.  You might want to look at something like an Epson Stylus CX6400.  It's an all in one that does everything but FAX.  The beauty here is that it uses separate ink cartridges for each color and they are ~12 bucks each.  Good Luck!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615762">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615762">4</a> by anthony petruzzi
		posted on 6/11/2004 at 10:59 PM
		</div>
		<div class="comment_text"><p>I think I have the best plan here. I just print everything to pdf from my house, then I print out the important stuff when I get to work, so I don't need a printer. :P</p><p>In all seriousness, printers suck. Seems that since they have come down in price, they have also come down in quality. I know poeple who have a dot matrix printer from the 1980 and the thing still works. Yet  my Office Jet 600 keeps screwing up.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615765">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615765">5</a> by Michael Conger
		posted on 6/12/2004 at 2:33 AM
		</div>
		<div class="comment_text"><p>I too have had good luck with my Epson ink jet.  I believe the model number is 825c.  My dad, brother, father-in-law, and sister all have similar Epson ink jets.  They've all been pretty happy with them.</p><p>The ink cost for epson seems a little high compared with a few others (lexmark for example) but it's about on par with HP ink jets I've used in the past.</p><p>ps. if you buy the right epson model it also comes with multiple PCMCIA cards to read camera memory cards.  They're just standard PCMCIA cards that plug into the printer.  The cool part is... since they're standard and removable, you can yank them out and use them in your laptop too... sweet!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615770">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615770">6</a> by Peter Farrell
		posted on 6/12/2004 at 9:24 AM
		</div>
		<div class="comment_text"><p>Well, I have given up on all lousy inkjets - period (unless I need something in colour).  I rely on my trusted HP laserjet series II from 1987 with a whopping 4 MB of RAM and a postscript cartriage (which is gathering dust due to truetype fonts these days).  Buy yourself a steel caged old HP laserjet for your black and white needs.  The only thing I've ever done to it is replace the fuser twice (about $37 each time).  Come on - it's done at least 1.5 million pages by now.  Check out the <a href="http://disq.us/url?url=http%3A%2F%2Fprinterworks.com%3A1eMPZqBJRlbeMEnNl3ZbVExOP7U&amp;cuid=3321886" rel="nofollow noopener" title="printerworks.com">printerworks.com</a> - they got a rfb one for $199.  By the way, I have no connection to them - just good luck with them in the past.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615764">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615764">7</a> by Chris Brandt
		posted on 6/12/2004 at 5:31 PM
		</div>
		<div class="comment_text"><p>You know what I'd like... When you do a nozzle check and you see that ONE of the print nozzles is clogged (one of the lines is misprinting) that you could choose just a single color to have the heads cleaned rather than wasting ink for all the other colors.</p><p>I once had to clean the heads on my epson 900 10 times in a row to get something fixed -- it used up half of my ink!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615766">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615766">8</a> by John Blayter
		posted on 6/13/2004 at 1:55 AM
		</div>
		<div class="comment_text"><p>I recently beat the living crap out of my HP DeskJet R40xi after it had pissed me off for the last time after 4 years. If you decide to do the same to your printer make sure to play this while doing so.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.blayter.com%2Fcontent%2Femail%2Fghettoboys.mp3%3ArBM9AmVU-zgG4ab4vW4-gDJbPlU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.blayter.com/content/email/ghettoboys.mp3">http://www.blayter.com/cont...</a></p><p>good luck in hunting for a printer.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615768">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615768">9</a> by Chris Brandt
		posted on 6/13/2004 at 6:57 PM
		</div>
		<div class="comment_text"><p>John,</p><p>I think the printer destruction song is 'Still' - also from the Getto Boys.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615773">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615773">10</a> by Paul Kenney
		posted on 6/14/2004 at 6:35 PM
		</div>
		<div class="comment_text"><p>Here's the link to the song (sorry, not my title):</p><p>http://68.100.100.125:8080/awfuly/muzak/GhettoBoys-DieMotherFuckers.mp3</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615774">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615774">11</a> by Rick Root
		posted on 6/15/2004 at 10:04 PM
		</div>
		<div class="comment_text"><p>Laser is the only way to go.  I've hated inkjets since their inception.. I got my first laser printer back in the early 90s... a Panasonic Sidewriter KXP4400.. which was actually an "LED printer" supposedly, but it was basically a laser printer.  My current laser printer is a Samsung ML1710, purchased about 6 months ago at Best Buy for $100... I've seen them "brand new" on ebay for even less than that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615767">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615767">12</a> by haiki
		posted on 4/23/2006 at 5:51 PM
		</div>
		<div class="comment_text"><p>Hewlett Packard ink cartridge, just another auto part to be recycled.</p><p>Do you have  printer ink cartridge problems? Focus on the printer, not the ink cartridge.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615775">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615775">13</a> by haiki
		posted on 4/27/2006 at 4:25 PM
		</div>
		<div class="comment_text"><p>Smith and Roberson’s Business Law, ninth edition. West Publishing. Chapter 43; ANTITRUST. <br>“Characterizing a type of restraint as per se illegal therefore has a significant effect on the prosecution of an antitrust suit. In such a case, the plaintiff need only show that the type of restraint occurred, she does not need to prove that the restraint limited competition.....Tying arrangements. A tying arrangement occurs when the seller of a product, service, or intangible (the "tying" product) conditions its sale on the buyers purchasing a second product, service, or intangible (the "tied" product) from the seller....Because tying arrangements limit buyers' freedom of choice and may exclude competitors, the law closely scrutinizes such agreements.”</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615771">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615771">14</a> by DOHMANN  JOHANN
		posted on 7/8/2006 at 12:51 AM
		</div>
		<div class="comment_text"><p>i have a hp 1400 I'VE HAD NOTHING BUT TROUBLE WITH IT ,NOW IT PRINTS OK BUT THE PICTURES ARE MOSTLY ORANGE,HOW DO I FIX THAT??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615777">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615777">15</a> by Dara Finnegan
		posted on 5/5/2008 at 7:42 PM
		</div>
		<div class="comment_text"><p>I've had an HP OfficeJet K80 for about 3 years and I've never had 1 problem with it.</p><p>_____________________________________________</p><p>Great printer toner and ink cartridge deals, discounts and coupons.  Also, check out the latest printer reviews and technology news. <br><a href="http://disq.us/url?url=http%3A%2F%2Fblog.concordsupplies.com%3AgzD8U2E4od_BviniQIYZ4NsMFuE&amp;cuid=3321886" rel="nofollow noopener" title="http://blog.concordsupplies.com">http://blog.concordsupplies...</a></p></div>
	</div>
</div>
		