
<div class="comment" id="c_1713742568">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742568">1</a> by Chad
		posted on 8/17/2012 at 10:49 PM
		</div>
		<div class="comment_text"><p>Be ready! Notifications will be a hot topic! Thanks again for doing these! I learned a ton last time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742575">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742575">2</a> by Raymond Camden
		posted on 8/17/2012 at 10:51 PM
		</div>
		<div class="comment_text"><p>Oh crap - I think last time we punted on that. Need to check into it again. :)</p></div>
	</div>
</div>
		