
<div class="comment" id="c_1713616178">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616178">1</a> by Peter Tilbrook
		posted on 9/17/2004 at 8:17 PM
		</div>
		<div class="comment_text"><p>I've actually started working on something along those lines here:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.actcfug.com%2Findex.cfm%3Ffuseaction%3DDocumentView%26DocumentID%3D5%3Aa5Gf0qgaKAC2wuArpBjjFqrmo08&amp;cuid=3321886" rel="nofollow noopener" title="http://www.actcfug.com/index.cfm?fuseaction=DocumentView&amp;DocumentID=5">http://www.actcfug.com/inde...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616193">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616193">2</a> by Harry Klein
		posted on 9/20/2004 at 9:26 AM
		</div>
		<div class="comment_text"><p>You can also find a good overview here:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.cielen.com%2Fcfmlhistory%2F%3AsYr0BZdA3rhexmhbV_x7VLfcLW0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.cielen.com/cfmlhistory/">http://www.cielen.com/cfmlh...</a></p></div>
	</div>
</div>
		