
<div class="comment" id="c_1704183834">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1704183834">1</a> by Raymond Camden
		posted on 11/20/2014 at 11:11 PM
		</div>
		<div class="comment_text"><p>This is Ray testing. Sorry. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1704194195">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1704194195">2</a> by Robert Zehnder
		posted on 11/20/2014 at 11:19 PM
		</div>
		<div class="comment_text"><p>Awesome :)</p></div>
	</div>
</div>
		