
<div class="comment" id="c_1713661124">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661124">1</a> by Andrew
		posted on 1/6/2007 at 12:36 AM
		</div>
		<div class="comment_text"><p>FYI...as of 2:30 PM eastern, the updater has not been posted to the Adobe website.  Does anyone know when the updater will be available for download?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661115">2</a> by Jerry hamby
		posted on 1/6/2007 at 12:48 AM
		</div>
		<div class="comment_text"><p>I would like to make a feature request for this "un-named" project. I need to create something similar for my high school reunion group. The project would have all the features you have mentioned with the addition of the following:</p><p>1- Master admin login feature (can create/edit/remove all contacts)<br>2- All members can login with their own separate userid and password (for viewing all contacts), but they would only be allowed to create and edit their contact information.</p><p>I guess this would be called a group contact program. Instead of it being "OneNote" it might be called "OneNote + Friends" :)</p><p>If your are interested and need my help, let me know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661126">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661126">3</a> by Brian Swartzfager
		posted on 1/6/2007 at 1:34 AM
		</div>
		<div class="comment_text"><p>(Laugh) Reader-generated scope creep already.</p><p>Ray, I look forward to seeing your app when it's ready.  It sounds like it would be a great example of the kinds of apps I would potentially use Flex to build and therefore a better learning resource than some of the more graphically-flashy Flex apps out there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661129">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661129">4</a> by Ali Daniali
		posted on 1/6/2007 at 6:05 AM
		</div>
		<div class="comment_text"><p>Would you consider adding voiceNote support? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661130">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661130">5</a> by Raymond Camden
		posted on 1/6/2007 at 7:11 AM
		</div>
		<div class="comment_text"><p>You people are insane. :) I promise it will go quicker if someone wants to support the dev work financially. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713661141">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713661141">6</a> by Sid Wing
		posted on 1/9/2007 at 11:51 PM
		</div>
		<div class="comment_text"><p>hate to say it, but welcome to the "freelance" world, Ray.  Everyone wants it all for "free" - :-)</p></div>
	</div>
</div>
		