
<div class="comment" id="c_1713652015">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652015">1</a> by Michael White
		posted on 4/20/2006 at 6:59 PM
		</div>
		<div class="comment_text"><p>screenshot on projects page shows flash version...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652008">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652008">2</a> by Raymond Camden
		posted on 4/20/2006 at 7:10 PM
		</div>
		<div class="comment_text"><p>I know, I know... ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652013">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652013">3</a> by Dan Sorensen
		posted on 4/20/2006 at 8:03 PM
		</div>
		<div class="comment_text"><p>2.0.2.104 installed smoothly. The new [+] feature is handy. I customized my layout.cfm to add a tooltip to the [+] link: title="Add new issue to #name#"</p><p>Could be overkill, but it's pretty nice now. :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652017">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652017">4</a> by Raymond Camden
		posted on 4/20/2006 at 8:11 PM
		</div>
		<div class="comment_text"><p>Nice idea. I just stole it and put it in source, but I probably won't udpate the zip for a while.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652018">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652018">5</a> by Jeff Bourassa
		posted on 4/29/2006 at 1:01 AM
		</div>
		<div class="comment_text"><p>How about a due date iade with the tasks?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652014">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652014">6</a> by Raymond Camden
		posted on 4/29/2006 at 1:11 AM
		</div>
		<div class="comment_text"><p>I've added Due Date to my TODO list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652021">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652021">7</a> by Edgar "egspoony" Gar
		posted on 5/1/2006 at 6:54 PM
		</div>
		<div class="comment_text"><p>Hey Ray... that [+] feature is handy... Thumbs up to whomever suggested it... :-P</p><p>Keep up the awesome work!</p></div>
	</div>
</div>
		