
<div class="comment" id="c_1713669459">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669459">1</a> by O?uz Demirkap?
		posted on 8/1/2007 at 10:18 PM
		</div>
		<div class="comment_text"><p>Congrats!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669464">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669464">2</a> by Max Hamby
		posted on 8/2/2007 at 12:17 AM
		</div>
		<div class="comment_text"><p>I love to see O?uz Demirkap? post comments just to see how badly his name is going to be massacred!</p><p>Is that wrong? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669465">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669465">3</a> by Raymond Camden
		posted on 8/2/2007 at 12:28 AM
		</div>
		<div class="comment_text"><p>It is. Working on stuff like that for BlogCFC 5.9.</p></div>
	</div>
</div>
		