
<div class="comment" id="c_1713735711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735711">1</a> by Peter Schmidt
		posted on 10/13/2011 at 9:37 PM
		</div>
		<div class="comment_text"><p>I try to execute the code you provided and got</p><p>The current user is not authorized to invoke this method.</p><p>Any Ideas??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735716">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735716">2</a> by Geoff B
		posted on 10/13/2011 at 9:47 PM
		</div>
		<div class="comment_text"><p>Peter, make sure you replace "admin" with your actual cfadmin password.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735712">3</a> by Peter Schmidt
		posted on 10/13/2011 at 10:14 PM
		</div>
		<div class="comment_text"><p>Thank you</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735713">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735713">4</a> by Mark Landmann
		posted on 10/14/2011 at 1:30 AM
		</div>
		<div class="comment_text"><p>Where are all these internal APIs defined.  I would like to access one specifically that turns OFF caching if it is on.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735715">5</a> by Raymond Camden
		posted on 10/14/2011 at 1:58 AM
		</div>
		<div class="comment_text"><p>This isn't an internal API. It's a documented feature. Go to /CFIDE/adminapi and you can see the CFCs there.</p><p>The official docs are here: <a href="http://disq.us/url?url=http%3A%2F%2Fhelp.adobe.com%2Fen_US%2FColdFusion%2F9.0%2FAdmin%2FWSc3ff6d0ea77859461172e0811cbf364104-7fcf.html%3A6SOBfL4NePOBnEEdw3jGQ2GyJfU&amp;cuid=3321886" rel="nofollow noopener" title="http://help.adobe.com/en_US/ColdFusion/9.0/Admin/WSc3ff6d0ea77859461172e0811cbf364104-7fcf.html">http://help.adobe.com/en_US...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735725">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735725">6</a> by Mike Henke
		posted on 10/14/2011 at 2:26 AM
		</div>
		<div class="comment_text"><p>@cfaddict mentioned also application.getApplicationSettings() will return a struct w/ all of your application settings or new Application() - new instance.</p><p>And this is the link I used to see all the method documentation for the cfc's <a href="http://disq.us/url?url=http%3A%2F%2Fwww.cfexecute.com%2Fadmin-api-documentation%2F%3A-QBsSIn_Q7B5_Rny7nKndLx7NRQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.cfexecute.com/admin-api-documentation/">http://www.cfexecute.com/ad...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735726">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735726">7</a> by Sooraj
		posted on 10/14/2011 at 10:46 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>How do we implement the same for Railo?</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713735724">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713735724">8</a> by Raymond Camden
		posted on 10/14/2011 at 2:34 PM
		</div>
		<div class="comment_text"><p>I don't use Railo.</p></div>
	</div>
</div>
		