
<div class="comment" id="c_1714082999">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082999">1</a> by Adam Austin
		posted on 8/20/2014 at 8:20 PM
		</div>
		<div class="comment_text"><p>Well, I just got back from GenCon and I happen to be perusing your blog when I found this little nugget based on tabletop gaming.  I cannot tell you how many games I played, much less the names (such as Panamax, Caverna, etc) but the one that sticks out the most is Tzolk'in: The Mayan Calendar.  A. MAZE. ZING. It's a worker placement game that challenges your mind more than chess.  I think I'm gonna order it now...  (next stop: Spiel 2014 in Essen, Germany)</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coolstuffinc.com%2Fp%2F183431%3ANabkbnHHKX9vsd-DPrPS-KOvals&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coolstuffinc.com/p/183431">http://www.coolstuffinc.com...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083005">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083005">2</a> by Raymond Camden
		posted on 8/20/2014 at 9:17 PM
		</div>
		<div class="comment_text"><p>Thanks Adam - I added it to my wish list.</p></div>
	</div>
</div>
		