
<div class="comment" id="c_1713679243">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679243">1</a> by Tony Garcia
		posted on 4/8/2008 at 3:26 PM
		</div>
		<div class="comment_text"><p>Hmmm... are you sure? Your "About Me" page says you're still 33 ;-)</p><p>Happy birthday, Ray!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679265">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679265">2</a> by Raymond Camden
		posted on 4/8/2008 at 3:28 PM
		</div>
		<div class="comment_text"><p>Oops. Fixed. :) Thank goodness I have a good CMS behind my blog. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679268">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679268">3</a> by Trond Ulseth
		posted on 4/8/2008 at 3:40 PM
		</div>
		<div class="comment_text"><p>Happy Birthday!!!</p><p>I turned 35 in december and it was like "damn I'm closer to 40 than 30 now - maybe I'm growing up after all :)"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679267">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679267">4</a> by Akira
		posted on 4/8/2008 at 3:42 PM
		</div>
		<div class="comment_text"><p>Happy Birthday! :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679266">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679266">5</a> by C.Gratz
		posted on 4/8/2008 at 3:52 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray....Hope you have a great day and get alls sorts of Star Wars goodness.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679255">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679255">6</a> by Srinivas.VK
		posted on 4/8/2008 at 3:56 PM
		</div>
		<div class="comment_text"><p>Happy Birthday to RaY.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679251">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679251">7</a> by Raul Riera
		posted on 4/8/2008 at 4:17 PM
		</div>
		<div class="comment_text"><p>Happy Birthday, I turn 26 on September 11 (yeah I know)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679254">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679254">8</a> by joshua cyr
		posted on 4/8/2008 at 4:25 PM
		</div>
		<div class="comment_text"><p>Congrats!  I hit 34 on Sunday.  I hear once we hit 40 we get a mount.... err new car.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679253">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679253">9</a> by Gary Gilbert
		posted on 4/8/2008 at 4:27 PM
		</div>
		<div class="comment_text"><p>The higher levels seem to come faster from 35 onwards, but not any easier.</p><p>Happy B-day</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679252">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679252">10</a> by Joerg Zimmer
		posted on 4/8/2008 at 4:28 PM
		</div>
		<div class="comment_text"><p>Happy birthday Ray !!! Have a pleasant day!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679256">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679256">11</a> by Yves Arsenault
		posted on 4/8/2008 at 4:35 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray. I'm not far behind. ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679262">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679262">12</a> by Nathan Mische
		posted on 4/8/2008 at 4:40 PM
		</div>
		<div class="comment_text"><p>Happy Birthday!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679260">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679260">13</a> by Jared Legg
		posted on 4/8/2008 at 4:46 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679257">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679257">14</a> by Todd Rafferty
		posted on 4/8/2008 at 4:50 PM
		</div>
		<div class="comment_text"><p>Thank goodness I have you to check out level 35 before I approach it in 6 months.  You can powerlevel me thru teh dungeons, kk?</p><p>Happy Birthday. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679259">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679259">15</a> by Sam Farmer
		posted on 4/8/2008 at 4:51 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679261">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679261">16</a> by Daniel Gilbert
		posted on 4/8/2008 at 4:57 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679263">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679263">17</a> by Ben Nadel
		posted on 4/8/2008 at 5:00 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679258">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679258">18</a> by Rob Brooks-Bilson
		posted on 4/8/2008 at 5:09 PM
		</div>
		<div class="comment_text"><p>Congrats Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679264">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679264">19</a> by Lance
		posted on 4/8/2008 at 5:13 PM
		</div>
		<div class="comment_text"><p>Happy birthday, Ray!!  Have a great one.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679270">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679270">20</a> by Greg Nilsen
		posted on 4/8/2008 at 5:14 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679273">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679273">21</a> by Will Swain
		posted on 4/8/2008 at 5:33 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray. Hope you'll be taking it easy today.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679271">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679271">22</a> by Raymond Camden
		posted on 4/8/2008 at 5:34 PM
		</div>
		<div class="comment_text"><p>@All - Thanks!<br>@Will - Yep. I had planned on picking up The Force Unleashed, but I somehow missed that it got delayed till September. So after lunch today I'll just kill some Nazis in Fall of Liberty.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679274">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679274">23</a> by shaunw
		posted on 4/8/2008 at 5:37 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray!  Keep grinding!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679272">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679272">24</a> by Steve Withington
		posted on 4/8/2008 at 5:54 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Jedi Master!  May the Force be with you always!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679275">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679275">25</a> by Jason Dean
		posted on 4/8/2008 at 6:10 PM
		</div>
		<div class="comment_text"><p>Happy Birthday, Ray. I will hit 35 in June. I actually just realized that this morning. Thanks ;)</p><p>Hope all goes well. See you @ cf.Objective()</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679279">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679279">26</a> by Ray Buechler
		posted on 4/8/2008 at 6:12 PM
		</div>
		<div class="comment_text"><p>I hit level 41 today myself. ;)</p><p>Happy Birthday, Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679276">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679276">27</a> by Raymond Camden
		posted on 4/8/2008 at 6:33 PM
		</div>
		<div class="comment_text"><p>@Ray - It must be 'Ray Day' ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679282">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679282">28</a> by Gary Funk
		posted on 4/8/2008 at 6:44 PM
		</div>
		<div class="comment_text"><p>@Ray. I'd like to say I remember when I hit 35, but that was so long ago and I can't remember that far back. On another note, My wife and I are expecting our forth child in August. Since the first three are boys, I am very happy to report that this on is a girl.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679277">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679277">29</a> by Sean Corfield
		posted on 4/8/2008 at 6:55 PM
		</div>
		<div class="comment_text"><p>I'm not sure I remember 35 - it was nearly 11 years ago.</p><p>Happy Birthday young man! See you at cf.Objective()!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679283">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679283">30</a> by David McGuigan
		posted on 4/8/2008 at 8:17 PM
		</div>
		<div class="comment_text"><p>Pleasant age milestone, young jedi. May the force not be with you, such that you can control your bladder well into your 70's.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679284">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679284">31</a> by Seth Aaronson
		posted on 4/8/2008 at 8:23 PM
		</div>
		<div class="comment_text"><p>Happy anniversary of your first day on Earth.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679278">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679278">32</a> by Patrick
		posted on 4/8/2008 at 8:40 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray, hope its a good one!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679280">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679280">33</a> by Seth Bienek
		posted on 4/8/2008 at 9:06 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray!</p><p>I turned 34 last Friday, so I'm right behind you.. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679281">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679281">34</a> by Akbar
		posted on 4/8/2008 at 9:10 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679289">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679289">35</a> by noname
		posted on 4/8/2008 at 9:14 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray, from all us nonamers!  lol</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679285">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679285">36</a> by Mark Mazelin
		posted on 4/8/2008 at 9:21 PM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray! So, how's it feel? My 35th is coming in 3 months and 3 days...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679286">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679286">37</a> by Mark Mazelin
		posted on 4/8/2008 at 9:22 PM
		</div>
		<div class="comment_text"><p>Mmm, must be getting old already. That would be _4_ months and 3 days.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679288">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679288">38</a> by Sid Wing
		posted on 4/9/2008 at 12:45 AM
		</div>
		<div class="comment_text"><p>Happy Birthday! But you still haven't caught up to me ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679287">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679287">39</a> by Montreal
		posted on 4/9/2008 at 2:44 AM
		</div>
		<div class="comment_text"><p>Happy Birthday Ray! Wish I was 35 again. See you at cfobjective().</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679292">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679292">40</a> by salvatore fusto
		posted on 4/9/2008 at 10:47 AM
		</div>
		<div class="comment_text"><p>Ray,<br>Skype advised me yesterday<br>Happy Birthday<br>salvatore</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713679291">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713679291">41</a> by Luca
		posted on 4/9/2008 at 6:11 PM
		</div>
		<div class="comment_text"><p>happy birthday Ray from Tuscany !</p></div>
	</div>
</div>
		