
<div class="comment" id="c_1713649830">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649830">1</a> by jj
		posted on 2/6/2006 at 7:41 PM
		</div>
		<div class="comment_text"><p>Uh oh... there goes my styling :(</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649818">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649818">2</a> by jeff
		posted on 2/6/2006 at 8:09 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>I am working on a website which incorporates your blogcfc product, which is great.  However, there are a few modifications, that i need to make, so that it fits INSIDE of our template, instead of a standalone page like the way it comes out of the box.</p><p>I find myself having to make these corrections every time i upgrade.  Do you have any suggestions for me that might make my life easier?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649831">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649831">3</a> by john smoltz
		posted on 2/6/2006 at 8:27 PM
		</div>
		<div class="comment_text"><p>Use a robot - definitely a robot.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649833">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649833">4</a> by jeff
		posted on 2/6/2006 at 8:28 PM
		</div>
		<div class="comment_text"><p>Uh, can you be a little more specific.  I'm unfamiliar with that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649836">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649836">5</a> by mikeD
		posted on 2/6/2006 at 9:08 PM
		</div>
		<div class="comment_text"><p>I use a helper monkey.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649835">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649835">6</a> by Raymond Camden
		posted on 2/6/2006 at 9:15 PM
		</div>
		<div class="comment_text"><p>jeff - No real advice except maybe to get a good diff tool. Also, my readme files will normally tell you which files to worry about.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713649834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713649834">7</a> by Mujeebur Rahmansaher
		posted on 2/16/2006 at 12:00 PM
		</div>
		<div class="comment_text"><p>Please Have a look at Siraj Sayeed's Blog which is using BLOGCFC. He has done an excellent job in creating a nice theme for BLOGCFC community.Please have a look at <a href="http://disq.us/url?url=http%3A%2F%2Fwww.sirajsayeed.com%3AdiD-k0mvm956l_Lvg3rmfPuNlBg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.sirajsayeed.com">http://www.sirajsayeed.com</a> . I am sure he is going to make it availabe for download as well</p></div>
	</div>
</div>
		