
<div class="comment" id="c_3342957344">
	<div>
		<img src="https://disqus.com/api/users/avatars/krhoyt.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3342957344">1</a> by Kevin Hoyt
		posted on 6/5/2017 at 9:47 PM
		</div>
		<div class="comment_text"><p>You can also click on the activation ID in the web-based tooling to get this information. You know, if you're CLI-challenged.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3343001490">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3343001490">2</a> (In reply to <a href="#c_3342957344">#1</a>) by Raymond Camden
		posted on 6/5/2017 at 10:04 PM
		</div>
		<div class="comment_text"><p>Oh lord - thanks. I forgot to mention that. I *am* planning a comprehensive blog post on the UI stuff. I keep putting it off but it definitely has some great features.</p></div>
	</div>
</div>
		