
<div class="comment" id="c_1713737985">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737985">1</a> by Ben Nadel
		posted on 1/6/2012 at 8:40 PM
		</div>
		<div class="comment_text"><p>That's pretty exciting! There are a ton of functions in XPath that look useful. Granted, as you said, JSON is way cooler than XML. But, when you need to use XML, more robust XPath is gonna be sweet!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737993">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737993">2</a> by Raymond Camden
		posted on 1/6/2012 at 8:52 PM
		</div>
		<div class="comment_text"><p>It makes me wonder - how do folks search JSON? I mean - I could see turning into a CFML query and doing a QOQ, but XPath is _much_ more direct in this case. (To be fair though, a "good" service would let you do searches/filters/etc before returning the data.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737996">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737996">3</a> by Dan G. Switzer, II
		posted on 1/6/2012 at 8:56 PM
		</div>
		<div class="comment_text"><p>@Raymond:</p><p>Just a CSS suggestion, but it would be extremely useful if you updated your CSS to style anchor links, well like links (at least w/in the context of a blog article text.)</p><p>Right now they're styled like normal text and very easy to overlook. At bare minimum applying some kind of alternative text styling would help (bold, italics, alt color, etc.)</p><p>Maybe you're trying to make them obscure, but I just find it frustrating.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737998">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737998">4</a> by Raymond Camden
		posted on 1/6/2012 at 8:57 PM
		</div>
		<div class="comment_text"><p>It looks like just an issue with links in ULs. Will fix. (Later... ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737995">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737995">5</a> by Ben Nadel
		posted on 1/6/2012 at 9:04 PM
		</div>
		<div class="comment_text"><p>re: Searching JSON, it's an interesting question. I think people have dabbled with "oPath" type things for searching objects. But, for the most part, the JSON data that I deal with doesn't usually need searching. Maybe XML just lends better to a time where responses were less uniform? Even APIs that I see now will return consistent objects, even if certain things failed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737997">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737997">6</a> by Jeff Coughlin
		posted on 1/7/2012 at 4:22 AM
		</div>
		<div class="comment_text"><p>I believe there was a solution 3 or 4 years ago called JSONPath.  Haven't played with it since then.  I think it was originally written in js though, but was pretty fast.  Probably wouldn't be difficult to convert to java or CF.  Only problem is whether or not it's a standard or just a cult following :)</p></div>
	</div>
</div>
		