
<div class="comment" id="c_1713737971">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737971">1</a> by Todd Sharp
		posted on 1/6/2012 at 12:59 AM
		</div>
		<div class="comment_text"><p>Wow, you know how to read?!</p><p>;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737984">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737984">2</a> by Dave Ferguson
		posted on 1/6/2012 at 1:01 AM
		</div>
		<div class="comment_text"><p>Only 18 more to go... ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737987">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737987">3</a> by Raymond Camden
		posted on 1/6/2012 at 1:07 AM
		</div>
		<div class="comment_text"><p>18 more what?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737986">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737986">4</a> by Raymond Camden
		posted on 1/6/2012 at 1:07 AM
		</div>
		<div class="comment_text"><p>Oh duh. Look - I'm helping.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737989">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737989">5</a> by Matt Busche
		posted on 1/6/2012 at 5:58 AM
		</div>
		<div class="comment_text"><p>I use <a href="http://disq.us/url?url=http%3A%2F%2Fgoodreads.com%3AurUa_N_yByXWgU0N0OC1gLEU488&amp;cuid=3321886" rel="nofollow noopener" title="goodreads.com">goodreads.com</a> to track my read books, but bagcheck looks cool as well</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737968">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737968">6</a> by Phillip Senn
		posted on 1/6/2012 at 8:08 PM
		</div>
		<div class="comment_text"><p>I just signed up to bagcheck and then I followed a link, and then another and then another.<br>This whole Internet thing...I think it's gonna be big.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737969">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737969">7</a> by Raymond Camden
		posted on 1/6/2012 at 8:33 PM
		</div>
		<div class="comment_text"><p>@Phillip: The only way the Internet can take off is if gets porn. I've looked but cannot find any porn.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737970">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737970">8</a> by Pete
		posted on 1/9/2012 at 7:13 PM
		</div>
		<div class="comment_text"><p>Actually Ray I'm pleased you've posted your reading list, I've already bought some of your recommendations (Robopocalypse and Embassy town) so I'll probably check your list out for other books I might like.</p><p>You should post your game play and movie list as well.</p><p>Also I know this is the wrong post for it, but I like the new skin.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737972">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737972">9</a> by Raymond Camden
		posted on 1/9/2012 at 7:15 PM
		</div>
		<div class="comment_text"><p>Glad to share. I started a new Bagcheck list for 2012 - only one book there now.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fbagcheck.com%2Fbag%2F3628-my-2012-reading-list%3ABK00BTJW-gA72ENIMR2Ok7f8dbI&amp;cuid=3321886" rel="nofollow noopener" title="http://bagcheck.com/bag/3628-my-2012-reading-list">http://bagcheck.com/bag/362...</a></p><p>As for games and movies - I normally tweet reviews on the movies I see and post game reviews here, so I don't think I'll make a list just yet.</p><p>I'm currently playing Skyrim (100 hours in), and just began Gears of War 3.</p></div>
	</div>
</div>
		