
<div class="comment" id="c_1923114694">
	<div>
		<img src="https://disqus.com/api/users/avatars/danskaggs.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1923114694">1</a> by Dan Skaggs
		posted on 3/23/2015 at 12:09 PM
		</div>
		<div class="comment_text"><p>I only use the full-screen view when I have my laptop "undocked" from Thunderbolt monitors on my desk and then usually only for IntelliJ. Double clicking the title bar doesn't seem to work in all apps for me. For instance Chrome doesn't have enough above the tabs for me to really double click on. My RSS reader (ReadKit) doesn't seem to work either.  However things like Slack, Sublime Text and Mail all work. So it seems like *if* the application actually has the title at the top of its Window, then it works. Still wish they'd left the full-screen behavior the way it was previously since the app title thing is kind of hit or miss.</p></div>
	</div>
</div>
		