
<div class="comment" id="c_1713624032">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624032">1</a> by bgoose
		posted on 1/9/2006 at 5:19 PM
		</div>
		<div class="comment_text"><p>What is the picture of that looks like a wet ball? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624033">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624033">2</a> by Rob Brooks-Bilson
		posted on 1/9/2006 at 6:54 PM
		</div>
		<div class="comment_text"><p>The pic came with the template.  Perhaps someone out there with design skills can help out with something more "CF" that fits the space?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624030">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624030">3</a> by Raymond Camden
		posted on 1/9/2006 at 7:07 PM
		</div>
		<div class="comment_text"><p>If someone does, I'd be happy to change it. I'm ok with the picture, but it doesn't really matter much to me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624034">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624034">4</a> by Raymond Camden
		posted on 1/9/2006 at 7:09 PM
		</div>
		<div class="comment_text"><p>Just an FYI - I noticed I can't post a new comment to one entry. Definitely a bug there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624029">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624029">5</a> by Raymond Camden
		posted on 1/9/2006 at 7:16 PM
		</div>
		<div class="comment_text"><p>Bug fixed. Duh. Forgot to htmlEditFormat the comments. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624037">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624037">6</a> by Kyle Hayes
		posted on 1/9/2006 at 9:18 PM
		</div>
		<div class="comment_text"><p>I created a graphic for the cookbook to replace the wet ball if you are interested. Email me to let me know. Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624035">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624035">7</a> by Maxx
		posted on 1/9/2006 at 9:43 PM
		</div>
		<div class="comment_text"><p>FYI: more rss issues...</p><p>XML Parsing Error: not well-formed<br>Location: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusioncookbook.com%2Frss%3Aw7moCUfHaO4hxDwBeh50XqHfajI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusioncookbook.com/rss">http://www.coldfusioncookbo...</a><br>Line Number 190, Column 18:&amp;lt;cfquery name=myTest datasource=...&lt;/description&gt;<br>-----------------^</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624036">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624036">8</a> by Raymond Camden
		posted on 1/9/2006 at 10:11 PM
		</div>
		<div class="comment_text"><p>Fixed. Darn smart quotes.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624042">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624042">9</a> by Raymond Camden
		posted on 1/10/2006 at 12:02 AM
		</div>
		<div class="comment_text"><p>Kyel's new header is up - and it ROCKS!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624039">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624039">10</a> by Grant
		posted on 1/10/2006 at 12:03 AM
		</div>
		<div class="comment_text"><p>Could you make the links look like links?  They are currently a pale blue-gray (non-underlined) that is hard to distinguish from regular text.  You shouldn't have to put your mouse over every word on the page to see what's a link.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624040">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624040">11</a> by charlie griefer
		posted on 1/10/2006 at 12:24 AM
		</div>
		<div class="comment_text"><p>/me makes mental note to call Kyle when he needs design work done.</p><p>VERY nice :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624043">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624043">12</a> by scott
		posted on 1/10/2006 at 3:43 AM
		</div>
		<div class="comment_text"><p>great googly-moogly....looks great</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624038">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624038">13</a> by Raymond Camden
		posted on 1/10/2006 at 3:45 AM
		</div>
		<div class="comment_text"><p>And the design is all mine!!!! Mu-hahaha. No, seriously, thank Kyle for the logo and Andreas for the layout.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713624041">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713624041">14</a> by Aboo Mujaahideen
		posted on 1/12/2006 at 2:37 AM
		</div>
		<div class="comment_text"><p>Nice project.  I was wondering if anyone could do something like an answers site for ColdFusion.  This is the closest thing to it.  But I'm speaking more like an Experts Exchange site for ColdFusion.  A person submits a question and people in the community help answer.  There are plenty of newbies out there wondering how to do things in ColdFusion who lack the knowledge and experience of a seasoned ColdFusion developer.</p></div>
	</div>
</div>
		