
<div class="comment" id="c_1713663111">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663111">1</a> by Cutter
		posted on 3/14/2007 at 4:32 PM
		</div>
		<div class="comment_text"><p>Yep, I have seen that. I've also seen, within T-bird's RSS reader, that clicking on a post can take a long time to load in the view pane (especially that camdenfamily feed;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663113">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663113">2</a> by DK
		posted on 3/14/2007 at 5:06 PM
		</div>
		<div class="comment_text"><p>The last time this happened to me I removed all my extensions from both and it went away. It turned out one had a memory leak, and I hadn't updated it in awhile.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663119">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663119">3</a> by Sam
		posted on 3/14/2007 at 7:29 PM
		</div>
		<div class="comment_text"><p>I haven't seen that problem.  I've noticed FF takes a while to load the first time I load it, but that happens regardless of where I click a link from or if I open it by icon.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663108">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663108">4</a> by Tom Mollerus
		posted on 3/14/2007 at 8:09 PM
		</div>
		<div class="comment_text"><p>Have you compressed your folders in a while? I found that I had all sorts of problems once my folders were extremely large and uncompressed (In Thunderbird, emails are stored together in one text file for each folder you have; "compression" refers to removal of the line breaks left in the files when you delete emails).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663120">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663120">5</a> by Matt Osbun
		posted on 3/14/2007 at 8:09 PM
		</div>
		<div class="comment_text"><p>Is that what's going on?  I had just assumed that some extension or setting I had was blocking this behavior.  Of course, I never had the patience to wait 30-45 seconds to see if anything would happen.  I would just Right-Click, Copy Link Location, and paste into Firefox.</p><p>So, I guess that yeah, I'm seeing it too.  :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663117">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663117">6</a> by Amol
		posted on 3/29/2007 at 5:56 AM
		</div>
		<div class="comment_text"><p>Raymond,</p><p>Did compressing the folders, work? Did it speed up T-Bird?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663114">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663114">7</a> by Raymond Camden
		posted on 3/29/2007 at 7:40 AM
		</div>
		<div class="comment_text"><p>Nope.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663121">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663121">8</a> by Nico M
		posted on 6/27/2007 at 10:23 AM
		</div>
		<div class="comment_text"><p>Did you manage to solve this problem?   I am now suffering from the exact same thing.  Very annoying.   Any help would be much appreciated :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663123">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663123">9</a> by Raymond Camden
		posted on 6/27/2007 at 2:44 PM
		</div>
		<div class="comment_text"><p>I fixed it by switching to OS X. ;) Seriously - it must have been something bad in the registry or whatever. I don't have it in OS X nor my virtual Windows installs.</p></div>
	</div>
</div>
		