
<div class="comment" id="c_1714080744">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080744">1</a> by Phillip Senn
		posted on 11/9/2013 at 9:24 PM
		</div>
		<div class="comment_text"><p>Bleh.  I spent about an hour trying to install Brackets and ColdFusion on my Windows 8 machine this morning.</p><p>I got stuck with windows making wwwroot read only.</p><p>I'm going to work on something else now (error trapping).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080729">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080729">2</a> by Raymond Camden
		posted on 11/9/2013 at 9:38 PM
		</div>
		<div class="comment_text"><p>Err, so did Brackets fail or ColdFusion? I've run Brackets on Win8 with no problem.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080742">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080742">3</a> by Phillip Senn
		posted on 11/9/2013 at 10:28 PM
		</div>
		<div class="comment_text"><p>Actually, it was IIS that failed me.  <br>I had to run appwiz.cpl to turn IIS on, then I had to turn on ASP.NET, CGI and ISAPI before installing ColdFusion.</p><p>It created inetpub\wwwroot, but made it read only.</p></div>
	</div>
</div>
		