
<div class="comment" id="c_1713742757">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742757">1</a> by Simon MacDonald
		posted on 8/24/2012 at 5:23 PM
		</div>
		<div class="comment_text"><p>Yeah, this is some pretty good work by the build team that Fil started over a year ago with his Hydra project. I prefer the analogy to the multi-headed dragon versus water but I'm not in marketing.</p><p>Anyway, everything needs more cowbell:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.laughness.com%2Fsnl-gotta-have-more-cowbell-original-skit.1126%3Agd8u0AoZYBT-tw1c3w2bfeUG0jw&amp;cuid=3321886" rel="nofollow noopener" title="http://www.laughness.com/snl-gotta-have-more-cowbell-original-skit.1126">http://www.laughness.com/sn...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742761">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742761">2</a> by Patrick Whittingham
		posted on 8/27/2012 at 7:00 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Is this a feature of build.phonegap only or does it apply to other site like Google play?</p><p>Pat</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742758">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742758">3</a> by Raymond Camden
		posted on 8/27/2012 at 7:01 PM
		</div>
		<div class="comment_text"><p>Patrick: This is a feature of <a href="http://disq.us/url?url=http%3A%2F%2Fbuild.phonegap.com%3A3uSHzxAbk16923y7ubV1pPbxE78&amp;cuid=3321886" rel="nofollow noopener" title="build.phonegap.com">build.phonegap.com</a>. The _end_ result is an app that can automatically update on load. But this is NOT the app you would deploy to Google Play or Apple's AppStore.</p><p>Rather - you would use this during development to make it easier for your testers to get the latest bits.</p><p>Does that distinction make sense?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742762">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742762">4</a> by Pete
		posted on 8/28/2012 at 1:55 PM
		</div>
		<div class="comment_text"><p>Have you heard of Test Flight Ray?<br><a href="https://disq.us/url?url=https%3A%2F%2Ftestflightapp.com%2Fdashboard%2F%3A_oS0QpDaoAquFjYfgDLKApzYlPY&amp;cuid=3321886" rel="nofollow noopener" title="https://testflightapp.com/dashboard/">https://testflightapp.com/d...</a></p><p>They do something pretty similar but just with iOS apps, they're pretty brilliant, so I'm glad to see phone gap build doing something similar.</p><p>Test flight works with native apps (As it's just uploading the ipa file), but for Phonegap stuff I guess I'll be switching to Hydration.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742759">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742759">5</a> by Raymond Camden
		posted on 8/28/2012 at 5:49 PM
		</div>
		<div class="comment_text"><p>Yep, heard of it, but haven't used it. Also, the Brightcove stuff (which I reviewed a while ago) also has something a bit similar.</p><p>But this is better because we own it.</p><p>(Kidding.)</p><p>(Mostly.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4790820800">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_OrIhm5tGbT.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4790820800">6</a> by Mary Daniel
		posted on 2/10/2020 at 5:48 PM
		</div>
		<div class="comment_text"><p>Useless feature. Hydration does not work, and App gets stuck at a grey screen.</p></div>
	</div>
</div>
		