
<div class="comment" id="c_1713678574">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678574">1</a> by Sam Farmer
		posted on 3/27/2008 at 8:37 PM
		</div>
		<div class="comment_text"><p>You got some cute kids there, Ray!</p><p>Not that impressed with Photoshop Express; its pretty ugly, slow, and asks for a certificate when clicking on that link.  Feels very beta-ish to me.</p><p>As an online service as software its a very interesting move.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678566">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678566">2</a> by Raymond Camden
		posted on 3/27/2008 at 8:43 PM
		</div>
		<div class="comment_text"><p>Well to be fair - it _is_ beta. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678560">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678560">3</a> by Tom Chiverton
		posted on 3/27/2008 at 8:43 PM
		</div>
		<div class="comment_text"><p>Ray, at the bottom of the FireFox 3 error screen there should be a link to 'add an exception'.<br>There is in my beta 2, anyway.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678563">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678563">4</a> by Steve Withington
		posted on 3/27/2008 at 11:47 PM
		</div>
		<div class="comment_text"><p>After reading your post, I had to go, setup an account and play around a little.  I found it easy to use (although a little sluggish).  I even played a bit with the editing tools, which were also easy to use.  Yet another avenue for people to share photos with their family and friends.  A great start, and I know there is much more potential for this application.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678562">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678562">5</a> by Mikkel Johansen
		posted on 3/28/2008 at 2:43 AM
		</div>
		<div class="comment_text"><p>Nice 3D browser, but very slow (I know it's beta).</p><p>Take a look at PicLens (cooliris) a very cool picture browser, it works with a lot of picture-sites (picasaweb, flickr, yahoo, google image search etc.).</p><p>Make sure to download the 1.6 version. Not yet available for Safari :-(</p><p>Get it here: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.piclens.com%3Adw-m61pnuHqE7k30run6S6UqzFw&amp;cuid=3321886" rel="nofollow noopener" title="www.piclens.com">www.piclens.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678567">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678567">6</a> by Tom Chiverton
		posted on 3/28/2008 at 1:18 PM
		</div>
		<div class="comment_text"><p>It's also interesting to ponder that Adobe now has a whole online office suite...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678565">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678565">7</a> by Akira
		posted on 3/31/2008 at 7:42 PM
		</div>
		<div class="comment_text"><p>I haven't visited the site yet, but it looks cool. I did see this article on /., apparently there are EULA problems?</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fyro.slashdot.org%2Fyro%2F08%2F03%2F30%2F1628225.shtml%3Ag1QhfVPZxHD_sBVXEJMesTFNL3Y&amp;cuid=3321886" rel="nofollow noopener" title="http://yro.slashdot.org/yro/08/03/30/1628225.shtml">http://yro.slashdot.org/yro...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678557">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678557">8</a> by Raymond Camden
		posted on 3/31/2008 at 8:00 PM
		</div>
		<div class="comment_text"><p>Yeah, I saw that. Looks like a simple mistake really.</p></div>
	</div>
</div>
		