
<div class="comment" id="c_1713742721">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742721">1</a> by Mark
		posted on 8/21/2012 at 5:05 PM
		</div>
		<div class="comment_text"><p>There is no information on how to apply for the jobs in Maryland.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742727">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742727">2</a> by Raymond Camden
		posted on 8/21/2012 at 6:36 PM
		</div>
		<div class="comment_text"><p>Please see the last paragraph. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742712">3</a> by Mark
		posted on 8/21/2012 at 6:45 PM
		</div>
		<div class="comment_text"><p>I'm missing something. In the Word .doc there is only one parapgraph and then lots of bullets. The bullets are about the Education/Experience requirements.</p><p>The last paragraph of the blog post is "The second position was sent to me as a Word doc - so I've attached it to the blog entry." The paragraph before that appears to be about the position in AZ, not MD. Is that what I am missing? Is it the same contact info for BOTH positions?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742723">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742723">4</a> by Raymond Camden
		posted on 8/21/2012 at 6:47 PM
		</div>
		<div class="comment_text"><p>In the word doc, the second pragraph is a list of positions. You don't see that?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742722">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742722">5</a> by Mark
		posted on 8/21/2012 at 6:51 PM
		</div>
		<div class="comment_text"><p>I'm looking at the .doc now. The first (only) parapgraph is labeled "Overview". Then there is a section labled "Positions include:" followed by three bullet points with titles and cities. No email address. No contact information.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742729">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742729">6</a> by Raymond Camden
		posted on 8/21/2012 at 6:54 PM
		</div>
		<div class="comment_text"><p>Oh I'm sorry - I misread you. I will ping the person right now and have them post a comment.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742733">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742733">7</a> by Mark
		posted on 8/21/2012 at 6:56 PM
		</div>
		<div class="comment_text"><p>Many Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742728">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742728">8</a> by Bill Davidson
		posted on 8/21/2012 at 7:27 PM
		</div>
		<div class="comment_text"><p>I apologize - I sent the DOC to Ray without contact info. First - yes - there are SEVERAL positions open.  Depending on strength of the candidate and possibly location preference (College Park vs. Rockville) would dictate where they would be.  We are really building out our CF team and looking for the best!</p><p>Please contact Nicole Allio to apply: nallio@gnsi.com</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742731">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742731">9</a> by Bill Davidson
		posted on 8/21/2012 at 7:31 PM
		</div>
		<div class="comment_text"><p>Also, please let Nicole (and me if I interview you) know that you came from Ray's blog!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742734">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742734">10</a> by Ken Caldwell
		posted on 8/22/2012 at 3:10 AM
		</div>
		<div class="comment_text"><p>Bill,<br>Taking applicants from overseas?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742730">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742730">11</a> by Bill Davidson
		posted on 9/17/2012 at 6:56 AM
		</div>
		<div class="comment_text"><p>Ken - the job is on-location in the US, but I am not opposed to doing initial interviews over the phone/skype.    I am fairly certain we don't have any relocation packages.</p><p>Please submit your resume!</p><p>We still have several positions open and if you are reading this blog you are likely a good candidate! :)   It's a great company.  We have a lot of new ColdFusion work starting RIGHT NOW.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742732">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742732">12</a> by Swapnil
		posted on 10/10/2012 at 8:05 PM
		</div>
		<div class="comment_text"><p>Any opportunity for Indian guys??</p></div>
	</div>
</div>
		