
<div class="comment" id="c_1713711100">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711100">1</a> by Glyn Jackson
		posted on 12/30/2008 at 10:54 PM
		</div>
		<div class="comment_text"><p>The work Brian Meloche is doing with the podcasts are excellent I am glad he has got the PC sorted now I look forward to his posts.</p></div>
	</div>
</div>
		