
<div class="comment" id="c_1713673950">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673950">1</a> by Ian
		posted on 11/3/2007 at 11:57 PM
		</div>
		<div class="comment_text"><p>how do you get IE to recognize a feed link like the one on your page? Clicking it gives a page not found error in IE.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673957">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673957">2</a> by Raymond Camden
		posted on 11/4/2007 at 1:05 AM
		</div>
		<div class="comment_text"><p>Thats two questions. WHen you say - get IE to recognize a feed link. That's just a link tag:</p><p>&lt;link rel="alternate" type="application/rss+xml" title="RSS" href="<a href="http://disq.us/url?url=http%3A%2F%2Ffeeds.feedburner.com%2FRaymondCamdensColdfusionBlog%3AnzK9XwIeRKezL04qv_G4nQ6RQfE&amp;cuid=3321886" rel="nofollow noopener" title="http://feeds.feedburner.com/RaymondCamdensColdfusionBlog">http://feeds.feedburner.com...</a>" /&gt;</p><p>IE7 recognizes it.</p><p>As for page not found - not sure what to say. That's a valid URL.</p></div>
	</div>
</div>
		