
<div class="comment" id="c_1713669404">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669404">1</a> by Gary Funk
		posted on 7/31/2007 at 4:31 AM
		</div>
		<div class="comment_text"><p>Check the email headers and see what IP address the mail came from. Then just go to that website and see what you get.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669402">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669402">2</a> by Dustin
		posted on 7/31/2007 at 6:19 PM
		</div>
		<div class="comment_text"><p>You could try doing a reverse DNS lookup using IP out of the email header. You should be able to easily find an online utility to do it.</p></div>
	</div>
</div>
		