
<div class="comment" id="c_1713618883">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618883">1</a> by andrew lucking
		posted on 6/23/2005 at 7:28 PM
		</div>
		<div class="comment_text"><p>Ha,ha. Me too. Bloglines package tracking may help extend the life of your F5 key ;-)<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.bloglines.com%2Fsub%3Fmode%3D4%3AdaYM--qqX6yvaUGgi8T5fB8Gey4&amp;cuid=3321886" rel="nofollow noopener" title="http://www.bloglines.com/sub?mode=4">http://www.bloglines.com/su...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618885">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618885">2</a> by Simeon
		posted on 6/23/2005 at 8:07 PM
		</div>
		<div class="comment_text"><p>I am right there with you man.  Except it usually just makes me mad because I will watch the package stop in a city for a couple days.  Or it will get here to portland and wait until the proper day to actually come out to me.</p><p>But I sit and watch for updates all day long anyhow :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618888">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618888">3</a> by Mike Rankin
		posted on 6/23/2005 at 10:01 PM
		</div>
		<div class="comment_text"><p>I still want gps tracking of my package.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618884">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618884">4</a> by eapen
		posted on 6/23/2005 at 10:15 PM
		</div>
		<div class="comment_text"><p>ahh... someones tracking their PSP hack :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618890">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618890">5</a> by Raymond Camden
		posted on 6/23/2005 at 10:39 PM
		</div>
		<div class="comment_text"><p>Yep, it's for my PSP. :) Unfortunately, I can't use the new hack - as I upgraded to 1.51, and it's only for 1.5. :( But I have faith it won't be long. I'm going to stay at 1.51 and not go to 1.52.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618889">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618889">6</a> by Scott Stroz
		posted on 6/23/2005 at 11:11 PM
		</div>
		<div class="comment_text"><p>I can take the obsession one step further.</p><p>After I receive the package, I check every so often to see how long it takes to update that the package was delivered.  This can give me an idea on the latency of the system.</p><p>I need help :(</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618886">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618886">7</a> by g.wygonik
		posted on 6/24/2005 at 1:37 AM
		</div>
		<div class="comment_text"><p>with FedEx, i like to go back a few days later and look at the digitized signature of the recipient. it seems that UPS anymore just leaves packages and doesn't get signatures - unless you request it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618891">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618891">8</a> by Kevin
		posted on 6/24/2005 at 3:04 AM
		</div>
		<div class="comment_text"><p>Yeah, me too. But I add another step (especially if the package gets shipped by ground). I go to mapquest and map out the route the package took to get to me.</p><p>My kids think it's cool, but I think I need help too!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618893">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618893">9</a> by James Edmunds
		posted on 6/24/2005 at 6:43 AM
		</div>
		<div class="comment_text"><p>Wanna see when my new Blackberry 7100g arrives? Look here, as I have done more times than I will admit!<br><a href="http://disq.us/url?url=http%3A%2F%2Ftinyurl.com%2Farkn4%3AxYYjeCbFWgdV-e7i2ZS03xBxSYc&amp;cuid=3321886" rel="nofollow noopener" title="http://tinyurl.com/arkn4">http://tinyurl.com/arkn4</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618894">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618894">10</a> by Doug
		posted on 6/24/2005 at 7:23 PM
		</div>
		<div class="comment_text"><p>Yes, we are addicted to some very strange things. Found that you can google tracking numbers. It works great.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713618887">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713618887">11</a> by Cool::UPS Support Group
		posted on 8/3/2005 at 10:23 PM
		</div>
		<div class="comment_text"><p>Yes! I am addicted to tracking!.   My f5 key is faded completely out!. Help me!   Just kidding--I am addicted to tracking though, and at the moment am all over my violin coming from Texas to the east Coast.</p></div>
	</div>
</div>
		