
<div class="comment" id="c_1713736319">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736319">1</a> by Joseph R. Jones
		posted on 11/8/2011 at 1:42 AM
		</div>
		<div class="comment_text"><p>This scares the bejeezus out of me, but is very cool.</p><p>Will be interesting to see what people do with this API. Even without plugging into the facebook identity, it's interesting to see features like whether the user is male/female, wearing glasses, etc. Very cool stuff.</p><p>Thanks for the simple sample code to help folks get started playing with this.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736321">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736321">2</a> by Mika
		posted on 11/8/2011 at 5:19 PM
		</div>
		<div class="comment_text"><p>It may later be combined with image search functionality displayed at MAX sneaks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736318">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736318">3</a> by Ben B
		posted on 11/8/2011 at 6:38 PM
		</div>
		<div class="comment_text"><p>The next version of the API needs to distinguish between a smile and a *smirk*, like the one I'm wearing now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736320">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736320">4</a> by Jeremy Battle
		posted on 11/9/2011 at 12:17 AM
		</div>
		<div class="comment_text"><p>I actually discovered this API last week while looking for some fun stuff to code. I was super surprised with how easy it was to work with, definitely a cool one to play around with and works much better than the java face recognition libraries I've fooled around with in the past.</p></div>
	</div>
</div>
		