
<div class="comment" id="c_1713621230">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621230">1</a> by Kiriran
		posted on 10/6/2005 at 6:42 PM
		</div>
		<div class="comment_text"><p>flex2 seems to be pretty cool. if i understood it right, you dont need a flex server anymore, just the flex builder and can put the swf onto the server?! that would be very cool!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713621233">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621233">2</a> by Raymond Camden
		posted on 10/6/2005 at 6:43 PM
		</div>
		<div class="comment_text"><p>Yep, you understood right. There is still a Flex server, but it is separate.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713621234">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621234">3</a> by Kiriran
		posted on 10/6/2005 at 6:57 PM
		</div>
		<div class="comment_text"><p>so what is the flexserver good for if you dont need it anymore, since you can put the swf just on a normal server?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713621236">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621236">4</a> by Dave Carabetta
		posted on 10/6/2005 at 7:58 PM
		</div>
		<div class="comment_text"><p>Well, there will be a different in terms of enterprise features. For example, Flex Builder 2 (aka Zorn) will allow you to deploy XML and SOAP web services, but not AMF. As somebody who has been working a bit with Flex and ColdFusion, you will see, particularly with larger data sets that there is a demonstrable performance difference, as AMF is a binary protocol. There is an open source OpenAMF project, but I don't know the benchmarks of it, as I haven't had a need to use it. Also, I though I had read somewhere that some of the features of Flash Communication Server (i.e., the ability to push data to clients as opposed to the client polling) will be integrated into the Enterprise version. That being said, I can't find that link right now.</p></div>
	</div>
</div>
		