
<div class="comment" id="c_1713743546">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743546">1</a> by Mikel
		posted on 10/29/2012 at 6:38 PM
		</div>
		<div class="comment_text"><p>I think that is easily the BEST help wanted ad that I've ever seen!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743556">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743556">2</a> by Raymond Camden
		posted on 10/29/2012 at 6:43 PM
		</div>
		<div class="comment_text"><p>Agreed. :)</p></div>
	</div>
</div>
		