
<div class="comment" id="c_1713682092">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682092">1</a> by Scott P
		posted on 6/20/2008 at 11:32 PM
		</div>
		<div class="comment_text"><p>taking that one step further - someone needs to take this and create a word/excel/powerpoint to pdf converter.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682105">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682105">2</a> by Peter Hoopes
		posted on 6/21/2008 at 12:07 AM
		</div>
		<div class="comment_text"><p>Is there currently a way for CF8 to process a .docx or .xlsx file uploaded and show it back - or even store it for later editing?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682089">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682089">3</a> by nick tong
		posted on 6/21/2008 at 1:05 PM
		</div>
		<div class="comment_text"><p>Hi Ray - Lucene VS Verity - thoughts?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682098">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682098">4</a> by Raymond Camden
		posted on 6/21/2008 at 3:45 PM
		</div>
		<div class="comment_text"><p>@Peter - Not sure. I think the POI folks may add support for those new formats, but I've heard they are pretty different.</p><p>@Nick - Rough thoughs:</p><p>So obviously if you aren't on a Mac, then Verity is built in. No need to 'install' Seeker. I also like the category and suggestions support for Verity. You could probably duplicate category support, but it would be more difficult to do suggestions. (As far as I know, I'm still learning Lucene.)</p><p>The big plus for Lucene is index size. You have no license limits like Verity (250k). As I blogged about earlier, I tested w/ an index of 25 million records.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682102">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682102">5</a> by nick tong
		posted on 6/21/2008 at 8:04 PM
		</div>
		<div class="comment_text"><p>@ray - thanks. Well as i've moved over to the 'mac side' i'll give it a bash.  Thanks for your thoughts.  I presume you only use this locally when wanting to have an search service?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682099">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682099">6</a> by Raymond Camden
		posted on 6/23/2008 at 11:55 PM
		</div>
		<div class="comment_text"><p>Correct. I'm still using Verity for production.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682100">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682100">7</a> by Medman
		posted on 6/24/2008 at 1:20 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>does seeker work with Coldfusion 7?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682086">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682086">8</a> by Raymond Camden
		posted on 6/24/2008 at 1:23 AM
		</div>
		<div class="comment_text"><p>I haven't tested - but it should. Try it. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682103">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682103">9</a> by Sami Hoda
		posted on 6/30/2008 at 10:51 PM
		</div>
		<div class="comment_text"><p>Not sure the instructions are there to add cfadmin pages. You need to add a page for the menu item to show up, correct?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682093">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682093">10</a> by Raymond Camden
		posted on 6/30/2008 at 11:02 PM
		</div>
		<div class="comment_text"><p>There is a file in the root of the CF Admin named custommenu.xml. If you open that up, you will see instructions on how to modify the CF Admin to show new links.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682097">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682097">11</a> by Sami Hoda
		posted on 6/30/2008 at 11:04 PM
		</div>
		<div class="comment_text"><p>I just created a file extensionscustom.cfm, and added:<br>&lt;a href="seeker/index.cfm" target="content"&gt;Seeker&lt;/a&gt;&lt;br&gt; to it. Is the XML the new approach?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682090">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682090">12</a> by Raymond Camden
		posted on 6/30/2008 at 11:05 PM
		</div>
		<div class="comment_text"><p>Yes. Either works, but the XML way is the 'new' way.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682087">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682087">13</a> by Sami Hoda
		posted on 6/30/2008 at 11:06 PM
		</div>
		<div class="comment_text"><p>I see, there needs to be multiple links, not just to index.cfm. So searchtool.cfm and index.cfm are the two links?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682096">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682096">14</a> by Sami Hoda
		posted on 6/30/2008 at 11:07 PM
		</div>
		<div class="comment_text"><p>Or is index.cfm the only file needed?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682094">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682094">15</a> by Raymond Camden
		posted on 6/30/2008 at 11:11 PM
		</div>
		<div class="comment_text"><p>index.cfm is the only one you need.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682091">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682091">16</a> by Sami Hoda
		posted on 7/1/2008 at 12:53 AM
		</div>
		<div class="comment_text"><p>Blogged install instructions. Will be eval'ing Seeker.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682088">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682088">17</a> by Will Wilson
		posted on 4/28/2009 at 12:09 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>Any chance you could add snippets on the next version (similar to verity where it highlights text etc).</p><p>Would also be cool if you could link to pages within a framework...although I'm baffled how one would accomplish this.</p><p>Keep up the good work! Being on a mac, I'm finding this tool invaluable!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682106">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682106">18</a> by Raymond Camden
		posted on 4/28/2009 at 12:59 AM
		</div>
		<div class="comment_text"><p>I don't believe Lucene support this. If I'm wrong, I'd be happy to add it.</p><p>Also, you need to clearly differentiate between snippets and context. A snippet could be from anywhere in the document, but helps identify the document, whereas context shows you the match. So I'm sure you mean context.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682104">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682104">19</a> by Will Wilson
		posted on 4/28/2009 at 11:29 PM
		</div>
		<div class="comment_text"><p>That's a shame, it's a cool feature. Yeah my bad, I meant context. Mental note made :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682101">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682101">20</a> by janusz
		posted on 6/17/2009 at 1:20 PM
		</div>
		<div class="comment_text"><p>hi ray</p><p>im wondering if seeker allows for more than one index to be created?</p><p>i currently need to index lots of different tables with different columns. Instead of trying to collate them into one index, thought it may be easier to create more than one index?</p><p>thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682109">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682109">21</a> by Raymond Camden
		posted on 6/17/2009 at 3:16 PM
		</div>
		<div class="comment_text"><p>Like Verity, Seeker works with multiple indexes. So yes, you can do multiple indexes. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682110">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682110">22</a> by janusz
		posted on 6/17/2009 at 3:38 PM
		</div>
		<div class="comment_text"><p>hi ray.. thanks for letting me know.<br>if  i have this...</p><p>		&lt;cf_indexquery directory="#index_folder#" indexdirectory="#index_folder#"<br>			query="#arguments.index_qry#" <br>			storecolumns="id,title,content,type,link" indexcolumns="id,title,content"&gt;</p><p>where would the name of the index file go?</p><p>seeker has been a lifesaver as im on a mac.</p><p>thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682111">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682111">23</a> by Raymond Camden
		posted on 6/17/2009 at 3:39 PM
		</div>
		<div class="comment_text"><p>It's directory based. So give it a new indexdirectory value.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682115">24</a> by janusz
		posted on 6/17/2009 at 3:45 PM
		</div>
		<div class="comment_text"><p>brilliant... thanks for your help.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682113">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682113">25</a> by rchinoy
		posted on 1/29/2010 at 2:48 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>It doesn't seem like stemming is working when I use Seeker. Is there something I need to do to get it working?</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682114">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682114">26</a> by Raymond Camden
		posted on 2/1/2010 at 11:49 PM
		</div>
		<div class="comment_text"><p>Forgive me - but I'm a bit rusty on my code base. I believe you would need to change the analyzer used to parse data. I'd have to look into which are available and what could easily be used with Seeker. You can file an ER for this at RIAForge, but no promise on when I'd have time to get it working.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682112">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682112">27</a> by farshid
		posted on 2/8/2010 at 7:38 PM
		</div>
		<div class="comment_text"><p>Hi,<br>what are you doing with MS word math equations? could you insert formula to database via rich text box or reading  from doc files?<br>Please help me.<br>regards<br>farshid</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682117">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682117">28</a> by web design liverpool
		posted on 6/4/2010 at 1:45 PM
		</div>
		<div class="comment_text"><p>Hi</p><p>Maybe a stupid question but how would I search 2 indexes at the same time, one a file index the other a DB index? Or can I join the two together?</p><p>Thanks</p><p>Peter</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713682119">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713682119">29</a> by Raymond Camden
		posted on 6/4/2010 at 3:19 PM
		</div>
		<div class="comment_text"><p>Yes. Just provide a list to the collection attribute. This is only allowed if you aren't doing a category search.</p></div>
	</div>
</div>
		