
<div class="comment" id="c_1713716078">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716078">1</a> by Michael Santoroski
		posted on 6/16/2009 at 6:41 AM
		</div>
		<div class="comment_text"><p>Looks cool. When did you say that Bolt is going into public beta?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716060">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716060">2</a> by Raymond Camden
		posted on 6/16/2009 at 6:42 AM
		</div>
		<div class="comment_text"><p>It already is - but you have to have a Golden Ticket.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716062">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716062">3</a> by Jason
		posted on 6/16/2009 at 6:44 AM
		</div>
		<div class="comment_text"><p>Craps.  How about a quick bolt rundown, first impressions, etc.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716064">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716064">4</a> by Michael Santoroski
		posted on 6/16/2009 at 6:44 AM
		</div>
		<div class="comment_text"><p>I'll start buying lots of Adobe Chocolate Bars!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716063">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716063">5</a> by Raymond Camden
		posted on 6/16/2009 at 6:49 AM
		</div>
		<div class="comment_text"><p>The first rule of NDA is that you don't speak about NDA. ;)</p><p>Seriously - I can't say anything yet. But um, I wouldn't bash it. Not at all. I'd do the opposite. I'll stop now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716065">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716065">6</a> by Torgo
		posted on 6/16/2009 at 7:18 AM
		</div>
		<div class="comment_text"><p>Do you know if they're going to be adding more people to the pre-release?  I've been in the Centaur one for months, but haven't heard anything about Bolt yet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716070">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716070">7</a> by Raymond Camden
		posted on 6/16/2009 at 7:20 AM
		</div>
		<div class="comment_text"><p>Repeat after me. "Ray can't say squat."</p><p>Sorry - I should have been clear on that. I have no idea what Adobe plans.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716071">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716071">8</a> by Sean Coyne
		posted on 6/16/2009 at 2:48 PM
		</div>
		<div class="comment_text"><p>@ray can you add a search feature?  maybe w/ a little ajax autocomplete?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716067">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716067">9</a> by Raymond Camden
		posted on 6/16/2009 at 5:05 PM
		</div>
		<div class="comment_text"><p>I haven't yet tested Ajax w/n the confines of Bolt. Of course, it need not be Ajax (search doesn't, autocomplete would). It's on my list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716172">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716172">10</a> by Lola LB
		posted on 6/16/2009 at 5:44 PM
		</div>
		<div class="comment_text"><p>Wow . . . looks great!  This will make developing so much more easier.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716174">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716174">11</a> by inj
		posted on 6/17/2009 at 12:44 AM
		</div>
		<div class="comment_text"><p>Hi, Ray!<br>I just installed this extension, but was unable to use it - got an error message: "Error occurred while parsing response from handler "/handlers/selectcategory.cfm".<br>What am I doing wrong?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716175">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716175">12</a> by Raymond Camden
		posted on 6/17/2009 at 12:47 AM
		</div>
		<div class="comment_text"><p>Please try the version I just posted. I had forgotten to disable CF debugging, and it was using the same app space as the RIAForge extension.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716173">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716173">13</a> by inj
		posted on 6/17/2009 at 12:53 AM
		</div>
		<div class="comment_text"><p>Ok, now it works fine! <br>Thank you.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713716176">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713716176">14</a> by Raymond Camden
		posted on 6/17/2009 at 12:55 AM
		</div>
		<div class="comment_text"><p>Yeah, once we can speak a bit more openly about Bolt and extensions, I'm sure myself (and others) will be posting tips,guides,etc to working with them.</p><p>If you get my RIAForge extension, it does NOT have this fix. So be sure to copy the line from onRequestStart.</p></div>
	</div>
</div>
		