
<div class="comment" id="c_1713654491">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654491">1</a> by Tom Chiverton
		posted on 6/28/2006 at 8:11 PM
		</div>
		<div class="comment_text"><p>CF8 - well, it sounds great, but nothing compelling enough to make me want to rush out and upgrade unless/untill I need some more eye candy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654506">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654506">2</a> by Raymond Camden
		posted on 6/28/2006 at 8:13 PM
		</div>
		<div class="comment_text"><p>Bear in mind this is just two features. I can promise you there will be a lot more.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654503">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654503">3</a> by Jim
		posted on 6/28/2006 at 8:19 PM
		</div>
		<div class="comment_text"><p>Exactly what I DIDN'T want to hear.  I wish they would have a good bug fix release...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654504">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654504">4</a> by Sam Farmer
		posted on 6/28/2006 at 8:30 PM
		</div>
		<div class="comment_text"><p>Thanks for the updates Ray.</p><p>Some cool new features.  Was there any mention of being able to convert Word or Excel documents into PDF?  That would be awesome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654502">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654502">5</a> by Dan Sorensen
		posted on 6/28/2006 at 8:31 PM
		</div>
		<div class="comment_text"><p>PDF Forms are big (whether that's good or bad is a different question), nevertheless, anything they can do to make PDFs interact with CF better is a good thing in my mind! :-)</p><p>I wouldn't be surprised if they found a way to simplify AJAX integration as well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654505">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654505">6</a> by Dan Sorensen
		posted on 6/28/2006 at 8:31 PM
		</div>
		<div class="comment_text"><p>By the way, THANKS A BUNCH for posting what you can. It's a big help for those of us who couldn't get to the conference. :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654492">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654492">7</a> by Tony Petruzzi
		posted on 6/28/2006 at 8:45 PM
		</div>
		<div class="comment_text"><p>Ray, do me this favor. Run up and smack Jason Delmore. What the heck is this they're doing?!?! These are totally usless "upgrades" to CF. What they should be concentrating on is making the thing faster and more realiable. CFMX has been nothing but a disaster since it's inception.</p><p>And what kind of stupid features are these:</p><p>CFPDFFORM - anyone heard of FDF or better yet XFDF?<br>CFPRESENTATION - yeah, if this spikes the server like CFDOCUMENT  does I'm sure to be using it.</p><p>No offense to Adobe, but they ought to be looking at what New Atlanta has added in BD7.0 and copy them:</p><p>CFTHREAD - I just droodled on my keyboard.<br>CFQUERY CACHEDUNTILCHANGE - awesome way to leverage the power of MSSQL2005.</p><p>I hate to say it, but Adobe better get their act together before they start to lose more market share to BD and .Net.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654494">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654494">8</a> by Tony Petruzzi
		posted on 6/28/2006 at 8:59 PM
		</div>
		<div class="comment_text"><p>Oh in case anyone reading my revious post wants to know what new features are in BD:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fblog.newatlanta.com%2Findex.cfm%3Fmode%3Dentry%26entry%3DD689EF9B-E7C5-148D-99C3E63B57563844%3AFSQ9sSnyo678Hq1OHubdDte7aPg&amp;cuid=3321886" rel="nofollow noopener" title="http://blog.newatlanta.com/index.cfm?mode=entry&amp;entry=D689EF9B-E7C5-148D-99C3E63B57563844">http://blog.newatlanta.com/...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654497">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654497">9</a> by Jim
		posted on 6/28/2006 at 9:16 PM
		</div>
		<div class="comment_text"><p>Thanks for the BD link!  We're still on CF6.1 and are looking at moving to 7 so we can start messing with Flex but I really, really wish Adobe would fix some of the more annoying bugs - cfschedule gives me recurring heartburn - and yes I know there are alternatives but wouldn't it just be easier if they fixed it? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654493">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654493">10</a> by Daniel Greenfeld
		posted on 6/28/2006 at 9:40 PM
		</div>
		<div class="comment_text"><p>The solution I've seen that works best with CFSCHEDULE problems is to simply ban its use.  This is the sort of thing that really should be handled via the Administrator?  Why?  because some idiot will always stick it into their application.cfc or .cfm to run every time a page loads.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654495">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654495">11</a> by joe
		posted on 6/28/2006 at 11:42 PM
		</div>
		<div class="comment_text"><p>hey ray -</p><p>wifi works great in the back right corner of ballroom 3.  just type quietly when there's a preso going...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654498">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654498">12</a> by Raymond Camden
		posted on 6/29/2006 at 7:12 AM
		</div>
		<div class="comment_text"><p>Some responses:</p><p>Jim, you asked for a bug fix. They released that today. 7.0.2 collect hot fixes and patches from earlier releases. There ya go. :)</p><p>Sam - nope - I blogged everything mentioned.</p><p>Tony, respectfully I disagree. Again - these are just two features. They may not be useful to you, but I think are useful to me. That is true of any new feature - some folks will use it, some will not. I do not think it is reasonable or fair to expect that you (or anyone) would find _every_ tag/function useful.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654496">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654496">13</a> by Tom Chiverton
		posted on 6/29/2006 at 12:11 PM
		</div>
		<div class="comment_text"><p>"these are just two features. They may not be useful to you, but I think are useful to me"<br>This is true, and I hope more cool stuff will come out about CF8.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654499">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654499">14</a> by Jim
		posted on 6/29/2006 at 3:55 PM
		</div>
		<div class="comment_text"><p>"Jim, you asked for a bug fix. They released that today. 7.0.2 collect hot fixes and patches from earlier releases...."</p><p>Is there a list of bugs fixed in each release? I'm running 7.x at home so I'll have to download - maybe there are release notes included. Just need to nag my boss about upgrading to 7.</p><p>Jim</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713654501">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713654501">15</a> by Raymond Camden
		posted on 6/30/2006 at 3:45 PM
		</div>
		<div class="comment_text"><p>Jim: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.adobe.com%2Fsupport%2Fdocumentation%2Fen%2Fcoldfusion%2Fmx702%2Fcf702_releasenotes.html%3AueXMwXUcSFMD-vqqmX6rDeSdnic&amp;cuid=3321886" rel="nofollow noopener" title="http://www.adobe.com/support/documentation/en/coldfusion/mx702/cf702_releasenotes.html">http://www.adobe.com/suppor...</a></p></div>
	</div>
</div>
		