
<div class="comment" id="c_1713614515">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614515">1</a> by Nathan Dintenfass
		posted on 3/20/2003 at 5:49 AM
		</div>
		<div class="comment_text"><p>And for those folks who would prefer to not use a command line, I highly recommend TortoiseCVS, which turns your Windows Explorer into a point-and-click CVS client (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.tortoisecvs.org%3APObvyjIGwvoc0goGjI0yuQGEjSM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.tortoisecvs.org">http://www.tortoisecvs.org</a>)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614512">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614512">2</a> by Raymond Camden
		posted on 3/20/2003 at 5:10 PM
		</div>
		<div class="comment_text"><p>Another option is WinCVS: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.wincvs.org%2F%3ADVCKcLxJkkfNvoBiAuQWRbiDzwI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.wincvs.org/">http://www.wincvs.org/</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614510">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614510">3</a> by Steve Collins
		posted on 3/21/2003 at 1:40 AM
		</div>
		<div class="comment_text"><p>So, young Jedi, once SS was the Master, now CVS is the Master!</p><p>Welcome to the fabulous world of CVS.  There are a heap of resources out there for you if you wnat to read them.  I especially recommend DevGuy (<a href="http://disq.us/url?url=http%3A%2F%2Fwww.devguy.com%2Ffp%2Fcfgmgmt%2Fcvs%2F%29%3AjfZ4R0uDU1_Se0hpY4iLkec7WIU&amp;cuid=3321886" rel="nofollow noopener" title="http://www.devguy.com/fp/cfgmgmt/cvs/)">http://www.devguy.com/fp/cf...</a>.  Also, most of the CVS tools have a "Daily Use Guide" which tends to be very helpful.</p><p>Like Nathan says, use Tortoise if you''re developing in Windows, or gCVS if you''re a Linux-head (I am cursed with both diseases).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614516">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614516">4</a> by Scott Barnes
		posted on 3/21/2003 at 8:49 AM
		</div>
		<div class="comment_text"><p>Spike (Teaboy) just showed me TortoiseCVS and WOAH.. I last used a CVS back in the day with Visual Source Safe (which DWMX basically does now but betterer)..</p><p>I''m a convert aswell.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614511">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614511">5</a> by Christian Cantrell
		posted on 4/23/2003 at 12:13 AM
		</div>
		<div class="comment_text"><p>Personally, I can''t develop without CVS.  It is almost as important as my editor.  I have found that those who don''t like CVS just don''t understand it.  I have never known anyone who really understands CVS claim to not like it.</p></div>
	</div>
</div>
		