
<div class="comment" id="c_2233179325">
	<div>
		<img src="https://disqus.com/api/users/avatars/martincisneroscapistrn.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2233179325">1</a> by Martin Cisneros Capistrán
		posted on 9/3/2015 at 3:31 AM
		</div>
		<div class="comment_text"><p>I'm in :D</p></div>
	</div>
</div>
		
<div class="comment" id="c_2233549555">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2233549555">2</a> (In reply to <a href="#c_2233179325">#1</a>) by Raymond Camden
		posted on 9/3/2015 at 10:48 AM
		</div>
		<div class="comment_text"><p>Cool. Hopefully I can blog on this more in the future.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2248487571">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_ySzUQJxq6s.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2248487571">3</a> by George
		posted on 9/11/2015 at 6:02 PM
		</div>
		<div class="comment_text"><p>I am so in.  I am a newbie ionic developer, but also in healthcare.  Your project looked exciting!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2269721068">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_vVXchz5u1z.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2269721068">4</a> by Julio
		posted on 9/23/2015 at 7:31 PM
		</div>
		<div class="comment_text"><p>I'm in, keep me posted very interested!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2271105116">
	<div>
		<img src="https://disqus.com/api/users/avatars/lawkig.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2271105116">5</a> by Lawkig
		posted on 9/24/2015 at 8:36 AM
		</div>
		<div class="comment_text"><p>You're talking about context-aware applications. I think machine learning can help here.</p></div>
	</div>
</div>
		