
<div class="comment" id="c_1713614676">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614676">1</a> by Steven Erat
		posted on 6/19/2003 at 4:55 PM
		</div>
		<div class="comment_text"><p>For a detailed explanation, see my blog entry here: <br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.talkingtree.com%2Fblog%2Findex.cfm%3Fdata%3D20030619%23E0BBB697-40CA-1709-54E6058CD958ECDF%3A83zK4ODjaUtIA2_XV6pccfT-shg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.talkingtree.com/blog/index.cfm?data=20030619#E0BBB697-40CA-1709-54E6058CD958ECDF">http://www.talkingtree.com/...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614670">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614670">2</a> by Rob Brooks--Bilson
		posted on 6/19/2003 at 5:08 PM
		</div>
		<div class="comment_text"><p>I''ve had this happen several times as well.  It''s particularly annoying!</p><p>-Rob</p></div>
	</div>
</div>
		