
<div class="comment" id="c_1713684654">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684654">1</a> by Mike Brunt
		posted on 8/4/2008 at 8:30 PM
		</div>
		<div class="comment_text"><p>Ray, yes you certainly have an incredible team there at Broadchoice and a very good application also.  I was fortunate enough to help Sean et al tune it before launch.  Oh and I should say not only a great concentration of talent but also a bloody great group of decent human beings!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684679">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684679">2</a> by GaryFunk
		posted on 8/4/2008 at 10:39 PM
		</div>
		<div class="comment_text"><p>Ray, Brian is almost as cool as you are. Both of you have been a great help, to me, and thousands others.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684671">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684671">3</a> by Esmeralda
		posted on 8/5/2008 at 12:06 AM
		</div>
		<div class="comment_text"><p>Congratulations Brian!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713684672">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713684672">4</a> by Nick
		posted on 8/5/2008 at 12:38 AM
		</div>
		<div class="comment_text"><p>The last great collection of minds like this was the Manhattan Project and they created the Atomic Bomb. So yeah, the bar is set a little high.</p></div>
	</div>
</div>
		