
<div class="comment" id="c_1713708712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713708712">1</a> by Anthony Hixon, Jr.
		posted on 9/23/2008 at 4:30 PM
		</div>
		<div class="comment_text"><p>I have to say that even though I don't post that often, I have been following your posts for a long while and I'd like to say thank you for sharing. Your examples and insight have helped me many times over the years.</p></div>
	</div>
</div>
		