
<div class="comment" id="c_1713742123">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742123">1</a> by Ciaran Archer
		posted on 7/7/2012 at 11:44 AM
		</div>
		<div class="comment_text"><p>Jasmine is really great. The next step is to stop tying your code to the DOM and instead just create a JS object that encapsulates the functionality. Then once you have a few tests is to use jasmine-node to run them from the command line using nodejs. Then it's trivial to add them as a step in a CI environment.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742124">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742124">2</a> by Raymond Camden
		posted on 7/7/2012 at 4:53 PM
		</div>
		<div class="comment_text"><p>To be clear though, this code isn't tied to the DOM, right? (Just making sure I understand you.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742128">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742128">3</a> by Ben Nadel
		posted on 7/8/2012 at 9:36 PM
		</div>
		<div class="comment_text"><p>Ha ha, what timing - I also just tried Jasmine for the first time on Friday. Ran my first-ever Unit Test. Pretty exciting. Now to try something on the server side. After using Jasmine, I'm tempted to use Marc's new unit testing CF10 project; but, I don't do anything in CF10 for production yet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4837477162">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4837477162">4</a> by Ronak Vanpariya
		posted on 3/18/2020 at 8:20 AM
		</div>
		<div class="comment_text"><p>Thanks a Lot.</p></div>
	</div>
</div>
		