
<div class="comment" id="c_1713744113">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744113">1</a> by Jake Munson
		posted on 12/5/2012 at 1:22 AM
		</div>
		<div class="comment_text"><p>"At the end of the day, I'll use jQuery, but I truly feel like we need to start writing more vanilla JavaScript if we ever hope to improve our skills."</p><p>+1 to that. I have said this a lot but I usually get negative reactions from people. I still don't understand why so many web developers hate JavaScript.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744114">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744114">2</a> by Pete
		posted on 12/5/2012 at 1:06 PM
		</div>
		<div class="comment_text"><p>I agree as well, Javscript has loads of features built into it that I used to use jQuery for - like JSON parsing.</p><p>It's not just the JS either, I've barely made any effort to learn about CSS animation and transforms because of all the Javascript libraries that do CSS for us.</p><p>Cross browser support is probably the main reason I stick with a lot of libraries - but with vanilla CSS and JS getting much more capable, I'm building a bigger tool set of my own libraries.</p><p>Ok, cross browser support and laziness... jQuery does make live so easy.</p><p>The book sounds good though Ray, I'll check it out, I've never really got the Doctype.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744115">3</a> by Simon MacDonald
		posted on 12/7/2012 at 8:08 PM
		</div>
		<div class="comment_text"><p>I agree with you on the jQuery thing. Folks need to learn some more plain vanilla JavaScript especially for mobile browsers where a toolkit like jQuery is less important as there are not as many differences for it to smooth over.</p><p>This looks like a very interesting book but at $29 for an eBook I think I'll put it on my come back to it list. Especially since I have 70 books on my to read stack.</p></div>
	</div>
</div>
		