
<div class="comment" id="c_1713743533">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743533">1</a> by bender
		posted on 11/1/2012 at 3:13 AM
		</div>
		<div class="comment_text"><p>Hi, awesome blog. Can you please tell if its possible to download data that is hosted on parse (in case you move to your own server)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743539">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743539">2</a> by Tom
		posted on 11/1/2012 at 3:42 AM
		</div>
		<div class="comment_text"><p>Hi Ray:</p><p>Awesome introduction to Phonegap+Parse User.  Is there any possibility that you would cover Phonegap+ParseFacebookUtils?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743537">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743537">3</a> by sam
		posted on 11/2/2012 at 1:02 AM
		</div>
		<div class="comment_text"><p>awesome article! I would love to see this incorporated with Facebook authentication as well..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743534">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743534">4</a> by Raymond Camden
		posted on 11/2/2012 at 1:02 AM
		</div>
		<div class="comment_text"><p>Bender: Absolutely. That's one of the best features. If you are worried about Parse going bankrupt or just want to keep a copy, you can export data right from the dashboard. I thought they had an API as well, but I don't see it.</p><p>Tom: I plan on covering Facebook and Twitter next.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743536">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743536">5</a> by Brandon
		posted on 11/8/2012 at 9:37 AM
		</div>
		<div class="comment_text"><p>Great blog! I've found a number of your blog postings very helpful.<br>Have you done any in-app purchases with phonegap and parse yet?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743538">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743538">6</a> by Raymond Camden
		posted on 11/8/2012 at 5:21 PM
		</div>
		<div class="comment_text"><p>Nope, not yet. Ecom stuff is a bit harder to test normally. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743540">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743540">7</a> by Tim B
		posted on 11/10/2012 at 1:50 AM
		</div>
		<div class="comment_text"><p>I tried opening the zip package in chrome but the ajax didn't work. Packaging it into a phonegap app then opening it in the android emulator made it work. Is there any way to run it from a browser?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743543">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743543">8</a> by Raymond Camden
		posted on 11/10/2012 at 1:54 AM
		</div>
		<div class="comment_text"><p>If you can't run it from a local web server, try with this Chrome command line:</p><p>(obviously this is for Mac, you can tweak for PC)</p><p>open -a /Applications/Google\ <a href="http://disq.us/url?url=http%3A%2F%2FChrome.app%3AsEN-TKeiE6hz5x5akNeAgXYkB18&amp;cuid=3321886" rel="nofollow noopener" title="Chrome.app">Chrome.app</a> --args --allow-file-access-from-files --disable-web-security</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743542">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743542">9</a> by Tim B
		posted on 11/10/2012 at 1:58 AM
		</div>
		<div class="comment_text"><p>K, I tried the command line but no luck. I went ahead and looked at the cylon.js file. It looks like its only listening for touch events and since I can only send click events in chrome it won't work unless I switch it to jquery mobile or tweak the js.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743544">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743544">10</a> by Raymond Camden
		posted on 11/10/2012 at 1:59 AM
		</div>
		<div class="comment_text"><p>Oh, in Chrome, open dev tools, go to settings. There is an option to emulate touch.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743545">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743545">11</a> by Tim B
		posted on 11/10/2012 at 2:10 AM
		</div>
		<div class="comment_text"><p>Sweet that worked.</p><p>Also the app isn't allowing me to register or login, no errors. It appears as though its not communicating with Parse. Do I need to recreate your DB and enter my own Parse API Keys. Or is it a matter of adding the parse android jar to my phonegap app and redeploy?</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743558">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743558">12</a> by Raymond Camden
		posted on 11/10/2012 at 2:19 AM
		</div>
		<div class="comment_text"><p>It should work. DO you see anything in console?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743557">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743557">13</a> by Tim B
		posted on 11/10/2012 at 2:26 AM
		</div>
		<div class="comment_text"><p>Nope, the console is clear, no errors. However I just deployed it in the android emulator and its working. Just not working in chrome, I guess.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743561">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743561">14</a> by Raymond Camden
		posted on 11/10/2012 at 2:31 AM
		</div>
		<div class="comment_text"><p>Weird, I did all my testing there. Well, just happy you got it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743562">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743562">15</a> by Tim B
		posted on 11/10/2012 at 2:32 AM
		</div>
		<div class="comment_text"><p>Maybe its a pc thing :)</p><p>Anyways, thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743564">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743564">16</a> by Pete
		posted on 11/14/2012 at 3:17 PM
		</div>
		<div class="comment_text"><p>Parse keeps on getting better, I haven't looked into the User side of things yet, but reading this is making me wonder why I bother with a MySQL database at all any more.</p><p>I know you can do basic queries with Parse, can you get really complicated with Joins and Subqueries?</p><p>I'm leaning towards ditching my server and just having simple web site hosting and using Parse for everything else.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743563">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743563">17</a> by Pete
		posted on 11/14/2012 at 4:01 PM
		</div>
		<div class="comment_text"><p>Ok, so I read through the docs, relational objects and queries are all possible and look pretty easy to do.</p><p>I need to be using Parse more.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743565">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743565">18</a> by Raymond Camden
		posted on 11/14/2012 at 5:26 PM
		</div>
		<div class="comment_text"><p>Glad you like it. :) I still plan on doing Twitter/FB integration soon - just have other stuff in the pipeline.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743567">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743567">19</a> by Justin
		posted on 11/15/2012 at 12:42 PM
		</div>
		<div class="comment_text"><p>Great site and great tutoials.</p><p>How would I make it so that once the user is logged in, they can see all the notes? Sort of like a rough forum.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743568">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743568">20</a> by Raymond Camden
		posted on 11/15/2012 at 7:56 PM
		</div>
		<div class="comment_text"><p>Justin, I talk about getting "your" content at the end of the blog entry - does it not make sense?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743571">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743571">21</a> by Alex
		posted on 12/20/2012 at 11:11 PM
		</div>
		<div class="comment_text"><p>Still looking forward for your promised <a href="http://disq.us/url?url=http%3A%2F%2Fparse.com%3A9NAZCuXuWB_KfP-1b0V6Vh4y4SA&amp;cuid=3321886" rel="nofollow noopener" title="parse.com">parse.com</a> &lt;-&gt; Phongap login integration through parse facebook user management without the need to open a Website. Its not that easy... but would be incredible usefull<br>Sincerely,<br>Alex</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743572">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743572">22</a> by Raymond Camden
		posted on 12/20/2012 at 11:14 PM
		</div>
		<div class="comment_text"><p>Still planning it. Life got super busy. I had hoped things would slow down before XMas, but I've got some big presentations right after the break. It may not be done till mid Jan.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743573">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743573">23</a> by sam
		posted on 3/14/2013 at 2:57 AM
		</div>
		<div class="comment_text"><p>Are you still going to do a FaceBook or Open Id integration?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743574">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743574">24</a> by Raymond Camden
		posted on 3/14/2013 at 3:43 PM
		</div>
		<div class="comment_text"><p>I still _want_ to. Just not sure when.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743575">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743575">25</a> by Steve
		posted on 4/23/2013 at 9:02 PM
		</div>
		<div class="comment_text"><p>Really good stuff.  Considering having a free version of my app -- which currently calls a .net Web API service to do look up some values on my SQL Server (hosted) db and perform some math before sending results back to phone.</p><p>As for a paid version of the app, Parse seems to be a good way to have a db of paid users and to handle authentication, keeping the Web API &amp; SQL Server stuff as is.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743576">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743576">26</a> by Rigel
		posted on 5/27/2013 at 6:56 PM
		</div>
		<div class="comment_text"><p>Hi I am trying to use parse-1.2.7 with ember tool. <a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Frpflorence%2Fember-tools%2F%3APHlUqzi8U-KsNRpPggQ2wc74tpk&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/rpflorence/ember-tools/">https://github.com/rpfloren...</a> when I include Parse from cdn it works fine. But when I download a copy it gives me error of list of dependencies like failed to require LocalStorage, xmlhttprequest. I am using LAMP. I am noob can you give me some pointer.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743578">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743578">27</a> by Raymond Camden
		posted on 5/28/2013 at 2:52 AM
		</div>
		<div class="comment_text"><p>I'm sorry, but I don't use Ember.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743579">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743579">28</a> by Pratik
		posted on 6/21/2013 at 4:12 PM
		</div>
		<div class="comment_text"><p>Hi I am trying to do the same thing using <a href="http://disq.us/url?url=http%3A%2F%2Ftrigger.io%3A2XcZC12i0pXBUKq9_MpSndG_b0Y&amp;cuid=3321886" rel="nofollow noopener" title="trigger.io">trigger.io</a> , can u please help me with this ? how can we create same thing using <a href="http://disq.us/url?url=http%3A%2F%2Fparse.com%3A9NAZCuXuWB_KfP-1b0V6Vh4y4SA&amp;cuid=3321886" rel="nofollow noopener" title="parse.com">parse.com</a> and <a href="http://disq.us/url?url=http%3A%2F%2Ftrigger.io%3A2XcZC12i0pXBUKq9_MpSndG_b0Y&amp;cuid=3321886" rel="nofollow noopener" title="trigger.io">trigger.io</a>.</p><p>thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743696">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743696">29</a> by Raymond Camden
		posted on 6/21/2013 at 5:33 PM
		</div>
		<div class="comment_text"><p>I don't know <a href="http://disq.us/url?url=http%3A%2F%2Ftrigger.io%3A2XcZC12i0pXBUKq9_MpSndG_b0Y&amp;cuid=3321886" rel="nofollow noopener" title="trigger.io">trigger.io</a>. Can you read their docs and share your experience?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743714">30</a> by Pratik
		posted on 6/24/2013 at 10:47 AM
		</div>
		<div class="comment_text"><p>Hi Raymond , <br> I tried the this tutorial on phonegap build . i am getting an error saying "connection to server was unsuccessful "</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743701">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743701">31</a> by Raymond Camden
		posted on 6/24/2013 at 4:40 PM
		</div>
		<div class="comment_text"><p>You got that on PhoneGap Build, or did you get it when you ran the app?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743700">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743700">32</a> by Pratik
		posted on 6/24/2013 at 7:31 PM
		</div>
		<div class="comment_text"><p>Yes i did this in phonegap build ...but was unable to get through login and registration screen ..and was not able to see any data in <a href="http://disq.us/url?url=http%3A%2F%2Fparse.com%3A9NAZCuXuWB_KfP-1b0V6Vh4y4SA&amp;cuid=3321886" rel="nofollow noopener" title="parse.com">parse.com</a> ..<br>I am trying to do user support but a slight difference in the third page ..i mean instead of uploading and saving notes ..i want to upload music files .</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743708">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743708">33</a> by Pratik
		posted on 6/25/2013 at 1:36 AM
		</div>
		<div class="comment_text"><p>Hello , i think i am going wrong somewhere.<br>i also tried this by downloading the source code zip file .. updated the application id and js key from parse . but still wen i run the app on my phone ..i can see the first screen and when i click registration , fill my details and hit register button then it again takes me back to the first screen with login and registration button , the same thing happens even when i click login on first screen ..and as soon as i fill details and hit login button it takes me back to first screen .</p><p>Please help me</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743704">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743704">34</a> by Raymond Camden
		posted on 6/25/2013 at 5:26 PM
		</div>
		<div class="comment_text"><p>I'd suggest running this via the Ripple emulator so you can use the Chrome debug tools. That's all I can recommend from here.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743702">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743702">35</a> by Pratik
		posted on 6/25/2013 at 7:15 PM
		</div>
		<div class="comment_text"><p>Thank you Raymond ..<br>I tried your another stuffs u blogged regarding integrating parse with phonegap ..<br>all those tutorials worked even the offline support with parse but I am just unable to get this run successfully.</p><p>I am not getting the point where I am going wrong ..Please suggest me. .</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743718">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743718">36</a> by Raymond Camden
		posted on 6/25/2013 at 7:19 PM
		</div>
		<div class="comment_text"><p>Pratik, did you see my comment? You need to try running this using Ripple and use Chrome's debug tools to try to diagnose what the error may be. I've got a blog post on using Ripple as well as ones that talk about Chrome Dev Tools. I can't just tell you what's wrong.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743703">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743703">37</a> by Pratik
		posted on 6/25/2013 at 7:21 PM
		</div>
		<div class="comment_text"><p>When i tested this in my android phone , i was not able to see any validation messages or error messages related to username and not even reset password thing is not working ..<br>and mainly I am not getting any data in parse .</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743716">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743716">38</a> by Pratik
		posted on 6/25/2013 at 7:24 PM
		</div>
		<div class="comment_text"><p>Ok Raymond , Will test this in ripple and will check and get back to you.</p><p>Thank you</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743715">39</a> by Pratik
		posted on 6/25/2013 at 9:11 PM
		</div>
		<div class="comment_text"><p>Hello Raymond ,</p><p>I tested the code in ripple emulator and this is the error message i am getting -<br>"Validation Failed"</p><p>"Config.xml file could not be found in the application's root or is malformed xml"</p><p>and in developers tools ..</p><p>the error I am getting is this .<br>"Uncaught type error : cannot read property 'type' of undefined"<br>inside this function</p><p>++++++++++<br>function deviceready() {<br>    console.log("device ready to roll");<br>    if(navigator.connection.type == Connection.UNKNOWN ||<br>Uncaught TypeError: Cannot read property 'type' of undefined<br>        navigator.connection.type == Connection.NONE) {<br>        //handle user being offline<br>    } else {<br>        console.log("Initialize Parse");<br>        appReady();<br>    }<br>} <br>.<br>+++++</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743710">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743710">40</a> by Raymond Camden
		posted on 6/26/2013 at 11:39 PM
		</div>
		<div class="comment_text"><p>Ensure you are using the latest PhoneGap SDK/JS file.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743712">41</a> by John
		posted on 5/20/2014 at 1:11 AM
		</div>
		<div class="comment_text"><p>I know this is an old post, but I came across it and tried it out but haven't been able to get it to work yet. I've tested on a local server with ripple, and even tested on a live server with ripple and the browser on my phone. I connected my <a href="http://disq.us/url?url=http%3A%2F%2Fparse.com%3A9NAZCuXuWB_KfP-1b0V6Vh4y4SA&amp;cuid=3321886" rel="nofollow noopener" title="parse.com">parse.com</a> account to it and whenever I enter my username/password and hit login it just refreshes to the login page.</p><p>Any idea what could be causing that?</p><p>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743713">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743713">42</a> by Raymond Camden
		posted on 5/20/2014 at 1:20 AM
		</div>
		<div class="comment_text"><p>Do you see anything in the console?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743709">43</a> by John
		posted on 5/20/2014 at 1:21 AM
		</div>
		<div class="comment_text"><p>No, that's the weird thing, nothing is thrown in the console, it just goes right back to the first page. I even updated to the latest version of Zepto.js</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743711">44</a> by Raymond Camden
		posted on 5/20/2014 at 1:24 AM
		</div>
		<div class="comment_text"><p>Maybe add 'preserve log' to your console settings and see if it is being cleared away. Is it online where I can run it? I can just fire deviceready manually.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743707">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743707">45</a> by John
		posted on 5/20/2014 at 1:27 AM
		</div>
		<div class="comment_text"><p>I've got it hosted online here:<a href="http://disq.us/url?url=http%3A%2F%2Fsoutharealearning.com%2Fcopy%2Findex.html%3AGF-7GkVncPn06IpFuP3ZfS8tJ-Y&amp;cuid=3321886" rel="nofollow noopener" title="http://southarealearning.com/copy/index.html">http://southarealearning.co...</a></p><p>I basically just changed the App key and JS key then uploaded it to see if it worked or not, since the custom one I built based off your tutorial wasn't working.</p><p>Thanks,</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743717">46</a> by Raymond Camden
		posted on 5/20/2014 at 7:08 AM
		</div>
		<div class="comment_text"><p>You want to make sure you install the connection plugin for PhoneGap. Did you ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743705">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743705">47</a> by John
		posted on 5/20/2014 at 4:05 PM
		</div>
		<div class="comment_text"><p>That could be what is causing the issue then, I don't know what that means, I was trying to run everything from the web, not run it through phonegap to create a stand alone app.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743706">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743706">48</a> by Raymond Camden
		posted on 5/20/2014 at 4:08 PM
		</div>
		<div class="comment_text"><p>You need to read my blog article on PG3 and plugins: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.raymondcamden.com%2Findex.cfm%2F2013%2F7%2F19%2FPhoneGap-30-Released--Things-You-Should-Know%3A6Ud7p3nuTutcZtRWDHmq1J28erg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.raymondcamden.com/index.cfm/2013/7/19/PhoneGap-30-Released--Things-You-Should-Know">http://www.raymondcamden.co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_2499572048">
	<div>
		<img src="https://disqus.com/api/users/avatars/eugeneyamnitsky.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2499572048">49</a> by Eugene
		posted on 2/6/2016 at 4:09 PM
		</div>
		<div class="comment_text"><p>Hi Raymond! Do you happen to have the full demo code around?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2499650651">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2499650651">50</a> (In reply to <a href="#c_2499572048">#49</a>) by Raymond Camden
		posted on 2/6/2016 at 5:07 PM
		</div>
		<div class="comment_text"><p>I've put it here now: <a href="http://disq.us/url?url=http%3A%2F%2Fstatic.raymondcamden.com%2Fenclosures%2Fwwwparse.zip%3AWO-A8Nkw2y9Zo_IbqDVHJvrInXc&amp;cuid=3321886" rel="nofollow noopener" title="http://static.raymondcamden.com/enclosures/wwwparse.zip">http://static.raymondcamden...</a>.</p><p>Note - I do NOT recommend doing anything with Parse now. Facebook is killing it off.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2499700597">
	<div>
		<img src="https://disqus.com/api/users/avatars/eugeneyamnitsky.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2499700597">51</a> (In reply to <a href="#c_2499650651">#50</a>) by Eugene
		posted on 2/6/2016 at 5:44 PM
		</div>
		<div class="comment_text"><p>Thanks Raymond! I'm counting on someone to deploy a commercial offering off their open source server. Worst case Azure made it possible to deploy the server on your own.</p></div>
	</div>
</div>
		