
<div class="comment" id="c_1713616256">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616256">1</a> by PaulH
		posted on 10/6/2004 at 2:29 AM
		</div>
		<div class="comment_text"><p>then how would we know when another blog was assimilated by the borg of blogs?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616257">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616257">2</a> by seancorfield
		posted on 10/6/2004 at 2:43 AM
		</div>
		<div class="comment_text"><p>The Blog link in MY TOOLS still points to the 351 release... Where's the new release?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616254">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616254">3</a> by PaulH
		posted on 10/6/2004 at 2:58 AM
		</div>
		<div class="comment_text"><p>there are 4-5 files (blog cfc,calendar,etc.) in it that were modified oct-5. i guess ray's pretty conservative with his version numbering...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616255">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616255">4</a> by Raymond Camden
		posted on 10/6/2004 at 3:03 AM
		</div>
		<div class="comment_text"><p>Paul is right. I didn't bother increasing the version number. I -did- add a new feature, a minor one, so I should have made it maybe 3.5.2 or 3.52 or whatever. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616252">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616252">5</a> by Boyzoid
		posted on 10/6/2004 at 3:49 AM
		</div>
		<div class="comment_text"><p>Ray -</p><p>What is the &lt;link rel=alternate" type="application/rss+xml" title="RSS" href="rss.cfm?mode=full" /&gt; supposed to do in FireFox&gt;?</p><p>I use FireFox almost exclusively, but did not notice a difference in the page.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616265">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616265">6</a> by Boyzoid
		posted on 10/6/2004 at 3:56 AM
		</div>
		<div class="comment_text"><p>Ray -</p><p>Disregard...I don't think that I am running a version that supports that tag.</p><p>BTW - I have ported your BlogCFC over to a layout that uses CSS for all layout and most formatting (except when the &lt;code/&gt; tag is used, the jCOmponents[<a href="http://disq.us/url?url=http%3A%2F%2Fwww.clearsoftware.net%3AzDbNRFYrtuwDi0TRGSA6dqcThAI&amp;cuid=3321886" rel="nofollow noopener" title="www.clearsoftware.net">www.clearsoftware.net</a>] and the Google ads) :-).  <a href="http://disq.us/url?url=http%3A%2F%2Fwww.boyzoid.com%3AZx3Tsk2KK_MTKJy6mH2Eic-X0lY&amp;cuid=3321886" rel="nofollow noopener" title="www.boyzoid.com">www.boyzoid.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616259">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616259">7</a> by Raymond Camden
		posted on 10/6/2004 at 4:10 AM
		</div>
		<div class="comment_text"><p>It allows you to subscribe to a RSS feed. It adds them to your bookmarks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616264">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616264">8</a> by Bob Goble
		posted on 10/6/2004 at 3:50 PM
		</div>
		<div class="comment_text"><p>I use BlogMan, I have found that everything you have been working on for almost the last year that BlogMan already has.</p><p>I've been thinking about why people like your blog over a more feature rich blog that at least to me is more elegent than your approach.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616261">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616261">9</a> by Raymond Camden
		posted on 10/6/2004 at 4:09 PM
		</div>
		<div class="comment_text"><p>Bob,</p><p>I agree. BlogMan is a great blog. However, I like to code. I often write applications that other folks have done. Not because I think I can always do it beter, but because, as I said, I like to code. I like using my own technology when I can. If you prefer BlogMan, more power to you. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616260">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616260">10</a> by seancorfield
		posted on 10/6/2004 at 6:27 PM
		</div>
		<div class="comment_text"><p>BlogMan / Blog are Windows-only which kills them instantly as far as a lot of people are concerned... They're certainly no use to me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616263">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616263">11</a> by Bob Goble
		posted on 10/6/2004 at 10:52 PM
		</div>
		<div class="comment_text"><p>Don't know what version you got but the one I have from the DRK worked like a charm for me on my Linux box.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616266">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616266">12</a> by seancorfield
		posted on 10/6/2004 at 11:08 PM
		</div>
		<div class="comment_text"><p>Ah, then we're talking about different BlogMan products I suspect...</p></div>
	</div>
</div>
		