
<div class="comment" id="c_1713662029">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662029">1</a> by Ryan Everhart
		posted on 2/7/2007 at 9:30 AM
		</div>
		<div class="comment_text"><p>Mark has put in a lot of time on the CFEclipse project, we all need to send him a big thanks!  It's a great product!</p><p>Ryan</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662010">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662010">2</a> by DK
		posted on 2/7/2007 at 7:42 PM
		</div>
		<div class="comment_text"><p>do nbrs 4 and 5 have no audio behind them? The first 3 I had to really crank it to hear. I was hoping to see something on shortcuts and macroing etc,  thats where I'm extremely weak on CFEclipse and lean more towards using G15 built ones :)</p></div>
	</div>
</div>
		