
<div class="comment" id="c_1713673727">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673727">1</a> by David Buhler
		posted on 10/29/2007 at 6:09 PM
		</div>
		<div class="comment_text"><p>I usually add an "_" or "!" if I want to float a folder to the top of a directory.</p><p>I usually add a graveyard folder as _graveyard, and if I am on a server with a shared database, I add my Datasource as !datasource. This way, I'm first on the list (before all the people with "A's".</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673709">2</a> by Nathan D
		posted on 3/29/2010 at 11:21 AM
		</div>
		<div class="comment_text"><p>Thankfully, this bit of wisdom came in handy once again -- I used Google to figure out WTF was up with my install, and sure enough, I had already faced this same problem 2.5 years earlier ;)</p></div>
	</div>
</div>
		