
<div class="comment" id="c_1713732203">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732203">1</a> by Michael Santoroski
		posted on 5/10/2011 at 5:24 PM
		</div>
		<div class="comment_text"><p>We have been using Peter Freitag's implementation of Textile and it works really well. It's more "natural language" than HTML.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.textism.com%2Ftools%2Ftextile%2F%3AuzOaDviXvwxtbUoQYfp-ReNePN0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.textism.com/tools/textile/">http://www.textism.com/tool...</a></p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.petefreitag.com%2Fitem%2F540.cfm%3AgCIBU69jSi27zCvMuhPBGYtjezo&amp;cuid=3321886" rel="nofollow noopener" title="http://www.petefreitag.com/item/540.cfm">http://www.petefreitag.com/...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732204">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732204">2</a> by Henry
		posted on 5/12/2011 at 2:56 AM
		</div>
		<div class="comment_text"><p>Oh, guess what, There's a ColdBox Plugin for Markdown.<br><a href="http://disq.us/url?url=http%3A%2F%2Fcoldbox.org%2Fforgebox%2Fview%2FMarkdown%3AvEoTF1SjAMK053fqG0NR2TxYwZ8&amp;cuid=3321886" rel="nofollow noopener" title="http://coldbox.org/forgebox/view/Markdown">http://coldbox.org/forgebox...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732206">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732206">3</a> by Irvin
		posted on 11/9/2011 at 7:05 AM
		</div>
		<div class="comment_text"><p>It seems Ben Forta's ParagraphFormat2 function does not work as described by him - a cursory glance at the code reveals that at no point is anything replaced by a p tag (opening or closing).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732205">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732205">4</a> by Raymond Camden
		posted on 11/9/2011 at 7:28 AM
		</div>
		<div class="comment_text"><p>That's just a case of the description being a bit out of date. The idea was to work better than the built in paragraphformat, and it does. :)</p></div>
	</div>
</div>
		