
<div class="comment" id="c_2124545305">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2124545305">1</a> by Robert Zehnder
		posted on 7/8/2015 at 6:39 PM
		</div>
		<div class="comment_text"><p>All the slugs appear to be an-article-about-foo (on surge). The title appears right on the page when you link off, but it seems a bit...  strange.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2124864831">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2124864831">2</a> (In reply to <a href="#c_2124545305">#1</a>) by Raymond Camden
		posted on 7/8/2015 at 8:07 PM
		</div>
		<div class="comment_text"><p>Totally not related - just me being lazy on the slugs. But do you think it will confuse people?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2124907343">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2124907343">3</a> (In reply to <a href="#c_2124864831">#2</a>) by Robert Zehnder
		posted on 7/8/2015 at 8:19 PM
		</div>
		<div class="comment_text"><p>Honestly, most people wouldn't even notice it :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_2124923205">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2124923205">4</a> (In reply to <a href="#c_2124907343">#3</a>) by Raymond Camden
		posted on 7/8/2015 at 8:24 PM
		</div>
		<div class="comment_text"><p>Ok, if someone else comments I'll change a few.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2236497316">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_OGqHjaVtSG.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2236497316">5</a> by алик
		posted on 9/4/2015 at 7:48 PM
		</div>
		<div class="comment_text"><p>But what if you ll reach the inode numbers limit with all that articles in small billions directories?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2237340720">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2237340720">6</a> (In reply to <a href="#c_2236497316">#5</a>) by Raymond Camden
		posted on 9/5/2015 at 10:23 AM
		</div>
		<div class="comment_text"><p>Eh? Billions of directories? I've been blogging for 10+ years and have 5.5K blog entries.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2237836330">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_OGqHjaVtSG.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2237836330">7</a> (In reply to <a href="#c_2237340720">#6</a>) by алик
		posted on 9/5/2015 at 5:38 PM
		</div>
		<div class="comment_text"><p>And how about inode numbers on the server side? Linux.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2239940747">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2239940747">8</a> (In reply to <a href="#c_2237836330">#7</a>) by Raymond Camden
		posted on 9/7/2015 at 2:58 AM
		</div>
		<div class="comment_text"><p>I honestly don't quite get what you mean. If the static site got so large it was hitting some OS limit, then, I guess your screwed, but as I said, even my 10 year old blog with 5K blog entries wouldn't hit that. Static sites aren't necessarily for *every* situation.</p></div>
	</div>
</div>
		