
<div class="comment" id="c_1713616480">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616480">1</a> by JesterXL
		posted on 10/29/2004 at 11:19 PM
		</div>
		<div class="comment_text"><p>Whateva' hatah'!!!  Tales of Symphonia rocked the house; so does Super Smash Brothers as a party game.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713616496">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713616496">2</a> by david
		posted on 11/3/2004 at 3:12 AM
		</div>
		<div class="comment_text"><p>i agree some people hide the fact that companies apologize, and gamecube does indeed, suck.</p></div>
	</div>
</div>
		