
<div class="comment" id="c_1713739933">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739933">1</a> by Phillip Senn
		posted on 3/22/2012 at 12:41 AM
		</div>
		<div class="comment_text"><p>I might have just gotten a new avatar.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739941">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739941">2</a> by Raymond Camden
		posted on 3/22/2012 at 12:51 AM
		</div>
		<div class="comment_text"><p>Eh?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739938">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739938">3</a> by Phillip Senn
		posted on 3/22/2012 at 1:16 AM
		</div>
		<div class="comment_text"><p>Baby seal.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739942">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739942">4</a> by Joshua Gonzalez
		posted on 3/22/2012 at 2:49 AM
		</div>
		<div class="comment_text"><p>The jQuery mobile presentation was helpful and highly entertaining. More presenters need to follow your steps in-regards to presenting.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739939">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739939">5</a> by Raymond Camden
		posted on 3/22/2012 at 3:20 AM
		</div>
		<div class="comment_text"><p>@Phillip: Ah, heh, well, you had to be there for it to make sense. :)</p><p>@Joshua: Thank you!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739957">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739957">6</a> by Scott Busche
		posted on 3/22/2012 at 10:00 PM
		</div>
		<div class="comment_text"><p>For anyone that's not familiar with DevNexus, the presentations are on jQuery Mobile and Phonegap.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739943">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739943">7</a> by Raymond Camden
		posted on 3/22/2012 at 10:01 PM
		</div>
		<div class="comment_text"><p>Heh, I figured no one else would care. ;)</p></div>
	</div>
</div>
		