
<div class="comment" id="c_1713620144">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620144">1</a> by Michael
		posted on 8/19/2005 at 9:58 AM
		</div>
		<div class="comment_text"><p>Hmm.. I think I got 3 actually ;)<br>BUT, the thought of unsubscribing didn't even cross my mind.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620147">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620147">2</a> by Raymond Camden
		posted on 8/20/2005 at 12:56 AM
		</div>
		<div class="comment_text"><p>Heh, I got a few... not so happy emails from folks, but in general most people just let me know.</p></div>
	</div>
</div>
		