
<div class="comment" id="c_1713623659">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623659">1</a> by Seth Petry-Johnson
		posted on 12/24/2005 at 7:10 PM
		</div>
		<div class="comment_text"><p>FWIW I remember Spectra.  Well, at least I remember READING ABOUT Spectra in CFDJ.  Never did get a chance to use it :(</p><p>Merry Christmas!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623662">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623662">2</a> by Jeff
		posted on 12/24/2005 at 8:24 PM
		</div>
		<div class="comment_text"><p>Nowhere in your code do you have a "cf_foo" which may make your explanation of the code confusing to some (like me)</p><p> Where exactly does CF return to after hitting the exit?  I think you meant "cf_looper" in your desciprion text.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623656">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623656">3</a> by Raymond Camden
		posted on 12/24/2005 at 9:12 PM
		</div>
		<div class="comment_text"><p>Ah yes, where I say cf_foo, I meant cf_looper. So right, when the cfexit is run, we go back to the "middle" portion, the stuff after the starting cf_looper tag. Basically we rerun the middle and the end again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623664">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623664">4</a> by Patrick McElhaney
		posted on 12/27/2005 at 5:46 PM
		</div>
		<div class="comment_text"><p>Thanks for the reminder.</p><p>I haven't thought about custom tags much since I started using CFCs, but this could come in handy. For example, we could make a cf_foreach tag to loop over the elements in a Java collection.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623665">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623665">5</a> by Adam Cameron
		posted on 8/14/2010 at 4:59 PM
		</div>
		<div class="comment_text"><p>Ray, you are a star.</p><p>I've been confronted with a requirement to do a "repeater" sort of construct with a custom tag which before I started looking at it I thought "yeah, how hard can that be?  All one needs to do is... is... [voice trails off]... umm...", then - despite having been doing CF for about ten years now - I realised I had never had to do this before and had no idea how to get it to work.  And the CF docs were no bl**dy use whatsoever.</p><p>My initial approach of bashing my head against the wall and swearing at my code a lot didn't work too well, but then with the assistance of Google &amp; your blog, I've got it working.</p><p>Thanks mate.  That's yet another beer I owe you.</p><p>-- <br>Adam</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623661">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623661">6</a> by Raymond Camden
		posted on 8/14/2010 at 5:15 PM
		</div>
		<div class="comment_text"><p>You're lucky I'm a light weight - 3 beers in and you can tell me we are caught up. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623663">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623663">7</a> by Adam Cameron
		posted on 8/14/2010 at 6:17 PM
		</div>
		<div class="comment_text"><p>I seem to recall you had a few more than three last time we sat down.  Well *I* certainly had a few more than three... and you seemed to be keeping up... ;-)</p><p>-- <br>Adam</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623657">8</a> by Raymond Camden
		posted on 8/14/2010 at 6:18 PM
		</div>
		<div class="comment_text"><p>Heh, true - I've had "practice" for a few years. :)</p></div>
	</div>
</div>
		