
<div class="comment" id="c_1713738898">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738898">1</a> by Todd Rafferty
		posted on 1/30/2012 at 10:47 PM
		</div>
		<div class="comment_text"><p>Apparently you haven't used the email app on the iPad either. It's the same interface. I guess they're just following an annoying standard that has already been established.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738912">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738912">2</a> by Ryan Vikander
		posted on 1/30/2012 at 10:56 PM
		</div>
		<div class="comment_text"><p>That's actually a common theme for frames in iOS apps. If you look at twitter, facebook, heck even the built in email client the frame doesn't show up unless you click the button in the top left and then when you flip it landscape view it looks fine. I usually use my iPad in landscape anyways.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738913">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738913">3</a> by Terry Sampson
		posted on 1/30/2012 at 11:16 PM
		</div>
		<div class="comment_text"><p>I'd check to see which mobile device is accessing my pages and switch accordingly to compose the view. I use dynamic CSS (&lt;div&gt;&lt;/div&gt; tags) to allow for expansion on the white space so it auto stretches the blank space as needed (as in this case where the space is pre-configured to the length of the largest drop down). Not hard to do in CSS for mobile, but not easy either. On most it works on some it does not.</p><p>My guess is that they also messed up on the DTD for I-Pads. While most mobile devices use the DTD for mobile sites, I also include the basic web DTD as well for I-Pad. This seems to help on my mobile developed sites.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738915">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738915">4</a> by Andrew Scott
		posted on 1/31/2012 at 12:07 AM
		</div>
		<div class="comment_text"><p>I am guessing that this was designed for mobiles first, and nothing was changed for it to run on the tablet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738923">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738923">5</a> by Terry Sampson
		posted on 1/31/2012 at 12:11 AM
		</div>
		<div class="comment_text"><p>Totally Andrew.</p><p>I still remember the days when I had to build two websites for one product. One for IE and one for Netscape! Both in seperate folders</p><p>Ah! Thise were the days.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738917">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738917">6</a> by Andrew Scott
		posted on 1/31/2012 at 12:12 AM
		</div>
		<div class="comment_text"><p>no comment, except what a pain those days where.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738918">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738918">7</a> by Nick Collins
		posted on 1/31/2012 at 1:37 AM
		</div>
		<div class="comment_text"><p>That is why we bill by the hour. :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738921">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738921">8</a> by Michael Long
		posted on 1/31/2012 at 2:29 AM
		</div>
		<div class="comment_text"><p>The simplest possible way to make an iPhone app "work" on an iPad is to add your existing list screen and detail screen to a standard split view controller. (That's portrait/menu, landscape/side-by-side view shown in your example.)</p><p>Boom. A couple of hours work, and you're now iPad compatible.</p><p>Either they're working on an iPad-specific app, and this is just a placeholder until it's done... or they're incredibly lazy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738920">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738920">9</a> by Terry Sampson
		posted on 1/31/2012 at 5:18 PM
		</div>
		<div class="comment_text"><p>Also there are plenty of cyber aids out there to test mobile apps. Why not use one of those?</p><p>My favourite is <a href="http://disq.us/url?url=http%3A%2F%2Fwww.mobilephoneemulator.com%2F%3AdWTlcDt_nksftqkTZdPDhahC2vE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.mobilephoneemulator.com/">http://www.mobilephoneemula...</a> by Pixmobi</p><p>You set the size of your screen and run the mobile site on it. <br>You can change the settings and use different browsers to test as well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738919">10</a> by Gareth Arch
		posted on 1/31/2012 at 11:31 PM
		</div>
		<div class="comment_text"><p>This is the standard for the SplitViewNavigator in Flex Mobile</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fdevgirl.org%2F2011%2F12%2F01%2Fflex-mobile-development-splitviewnavigator-tutorial%2F%3AjRWRgep3Stz-ZdaaWx7DyQN5QpE&amp;cuid=3321886" rel="nofollow noopener" title="http://devgirl.org/2011/12/01/flex-mobile-development-splitviewnavigator-tutorial/">http://devgirl.org/2011/12/...</a></p><p>It certainly makes development quicker.  I've used the same method on one app I wrote.  I managed it manually for the 2nd app I wrote, but this (as others have said) does seem pretty standard.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738925">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738925">11</a> by Raymond Camden
		posted on 2/1/2012 at 12:06 AM
		</div>
		<div class="comment_text"><p>Gareth - I have no issue with the UI per se - but in this case, they didn't use it correctly. The itinerary could have been put on the main view, and some other content in the pop up.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738922">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738922">12</a> by Gareth Arch
		posted on 2/1/2012 at 12:12 AM
		</div>
		<div class="comment_text"><p>I didn't know if it was a Flex Mobile app styled in the Apple Theme though.  If so, the setup of what shows there is somewhat set (unless you manually alter it).  I agree that perhaps they could've chosen better content, but the default is adding the method calls and attributes of  "showFirstViewNavigatorInPopUp" and "autoHideFirstViewNavigator"  Definitely a very lazy way to switch from portait to landscape and have all of your navigation handled for you, but perhaps they went the quick 'n' easy way :)</p></div>
	</div>
</div>
		