
<div class="comment" id="c_1713719246">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719246">1</a> by Ryan Vikander
		posted on 10/27/2009 at 12:47 AM
		</div>
		<div class="comment_text"><p>I restarted the campaign because I haven't picked it up in maybe a month or so, so I wanted to begin from the beginning just so the story is fresh in my mind. But I definitely agree that the story is strong. It is a very different game from the other Halos. This one you can't just go run around with your gun in hand (I still forget that everytime I start a new level). Also the one thing I don't care for as the Rookie is some levels I have a hard time finding the beacon and once was stuck on one level for almost an hour before turning it off because we couldn't move on. Maybe I had missed something previously that wasn't triggering the beacon.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719248">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719248">2</a> by Raymond Camden
		posted on 10/27/2009 at 12:53 AM
		</div>
		<div class="comment_text"><p>Ryan, good point on the beacon. That is definitely one negative for the game. I got stuck too - but just for 5 minutes. It's funny- Halo3 also suffered from 'where do I go next' syndrome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719250">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719250">3</a> by Ryan Vikander
		posted on 10/27/2009 at 12:59 AM
		</div>
		<div class="comment_text"><p>I had the same issues with Halo 1. I wondered around the snowy levels for ever trying to find the trigger for the next part. Atleast with ODST it was helpful to know my checklist of items that I needed to do and the waypoints and the map was really helpful.</p><p>The thing I like best about Halo 3's campaign is that you can do MP online. We used to run the Halo 3's campaign every Sunday with skulls turned on and scoring on and see who could get the best scores. I don't know it's just a fun twist to a short campaign.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719261">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719261">4</a> by Usul
		posted on 10/27/2009 at 6:34 PM
		</div>
		<div class="comment_text"><p>"I wish I could invite my readers to come kill me online"</p><p>The best feature of ODST I think is the firefight mode multiplayer. Instead of just killing each other, you and 3 other people can get together to fend off never ending hordes of enemies. It's pretty fun especially because you get to see killtaculars a lot more often :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719262">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719262">5</a> by DanaK
		posted on 10/27/2009 at 7:29 PM
		</div>
		<div class="comment_text"><p>Ray - have you seen Brutal Legend at all? I'd recommend trying that one out. I had a blast playing it SP. It's a mixture of hack n slash, rts, driving, and mmo open world styles.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713719259">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713719259">6</a> by Raymond Camden
		posted on 10/27/2009 at 7:30 PM
		</div>
		<div class="comment_text"><p>I've seen it - but I have to say - it looks pretty stupid to me.</p></div>
	</div>
</div>
		