
<div class="comment" id="c_1713711480">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711480">1</a> by Abhishek
		posted on 1/15/2009 at 2:08 PM
		</div>
		<div class="comment_text"><p>Thank you Raymond, solution given by you worked for me. Its been a great help.<br>Thanks so much..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711483">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711483">2</a> by Francois Levesque
		posted on 1/15/2009 at 7:36 PM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>I've used this solution in the past also for serving up cfcharts via AJAX. That way, I only need to send the link to the image file, rather than a savedcontent of the generated markup. I can then modify the src of the img tag and the image reloads seamlessly.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711482">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711482">3</a> by larry c. lyons
		posted on 1/15/2009 at 7:52 PM
		</div>
		<div class="comment_text"><p>thanks Ray, this is very useful (working on something similar) but I've a dumb question, I take it in<br>&lt;cfset fileWrite(savedFile,chart)&gt;<br>fileWrite is a UDF?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711486">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711486">4</a> by Raymond Camden
		posted on 1/15/2009 at 7:54 PM
		</div>
		<div class="comment_text"><p>@Larry - thats a CF8 function.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711488">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711488">5</a> by larry c. lyons
		posted on 1/15/2009 at 8:03 PM
		</div>
		<div class="comment_text"><p>Strange it never showed up in cfquickdocs. needless to say d'oh</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711492">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711492">6</a> by RobW
		posted on 1/16/2009 at 5:37 AM
		</div>
		<div class="comment_text"><p>Another good reason to use cfmailparam tag and an inline image is that, increasingly mail clients won't display images that are linked from a website in order to cut down on spam. So your recipient gets a big blank spot in the e-mail and your e-mail format gets ruined.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711495">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711495">7</a> by Steve
		posted on 1/16/2009 at 1:00 PM
		</div>
		<div class="comment_text"><p>This is rad even for a man of the dark side.  I will definitely be testing this tomorrow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711493">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711493">8</a> by Ray Meade
		posted on 1/5/2010 at 11:22 PM
		</div>
		<div class="comment_text"><p>I tried this and for some reason the image doesn't show up on the web page. (although it does show up in the email...go figure)  When I right-click it and select "View Image" I get an error that says:</p><p>"Firefox doesn't know how to open this address, because the protocol (cid) isn't associated with any program."</p><p>Any suggestions?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713711494">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713711494">9</a> by Raymond Camden
		posted on 1/5/2010 at 11:29 PM
		</div>
		<div class="comment_text"><p>Because the cid is valid in email only, not the web. If you want the image to show up on the web, you need to use img src with the http protocol.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1858631219">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_it501Gisz4.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1858631219">10</a> by Sandi S
		posted on 2/16/2015 at 8:11 PM
		</div>
		<div class="comment_text"><p>Thanks Ray, still helping people all these years later!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1858650591">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1858650591">11</a> (In reply to <a href="#c_1858631219">#10</a>) by Raymond Camden
		posted on 2/16/2015 at 8:23 PM
		</div>
		<div class="comment_text"><p>Glad it was still useful for you.</p></div>
	</div>
</div>
		