
<div class="comment" id="c_1713680647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680647">1</a> by kd
		posted on 5/5/2008 at 8:21 PM
		</div>
		<div class="comment_text"><p>so is model-glue and machii and fusebox "framework frameworks"?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680624">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680624">2</a> by Laura Norris
		posted on 5/5/2008 at 9:00 PM
		</div>
		<div class="comment_text"><p>Does unicorn herder pay more?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680643">3</a> by Kevin Slane
		posted on 5/5/2008 at 9:07 PM
		</div>
		<div class="comment_text"><p>I guess we'll all need new business cards now.</p><p>What is the street value of unicorn meat these days?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680640">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680640">4</a> by Charlie Arehart
		posted on 5/5/2008 at 9:35 PM
		</div>
		<div class="comment_text"><p>b-a-a-h</p><p>Herd us Obiwan, you're our only hope. :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680644">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680644">5</a> by Richard Bremner
		posted on 5/5/2008 at 9:43 PM
		</div>
		<div class="comment_text"><p>The moon is made of green cheese.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680645">6</a> by Simon Romanski
		posted on 5/5/2008 at 10:15 PM
		</div>
		<div class="comment_text"><p>Does this then make us Java programmers? That's pretty cool.. we're now at the number 1 spot on Tiobe's language list! Us CF developers shouldn't worry about placement on a list. Our productivity and enthusiasm speaks for itself. Don't go after the development community, instead just find the people who are in need of a solution. That's what we CFers do best.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680646">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680646">7</a> by Jim Ruzicka
		posted on 5/5/2008 at 10:33 PM
		</div>
		<div class="comment_text"><p>Guess its back to Jedi training then!</p><p>Even if Tiobe's have no creditability, you know some business owners will see that their technology is not on this list and ask what am I doing using it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680627">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680627">8</a> by Charlie Arehart
		posted on 5/5/2008 at 10:49 PM
		</div>
		<div class="comment_text"><p>Hey just a follow-up: in my hurry to make a quip (and get bonus points from Ray for the Star wars reference), I failed to address the issue at hand, Tiobe's misguided removal of CF from its list of languages. I would have understood them renaming it to CFML, and I've emailed them (as we all should) to suggest that.</p><p>I'd just not yet seen Ben's blog entry when I last wrote, and since Ray didn't link to it, I read it after finishing my first comment above. Here's Ben's entry for those it may help:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.forta.com%2Fblog%2Findex.cfm%2F2008%2F5%2F5%2FTIOBE-From-Hype-To-Fiction%3A1hsVko3_orc4ydUDLYxJCNwA7DA&amp;cuid=3321886" rel="nofollow noopener" title="http://www.forta.com/blog/index.cfm/2008/5/5/TIOBE-From-Hype-To-Fiction">http://www.forta.com/blog/i...</a></p><p>Check out the comments for an email address to send to.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680629">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680629">9</a> by doug sims
		posted on 5/6/2008 at 12:56 AM
		</div>
		<div class="comment_text"><p>they didnt delete all the history yet:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.tiobe.com%2Fcontent%2Fpaperinfo%2Ftpci%2FColdFusion.html%3AO-2lQtIoFDyE0srlbK9LCoC1Ydk&amp;cuid=3321886" rel="nofollow noopener" title="http://www.tiobe.com/content/paperinfo/tpci/ColdFusion.html">http://www.tiobe.com/conten...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680628">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680628">10</a> by Kevin Sargent
		posted on 5/6/2008 at 1:33 AM
		</div>
		<div class="comment_text"><p>I just love how 'technical' people can be so ignorant. O-well. moon = cheese, earth = flat, etc...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680631">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680631">11</a> by Kevin Sargent
		posted on 5/6/2008 at 1:35 AM
		</div>
		<div class="comment_text"><p>Oh, Ben...</p><p>I've been having trouble cleaning up after our small herd of unicorns back at the ranch. any tips?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680626">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680626">12</a> by David McGuigan
		posted on 5/6/2008 at 9:27 AM
		</div>
		<div class="comment_text"><p>I don't know. Marker-upper sounds kind of prestigious to me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680635">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680635">13</a> by Edward Beckett
		posted on 5/6/2008 at 2:08 PM
		</div>
		<div class="comment_text"><p>From the May TIOBE Index Headlines ...</p><p> "May Headline: PowerShell on its way to the top 20 ... "</p><p>WTF?</p><p>Microsoft's definition of Powershell ...</p><p>"Windows PowerShell, formerly code-named Monad, is an interactive command-line and task-based &lt;strong&gt;scripting technology&lt;/strong&gt; ... "</p><p>Quality Score of TIOBE's Credibility = 0</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680632">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680632">14</a> by Jeffrey Price
		posted on 5/6/2008 at 4:36 PM
		</div>
		<div class="comment_text"><p>I'm waiting for Delphi to be delisted because it is also a framework, or more specifically an environment.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fdelphi.about.com%2Fcs%2Fazindex%2Fa%2Fblnewcomers.htm%3A_BVRZxc4571E2-q-GSqxlfJvfGk&amp;cuid=3321886" rel="nofollow noopener" title="http://delphi.about.com/cs/azindex/a/blnewcomers.htm">http://delphi.about.com/cs/...</a></p><p>"CodeGear (Borland subsidiary) Delphi is an object-oriented, visual programming environment to develop 32-bit and Microsoft .NET applications for deployment on the Internet, Windows and Linux."</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680630">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680630">15</a> by Edward Beckett
		posted on 5/6/2008 at 5:09 PM
		</div>
		<div class="comment_text"><p>@bremner</p><p>"The moon is made of green cheese. "</p><p>So, what are you a lobbyist of some sort? Or ...</p><p>Someone that thinks about what they say ...</p><p>very well ...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680633">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680633">16</a> by Adam Ness
		posted on 5/7/2008 at 1:26 AM
		</div>
		<div class="comment_text"><p>Well, they're right I suppose, in the same way that PHP is just a framework to run C code.  And Perl is just a framework to run C code, and Python, Ruby, etc..  And for that matter, C is just a framework to write Machine code.</p><p>I wonder if they've ever heard of BlueDragon.NET, which doesn't even run on on Java.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680649">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680649">17</a> by Richard Bremner III
		posted on 5/7/2008 at 9:37 PM
		</div>
		<div class="comment_text"><p>@Edward Not to defend the guy that is so important to TIOBE but the posting could have been entered by anyone.</p><p>BTW In case is not clear I'm not Richard Bremner, just making a point by entering things under that name.</p><p>how come this person doesn't show up anywhere? His name is the same as an Actor ( please tell me is not him) and if you google for "Richard Bremner TIOBE" all the results are from the CF community? what has this guy done to have such creditibility factor at TIOBE?</p><p>Not that I care but really pisses me off when a coworker comes and starts talking about the stupid list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680651">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680651">18</a> by Edward Beckett
		posted on 5/7/2008 at 10:09 PM
		</div>
		<div class="comment_text"><p>Very Nice ...</p><p>I think I'll leave the witch-hunt now ...</p><p>To work on some CF programming ...</p><p>: )</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713680653">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713680653">19</a> by Ali
		posted on 5/9/2008 at 12:20 AM
		</div>
		<div class="comment_text"><p>Thank Zeus, for the fact that none of my employers in the last 10 years have relied on stats from TIOBE, or any such site in giving me a job.</p><p>Also, I'm grateful that top government agencies, federal, state, and local, use CF pretty much ubiquitously.</p><p>I guess they didn't get the memo either.<br>Just looking at the GotCFM website, shows how widespread ColdFusion is throughout various industries.</p><p>In my experience, and it's proven right here, I have seen PHP coders the most rabidly anti-CF.<br>This is reflected in the fact that TIOBE's own website is written in PHP and they obviously have ranked PHP in the top 10.</p></div>
	</div>
</div>
		