
<div class="comment" id="c_1713655274">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655274">1</a> by Simon Horwith
		posted on 7/24/2006 at 5:12 PM
		</div>
		<div class="comment_text"><p>The course has changed a bit since you last taught it, Ray... but it's still a great class. Personally, I always have a lot of fun teaching both FastTrack to ColdFusion and the sequel - Advanced ColdFusion for Developers. The training folks at Adobe (many of whom are the core training staff from Allaire) are really good at their job.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655289">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655289">2</a> by Raymond Camden
		posted on 7/24/2006 at 5:14 PM
		</div>
		<div class="comment_text"><p>I still remember my test to be certified. It was scary. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655295">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655295">3</a> by Christopher Wigginton
		posted on 7/24/2006 at 6:49 PM
		</div>
		<div class="comment_text"><p>Now you're talking. A combination cooking Cajun Class and learning ColdFusion at the same time.</p><p>In this class you'll learn to throw down a big pot of Gumbo with all the fixin's, andouille sausage, the holy trinity (food, not the faith), nice rich brown and nutty roux and just enough Cayenne pepper to get your endorphins flowing.</p><p>Then, while you're brain is a buzzin, get on the fast track to ColdFusion and learn a framework or two.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655294">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655294">4</a> by Robert Owen
		posted on 7/24/2006 at 11:05 PM
		</div>
		<div class="comment_text"><p>Yeah, you could call it the Coldfusion Cajun Cookoff. I'll sign-up! When and how much!?!?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655296">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655296">5</a> by Raymond Camden
		posted on 7/24/2006 at 11:11 PM
		</div>
		<div class="comment_text"><p>I'll trade professional training for any company for one flat screen HD tv. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655297">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655297">6</a> by Jen
		posted on 7/25/2006 at 1:03 AM
		</div>
		<div class="comment_text"><p>Is that *Onsite* training? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713655306">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713655306">7</a> by Raymond Camden
		posted on 7/25/2006 at 1:13 AM
		</div>
		<div class="comment_text"><p>I'll make you a deal. Any company that gets me a HDTV in exchange for onsite training will get some _dang_ good meals out of it. :) My wife is an awesome cook. If you _think_ you know Cajun food, your in for a surprise. ;)</p></div>
	</div>
</div>
		