
<div class="comment" id="c_1713676497">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676497">1</a> by Chad
		posted on 1/22/2008 at 10:21 PM
		</div>
		<div class="comment_text"><p>Congrats Chris!</p><p>How about a top 3 Ray?  If my math is right i hit 3%.  Time for more exercise!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676515">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676515">2</a> by Raymond Camden
		posted on 1/22/2008 at 10:26 PM
		</div>
		<div class="comment_text"><p>Top 3 would be too much work. ;) I'll consider that for next week.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676514">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676514">3</a> by Gareth
		posted on 1/22/2008 at 11:15 PM
		</div>
		<div class="comment_text"><p>The first time I've been happy to be below average :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676511">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676511">4</a> by Justice
		posted on 1/22/2008 at 11:25 PM
		</div>
		<div class="comment_text"><p>(I am Chris for those who dont know Justice)</p><p>I imagine something about taking nearly 250 lbs and making it jump hundreds of times while playing DDR burns a few calories, and with a radical diet change its making a huge difference for me.  My pants feel more loose already!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676519">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676519">5</a> by Nick
		posted on 1/23/2008 at 12:18 AM
		</div>
		<div class="comment_text"><p>Top 3 is easy cakes Ray, c'mon now.</p><p>Try managing my Frolf League. You can see my graphs at my site.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.mindofneeko.com%3Aba8B8f26uzRsFA45xIYbBHr6T7U&amp;cuid=3321886" rel="nofollow noopener" title="http://www.mindofneeko.com">http://www.mindofneeko.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676518">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676518">6</a> by David McGuigan
		posted on 1/23/2008 at 6:00 AM
		</div>
		<div class="comment_text"><p>Is there a site to join in the contest?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676522">7</a> by David McGuigan
		posted on 1/23/2008 at 6:45 AM
		</div>
		<div class="comment_text"><p>Ignore that. I just found the first entry. For some reason when I googled "ColdFusion Biggest Loser" from my iPhone about a half hour ago Google flagged me as some kind of malicious robot and withheld my search results.</p><p>I've been looking for some quality, competitive motivation to get in better shape for a while now, and this is totally it. Game on.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676524">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676524">8</a> by Raymond Camden
		posted on 1/23/2008 at 6:52 AM
		</div>
		<div class="comment_text"><p>Be sure to email me and send me your weight. If you knew your weight last Monday, reat, if not, send me your weight from yesterday.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676521">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676521">9</a> by David McGuigan
		posted on 1/23/2008 at 7:06 AM
		</div>
		<div class="comment_text"><p>The coolest thing ever would be before and after pictures. I think it should even be a requirement since legitimate prizes are at stake. Front and side.</p><p>I'm just saying, 11 lbs. in one week? That's incredible. But if someone's going to take my CFWACK 8.2 and $40 giftcared I'd like to see proof hee hee.</p><p>Weight's in the mail.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676523">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676523">10</a> by David McGuigan
		posted on 1/23/2008 at 7:15 AM
		</div>
		<div class="comment_text"><p>Last question. Are liposuction and other similar techniques against the rules or are they not?</p><p>Dying to know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676525">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676525">11</a> by Raymond Camden
		posted on 1/23/2008 at 7:19 AM
		</div>
		<div class="comment_text"><p>If you video tape it and post it, it is allowed.</p></div>
	</div>
</div>
		