
<div class="comment" id="c_1713681698">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681698">1</a> by Dan Wilson
		posted on 6/11/2008 at 10:00 PM
		</div>
		<div class="comment_text"><p>Hey!</p><p>That looks HOT!</p><p>I'm updating from SVN as we speak!</p><p>DW</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681711">2</a> by Allen
		posted on 6/12/2008 at 2:42 AM
		</div>
		<div class="comment_text"><p>I'm not sure how that much code to simply let it know about a custom even "kicks butt".  Then again, I'm a bit old fashioned and don't think XML should be used for anything other than actual data.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681712">3</a> by Raymond Camden
		posted on 6/12/2008 at 5:40 AM
		</div>
		<div class="comment_text"><p>@Allen - In the past, you had to redirect to a display template, broadcast security on every secured method, etc, so this actually cuts down on a lot of code. I'm surprised you think the XML up there is a lot. The display template is 8 lines of code - used once.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681714">4</a> by Chris H
		posted on 6/12/2008 at 11:44 AM
		</div>
		<div class="comment_text"><p>sweet stuff, thanks for the info Ray</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681713">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681713">5</a> by Sameer Gupta
		posted on 6/12/2008 at 4:43 PM
		</div>
		<div class="comment_text"><p>makes by day</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713681715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713681715">6</a> by Jeremy Prevost
		posted on 6/12/2008 at 9:41 PM
		</div>
		<div class="comment_text"><p>Excellent.</p></div>
	</div>
</div>
		