
<div class="comment" id="c_1713614589">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614589">1</a> by Rob Brooks-Bilson
		posted on 6/2/2003 at 6:50 PM
		</div>
		<div class="comment_text"><p>Ray, it looks like the link to your updated PLP code is actually linking to your <a href="http://disq.us/url?url=http%3A%2F%2Fblog.zip%3Ajv3oe85pIMLMbZhgqID3FfTAdGM&amp;cuid=3321886" rel="nofollow noopener" title="blog.zip">blog.zip</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614592">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614592">2</a> by Raymond Camden
		posted on 6/2/2003 at 6:52 PM
		</div>
		<div class="comment_text"><p>Fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614596">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614596">3</a> by Rob Brooks-Bilson
		posted on 6/2/2003 at 7:06 PM
		</div>
		<div class="comment_text"><p>Ray, one more thing.  How does your PLP tag differ from the oneMike Nimer includes in his CMSToolkik:  <a href="http://disq.us/url?url=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcmstoolkit%3AyWawlJfAVCeyEH0GpTs2ce8JElQ&amp;cuid=3321886" rel="nofollow noopener" title="http://sourceforge.net/projects/cmstoolkit">http://sourceforge.net/proj...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614591">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614591">4</a> by Raymond Camden
		posted on 6/2/2003 at 7:38 PM
		</div>
		<div class="comment_text"><p>Rob, I purposely tried to avoid looking at his project, so it wouldn''t seem like I was copying him. Since both projects are ''free'', it''s not a big deal. If someone comes to me and says that his does Foo and mine should too, I''ll add it. Right now, the code does everything -I- think it should - that''s why I''m hoping I get good feedback from people who actually use it. :)</p></div>
	</div>
</div>
		