
<div class="comment" id="c_1713733795">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733795">1</a> by Gene
		posted on 6/24/2011 at 8:49 PM
		</div>
		<div class="comment_text"><p>Just downloaded it. I am really looking forward to this book. Once I have read it I will get back and give a short review.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733808">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733808">2</a> by Phillip Senn
		posted on 6/24/2011 at 9:22 PM
		</div>
		<div class="comment_text"><p>Dreamweaver uses 1.0a3 in the insert toolbar.  Is there a way to update that in DW?  Or to say "always use the latest version"?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733807">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733807">3</a> by Raymond Camden
		posted on 6/24/2011 at 10:09 PM
		</div>
		<div class="comment_text"><p>The web site is down now - but check this Phillip -</p><p>Ugh - my own spam blocker is stopping me. Let me try a short link.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fgoo.gl%2FL43Ez%3AQxsquSOswROvdgBApG4N1GR3giU&amp;cuid=3321886" rel="nofollow noopener" title="http://goo.gl/L43Ez">http://goo.gl/L43Ez</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733809">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733809">4</a> by Jeff Coughlin
		posted on 7/1/2011 at 8:19 AM
		</div>
		<div class="comment_text"><p>That link is still dead, however Greg wrote a simple how-to for updating the libraries in DW.  Seems pretty simple and straight forward.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fbit.ly%2FjfELWM%3A3xZQXMMoftZhqpHI9vE3JP8omZw&amp;cuid=3321886" rel="nofollow noopener" title="http://bit.ly/jfELWM">http://bit.ly/jfELWM</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733805">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733805">5</a> by Raymond Camden
		posted on 7/1/2011 at 2:53 PM
		</div>
		<div class="comment_text"><p>I haven't tested this yet - but I'm worried that that update only helps with code assist in JS. I don't believe it helps with code assist in tags. So for example, you can do data- in DW and get a drop down of JQM related items. I've been  trying to reach the DW PM to confirm (and if not, see what the plan is).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733804">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733804">6</a> by Phillip Senn
		posted on 7/1/2011 at 6:49 PM
		</div>
		<div class="comment_text"><p>Thanks Jeff!  That worked as far as using updating the links to the cdn. Although, even their blog post is now out of date because they're pointing to 1.0a4.1 and the latest (as of this millisecond) is 1.0b1.</p></div>
	</div>
</div>
		