
<div class="comment" id="c_1714082208">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082208">1</a> by Mallory S Woods
		posted on 2/26/2014 at 8:15 PM
		</div>
		<div class="comment_text"><p>Awesome! Now I can finally combine my love of comics with the passion of getting all of the Howard the Duck covers on my droid tablet! Seriously this is cool and I think I'll have to start a small project to pull in the cover images to my entire collection.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082210">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082210">2</a> by Raymond Camden
		posted on 2/26/2014 at 9:21 PM
		</div>
		<div class="comment_text"><p>The API *would* let you search for comics about Howard the Duck. While I don't think you can search *covers* by the person on them, this would be close.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082202">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082202">3</a> by Mallory S Woods
		posted on 2/26/2014 at 9:31 PM
		</div>
		<div class="comment_text"><p>Is it not more embarrassing to mention that I remember the Howard the Duck comic, and the movie. Leave me to my shame. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082189">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082189">4</a> by Raymond Camden
		posted on 2/26/2014 at 9:34 PM
		</div>
		<div class="comment_text"><p>Want more shame? I'm a fan of the Beyonder - even Secret Wars 2.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082195">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082195">5</a> by Eric Cobb
		posted on 2/26/2014 at 9:57 PM
		</div>
		<div class="comment_text"><p>I like the Beyonder!  Spider-man teaching him how to use the bathroom (Secret Wars 2) was awesome!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714082205">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082205">6</a> by Simon MacDonald
		posted on 2/26/2014 at 10:00 PM
		</div>
		<div class="comment_text"><p>@Ray,</p><p>Thanks for promoting my plugin. It wouldn't even be an idea in the back of my head without your original blog post.</p><p>The Beyonder in Secret Wars was cool, in Secret Wars II not so much. It took away too much of the mystery by giving him gerrie curls and a white Michael Jackson'esque Thriller era suit.</p><p>@Mallory</p><p>When I get some more time I'm going to add options to select covers by character or series. Also, there is nothing embarrassing about Howard the Duck comics by Steve Gerber. The movie on the other wing...</p></div>
	</div>
</div>
		