
<div class="comment" id="c_1713663105">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663105">1</a> by Lance
		posted on 3/14/2007 at 8:22 PM
		</div>
		<div class="comment_text"><p>I really like the logo as well--very clean!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713663115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713663115">2</a> by Laura
		posted on 3/14/2007 at 11:56 PM
		</div>
		<div class="comment_text"><p>I think that logo is really good! Very Nice</p></div>
	</div>
</div>
		