
<div class="comment" id="c_1713718844">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718844">1</a> by Andy Sandefer
		posted on 10/2/2009 at 9:46 PM
		</div>
		<div class="comment_text"><p>This looks pretty interesting.  I'll probably stick with cfchart because I love the simplicity but this would be pretty nice if you didn't have a ColdFusion or FLEX solution at your disposal.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718853">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718853">2</a> by Timothy
		posted on 10/2/2009 at 10:00 PM
		</div>
		<div class="comment_text"><p>Anyone using the COOP custom tag library who would like to try out a COOP tag wrapper for the flot plugin that we wrote about a year back, drop me a message at timothyfarrar@sosensible.com, and I'd be glad to send it your way.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718834">3</a> by Henry
		posted on 10/2/2009 at 10:05 PM
		</div>
		<div class="comment_text"><p>Hi Ray,<br>I recently implemented this for a client of ours, and one thing I noticed is IE doesn't handle it unless you include the canvas pack (IE8 anyway).<br>&lt; !--[if IE]&gt;&lt;script src="/js/excanvas.pack.js"&gt;&lt;/script&gt;&lt; ![endif]--&gt;</p><p>I think it's a great charting plugin.</p><p>Henry</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718847">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718847">4</a> by James Moberg
		posted on 10/2/2009 at 10:56 PM
		</div>
		<div class="comment_text"><p>I recently started using ChartDirector because I couldn't get what I needed out of CFChart and I didn't know of any way to embed a Flash-based version into a PDF for a consistent web-to-PDF experience.  This was both more powerful and flexible.  Check it out and the free download comes with sample CFM templates for 177 different graphs.<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.advsofteng.com%2Fcdcoldfusion.html%3AX4xNEULH4PVLvtZamNqWNQGEasg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.advsofteng.com/cdcoldfusion.html">http://www.advsofteng.com/c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718846">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718846">5</a> by Andy Sandefer
		posted on 10/2/2009 at 11:33 PM
		</div>
		<div class="comment_text"><p>@James Moberg<br>I checked out your link and it looks like a pretty awesome product.  Is it difficult to use in comparison to cfchart?  I'm working on a lot of manufacturing projects and I noticed that ChartDirector has a Gantt Chart - this would be totally beneficial to more than one of my clients.  What was the learning curve like with this product?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718843">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718843">6</a> by Todd Rafferty
		posted on 10/3/2009 at 12:35 AM
		</div>
		<div class="comment_text"><p>For the curious:<br>FireFox 3.5.3 (Windows): Works<br>Google Chrome 3.0.195.x (Windows): Works<br>Opera 10.x (Windows): Works<br>IE8 (Windows): Bombs - Workaround listed above<br>Safari 4.0.3 (Windows): Works</p><p>That's pretty good!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718839">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718839">7</a> by James Moberg
		posted on 10/3/2009 at 12:41 AM
		</div>
		<div class="comment_text"><p>Learning curve?  It's a little more difficult than using CFChart as everything is not defined in a couple of CFTags.  The feature setis like merging CFImage and CFChart.  You can control every little detail and the sample CFM templates and CHM help file provide lots of helpful samples.  (Download and review the source.)  Installation was easy, it's extremely fast and highly customizable.  Adobe should consider getting a royalty free redistribute license for $750 and including it in their product.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718838">8</a> by Dave
		posted on 10/3/2009 at 3:50 AM
		</div>
		<div class="comment_text"><p>Wow. very cool. I was looking for a charting solution for a project I am working on in the iPhone called jQTouch <a href="http://disq.us/url?url=http%3A%2F%2Fwww.jqtouch.com%2F%3A1r1C8LTBlY-IRwybfGHsIble0N0&amp;cuid=3321886" rel="nofollow noopener" title="http://www.jqtouch.com/">http://www.jqtouch.com/</a><br>This will work great with jQtouch jquery support.</p><p>Nice!</p><p>Thanks Ray.<br>Dave</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718840">9</a> by Dave
		posted on 10/3/2009 at 3:56 AM
		</div>
		<div class="comment_text"><p>@James</p><p>Thanks for that link to ChartDirector. That looks likes another great way to serve non flash charts to the iPhone.</p><p>Dave</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718851">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718851">10</a> by chuck
		posted on 10/3/2009 at 10:51 PM
		</div>
		<div class="comment_text"><p>We use Raphael in my office and while flot seems better for normal graphs you can make some amazing pie charts ect with raphael</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fraphaeljs.com%2F%3AUqMWFwFoXexZqsYaPAm1xIIAOSI&amp;cuid=3321886" rel="nofollow noopener" title="http://raphaeljs.com/">http://raphaeljs.com/</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718849">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718849">11</a> by Phillip Senn
		posted on 10/6/2009 at 5:41 AM
		</div>
		<div class="comment_text"><p>Here are some charting links I've found interesting:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.ted.com%2Ftalks%2Flang%2Feng%2Fhans_rosling_shows_the_best_stats_you_ve_ever_seen.html%3AUqIZCiUe5g_uric4PaYvRbnif7I&amp;cuid=3321886" rel="nofollow noopener" title="http://www.ted.com/talks/lang/eng/hans_rosling_shows_the_best_stats_you_ve_ever_seen.html">http://www.ted.com/talks/la...</a><br><a href="http://disq.us/url?url=http%3A%2F%2Fcode.google.com%2Fapis%2Fvisualization%2Fdocumentation%2Fgallery%2Fmotionchart.html%3ArJZPW7HJW2r86D-KmJlpeEakd7s&amp;cuid=3321886" rel="nofollow noopener" title="http://code.google.com/apis/visualization/documentation/gallery/motionchart.html">http://code.google.com/apis...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718842">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718842">12</a> by eremiya
		posted on 10/22/2009 at 12:27 PM
		</div>
		<div class="comment_text"><p>Hey, cool intro!<br>Take a look at my post. I did somthing similar.<br>Glad if that can help!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713718841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713718841">13</a> by eremiya
		posted on 10/23/2009 at 11:17 AM
		</div>
		<div class="comment_text"><p>Oops! Here is the link to my post!<br><a href="http://disq.us/url?url=http%3A%2F%2Feremiya.net%2F%3A3LFoz25ljWpgq4N6bnnC_g9jDwI&amp;cuid=3321886" rel="nofollow noopener" title="http://eremiya.net/">http://eremiya.net/</a></p></div>
	</div>
</div>
		