
<div class="comment" id="c_1713744662">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744662">1</a> by Peter Tilbrook
		posted on 2/12/2013 at 6:06 PM
		</div>
		<div class="comment_text"><p>New theme looks suspiciously like Twitter Bootstrap. Nothing wrong with that except NOT anything to do with malware ridden WordPress.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744661">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744661">2</a> by Raymond Camden
		posted on 2/12/2013 at 6:16 PM
		</div>
		<div class="comment_text"><p>Actually, I'm also considering this, <a href="http://disq.us/url?url=http%3A%2F%2Fwrapbootstrap.com%2Fpreview%2FWB02116NF%3A1_6T3Sn-nI6HFROXeWcEZco0wF4&amp;cuid=3321886" rel="nofollow noopener" title="http://wrapbootstrap.com/preview/WB02116NF">http://wrapbootstrap.com/pr...</a>, which is definitely Bootstrap.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744663">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744663">3</a> by Jim
		posted on 2/12/2013 at 6:17 PM
		</div>
		<div class="comment_text"><p>Congrats on 10 years Ray,</p><p>I've been following you for the last 5 years and you've helped me many times over the years.</p><p>thanks for all you do,</p><p>Jim</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744659">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744659">4</a> by Mikel
		posted on 2/12/2013 at 6:21 PM
		</div>
		<div class="comment_text"><p>Happy 10th Anniversary!</p><p>Thanks for all that you do!  It certainly is appreciated!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744643">5</a> by Matt Gifford
		posted on 2/12/2013 at 6:31 PM
		</div>
		<div class="comment_text"><p>Now I feel old. I remember all of those site themes. Congratulations, Ray! While you're in the process of the site update, why not bring back the good old death clock app, too.. complete with MS Access database. Go on, be retro!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744649">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744649">6</a> by Raymond Camden
		posted on 2/12/2013 at 6:35 PM
		</div>
		<div class="comment_text"><p>Matt: I actually sold <a href="http://disq.us/url?url=http%3A%2F%2Fdeathclock.com%3AeiulBuQDDe1SbPgJffb2cKinyiM&amp;cuid=3321886" rel="nofollow noopener" title="deathclock.com">deathclock.com</a> many years ago. :) I did build an Android app though - <a href="https://disq.us/url?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dair.DeathClock%26feature%3Dsearch_result%23%3Ft%3DW251bGwsMSwxLDEsImFpci5EZWF0aENsb2NrIl0%3A57DBheqJqymEpoMo8JIQnvmjC1w&amp;cuid=3321886" rel="nofollow noopener" title="https://play.google.com/store/apps/details?id=air.DeathClock&amp;feature=search_result#?t=W251bGwsMSwxLDEsImFpci5EZWF0aENsb2NrIl0">https://play.google.com/sto...</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744650">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744650">7</a> by Richard
		posted on 2/12/2013 at 7:43 PM
		</div>
		<div class="comment_text"><p>Congrats Ray - yes you're lucky but also you made your luck by sharing selflessly what you know!!!<br>Kissing a** but hey:) it has to be said!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744652">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744652">8</a> by Billy Eatman
		posted on 2/12/2013 at 8:04 PM
		</div>
		<div class="comment_text"><p>Congrats Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744653">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744653">9</a> by Tim Cunningham
		posted on 2/12/2013 at 8:09 PM
		</div>
		<div class="comment_text"><p>Great to see your Review of "So dies the fire" by S.M. Sterling all those years ago. It was much more kind than my review on <a href="http://disq.us/url?url=http%3A%2F%2Faudible.com%3AX6G_LDI8-yZkC8Owlt0m9VnjPTA&amp;cuid=3321886" rel="nofollow noopener" title="audible.com">audible.com</a> of it: <a href="http://disq.us/url?url=http%3A%2F%2Fcfml.us%2FTW%3AVJ-_WxoE_fxftC6S88E6DsmPkc0&amp;cuid=3321886" rel="nofollow noopener" title="http://cfml.us/TW">http://cfml.us/TW</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744655">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744655">10</a> by amar
		posted on 2/12/2013 at 9:51 PM
		</div>
		<div class="comment_text"><p>Wow 10 years with the blog. Not sure if you remember the demo app you had written for CF3.5 or 4.0 and it came with installation of CF. I remember it because of the floating menu in it. At the time it was like a magic. So I guess you are not that new to the JS and client side stuff. btw your blog has been useful in learning new stuff or some old stuff thats cool. Thanks and congrats.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744654">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744654">11</a> by Matt
		posted on 2/12/2013 at 11:00 PM
		</div>
		<div class="comment_text"><p>Wouldn't 4831 blog entries average out to 1.32 entries per day (4831/3650) ? Either way your blog is great. I used this blog post just the other day to make a quick calendar <a href="http://disq.us/url?url=http%3A%2F%2Fwww.raymondcamden.com%2Findex.cfm%2F2005%2F8%2F31%2FColdFusion-101-Building-a-Calendar%3A6OMQ6MqAws_lOsOfWPJ0u2Ye2lE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.raymondcamden.com/index.cfm/2005/8/31/ColdFusion-101-Building-a-Calendar">http://www.raymondcamden.co...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744657">12</a> by Sid Wing
		posted on 2/13/2013 at 5:06 AM
		</div>
		<div class="comment_text"><p>I, too, remember all of those designs (and most all of the posts)... Congrats, Man, on 10 years - here's hoping for AT LEAST another 10 :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744656">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744656">13</a> by Tushar Bhaware
		posted on 2/13/2013 at 10:45 AM
		</div>
		<div class="comment_text"><p>Congrats on Successful 10 years.<br>You are great help to me.<br>Your work is really appreciated.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744660">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744660">14</a> by William from Lagos
		posted on 2/13/2013 at 1:44 PM
		</div>
		<div class="comment_text"><p>Congrats to you Ray. Wishing you another 10 years of success. I attribute my interest in ColdFusion to you. I've since jumped ship though</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744658">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744658">15</a> by SuperAlly
		posted on 2/13/2013 at 10:02 PM
		</div>
		<div class="comment_text"><p>Congratulations Ray.<br>All of your efforts are greatly appreciated by everyone.  I know you've helped me out personally more than once, sometimes with your regular posts and at times going far above and beyond to lend advice and help.</p><p>Cheers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744664">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744664">16</a> by Troll
		posted on 2/14/2013 at 4:41 AM
		</div>
		<div class="comment_text"><p>Ray, I've alerted the media about this milestone. Wow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744665">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744665">17</a> by Ben Nadel
		posted on 2/16/2013 at 6:39 AM
		</div>
		<div class="comment_text"><p>Super badass :D Here's to another 10! As always, an inspiration!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744666">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744666">18</a> by papichulo
		posted on 3/5/2013 at 11:34 PM
		</div>
		<div class="comment_text"><p>Ray Camden - Best blog, always the worst design...<br>All the people you know and you can't get one designer to do something custom for you?<br>Twitter bootstrap design from hell. I think you should include the cheesy theme switcher with the color and background changer and let your readers change the site the way they like it:)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744667">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744667">19</a> by Raymond Camden
		posted on 3/5/2013 at 11:35 PM
		</div>
		<div class="comment_text"><p>I'll have to respectfully disagree with you, Papichulo. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744668">
	<div>
		<img src="https://disqus.com/api/users/avatars/nandobreiter.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744668">20</a> by Nando Breiter
		posted on 4/25/2013 at 3:38 PM
		</div>
		<div class="comment_text"><p>So how did you remember the day you made your first blog post after 10 years had gone by?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744669">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744669">21</a> by Raymond Camden
		posted on 4/25/2013 at 5:14 PM
		</div>
		<div class="comment_text"><p>My blogware tells me the first post date. :)</p></div>
	</div>
</div>
		