
<div class="comment" id="c_1713713361">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713361">1</a> by Chris Stevenson
		posted on 6/17/2009 at 1:43 PM
		</div>
		<div class="comment_text"><p>Helpful article. Thanks. Did you get a link for each entry? How did you map the columns?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713379">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713379">2</a> by Raymond Camden
		posted on 6/17/2009 at 3:16 PM
		</div>
		<div class="comment_text"><p>Mapping would be done using the columnMap feature of cffeed. Links would be atomLink I believe.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713713380">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713713380">3</a> by Nick Harvey
		posted on 11/3/2011 at 10:51 PM
		</div>
		<div class="comment_text"><p>I know this is an old post, but we are starting to build out on Atom at work and I was getting errors with cffeed expecting a struct (when RSS just requires a string). This solved my issue and preempted others I didn't yet encounter ('subtitle' as opposed to 'description' in RSS). Just wanted to say thanks. Thanks!</p></div>
	</div>
</div>
		