
<div class="comment" id="c_1713727820">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727820">1</a> by Charles
		posted on 11/23/2010 at 5:17 AM
		</div>
		<div class="comment_text"><p>Will be using this Coldfusion stuff to redirect all returned mail to Ray Camden.</p><p>You're the best blogger ever ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727800">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727800">2</a> by BB
		posted on 11/23/2010 at 8:01 AM
		</div>
		<div class="comment_text"><p>Thank you!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727819">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727819">3</a> by Gary Funk
		posted on 11/23/2010 at 6:51 PM
		</div>
		<div class="comment_text"><p>Thank you Ray.</p></div>
	</div>
</div>
		