
<div class="comment" id="c_1713744671">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744671">1</a> by Ty Whalin
		posted on 2/13/2013 at 10:12 PM
		</div>
		<div class="comment_text"><p>O, that is one of those one's you just through the puter out the window and call it a day. That pesky Google.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744674">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744674">2</a> by Patrick Whittingham
		posted on 2/19/2013 at 5:36 PM
		</div>
		<div class="comment_text"><p>Don't you know that you should be a mind-reader :)</p></div>
	</div>
</div>
		