
<div class="comment" id="c_1713653124">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653124">1</a> by Neil Bailey
		posted on 5/18/2006 at 6:46 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Off topic - change your employer link down on the bottom-right of your blog...  I can't imagine I am the only one in the world to have seen it, and if you've gotten a thousand of these, I apologize in advance.</p><p>nb</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653115">2</a> by Raymond Camden
		posted on 5/18/2006 at 6:50 PM
		</div>
		<div class="comment_text"><p>Nope, you are the first. Thank you!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653123">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653123">3</a> by Teddy Payne
		posted on 5/19/2006 at 1:00 AM
		</div>
		<div class="comment_text"><p>*sniff sniff* is that glue I smell?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653128">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653128">4</a> by Doug Reynolds
		posted on 5/24/2006 at 12:35 AM
		</div>
		<div class="comment_text"><p>Ray,<br>I RSVP'd to attend via Breeze but have not heard back.  Should I have received some connection information at this point?<br>Hope to be able to sit in the Breeze room.<br>Thanks,<br>D</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653130">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653130">5</a> by Raymond Camden
		posted on 5/24/2006 at 12:49 AM
		</div>
		<div class="comment_text"><p>Doug, I think it will be ok. I'll ping Aaron.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653129">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653129">6</a> by Aaron West
		posted on 5/24/2006 at 6:57 AM
		</div>
		<div class="comment_text"><p>Doug, the URL to the breezo tomorrow night (5/24/2006) has been e-mailed to all those that RSVP'd.  If you don't receive this e-mail within the next few hours feel free to e-mail me personally and I'll hook you up with the info.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713653132">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713653132">7</a> by Doug Reynolds
		posted on 5/24/2006 at 7:41 AM
		</div>
		<div class="comment_text"><p>Got it, looking forward to it.<br>Thanks,<br>D</p></div>
	</div>
</div>
		