
<div class="comment" id="c_1713656240">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656240">1</a> by Scott P
		posted on 8/16/2006 at 1:58 AM
		</div>
		<div class="comment_text"><p>yeah, I got no life so count me in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656254">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656254">2</a> by Robert Owen
		posted on 8/16/2006 at 2:01 AM
		</div>
		<div class="comment_text"><p>I'm there.. I'd say I'll bring the beer.. but....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656255">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656255">3</a> by Sean Corfield
		posted on 8/16/2006 at 2:08 AM
		</div>
		<div class="comment_text"><p>6pm in which timezone?? If that's 3pm Pacific, yeah, I would probably tune in. And it's Wednesday, right? I'll put it in my calendar.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656253">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656253">4</a> by Dan Sorensen
		posted on 8/16/2006 at 2:11 AM
		</div>
		<div class="comment_text"><p>3pm PST sounds good with me. I'll be there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656250">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656250">5</a> by Raymond Camden
		posted on 8/16/2006 at 2:16 AM
		</div>
		<div class="comment_text"><p>6 CST. And again, the date isn't 100% firm. But I think it will most likey be that date.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656256">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656256">6</a> by Sean Corfield
		posted on 8/16/2006 at 2:21 AM
		</div>
		<div class="comment_text"><p>6pm CST = 4pm PST, right? (Sorry, I'm a bit timezone-challenged) That should still be OK.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656257">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656257">7</a> by Cary Gordon
		posted on 8/16/2006 at 2:23 AM
		</div>
		<div class="comment_text"><p>I think that Baton Rouge will still be on CDT on August 30th. That would make it 4 PM PDT for folks in the Golden State.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656259">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656259">8</a> by Adam Podolnick
		posted on 8/16/2006 at 2:25 AM
		</div>
		<div class="comment_text"><p>Sure, I'll be there.... here...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656258">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656258">9</a> by Cary Gordon
		posted on 8/16/2006 at 2:27 AM
		</div>
		<div class="comment_text"><p>I forgot the important part: I will try to make it as well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656262">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656262">10</a> by Chris
		posted on 8/16/2006 at 2:32 AM
		</div>
		<div class="comment_text"><p>Count me in!!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656260">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656260">11</a> by Daniel Budde II
		posted on 8/16/2006 at 2:39 AM
		</div>
		<div class="comment_text"><p>Count me in.  I will just need to check back for when the date is officialized so I can set a reminder for myself.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656264">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656264">12</a> by Tariq Ahmed
		posted on 8/16/2006 at 2:46 AM
		</div>
		<div class="comment_text"><p>Ya 4pm PST is do-able. 5 a bit better. Overhaul, highly interested.</p><p>Thx!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656261">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656261">13</a> by Jason
		posted on 8/16/2006 at 3:08 AM
		</div>
		<div class="comment_text"><p>I'm in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656263">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656263">14</a> by Joe
		posted on 8/16/2006 at 3:13 AM
		</div>
		<div class="comment_text"><p>I could most likely make it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656270">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656270">15</a> by charlie griefer
		posted on 8/16/2006 at 3:22 AM
		</div>
		<div class="comment_text"><p>that's right about the time i'll be making the move to California.</p><p>if i'm not in transit (and i have internet access wherever i happen to be), count me in :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656268">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656268">16</a> by Ken Auenson
		posted on 8/16/2006 at 3:31 AM
		</div>
		<div class="comment_text"><p>Count me in!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656252">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656252">17</a> by Sami Hoda
		posted on 8/16/2006 at 4:41 AM
		</div>
		<div class="comment_text"><p>Ray,</p><p>As a Adobe Community Expert, aren't you maxed out at 15 attendees?</p><p>Sami</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656267">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656267">18</a> by Raymond Camden
		posted on 8/16/2006 at 4:45 AM
		</div>
		<div class="comment_text"><p>That's why I blogged here - to get an idea of how many people would show up, and if I needed a bigger room.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656272">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656272">19</a> by Douglas Reynolds
		posted on 8/16/2006 at 4:50 AM
		</div>
		<div class="comment_text"><p>I can probably get off work a little early that day to attend.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656269">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656269">20</a> by dan
		posted on 8/16/2006 at 5:08 AM
		</div>
		<div class="comment_text"><p>Count me in! I have a rough draft about application inheritance im writing for cfdj if you woud like to proof read it for me that would be great. It may just give you some more material to speak on (not that you the jedi master needs it or anything)! ha</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656271">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656271">21</a> by Jonathan
		posted on 8/16/2006 at 6:02 AM
		</div>
		<div class="comment_text"><p>I am game for an online jedi group meeting.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656348">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656348">22</a> by John
		posted on 8/16/2006 at 6:13 AM
		</div>
		<div class="comment_text"><p>Please count me in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656359">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656359">23</a> by Raymond Camden
		posted on 8/16/2006 at 6:32 AM
		</div>
		<div class="comment_text"><p>Send it on over Dan. I actually don't normally inherit with app.cfc, but it is obviously something I will need to demo (at the end though as I don't think it is a common case), so send it on over to me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656349">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656349">24</a> by BL
		posted on 8/16/2006 at 7:22 AM
		</div>
		<div class="comment_text"><p>I like the idea Ray, I'm there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656347">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656347">25</a> by tj_d
		posted on 8/16/2006 at 7:37 AM
		</div>
		<div class="comment_text"><p>Im there</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656344">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656344">26</a> by Gary Funk
		posted on 8/16/2006 at 8:41 AM
		</div>
		<div class="comment_text"><p>Count me in Ray. I'll be there.</p><p>Is there a breeze account we can try?  I'm behind a firewall during the day and many ports are blocked.</p><p>Damn government.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656354">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656354">27</a> by George
		posted on 8/16/2006 at 1:29 PM
		</div>
		<div class="comment_text"><p>I'd quite like to come along, but 6pm CST is midnight GMT. Depending on the duration of the presentation I may be able to join, but I try to be in my cot by 1am during the week.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656346">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656346">28</a> by Richard Chappell
		posted on 8/16/2006 at 2:19 PM
		</div>
		<div class="comment_text"><p>Will these breeze presos be available to listen to after the event? Like George I'm in the UK, so 6PM your time is the middle of the night to me...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656343">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656343">29</a> by Raymond Camden
		posted on 8/16/2006 at 2:30 PM
		</div>
		<div class="comment_text"><p>Richard, as far as I know, yes.</p><p>I'm obviously trying something new here - so I ask that folks work with me. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656341">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656341">30</a> by Trond
		posted on 8/16/2006 at 3:52 PM
		</div>
		<div class="comment_text"><p>Ray - I'd like to join from Norway -- eventhough it will be at 1 in the morning...:-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656353">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656353">31</a> by Scot Hershman
		posted on 8/16/2006 at 4:08 PM
		</div>
		<div class="comment_text"><p>I'll be there</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656357">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656357">32</a> by Christian Ready
		posted on 8/16/2006 at 4:15 PM
		</div>
		<div class="comment_text"><p>I reckon I can be there :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656350">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656350">33</a> by Matthew Abbott
		posted on 8/16/2006 at 5:02 PM
		</div>
		<div class="comment_text"><p>Im Interested.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656358">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656358">34</a> by Andy J
		posted on 8/16/2006 at 5:19 PM
		</div>
		<div class="comment_text"><p>So that's 11pm GMT. Do'h I'll try and join though</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656363">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656363">35</a> by Don
		posted on 8/16/2006 at 5:23 PM
		</div>
		<div class="comment_text"><p>Definitely interested.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656351">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656351">36</a> by Terry Schmitt
		posted on 8/16/2006 at 6:05 PM
		</div>
		<div class="comment_text"><p>Let's add one more to the pile!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656342">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656342">37</a> by Doug Laakso
		posted on 8/16/2006 at 6:42 PM
		</div>
		<div class="comment_text"><p>Please, count me in too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656352">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656352">38</a> by Sean Corfield
		posted on 8/16/2006 at 7:14 PM
		</div>
		<div class="comment_text"><p>Looking at your Gravatar support, do you only fetch the image when a new comment is made or do you attempt to fetch images on every page render?</p><p>(sorry to go off-topic)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656355">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656355">39</a> by Sean Corfield
		posted on 8/16/2006 at 7:14 PM
		</div>
		<div class="comment_text"><p>OK, answered my own question. Thanx!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656345">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656345">40</a> by Trond Ulseth
		posted on 8/16/2006 at 7:15 PM
		</div>
		<div class="comment_text"><p>I'd probably be able to join.</p><p>(and - to avoid confusion - while also from Norway I'm not the same Trond that signed up above)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656361">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656361">41</a> by Raymond Camden
		posted on 8/16/2006 at 7:19 PM
		</div>
		<div class="comment_text"><p>As just an FYI, you guys do NOT have to RSVP anymore. I have the meeting scheduled and ensured I didn't have the 15 member cap. (Although if you want to comment anyway, be my guest. :)</p><p>Thank you to everyone who did. After the meeting, drop me a line and let me know how it goes so I can improve the next one.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656360">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656360">42</a> by Tim Davis
		posted on 8/16/2006 at 9:04 PM
		</div>
		<div class="comment_text"><p>Added to my Google Calendar</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656362">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656362">43</a> by Raymond Camden
		posted on 8/16/2006 at 9:12 PM
		</div>
		<div class="comment_text"><p>Same here. You can see mine at <a href="http://disq.us/url?url=http%3A%2F%2Fray.camdenfamily.com%2Fspeakingengagements.cfm%3ADP5M6lXzXNV5yodDrhrWxBiE-pU&amp;cuid=3321886" rel="nofollow noopener" title="http://ray.camdenfamily.com/speakingengagements.cfm">http://ray.camdenfamily.com...</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656356">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656356">44</a> by Stefan Vesterlund
		posted on 8/24/2006 at 12:18 AM
		</div>
		<div class="comment_text"><p>I would like to join. If the time could be posted in CET (Central European Time) :)</p><p>Seriously, all different US TZ's are very confusing.</p></div>
	</div>
</div>
		