
<div class="comment" id="c_1713621229">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621229">1</a> by Brian Rinaldi
		posted on 10/6/2005 at 12:40 AM
		</div>
		<div class="comment_text"><p>Not to detract from this "unnamed" developer's wiki project, but I do know of one wiki that is built in CF called seedwiki - but as a disclaimer I have never used it nor really examined it in detail, just know it exists. <a href="http://disq.us/url?url=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fseedwiki%2F%3ACfivgFq6-2mh76P_jgSV6RzyoKo&amp;cuid=3321886" rel="nofollow noopener" title="http://sourceforge.net/projects/seedwiki/">http://sourceforge.net/proj...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713621232">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621232">2</a> by Darin Kadrioski
		posted on 10/6/2005 at 1:43 AM
		</div>
		<div class="comment_text"><p>Sean Corfield's MachWiki works alright, and is a little nicer than seedwiki.</p><p>I've yet to find a *really good* wiki for CF though...  will be watching this thread like a hawk ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713621231">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713621231">3</a> by Sean Corfield
		posted on 10/6/2005 at 8:54 AM
		</div>
		<div class="comment_text"><p>Seedwiki was created by Kenneth Tyler (of BACFUG). For the last several years he's been threatening to rewrite it...</p><p>Thanx for the vote of confidence on my MachWiki but I'd say it's really low-feature and mostly intended to just show off some Mach II functionality.</p></div>
	</div>
</div>
		