
<div class="comment" id="c_1713664204">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664204">1</a> by Sam Farmer
		posted on 4/17/2007 at 11:11 PM
		</div>
		<div class="comment_text"><p>Can anyone listen in?  If so, you'll be on around 8pm EST right?</p><p>(I guess even if its restricted you'll still be on around 8ish EST)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664223">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664223">2</a> by Raymond Camden
		posted on 4/17/2007 at 11:14 PM
		</div>
		<div class="comment_text"><p>I pinged the manager to find out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664214">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664214">3</a> by Tony G.
		posted on 4/18/2007 at 12:25 AM
		</div>
		<div class="comment_text"><p>On the user group site they have you scheduled for 7:00 pm Kansas City time, which I guess would be 8:00pm EST.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664222">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664222">4</a> by Raymond Camden
		posted on 4/18/2007 at 12:28 AM
		</div>
		<div class="comment_text"><p>Yep. I was told 7CST. Which is good - gives me time before LOST.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664216">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664216">5</a> by Leif Wells
		posted on 4/18/2007 at 2:11 AM
		</div>
		<div class="comment_text"><p>Starbuck is the fifth Cylon!</p><p>(runs for cover)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664227">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664227">6</a> by John Ramon
		posted on 4/18/2007 at 6:21 AM
		</div>
		<div class="comment_text"><p>Ray your coming to Bolder?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664217">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664217">7</a> by Raymond Camden
		posted on 4/18/2007 at 6:48 AM
		</div>
		<div class="comment_text"><p>No plans. Unless someone wants to fly me out. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664230">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664230">8</a> by Scott P
		posted on 4/19/2007 at 9:43 PM
		</div>
		<div class="comment_text"><p>Did this get recorded?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664218">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664218">9</a> by Raymond Camden
		posted on 4/19/2007 at 9:59 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fadobechats.adobe.acrobat.com%2Fp84512406%2F%3A6oJ1RRtwbPQHwftpbjPr_ashHO8&amp;cuid=3321886" rel="nofollow noopener" title="http://adobechats.adobe.acrobat.com/p84512406/">http://adobechats.adobe.acr...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664213">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664213">10</a> by Raymond Camden
		posted on 6/13/2007 at 9:08 AM
		</div>
		<div class="comment_text"><p>Ryan, this blog entry has nothing to do with job postings, and while I want to help people find CF jobs, this post is spam. I'll be deleting it now. Do not repeat this mistake.</p></div>
	</div>
</div>
		