
<div class="comment" id="c_1713737010">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737010">1</a> by Doug
		posted on 11/30/2011 at 7:50 PM
		</div>
		<div class="comment_text"><p>Too bad I don't know ColdBox.  I wonder if I can learn it by the 16th...?</p><p>How's it compare to other frameworks?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736991">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736991">2</a> by Raymond Camden
		posted on 11/30/2011 at 7:54 PM
		</div>
		<div class="comment_text"><p>I've always been honest about ColdBox. I don't like it. There's nothing at all wrong with it. I just don't like the way it does things. I prefer Model-Glue and FW/1.</p><p>However - ColdBox is the gold standard for ColdFusion Open Source. It is the best maintained, most professional, just all around _incredibly_ high quality OS product out there - hell even outside of the ColdFusion community it is a _SHINING_ example of open source.</p><p>So what I tell people is - check it out. If it works for you, great. If not - try another framework. The best framework is the one that allows you to kick ass and get stuff done.</p></div>
	</div>
</div>
		