
<div class="comment" id="c_1713666932">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666932">1</a> by Justin Lewis
		posted on 6/10/2007 at 9:43 PM
		</div>
		<div class="comment_text"><p>May of screwed up the coil in the speaker in the printer, I smell sunday screwdriver project. If it prints fine, just open up the printer and disconnect that speaker.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666933">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666933">2</a> by Scott P
		posted on 6/11/2007 at 12:02 AM
		</div>
		<div class="comment_text"><p>Is the printer plugged into the ups?  Sounds like an overload on the ups.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666925">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666925">3</a> by Raymond Camden
		posted on 6/11/2007 at 12:13 AM
		</div>
		<div class="comment_text"><p>But why now? It's been set up for weeks. And I'm 99% certain the tone is coming out of the printer. I put my ear up to it. (But I can confirm that.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666930">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666930">4</a> by Critter
		posted on 6/11/2007 at 2:36 AM
		</div>
		<div class="comment_text"><p>ads in the rss feeds new?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666929">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666929">5</a> by Raymond Camden
		posted on 6/11/2007 at 3:57 AM
		</div>
		<div class="comment_text"><p>No - they have been around for a while. What do you think? I want say this TOO often publicly, but if they bug you, subscribe to (myurl)/rss.cfm instead.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666931">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666931">6</a> by Critter
		posted on 6/11/2007 at 4:05 AM
		</div>
		<div class="comment_text"><p>ah. weird. There were 5 posts showing only this one had an ad..</p><p>no biggie..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666935">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666935">7</a> by Dan G. Switzer, II
		posted on 6/11/2007 at 10:18 PM
		</div>
		<div class="comment_text"><p>@Raymon:</p><p>Is this printer also a fax machine? Could the tone becoming from the modem in the printer? You could have fried the printer's modem via the phone line.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666936">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666936">8</a> by Dan G. Switzer, II
		posted on 6/11/2007 at 10:19 PM
		</div>
		<div class="comment_text"><p>PS - I read the subject the first time as "Toner of Death", so I was expecting much more exciting story. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666944">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666944">9</a> by Raymond Camden
		posted on 6/11/2007 at 10:21 PM
		</div>
		<div class="comment_text"><p>Yes, it IS a modem. Crap. I don' tthink I was running the phone line through the "protector".</p><p>Of course - my phone is tied to the fax machine (wall, fax/printer, my phone), and my phone works fine.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666923">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666923">10</a> by Raymond Camden
		posted on 6/11/2007 at 10:25 PM
		</div>
		<div class="comment_text"><p>Ugh. So I tried a fax, and I got an error and all kinds of flashy lights.</p><p>So if it possible to fix a modem inside a fax printer? I hate to replace the whole thing. It is a darn good printer (especially compared to my last HP). I mean I know it would be a write off, but this thing is just over a year old.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666924">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666924">11</a> by Dan G. Switzer, II
		posted on 6/11/2007 at 11:03 PM
		</div>
		<div class="comment_text"><p>@Raymond:</p><p>I'd call HP. Since it was probably a lightning strike, who knows how much damage was actually done. It's possible if the modem board is fried, that could be replaced.</p><p>Hopefully the modem is a seperate module that can be replaced (and that it was the only thing that was fried.)</p><p>I bought a Brother MFC-8820D several years ago for like $300. Laser printer w/integrate color scanner and fax. Best money I ever spent on a printer. Very low cost to operate. I'd be really irratated if I lost it to a lightning strike.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666927">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666927">12</a> by Copier Toner
		posted on 10/8/2009 at 5:38 PM
		</div>
		<div class="comment_text"><p>Hello guys!<br>toner is a powder and you can buy refilled toner cartridges at many stores. if you insist on doing it yourself, you will need gloves, eye protection, a breathing mask, the powder itself..Thanks for sharing your thoughts..</p></div>
	</div>
</div>
		