
<div class="comment" id="c_1713617834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617834">1</a> by Darryl Lyons
		posted on 3/31/2005 at 3:29 AM
		</div>
		<div class="comment_text"><p>Tis a good game too -- about 1/2 way through at the moment!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617832">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617832">2</a> by sean tierney
		posted on 3/31/2005 at 4:45 AM
		</div>
		<div class="comment_text"><p>hey ray, that was me. you should also be getting a book on mindmapping.  thanks for the BlogCFC- it's a great app!</p><p>sean</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617833">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617833">3</a> by Ray Camden
		posted on 3/31/2005 at 4:49 AM
		</div>
		<div class="comment_text"><p>Thanks Sean! Mindmapping.... sounds very interesting - and I'm almost done with my current book (another wishlist item).</p></div>
	</div>
</div>
		