
<div class="comment" id="c_1713617838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617838">1</a> by amar
		posted on 3/31/2005 at 2:17 AM
		</div>
		<div class="comment_text"><p>I went to check it out and realized that they use CFC as their short-form for their name. That's a weird coincidence :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617840">2</a> by pim
		posted on 4/4/2005 at 4:46 PM
		</div>
		<div class="comment_text"><p>What I like with the accordions and tabnavigators, is the browser's back/forward integration, but my preference goes for the tabnavigator ;)</p></div>
	</div>
</div>
		