
<div class="comment" id="c_1713617653">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617653">1</a> by Malcolm
		posted on 3/24/2005 at 9:14 AM
		</div>
		<div class="comment_text"><p>Ray, are you able to let me know exactley what files you updated from 3.60 to 3.61? I don't really want to copy all the files aver again :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617652">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617652">2</a> by Ray Camden
		posted on 3/24/2005 at 9:10 PM
		</div>
		<div class="comment_text"><p>It is in the readme.txt file, but not explicitely as file A, B, etc. It should be layout.cfm, index.cfm, and blog.cfc.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617654">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617654">3</a> by Wayne Graham
		posted on 3/24/2005 at 9:10 PM
		</div>
		<div class="comment_text"><p>Any chance to get the Aura skin Joe did included in layout.cfm?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617657">4</a> by Ray Camden
		posted on 3/24/2005 at 9:16 PM
		</div>
		<div class="comment_text"><p>Probably not. I'd rather keep the layout simply and ugly for those who want to spend a lot of time customizing it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617658">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617658">5</a> by Ryan Guill
		posted on 3/26/2005 at 1:02 AM
		</div>
		<div class="comment_text"><p>Hey ray, I just found something that would be really cool to implement on blog.cfc.</p><p>I found it on <a href="http://disq.us/url?url=http%3A%2F%2Fwww.symphony21.com%2Ffeatures%2Fspecs%2F%3AJW2VZ06k15n5vycWfz9noQZHXDg&amp;cuid=3321886" rel="nofollow noopener" title="http://www.symphony21.com/features/specs/">http://www.symphony21.com/f...</a><br>It says that thier blog software, "Keyword Linker - Make a list of words you want Symphony to automatically turn into links (e.g. Google.)"</p><p>How hard do you think it would be to implement?  The hardest part would be where to store the list of words and their websites I would think.</p><p>What do you think?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617655">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617655">6</a> by sean tierney
		posted on 3/26/2005 at 1:59 PM
		</div>
		<div class="comment_text"><p>Ray,<br>BlogCFC is great, i'm migrating my current blog into it now. I noticed it's impossible to go forward or backward though months on the calendar thoguh (confirmed it just now on yours as well).  Any ideas what might be the fix before I dig into your code?<br>thanks<br>sean</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617659">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617659">7</a> by Raymond Camden
		posted on 3/26/2005 at 9:34 PM
		</div>
		<div class="comment_text"><p>Sean - this was a really, really dumb bug on my part. Fixed in 3.6.2 which was released 5 minutes ago.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617662">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617662">8</a> by Ray Camden
		posted on 3/29/2005 at 1:19 AM
		</div>
		<div class="comment_text"><p>Ryan: It would be trivial as a one off. But I don't think I'd make that part of the core (unless a lot of people ask for it).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617663">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617663">9</a> by sean tierney
		posted on 3/29/2005 at 1:27 AM
		</div>
		<div class="comment_text"><p>speaking of enhancement requests, one that would be useful would be to integrate the FCK editor.  i was using this one before: <a href="http://disq.us/url?url=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fplog%3AO92KAYeUAZXYk2AcVwc-1YM0JlI&amp;cuid=3321886" rel="nofollow noopener" title="http://sourceforge.net/projects/plog">http://sourceforge.net/proj...</a> and it has the FCK built in which makes it very nice for rich text and linking to sites and embedding images.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713617664">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617664">10</a> by Ray Camden
		posted on 3/29/2005 at 1:35 AM
		</div>
		<div class="comment_text"><p>I think I must be in the minority as I absolutely despise rich-text controls. I will tell you what I tell others.... just modify editor.cfm. ;)</p></div>
	</div>
</div>
		