
<div class="comment" id="c_1714083845">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083845">1</a> by Henry Ho
		posted on 9/15/2014 at 9:21 PM
		</div>
		<div class="comment_text"><p>Is there a list of all recordings from NCDevCon 2014? Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083846">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083846">2</a> by Henry Ho
		posted on 9/16/2014 at 2:01 AM
		</div>
		<div class="comment_text"><p>found it: <a href="http://disq.us/url?url=http%3A%2F%2Ftextiles.online.ncsu.edu%2Fonline%2FCatalog%2Fcatalogs%2Fncdevcon-2014%3ADTBxjo2yQe6LZ05OwUQmPtc2_XE&amp;cuid=3321886" rel="nofollow noopener" title="http://textiles.online.ncsu.edu/online/Catalog/catalogs/ncdevcon-2014">http://textiles.online.ncsu...</a></p><p>Thx</p></div>
	</div>
</div>
		