
<div class="comment" id="c_1713730523">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730523">1</a> by Edward - Florida SEO
		posted on 3/15/2011 at 8:18 AM
		</div>
		<div class="comment_text"><p>Nice :-)</p><p>I'm just using  --- onclick="window.location.reload();return false;" --- on an anchor next to the image ...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730536">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730536">2</a> by Misty
		posted on 3/15/2011 at 8:20 AM
		</div>
		<div class="comment_text"><p>Hi ray, I had also created the one before long, You can check this tutorial out!</p><p><a href="http://disq.us/url?url=http%3A%2F%2Ftutorial571.easycfm.com%2F%3AMY2TsymhBl5lCAbJ9zEgGXHW25Q&amp;cuid=3321886" rel="nofollow noopener" title="http://tutorial571.easycfm.com/">http://tutorial571.easycfm....</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730522">3</a> by Jonathan
		posted on 3/15/2011 at 12:04 PM
		</div>
		<div class="comment_text"><p>Hi Ray, you placed the captcha string in session, that means only one captcha at a time per session... so the user can't process a different form on a different tab in the browser.  I was thinking you can return the captcha image in xml, and the xmlroot includes the captcha string.  and when the xml is returned, the JS creates a hidden input with the value captcha string.  what do you think?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730538">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730538">4</a> by Raymond Camden
		posted on 3/15/2011 at 3:13 PM
		</div>
		<div class="comment_text"><p>@Jonathan: You could easily support N captchas and N forms by using different names. So if this form was a contact form, I could have used session.contactcaptcha.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730531">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730531">5</a> by Rich Hefter
		posted on 3/15/2011 at 5:06 PM
		</div>
		<div class="comment_text"><p>Ray, Your demo link doesn't work (for me) using IE7.  Safari for windows and Firefox was OK.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730533">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730533">6</a> by Raymond Camden
		posted on 3/15/2011 at 5:13 PM
		</div>
		<div class="comment_text"><p>Works in IE8. Can't test in 7. If you figure out why, please let us know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730524">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730524">7</a> by Brian
		posted on 3/15/2011 at 6:55 PM
		</div>
		<div class="comment_text"><p>I have an instance of IE7 also -- it may be an image caching issue -- Even a forced refresh of the page doesn't change the captcha graphic &lt;shrug&gt;</p><p>Hard to tell without Firebug support...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730528">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730528">8</a> by Raymond Camden
		posted on 3/15/2011 at 7:04 PM
		</div>
		<div class="comment_text"><p>Brian - mod my JS to add a ?x= random number to the end. I bet that fixes it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730530">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730530">9</a> by Brian
		posted on 3/15/2011 at 7:05 PM
		</div>
		<div class="comment_text"><p>An added piece to this puzzle... clearing the cookie, forced a refresh.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730526">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730526">10</a> by Chris Bowyer
		posted on 3/15/2011 at 7:07 PM
		</div>
		<div class="comment_text"><p>Works in IE7 if temporary internet files set to 'Every time I visit the webpage', but not if set to 'Automatically'</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730521">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730521">11</a> by Raymond Camden
		posted on 3/15/2011 at 7:11 PM
		</div>
		<div class="comment_text"><p>Yep, adding a random # to the URL would fix that. I haven't done it in a while, but I used to add a "iesucks" to the URL for stuff like this where the value was random.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730529">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730529">12</a> by JP
		posted on 3/15/2011 at 7:16 PM
		</div>
		<div class="comment_text"><p>It's most likely a caching issue... try adding a random URL variable to the showcaptcha.cfm request... like:</p><p>x = Math.floor(Math.random()*100000);<br>"showcaptcha.cfm?x=" + x;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730540">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730540">13</a> by Raymond Camden
		posted on 3/15/2011 at 7:17 PM
		</div>
		<div class="comment_text"><p>heh I keep saying "add a random # to the url" - is no one seeing that?? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730525">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730525">14</a> by Chris Bowyer
		posted on 3/15/2011 at 7:18 PM
		</div>
		<div class="comment_text"><p>Good one!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730527">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730527">15</a> by brian
		posted on 3/15/2011 at 8:23 PM
		</div>
		<div class="comment_text"><p>@Ray yup, adding a random # to the URL does make the diff.  You rat.  You forced me to go read some jQuery docs.  I've never played with it before -- not a desired interface at client sites that are remote and bandwidth throttled.  Still not something I can use here, but an interesting exercise, nonetheless.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730537">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730537">16</a> by Raymond Camden
		posted on 3/15/2011 at 8:25 PM
		</div>
		<div class="comment_text"><p>Sorry - what can't you use? jQuery? I made use of the remote library but you don't have to. You can download the jQuery library to your local web server.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730535">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730535">17</a> by Josh
		posted on 3/15/2011 at 8:30 PM
		</div>
		<div class="comment_text"><p>Since I've never found a time where I'd want a browser to cache my ajax requests, I add this line to the top of my main page.<br>$.ajaxSetup ({<br>	// Disable caching of ANY AJAX responses.<br>	cache: false<br>});</p><p>This tells jquery to add the current date string to the end of the url each time a request is made.  Simple and you never have to think about request caching again.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730532">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730532">18</a> by Raymond Camden
		posted on 3/15/2011 at 8:46 PM
		</div>
		<div class="comment_text"><p>Darn nice tip there Josh. Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730541">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730541">19</a> by Drew
		posted on 4/15/2011 at 11:29 PM
		</div>
		<div class="comment_text"><p>Have you thought about accessibility?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730534">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730534">20</a> by Raymond Camden
		posted on 4/16/2011 at 5:27 AM
		</div>
		<div class="comment_text"><p>Not yet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730547">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730547">21</a> by Nathanael Waite
		posted on 6/8/2011 at 8:28 PM
		</div>
		<div class="comment_text"><p>I started experiencing on one of my load balanced CF9 servers with captcha. and the cfimage tag.</p><p>One Server: coldfusion.image.ImageWriter$ImageWritingException: An exception occurred while trying to write the image.</p><p>The other one rendered it fine.</p><p>My simple test:<br>&lt;cfimage action="captcha" width="300" height="75" text="abcd3"&gt;</p><p>Does anyone have suggestions on why this happens or have they seen it before.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730550">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730550">22</a> by Raymond Camden
		posted on 6/9/2011 at 6:23 AM
		</div>
		<div class="comment_text"><p>A Google turned up this:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.bennadel.com%2Fblog%2F1289-ColdFusion-8-0-1-Bug-Coldfusion-Image-ImageWriter-ImageWritingException.htm%3A6ENpA29z_1uh-8GQ4z6-_1yGF_M&amp;cuid=3321886" rel="nofollow noopener" title="http://www.bennadel.com/blog/1289-ColdFusion-8-0-1-Bug-Coldfusion-Image-ImageWriter-ImageWritingException.htm">http://www.bennadel.com/blo...</a></p><p>Are you up to date with your hot fixes?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730548">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730548">23</a> by Adam
		posted on 6/14/2011 at 10:34 PM
		</div>
		<div class="comment_text"><p>Hi Ray -</p><p>Where does</p><p>$("#captchaDiv").load("showcaptcha.cfm");</p><p>go in the form so the captcha image loads?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730553">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730553">24</a> by Raymond Camden
		posted on 6/14/2011 at 10:38 PM
		</div>
		<div class="comment_text"><p>I'm confused. Do you not see it in the code template above? The last one in the blog entry?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730551">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730551">25</a> by Adam
		posted on 6/14/2011 at 10:49 PM
		</div>
		<div class="comment_text"><p>I do, however, the captcha image is not loading.  I was asking for verification.  I have simply copied and pasted all the code, but the image isn't showing.  I was previous using the quick and dirty version with no problem and only wanted to add in the element refresh.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730552">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730552">26</a> by Raymond Camden
		posted on 6/14/2011 at 10:50 PM
		</div>
		<div class="comment_text"><p>When you first hit the form does it load ok? When you do the refresh - what do you see with Firebug/Chrome Dev Tools?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730549">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730549">27</a> by Adam
		posted on 6/14/2011 at 11:02 PM
		</div>
		<div class="comment_text"><p>Looks like:</p><p>The requested scope session has not been enabled.</p><p>Before session variables can be used, the session state management system must be enabled using the cfapplication tag.</p><p>Should this be enabled in the CF Admin ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730556">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730556">28</a> by Raymond Camden
		posted on 6/14/2011 at 11:03 PM
		</div>
		<div class="comment_text"><p>Add an App.cfc/App.cfm to your folder and turn it on. I should have been more clear that it would be required for this demo.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730554">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730554">29</a> by Adam
		posted on 6/15/2011 at 12:32 AM
		</div>
		<div class="comment_text"><p>I added an application.cfm file with:</p><p>&lt;cfapplication name = "captcha" <br>sessiontimeout = #CreateTimeSpan(0, 0, 0, 60)# <br>sessionmanagement = "Yes"&gt;</p><p>and the captcha now shows.  Thanks for the help!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730558">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730558">30</a> by Micah
		posted on 6/28/2011 at 8:08 PM
		</div>
		<div class="comment_text"><p>Actually, Ray, on your old quick and dirty captcha, if the viewer simply submits the form with an incorrect or empty captcha text field, it refreshes the captcha without changing any text they have entered in the other forms.  I still prefer the hash anyway.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730557">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730557">31</a> by Raymond Camden
		posted on 6/28/2011 at 8:13 PM
		</div>
		<div class="comment_text"><p>Sorry - what? What I read you saying is "If I submit the form and do not put the right captcha in, a new one is made." That's desired is it not?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730555">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730555">32</a> by Adam
		posted on 9/6/2011 at 6:44 PM
		</div>
		<div class="comment_text"><p>@JP, @Ray -</p><p>Regarding the random URL variable, how do I incorporate the code</p><p>x = Math.floor(Math.random()*100000);<br>"showcaptcha.cfm?x=" + x;</p><p>into the showCaptcha.cfm code?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730559">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730559">33</a> by Raymond Camden
		posted on 9/6/2011 at 6:52 PM
		</div>
		<div class="comment_text"><p>I'm not sure what your question means. You don't add anything to showcaptcha.cfm. The random number is there to just trick IE into not using the cache.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730561">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730561">34</a> by Adam
		posted on 9/6/2011 at 8:21 PM
		</div>
		<div class="comment_text"><p>Thanks, Ray.  I read JP's response about adding the URL variable and thought the solution was to add a variable to the showCaptcha code in order to make the variable appear in the URL.  How do I make the random URL variable appear?  This method is working in every browser except IE.  Manually adding the variable works, but users won't be able to do it, so I need to code it to plug in automatically.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730560">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730560">35</a> by Raymond Camden
		posted on 9/6/2011 at 8:29 PM
		</div>
		<div class="comment_text"><p>"How do I make the random URL variable appear?"</p><p>What do you mean? It isn't "appearing" - it is simply being added to the end of the main url. It's a way to trick IE into thinking you are asking for something it hasnt asked for before. (Technically it isn't a trick - it IS a new url.)</p><p>"This method is working in every browser except IE."</p><p>How is it not working for you? Remember that this fixes an issue where IE users would see the same captcha. So are your IE users seeing the same captcha? If so - can you share the URL of where this is so I can test it myself?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730562">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730562">36</a> by Adam
		posted on 9/6/2011 at 8:47 PM
		</div>
		<div class="comment_text"><p>Yes, IE users see the same captcha and are unable to reload the captcha.  The page in question is <a href="http://disq.us/url?url=http%3A%2F%2Facademicaffairs.iupui.edu%2Ffaculty-advancement%2Fcareer-stages-support%2FnewFacultyReception.cfm%3AhMQ4zJq1sJVqlmhV9Y1NxUqtbsw&amp;cuid=3321886" rel="nofollow noopener" title="http://academicaffairs.iupui.edu/faculty-advancement/career-stages-support/newFacultyReception.cfm">http://academicaffairs.iupu...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730571">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730571">37</a> by Raymond Camden
		posted on 9/6/2011 at 8:52 PM
		</div>
		<div class="comment_text"><p>Um... because you didn't add the code. The code that appends the random crap. This is your JS:</p><p>$("#reloadLink").click(function(e) {<br>		$("#captchaDiv").load("showcaptcha.cfm");			<br>		e.preventDefault();<br>	});</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730564">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730564">38</a> by Adam
		posted on 9/6/2011 at 9:08 PM
		</div>
		<div class="comment_text"><p>So in adjusting that part of the code, this allows for the captcha to be reloaded, but only once:</p><p>	$("#reloadLink").click(function(e) {<br>		x = Math.floor(Math.random()*100000);<br>		$("#captchaDiv").load("showcaptcha.cfm?x="+x);			<br>		e.preventDefault();<br>	});</p><p>Is this incorrect?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730568">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730568">39</a> by Adam
		posted on 9/6/2011 at 9:16 PM
		</div>
		<div class="comment_text"><p>That got it.  Thanks for the assistance, Ray.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730570">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730570">40</a> by steve ryan
		posted on 5/24/2012 at 5:41 PM
		</div>
		<div class="comment_text"><p>&lt;!---MAKE A CAPTCHA---&gt;<br>	&lt;cffunction name="getCaptchaContact" access="remote" output="false" returnType="string" returnFormat="JSON"&gt;</p><p>		&lt;cfset local.fileName = CreateUUID() /&gt;<br>		&lt;cfset local.captchaString = makeRandomString() /&gt;<br>		&lt;cfset session.captchaContact =  local.captchaString /&gt;<br>		&lt;cfimage action="captcha" difficulty="low" text="#local.captchaString#" destination = "#local.fileName#.png" /&gt;<br>		&lt;cffile action="readbinary" file="/_cfc/#local.fileName#.png" variable="local.binimage"&gt;<br>		&lt;cffile action="delete" file="/_cfc/#local.fileName#.png" /&gt; <br>        &lt;cfset local.encodedImg = BinaryEncode(binimage, "Base64") /&gt;</p><p>        &lt;cfreturn local.encodedImg /&gt;</p><p>	&lt;/cffunction&gt;</p><p>This is probably lame.  But this is how I have been making captcha's.  I just ajax the captcha were ever I need it on my site.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730569">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730569">41</a> by Raymond Camden
		posted on 5/24/2012 at 5:57 PM
		</div>
		<div class="comment_text"><p>Not lame - kinda cool. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730566">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730566">42</a> by Nan
		posted on 9/11/2013 at 6:05 AM
		</div>
		<div class="comment_text"><p>Ray,<br> Your demo does not display captcha image any more. Do you have any suggestions? Is it anything to do with CF 10 upgrade?<br>Thanks for your help.</p><p>Nan</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730567">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730567">43</a> by Raymond Camden
		posted on 9/11/2013 at 6:13 AM
		</div>
		<div class="comment_text"><p>Yeah - the code should work fine if run on your own server.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730572">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730572">44</a> by Nan
		posted on 9/11/2013 at 7:59 PM
		</div>
		<div class="comment_text"><p>Ray,<br>I've a strange problem. Your code works as such on CF 8 server on all 3 major browsers (FF, Chrome and IE 7, 8, 9). But it doesn't work on IE (8 and 9 tested) after I upgrade our dev server to CF 10. (we jumped CF9). Both production and dev environments are under SSL behind F5. Unfortunately it is an internal site so the URL won't load from outside.<br>Have you seen it before?<br>thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730573">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730573">45</a> by Nan
		posted on 9/11/2013 at 8:09 PM
		</div>
		<div class="comment_text"><p>One more thing,<br>If I put the complete path on IE it loads the image as such.<br>CFFileServlet/_cf_captcha/_captcha_img1637508603629842317.png</p><p>I tried both --cfimage giving a name and destination as well as cfimage action=captcha, the result is same. the image doesn't load on IE and loads fine on FF and Chrome on CF 10 server.<br>Thanks for your help.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730576">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730576">46</a> by Raymond Camden
		posted on 9/11/2013 at 9:48 PM
		</div>
		<div class="comment_text"><p>Not sure what to suggest. Do you see anything in IE's dev tools?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730574">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730574">47</a> by Nan
		posted on 9/11/2013 at 10:46 PM
		</div>
		<div class="comment_text"><p>Figured it is something to do with JQery AJAX call to showcaptcha.cfm.<br>The dev server had debug output to the screen FF and Chrome didn't mind them. IE couldn't handle that but no errors anywhere. Simply no image displayed.</p><p>When I added &lt;cfsetting  showdebugoutput="no"&gt; on top of showcaptcha.cfm. IE now loads it fine.</p><p>Sorry for the false alarm.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713730577">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713730577">48</a> by Raymond Camden
		posted on 9/11/2013 at 11:35 PM
		</div>
		<div class="comment_text"><p>Ahhh - duh! :)</p></div>
	</div>
</div>
		