
<div class="comment" id="c_3852087013">
	<div>
		<img src="https://disqus.com/api/users/avatars/konsumer.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3852087013">1</a> by David Konsumer
		posted on 4/12/2018 at 5:25 PM
		</div>
		<div class="comment_text"><p>Nice!</p></div>
	</div>
</div>
		
<div class="comment" id="c_3892655828">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3892655828">2</a> by Raymond Camden
		posted on 5/9/2018 at 1:02 PM
		</div>
		<div class="comment_text"><p>So as an FYI - David Konsumer (see him in the comments below :) released a new library that makes it easier to work with your devices and removes the need to open a port. You can see it here: <a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fkonsumer%2Fkasa_control%3AZHFqFVvg5iFW0lcfdsHaOEyZy8Y&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/konsumer/kasa_control">https://github.com/konsumer...</a>.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3893104681">
	<div>
		<img src="https://disqus.com/api/users/avatars/konsumer.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3893104681">3</a> (In reply to <a href="#c_3892655828">#2</a>) by David Konsumer
		posted on 5/9/2018 at 6:00 PM
		</div>
		<div class="comment_text"><p>❤<br>Here is a more in-depth example using it:<br><a href="https://disq.us/url?url=https%3A%2F%2Fgist.github.com%2Fkonsumer%2F90962de1727fc322289e14a039a93fab%3A8deUm3LSE4qeDx0VaVTaCGttJEk&amp;cuid=3321886" rel="nofollow noopener" title="https://gist.github.com/konsumer/90962de1727fc322289e14a039a93fab">https://gist.github.com/kon...</a></p></div>
	</div>
</div>
		