
<div class="comment" id="c_1713662638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662638">1</a> by Will
		posted on 2/26/2007 at 12:22 AM
		</div>
		<div class="comment_text"><p>I didn't really read any reviews about it as I pre-ordered it when I bought my XBox to get a discount on them both :) But I'm only a level or 2 from the end and I played most of it straight through. I can only think of one thing bad to say about the game and that is that you can't save your progress anywhere during a mission. Other than that, the gameplay is great and intuitive, the visuals are awesome, and I love the variety of weapons and mechs (I can't not call them that either). I especially love how you can grab a weapon off a mech and use it yourself.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713662645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713662645">2</a> by Matthew Steiner
		posted on 2/27/2007 at 1:35 AM
		</div>
		<div class="comment_text"><p>I've only played the demo, but I did like it.  I almost bought, but then realized it's probably a game I'm only play until I beat it (a renter).  I loved Call of Duty 2, so I'm sorry to hear COD3 wasn't very good.  Rainbow Six Vegas or Gears of War are the best games out now.</p></div>
	</div>
</div>
		