
<div class="comment" id="c_2453915187">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2453915187">1</a> by Awesome Blog Raymond
		posted on 1/12/2016 at 6:56 PM
		</div>
		<div class="comment_text"><p>DUDE, THANKS A LOT!</p><p>You're a friggin life saver... I've been grinding on this college project for couple days now, and only JS and HTML and CSS are linting and that's because of the problem you described above. Lots of time was wasted while trying to figure this crap out but you saved my day! I'm runnin' full-stack on this shizzle and really needed this.</p><p>Again thank you for writing this blog man.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2453917774">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2453917774">2</a> (In reply to <a href="#c_2453915187">#1</a>) by Raymond Camden
		posted on 1/12/2016 at 6:57 PM
		</div>
		<div class="comment_text"><p>You are most welcome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2453931893">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2453931893">3</a> by Awesome Blog Raymond
		posted on 1/12/2016 at 7:05 PM
		</div>
		<div class="comment_text"><p>Wow 70&lt; errors and suggestions in just one 150-line PHP file! Sporting PHP Quality Tools (uses CodeSniffer).</p><p>And oh it appears JSHint was set in global to be used for all files, similarly to what you suggested in this awesome blog post.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2676470582">
	<div>
		<img src="https://disqus.com/api/users/avatars/vigneshkumarchinnachamy.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2676470582">4</a> by Vigneshkumar Chinnachamy
		posted on 5/15/2016 at 5:05 AM
		</div>
		<div class="comment_text"><p>Thanks a lot. I was searching for exactly the same thing.</p></div>
	</div>
</div>
		