
<div class="comment" id="c_1713657147">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657147">1</a> by Phillip Senn
		posted on 9/5/2006 at 8:07 PM
		</div>
		<div class="comment_text"><p>Love it.<br>I think in the original cf logo was an animated gif that had the lightening bolt flashing, didn't it?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657164">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657164">2</a> by Raymond Camden
		posted on 9/5/2006 at 8:15 PM
		</div>
		<div class="comment_text"><p>Yep. It just so happaned the web site had a the 'hand with lightning bolt' logo on it. I wonder if Allaire and this guy used the same clip art? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657177">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657177">3</a> by dickbob
		posted on 9/5/2006 at 9:13 PM
		</div>
		<div class="comment_text"><p>Will you be using your old friend CFLOGIN or have you moved away from that technique :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657151">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657151">4</a> by Raymond Camden
		posted on 9/5/2006 at 9:34 PM
		</div>
		<div class="comment_text"><p>I will mention cflogin by I will absolutely NOT be using it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657152">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657152">5</a> by Robert Owen
		posted on 9/5/2006 at 10:01 PM
		</div>
		<div class="comment_text"><p>This sounds great! I missed the last one but caught the recording. I've never used CFlogin, have done login checks based on session vairables. This will be a good oportunity to see how I should be doing things! Thanks Ray!!</p><p>Now all we need are membership cards?!? :)<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.owenwebs.com%2Fdownloads%2Fcfjediusg.jpg%3AX8AAzcX6gkkViX_VG5rh1l5vPUI&amp;cuid=3321886" rel="nofollow noopener" title="http://www.owenwebs.com/downloads/cfjediusg.jpg">http://www.owenwebs.com/dow...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657153">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657153">6</a> by Raymond Camden
		posted on 9/5/2006 at 10:05 PM
		</div>
		<div class="comment_text"><p>I'm just waiting for a lawsuit from Lucas. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657162">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657162">7</a> by Gary Funk
		posted on 9/6/2006 at 4:58 AM
		</div>
		<div class="comment_text"><p>I prefer the 'electric chicken' but that's been long retired.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657167">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657167">8</a> by Phillip Senn
		posted on 9/6/2006 at 6:24 PM
		</div>
		<div class="comment_text"><p>Let's ask this guy if we can meet at his house.<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.modernhometheater.com%2Fvirtualtours%2Fstar_wars%2Fslideshow%2F%3Aj9JSkHc4ZU47JMNNRJ34NenYAcE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.modernhometheater.com/virtualtours/star_wars/slideshow/">http://www.modernhometheate...</a><br>Be sure to look at slide 12 and beyond!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657166">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657166">9</a> by Nathan Strutz
		posted on 9/6/2006 at 9:48 PM
		</div>
		<div class="comment_text"><p>Don't you think that lightening bolt should have a red glowing end on it? I played with it a bit and made this:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.dopefly.com%2Fjunk%2Fcfjediseal.gif%3A8--bl01HjzwOaxSOBLWJoPN9Yp8&amp;cuid=3321886" rel="nofollow noopener" title="http://www.dopefly.com/junk/cfjediseal.gif">http://www.dopefly.com/junk...</a><br>PSD available.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657168">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657168">10</a> by Phillip Senn
		posted on 9/6/2006 at 10:08 PM
		</div>
		<div class="comment_text"><p>Shouldn't we get rid of the <a href="http://disq.us/url?url=http%3A%2F%2Fwww.says-it.com%2Fseal%3F%3AveEkqwGSKm09TBsrmEIBd8xEt9k&amp;cuid=3321886" rel="nofollow noopener" title="http://www.says-it.com/seal?">http://www.says-it.com/seal?</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657165">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657165">11</a> by Nathan Strutz
		posted on 9/6/2006 at 10:11 PM
		</div>
		<div class="comment_text"><p>Done, refresh.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657172">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657172">12</a> by Raymond Camden
		posted on 9/6/2006 at 10:45 PM
		</div>
		<div class="comment_text"><p>2 things: I don't actually like the glowing end... that's my personal pref.</p><p>Secondly, please put BACK the credit (says-it). The seal was made with their tool, and even if I don't use your version, its only fair.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657171">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657171">13</a> by Phillip Senn
		posted on 9/6/2006 at 11:42 PM
		</div>
		<div class="comment_text"><p>cf Jedi Code Monkeys!</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.jonathancoulton.com%2F2006%2F04%2F14%2Fthing-a-week-29-code-monkey%2F%3Aop2LiHSeN_VKJIvLqLNlsP2EKG8&amp;cuid=3321886" rel="nofollow noopener" title="http://www.jonathancoulton.com/2006/04/14/thing-a-week-29-code-monkey/">http://www.jonathancoulton....</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657169">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657169">14</a> by Nathan Strutz
		posted on 9/7/2006 at 2:36 AM
		</div>
		<div class="comment_text"><p>Ray - You don't like it, i was just playing around, NP. However, the credit, once I've modified it, doesn't it belong to me? Especially for the number of things I've done with it. Furthermore, it's not a copyright, and you can freely remove it as well for your own version. If you like says-it, you can keep the http address on there, but that's your own call, there is no legal reason to do either, and it's not like my /junk/ folder gets big traffic :)</p><p>If you wanted to use some bastardization of the thing I threw together, I can take off the white paint over the says-it address, np, and do whatever ya like. Just let me know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713657175">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713657175">15</a> by Raymond Camden
		posted on 9/7/2006 at 6:17 AM
		</div>
		<div class="comment_text"><p>Well, I'm no copyright lawyer - but I'd probably err on the side of caution. :)</p></div>
	</div>
</div>
		