
<div class="comment" id="c_1713734064">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734064">1</a> by Mike Henke
		posted on 7/7/2011 at 10:03 PM
		</div>
		<div class="comment_text"><p>There are some really cool upcoming topics also like:</p><p>July 14th 6pm ET, Josh Timonen is presenting on Sass (Syntactically Awesome Style Sheets).  He is the co-creator and voice of <a href="http://disq.us/url?url=http%3A%2F%2FScreencasts.org%3AUhDFjv1PwH8mXzgNmlJV_-GOomI&amp;cuid=3321886" rel="nofollow noopener" title="Screencasts.org">Screencasts.org</a>, which provides free educational screencasts on web technologies.</p><p>July 21st 6pm ET, Matthew McCullogh will be presenting on Git. He is a Git Rockstar/Trainer with regular 1 day courses and O'Reilly training videos.</p></div>
	</div>
</div>
		