
<div class="comment" id="c_1713714944">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714944">1</a> by John Ivanoff
		posted on 7/2/2010 at 11:49 PM
		</div>
		<div class="comment_text"><p>Thank you for posting this. It was exactly what I was looking for. Brill!</p></div>
	</div>
</div>
		