
<div class="comment" id="c_1713675609">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675609">1</a> by Boyan Kostadinov
		posted on 12/19/2007 at 7:54 PM
		</div>
		<div class="comment_text"><p>Also, if you are using SQL Server, you can use the built in SQL Server methods to return a query in XML string.</p></div>
	</div>
</div>
		