
<div class="comment" id="c_1713743560">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743560">1</a> by Scott Stroz
		posted on 10/28/2012 at 9:13 PM
		</div>
		<div class="comment_text"><p>Its been a while since I have seen it, but one movie that scared the crap out of me was Prince of Darkness - <a href="http://disq.us/url?url=http%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt0093777%2F%3ArWZQuYuIDMlgcFu-91ON0HY-dpo&amp;cuid=3321886" rel="nofollow noopener" title="http://www.imdb.com/title/tt0093777/">http://www.imdb.com/title/t...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743535">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743535">2</a> by Raymond Camden
		posted on 10/28/2012 at 9:16 PM
		</div>
		<div class="comment_text"><p>Never heard of it - but John Carpenter is typically a safe bet!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743552">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743552">3</a> by Scott Pinkston
		posted on 10/28/2012 at 10:42 PM
		</div>
		<div class="comment_text"><p>Fire in the Sky got to me - the scene where he is strapped down the table.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743555">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743555">4</a> by Dave Watts
		posted on 10/28/2012 at 10:55 PM
		</div>
		<div class="comment_text"><p>I just don't find supernatural horror films that scary. I did really like Cabin in the Woods, but it was more funny than scary.</p><p>I thought "Henry: Portrait of a Serial Killer" was a pretty chilling movie.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743553">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743553">5</a> by Chris Bowyer
		posted on 10/28/2012 at 11:32 PM
		</div>
		<div class="comment_text"><p>Who can look into a mirror and say "Candyman" three times? I can't</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743547">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743547">6</a> by David Hammond
		posted on 10/29/2012 at 5:59 PM
		</div>
		<div class="comment_text"><p>Nice post, Ray!  It is interesting how personal what we find scary can be.  The scariest movie I ever saw was The Ring (American version), and I can't explain why it was so scary.  All I know is that I, a 32 year-old man at the time, couldn't sleep a wink the night after I saw it thinking in terror about a girl with long straggly hair over her face.  For a while my wife would, just for fun, whisper "Seven days" to freak me out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743548">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743548">7</a> by David Hammond
		posted on 10/29/2012 at 6:01 PM
		</div>
		<div class="comment_text"><p>Oh, and I could retaliate against my wife by making those weird popping noises that the aliens in Signs made.  That was her personal weakness.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743550">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743550">8</a> by Craig Inman
		posted on 10/29/2012 at 7:05 PM
		</div>
		<div class="comment_text"><p>An oldy but goody, Trilogy of Terror. Specifically the one with Karen Black. Saw it when I was a four or five and it took me years to get used to turning on lights without looking into the lampshade first.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743549">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743549">9</a> by Jim
		posted on 10/31/2012 at 8:53 PM
		</div>
		<div class="comment_text"><p>A couple of others for me was the original Halloween with Jamie Lee Curtis, not the crazy sequels.</p><p>I also remember enjoying Evil Dead, and a lesser extent Evil Dead II and Army of Darkness.  I saw Evil Dead when I was in college so it was perfect at that age, even with the campiness.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743554">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743554">10</a> by Jim
		posted on 10/31/2012 at 8:56 PM
		</div>
		<div class="comment_text"><p>Oh, and The Thing!!!!  Especially the one with Kurt Russell, but the remake was pretty good too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743559">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743559">11</a> by Raymond Camden
		posted on 10/31/2012 at 10:10 PM
		</div>
		<div class="comment_text"><p>I'm ashamed to say I still haven't seen any Evil Dead film. Ashamed.</p></div>
	</div>
</div>
		