
<div class="comment" id="c_1713650353">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650353">1</a> by Pat Branley
		posted on 2/20/2006 at 3:22 AM
		</div>
		<div class="comment_text"><p>Hi Ray</p><p>I came across this same issue last week with PDF files. Particular documents created via InDesign or another application that are distilled to PDF will return very strange titles.</p><p>My soluution was to manually set the title via the custom3 attribute and ignore the verity title field.</p><p>Pat</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650361">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650361">2</a> by Tom Jordahl
		posted on 2/23/2006 at 12:18 AM
		</div>
		<div class="comment_text"><p>One could argue that the title of a document is what the document says it is.  This is the thinking behind the behavior of CFMX7.  Consider the use case where you index a directory of documents, some of which don't have a title, but you application will display the title as part of the result.  You can specify a default title ("My default title") while indexing.  IMHO either way you choose, someone is unhappy.  I guess I chose wrong for you Ray. :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713650360">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650360">3</a> by Raymond Camden
		posted on 2/23/2006 at 1:26 AM
		</div>
		<div class="comment_text"><p>Heh, I'll live. I just got to find time now to update the cookbook.</p></div>
	</div>
</div>
		