
<div class="comment" id="c_1713670094">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713670094">1</a> by Jake Munson
		posted on 8/10/2007 at 3:46 AM
		</div>
		<div class="comment_text"><p>"I don't know if it is just me - but I have a heck of a time finding stuff there."</p><p>It's not just you, I've always had problems finding things on Macrobe's site.</p></div>
	</div>
</div>
		