
<div class="comment" id="c_1713720144">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713720144">1</a> by Simon Romanski
		posted on 11/26/2009 at 10:49 PM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving to all the CF nerds out there. <br>&lt;cfturkey cooked="justRight" enjoy="all" servings="GT 1"&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713720157">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713720157">2</a> by Alirio Boquin
		posted on 11/27/2009 at 12:44 AM
		</div>
		<div class="comment_text"><p>Happy Thanksgiving every one</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713720159">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713720159">3</a> by Jody Fitzpatrick
		posted on 11/27/2009 at 2:54 PM
		</div>
		<div class="comment_text"><p>Thanks Ray</p><p>I hope you ate to much. --Mmm, leftovers today. Yippie!</p><p>Happy BeLated Thanksgiving.</p></div>
	</div>
</div>
		