
<div class="comment" id="c_1713617231">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713617231">1</a> by Rick
		posted on 3/4/2005 at 2:11 AM
		</div>
		<div class="comment_text"><p>I'll be there again, that is a great conference!</p><p>Too bad I can't stay in the conference hotel this time... in the words of Ray's dad from Everybody Loves Raymond.. "HOLY CRAP" it's expensive.  Maybe we'll stay in the doubletree.  hah.</p></div>
	</div>
</div>
		