
<div class="comment" id="c_1713744191">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744191">1</a> by SuperAlly
		posted on 12/19/2012 at 9:46 PM
		</div>
		<div class="comment_text"><p>Not nice to make fun, Ray.  Pretty sure I have that comic.<br>And maybe the roller skates :)</p><p>Thanks for the heads up though, I'm one of those not on twitter.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744192">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744192">2</a> by Phillip Senn
		posted on 12/20/2012 at 2:50 AM
		</div>
		<div class="comment_text"><p>Gmail said "This message may not have been sent by: raymondcamden@gmail.com".</p><p>I think this is solved by using port 465 and useSSL="true" along with your username and password of course.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744179">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744179">3</a> by Raymond Camden
		posted on 12/20/2012 at 2:57 AM
		</div>
		<div class="comment_text"><p>When I get around to it - sorry. Not high on my list. ;)</p></div>
	</div>
</div>
		