
<div class="comment" id="c_1713727046">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727046">1</a> by Phil Duba
		posted on 10/21/2010 at 6:15 PM
		</div>
		<div class="comment_text"><p>Ray, the updates look slick. I still prefer Spoolmail over the CF9 as you (and others who contributed) give more options with the editing you can do on those emails.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727042">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727042">2</a> by Raymond Camden
		posted on 10/21/2010 at 6:19 PM
		</div>
		<div class="comment_text"><p>Glad you like it. If for some reason you downloaded _immediately_ after posting, get version 2.001. I added a small tweak based on feedback from Scott Stroz.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727033">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727033">3</a> by John Ramon
		posted on 10/22/2010 at 7:18 PM
		</div>
		<div class="comment_text"><p>I'm glad you like the ColdFusion Builder port Ray I built it cause the application I'm working on sends lots of mail and I needed a way to see if fast while I developed.</p><p>Oh and yes ColdFusion Builder extensions are freakin sweet, I check <a href="http://disq.us/url?url=http%3A%2F%2FRIAForge.org%3AruCwEJIgTRpvW43X0oLGmPnNtds&amp;cuid=3321886" rel="nofollow noopener" title="RIAForge.org">RIAForge.org</a> once a week for new ones.</p></div>
	</div>
</div>
		