
<div class="comment" id="c_1713732965">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732965">1</a> by Dave Ferguson
		posted on 6/3/2011 at 7:43 AM
		</div>
		<div class="comment_text"><p>This is sooooo cool.  I was thinking of uses for this in the real world.  I thought this would be great for a support group to scan email content and route email based on content.</p><p>So, if the email is full of anger you can delete it.  Alternatively , if it is full of praise you can auto forward to your boss.</p><p>;)</p><p>--Dave</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732962">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732962">2</a> by Brian Swartzfager
		posted on 6/3/2011 at 3:43 PM
		</div>
		<div class="comment_text"><p>That is pretty cool.  But it doesn't take much to get your text tagged as "slang":  apparently it considers "isn't" to be slang.  :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732963">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732963">3</a> by Raymond Camden
		posted on 6/3/2011 at 3:46 PM
		</div>
		<div class="comment_text"><p>Maybe it considers the contraction to be more informal - and therefore close to slang?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732964">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732964">4</a> by Darrell Berry
		posted on 6/21/2011 at 6:23 PM
		</div>
		<div class="comment_text"><p>You'll get better results with the latest (2.1) version of the APi -- just change the endpoint so it's AmplifyWeb_v21 not AmplifyWeb_v20</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713732967">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713732967">5</a> by Raymond Camden
		posted on 6/21/2011 at 6:25 PM
		</div>
		<div class="comment_text"><p>Interesting. It would be cool if OpenAmplify could do something like jQuery's CDN - where you could just ask for version X and you automatically get the latest point release.</p></div>
	</div>
</div>
		