
<div class="comment" id="c_1713622486">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713622486">1</a> by Rich
		posted on 11/29/2005 at 9:53 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>Is there a way to use the dateDiff function in a CFGRID to determine days remaining for each dated item returned from a database? For Example: how would you show the comparison of days remaining from a database that stored expiration dates of individual products?</p><p>Thanks, love the blog,</p><p>Rich</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713622488">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713622488">2</a> by Raymond Camden
		posted on 11/29/2005 at 7:24 PM
		</div>
		<div class="comment_text"><p>This is possible in normal Flash, but I don't believe you would be able to do it in Flash Forms. All I would do is change the query yourself. You can even do it in SQL so it's just one more column.</p></div>
	</div>
</div>
		