
<div class="comment" id="c_2184608799">
	<div>
		<img src="https://disqus.com/api/users/avatars/karlbishop.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2184608799">1</a> by Karl Bishop
		posted on 8/10/2015 at 4:09 PM
		</div>
		<div class="comment_text"><p>Nice writeup.  As always, I look forward to more on this topic.</p><p>On the setServerUrl(), this is often used when a single app is white labeled for use by multiple companies. We do this in our IBM Maximo Anywhere product. One app, used by many different companies, which they obviously want hosted on different specific URLs (er Urls!). As part of install/setup, user would enter a specific company code on a generic view, then a call is made to a common server to get company details (logos, Url, themes, auth server, etc), then the target MFP Server url is set and we now have a custom App specifically for that user. Works quite well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2184626251">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2184626251">2</a> (In reply to <a href="#c_2184608799">#1</a>) by Raymond Camden
		posted on 8/10/2015 at 4:18 PM
		</div>
		<div class="comment_text"><p>Cool - thanks for sharing that! Yeah, I hope to get more posts on this topic once I get done with some travel.</p></div>
	</div>
</div>
		