
<div class="comment" id="c_1713667747">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667747">1</a> by todd sharp
		posted on 6/22/2007 at 3:38 AM
		</div>
		<div class="comment_text"><p>4 logged in users?  What is the referring to - sessions or actual users logged in via cflogin?  I'm sure it has to be actual logins - but is the actual proof that Ray is indeed a conglomerate and not a single person? :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667753">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667753">2</a> by Raymond Camden
		posted on 6/22/2007 at 5:31 PM
		</div>
		<div class="comment_text"><p>It specifically refers to cflogin.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667754">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667754">3</a> by Chris Phillips
		posted on 6/23/2007 at 12:21 AM
		</div>
		<div class="comment_text"><p>How is the memory utilization 0-0-0?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667756">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667756">4</a> by Raymond Camden
		posted on 6/23/2007 at 12:26 AM
		</div>
		<div class="comment_text"><p>That is the Memory Tracking. I have it turned off.</p></div>
	</div>
</div>
		