
<div class="comment" id="c_1713739320">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739320">1</a> by David McGuigan
		posted on 3/1/2012 at 7:48 AM
		</div>
		<div class="comment_text"><p>Open source license? Are you kidding me? I was ecstatic about this contest until I read that line. Now I can't even enter it frown.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739321">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739321">2</a> by Raymond Camden
		posted on 3/1/2012 at 7:56 AM
		</div>
		<div class="comment_text"><p>Sorry you feel that way. -Every- contest I've run has been that way. The idea being folks can download the code and play with it. You aren't giving up your copyright, just agreeing to allow others to make use of your code. As I said - every other contest run on this blog has followed the exact same rules.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739322">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739322">3</a> by David McGuigan
		posted on 3/1/2012 at 9:30 AM
		</div>
		<div class="comment_text"><p>I was just being bitter. It's an awesome contest. Can't wait to see the entries.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739329">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739329">4</a> by Raymond Camden
		posted on 3/1/2012 at 10:02 AM
		</div>
		<div class="comment_text"><p>Um.... ok. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739325">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739325">5</a> by Lola LB
		posted on 3/1/2012 at 6:10 PM
		</div>
		<div class="comment_text"><p>Love that Zeus cartoon!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739326">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739326">6</a> by Tom K
		posted on 4/14/2012 at 6:43 PM
		</div>
		<div class="comment_text"><p>Did the contest URL ever get posted? I don't see it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739324">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739324">7</a> by Raymond Camden
		posted on 4/14/2012 at 6:44 PM
		</div>
		<div class="comment_text"><p>No - but you can email me the zip directly.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739327">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739327">8</a> by Dale Fraser
		posted on 4/30/2012 at 6:16 PM
		</div>
		<div class="comment_text"><p>Love your contests,</p><p>Not really a submitter, but like to see what people put together. However I think the Facebook like model, is nothing more than a popularity contest.</p><p>Someone with 1000 facebook friends could easily get more votes by asking their friends than a non facebook user etc.</p><p>As I said it doesn't affect me as I wont submit, but hopefully you have thought of this and have a solution.</p><p>Look forward to reading the entries regardless.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713739328">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713739328">9</a> by Raymond Camden
		posted on 4/30/2012 at 6:36 PM
		</div>
		<div class="comment_text"><p>That's why we have 4 prizes - only 2 will be based on FB. As it stands - our community isn't a huge one. I don't think it will be much of a problem. (And if it is, well, we won't repeat it for CF11. ;)</p></div>
	</div>
</div>
		