
<div class="comment" id="c_1714083386">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083386">1</a> by Raymond Camden
		posted on 7/12/2014 at 1:25 AM
		</div>
		<div class="comment_text"><p>Wow, that video is crap. It is a bit better over at Youtube: <a href="https://disq.us/url?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-FjyvRe_RBk%26feature%3Dyoutube_gdata%3AcyiHrE1Mlt59XiwVxRBlPau84SM&amp;cuid=3321886" rel="nofollow noopener" title="https://www.youtube.com/watch?v=-FjyvRe_RBk&amp;feature=youtube_gdata">https://www.youtube.com/wat...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083387">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083387">2</a> by Jesper Hessius
		posted on 7/17/2014 at 11:47 PM
		</div>
		<div class="comment_text"><p>Due to shared folders and permission issues I need to sudo all my Cordova commands. Does this plugin support sudo-ing? If not, will it ever?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083389">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083389">3</a> by Raymond Camden
		posted on 7/20/2014 at 3:19 AM
		</div>
		<div class="comment_text"><p>Afaik you can't do sudo via the Node usage in Brackets. For the heck of it, try editing the code to add su in front of the command calls.</p></div>
	</div>
</div>
		