
<div class="comment" id="c_4032937378">
	<div>
		<img src="https://disqus.com/api/users/avatars/wilgenovese.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4032937378">1</a> by Wil Genovese
		posted on 8/10/2018 at 4:17 PM
		</div>
		<div class="comment_text"><p>Thank you for this Ray. I really needed this post about a month ago. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4032997387">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4032997387">2</a> by Robert Zehnder
		posted on 8/10/2018 at 4:49 PM
		</div>
		<div class="comment_text"><p>Great article, Ray. I got that book a year or so back when you recommended it to me, it does a great job of explaining Node and Express.</p><p>I will say one of the biggest stumbling blocks I had learning Node, coming from a ColdFusion background, is the fact Node is inherently asynchronous. Once you learn to leverage async/await it makes the "callback hell" bearable, but it got me in the beginning.</p><p>I love Node now so I guess I got past it. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4033051032">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4033051032">3</a> (In reply to <a href="#c_4032937378">#1</a>) by Raymond Camden
		posted on 8/10/2018 at 5:18 PM
		</div>
		<div class="comment_text"><p>Better late than never. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4033053955">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4033053955">4</a> (In reply to <a href="#c_4032997387">#2</a>) by Raymond Camden
		posted on 8/10/2018 at 5:19 PM
		</div>
		<div class="comment_text"><p>That kind of brings up a good point - if you come into Node with some basic JS experience, then the async stuff wouldn't be that big of an issue.</p><p>Well... now that I think about it... that was me, and the fact that nearly everything in Node is async was kind of a thing I had to adapt too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4033166062">
	<div>
		<img src="https://disqus.com/api/users/avatars/robbarthle.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4033166062">5</a> by Rob Barthle
		posted on 8/10/2018 at 6:20 PM
		</div>
		<div class="comment_text"><p>"Buy the book! Yes, this book here… (and if you do I get a few cents):</p><p>I will warn you. This book is old and a new version is coming sometime soon. However, this book is so damn good - I’m serious - that I’d buy it even if out of date. I have a physical and ebook copy - that’s how good it is. It was perfect for me as a ColdFusion developer because it focused heavily on how to do ‘web stuff’ in Express and used terminology I was already familiar with. I can’t recommend this enough - so buy a few copies today!"</p><p>So I don't see a link in this block of text... can you put the URL back up for it?</p></div>
	</div>
</div>
		
<div class="comment" id="c_4033173321">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4033173321">6</a> (In reply to <a href="#c_4033166062">#5</a>) by Raymond Camden
		posted on 8/10/2018 at 6:24 PM
		</div>
		<div class="comment_text"><p>You may have an ad blocker on - try this: <a href="https://disq.us/url?url=https%3A%2F%2Fwww.amazon.com%2FWeb-Development-Node-Express-Leveraging%2Fdp%2F1491949309%2Fref%3Das_sl_pc_qf_sp_asin_til%3Ftag%3Draymondcamd06-20%26linkCode%3Dw00%26linkId%3Daaabe8497495881b7850161f9ff63aaf%26creativeASIN%3D1491949309%3AnShbTHKqqd3Jdbg1mABf3wtrExg&amp;cuid=3321886" rel="nofollow noopener" title="https://www.amazon.com/Web-Development-Node-Express-Leveraging/dp/1491949309/ref=as_sl_pc_qf_sp_asin_til?tag=raymondcamd06-20&amp;linkCode=w00&amp;linkId=aaabe8497495881b7850161f9ff63aaf&amp;creativeASIN=1491949309">https://www.amazon.com/Web-...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_4033808981">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_9Z8J2Fq0yY.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4033808981">7</a> by James Parson, CA Islander
		posted on 8/11/2018 at 2:42 AM
		</div>
		<div class="comment_text"><p>A lot of Nodejs development seems to be done in Angular, React, Vuejs, and others. How do you see this fitting into the mix?</p></div>
	</div>
</div>
		
<div class="comment" id="c_4034375381">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4034375381">8</a> (In reply to <a href="#c_4033808981">#7</a>) by Raymond Camden
		posted on 8/11/2018 at 1:07 PM
		</div>
		<div class="comment_text"><p>If you're talking about server-side rendering, that's kind of a different story altogether. Being able to use Vue on the server is nice for me as I know Vue well and I'm more productive.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4088452290">
	<div>
		<img src="https://disqus.com/api/users/avatars/dani_szwarc.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4088452290">9</a> by Dani Szwarc
		posted on 9/10/2018 at 10:14 PM
		</div>
		<div class="comment_text"><p>Thank you very much Ray, perfect timing for me.<br>Still absolutely in love with Coldfusion, but I have the feeling Node will blow my mind.<br>Besides, the IBM i operating system supports it natively, so I understand this is the way to go for me.</p></div>
	</div>
</div>
		