
<div class="comment" id="c_1713678759">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678759">1</a> by James Buckingham
		posted on 4/1/2008 at 5:47 PM
		</div>
		<div class="comment_text"><p>Funny you say that because just this morning I check my Google Analytic's "Keyword" section and someone apparently visited my blog through the phrase:</p><p>"blogcfc was created by raymond camden bike bicycle"</p><p>Have you taken up cycling recently? :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678781">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678781">2</a> by Eric Cobb
		posted on 4/1/2008 at 5:53 PM
		</div>
		<div class="comment_text"><p>So, let me get this straight...anything we Google with your name in it gets reported back to you?  Oh, I'm going to have fun with this one!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678782">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678782">3</a> by noname
		posted on 4/1/2008 at 5:55 PM
		</div>
		<div class="comment_text"><p>I bet they were looking for that bike website started by a CF guy ... ?  Or the walking one?<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.barneyb.com%2Fbicycle%2F%3Atsg0QF8ymg_LXwz-OsgMsBJlH5s&amp;cuid=3321886" rel="nofollow noopener" title="http://www.barneyb.com/bicycle/">http://www.barneyb.com/bicy...</a><br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.walkjogrun.net%2F%3A6wjQXuQp_TM039E_y7sL--OtFDM&amp;cuid=3321886" rel="nofollow noopener" title="http://www.walkjogrun.net/">http://www.walkjogrun.net/</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678779">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678779">4</a> by Terrence Ryan
		posted on 4/1/2008 at 7:41 PM
		</div>
		<div class="comment_text"><p>Hey, I used CF_Perl for talking to an obscure technology that only Perl could access.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678775">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678775">5</a> by Randy
		posted on 4/1/2008 at 10:53 PM
		</div>
		<div class="comment_text"><p>@Eric,</p><p>Anytime google finds a website with Ray's name on it they send him an email.</p><p>-Randy</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713678780">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713678780">6</a> by me
		posted on 7/16/2008 at 1:25 AM
		</div>
		<div class="comment_text"><p>Hi</p></div>
	</div>
</div>
		