
<div class="comment" id="c_1713620858">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620858">1</a> by Jeff
		posted on 9/20/2005 at 12:33 AM
		</div>
		<div class="comment_text"><p>It might be worth noting that the dump tag which CF uses is written in CFML and can usually be found at"installroot\wwwroot\web-inf\cftags"  (at least on my machine).</p><p> It is encrypted, but the more enterprising readers should be able to find a way to view the code, or even get it working on BlueDragon.</p></div>
	</div>
</div>
		