
<div class="comment" id="c_1713673832">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673832">1</a> by Tunç
		posted on 10/30/2007 at 9:18 PM
		</div>
		<div class="comment_text"><p>Congratulations!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673835">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673835">2</a> by nate w
		posted on 10/30/2007 at 9:38 PM
		</div>
		<div class="comment_text"><p>Raymond, think bigger. Platinum!</p><p>Congrats on the great work and HUGE milestone.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673826">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673826">3</a> by Scott Stroz
		posted on 10/30/2007 at 10:04 PM
		</div>
		<div class="comment_text"><p>That's like 1 download for every 15 times you mention your wish list.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673841">4</a> by Raymond Camden
		posted on 10/30/2007 at 10:11 PM
		</div>
		<div class="comment_text"><p>Did I mention I have a wish list? You can find it here:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.amazon.com%2Fo%2Fregistry%2F2TCL1D08EZEYE%3Agyb61Su9v2bImuklfGOg_P_GnNw&amp;cuid=3321886" rel="nofollow noopener" title="http://www.amazon.com/o/registry/2TCL1D08EZEYE">http://www.amazon.com/o/reg...</a></p><p>Boy does that Call of Duty 4 look like a prime target.</p><p>;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713673838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713673838">5</a> by Anuj Gakhar
		posted on 10/31/2007 at 6:32 PM
		</div>
		<div class="comment_text"><p>Congrats! Thats a lot of downloads within the CF world.</p></div>
	</div>
</div>
		