
<div class="comment" id="c_1713685323">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685323">1</a> by James Moberg
		posted on 8/27/2008 at 7:27 AM
		</div>
		<div class="comment_text"><p>The ScopeCache page (from the provided link) indicates that it was last updated on 8/21.  Has it been updated since then?  Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685329">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685329">2</a> by Raymond Camden
		posted on 8/27/2008 at 7:58 AM
		</div>
		<div class="comment_text"><p>Nope, I was just a bit slow to announce it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685325">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685325">3</a> by John Farrar
		posted on 8/28/2008 at 6:06 PM
		</div>
		<div class="comment_text"><p>You should add file as a cache option in the description. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685331">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685331">4</a> by Raymond Camden
		posted on 8/28/2008 at 6:12 PM
		</div>
		<div class="comment_text"><p>Good point. Added. Thanks!</p></div>
	</div>
</div>
		