
<div class="comment" id="c_1713675519">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675519">1</a> by Hugh
		posted on 12/13/2007 at 8:35 PM
		</div>
		<div class="comment_text"><p>Their new LiveDocs search stinks as well, when searching for something like the Proxy class in AS3, you get a list of results for other products.  No!  Just search within the current document, just like the old way!  ARGH!!!  It's beyond frustrating!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675522">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675522">2</a> by Rob Brooks-Bilson
		posted on 12/13/2007 at 8:54 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>If you have a Google Search Appliance (like I do for internal search, still using Verity for external), they have two features that deal specifically with this issue.  The first is called keymatch.  This lets you define specific urls to show at the top (above normal search results) for specific terms.</p><p>The second feature is Search Biasing, so you can give certain search results greater weight to move to the top.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675508">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675508">3</a> by Ben Nadel
		posted on 12/13/2007 at 8:54 PM
		</div>
		<div class="comment_text"><p>We work with a lot of legal clients, and they need their site searches super customized. Sometimes they like the results grouped by attorney, practice area, event, etc. Sometimes they like it grouped in chronological order. Sometimes they want partners listed before associates. Sometimes they want certain items NOT to show up at all.</p><p>We tend to hand code a lot of our searches. They are not the most efficient as we don't really leverage tools like Verity, but otherwise, I am not sure how we can satisfy the attorneys.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675524">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675524">4</a> by Raymond Camden
		posted on 12/13/2007 at 8:59 PM
		</div>
		<div class="comment_text"><p>@Rob - Cool. I wonder if Adobe did this, but maybe hasn't kept it updated. That's another concern too - if you do 'hack up' your search, how hard is maintenance?</p><p>@Ben - ditto above. Sounds like difficult work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675520">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675520">5</a> by Rob Brooks-Bilson
		posted on 12/13/2007 at 9:02 PM
		</div>
		<div class="comment_text"><p>On the GSA side, it's pretty easy to maintain.  Keymatches can be imported/exported, so we just keep them in a spreadsheet for easy of updating, then bulk load them.  The rest of the GSA tools are pretty simple to work with.</p><p>One other advantage for us is that I can have a non-CF person manage the GSA as it's more user/admin focused with a relatively nice web based admin.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675528">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675528">6</a> by Pragnesh Vaghela
		posted on 12/13/2007 at 11:13 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>For a client of mine we started tracking every keyword/phrase entered in the search box. Every month the client gets a report and they make Architecture/UI changes accordingly.</p><p>Recently Site Search was added in Google Analytics (<a href="http://disq.us/url?url=http%3A%2F%2Fanalytics.blogspot.com%2F2007%2F11%2Fsite-search-now-available.html%29%3AbONzDQuF0nAAGB1Uo9I-GzTohtc&amp;cuid=3321886" rel="nofollow noopener" title="http://analytics.blogspot.com/2007/11/site-search-now-available.html)">http://analytics.blogspot.c...</a>. With Site Search, you can now see how people search your site once they are already on it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675527">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675527">7</a> by Troy Allen
		posted on 12/14/2007 at 1:09 AM
		</div>
		<div class="comment_text"><p>@Rob - The Google Search Appliance is very cool, and very flexible. But at a starting price of $30k, that is probably too high for most clients' search needs (at least my usual client base).</p><p>@Pragnesh - Thanks for posting that link...I had not heard that Google Analytics now included Site Search. That really opens up some cool new possibilities for me and my customers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675526">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675526">8</a> by Kristen Schofield
		posted on 12/14/2007 at 2:59 AM
		</div>
		<div class="comment_text"><p>Ray - thanks for pointing this out. I'm going to have it fixed for CF and pass along to other prod teams.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675531">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675531">9</a> by Jim Stout
		posted on 12/18/2007 at 3:24 AM
		</div>
		<div class="comment_text"><p>"If your search engine isn't returning what you want, what methods have you done to correct it? For my client it was a simple matter of "munging" the search string a bit. Have others done this? Or have you perhaps modified the result set?"</p><p>I would also to know how other people are 'weighting' Verity's search results. We are currently redesigning our site and I would like to include some ability to 'weight' the results in a way that satisfies our internal customers belief that one of their pages should be at the top a search....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675529">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675529">10</a> by Sebastiaan
		posted on 6/1/2009 at 11:14 PM
		</div>
		<div class="comment_text"><p>Hi Ray, I'm trying to make a searchtool for a website running CF8 and a MySQL5 database. But it's in a shared hosting environment and I only want to index or search in the body of the text of every entry. Help! I've tried Lucene and Verity but I get access denied errors all the time from the hosting provider. Is there a way to build a homegrown search tool - or can you give me some pointers? I have a get-set-go version using Lucene for BlueDragon 6 I built some years ago, but it just doesn't work in CF8 (shared hosting) ;-(</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675533">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675533">11</a> by Raymond Camden
		posted on 6/2/2009 at 3:16 PM
		</div>
		<div class="comment_text"><p>Can you ask your host to provide support for the access denied errors?</p></div>
	</div>
</div>
		