
<div class="comment" id="c_1713669232">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669232">1</a> by Michael Sharman
		posted on 7/27/2007 at 3:54 AM
		</div>
		<div class="comment_text"><p>Great fix, that was most annoying when on the mac!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713669238">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713669238">2</a> by Charlie Arehart
		posted on 7/27/2007 at 5:28 PM
		</div>
		<div class="comment_text"><p>To clarify, that's in includes/style.css.</p></div>
	</div>
</div>
		