
<div class="comment" id="c_1713715586">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715586">1</a> by Eric Cobb
		posted on 5/19/2009 at 10:47 PM
		</div>
		<div class="comment_text"><p>That is so cool!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715597">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715597">2</a> by Andy Sandefer
		posted on 5/19/2009 at 11:04 PM
		</div>
		<div class="comment_text"><p>That was an interesting read.  I had no idea what InContext Editing meant and now I know - and remember from watching GIJOE when you were a kid "Knowing is half the battle".<br>Well done @Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715595">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715595">3</a> by Raymond Camden
		posted on 5/19/2009 at 11:07 PM
		</div>
		<div class="comment_text"><p>You are welcome. I should point out that this is my last DW article. I'm glad I accepted the writing gig as I've gotten a whole new level of respect for Dreamweaver. Will I use it over Eclipse? No. But it comes darn close and I can definitely recommend it to others.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715599">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715599">4</a> by Patrick
		posted on 5/20/2009 at 1:37 PM
		</div>
		<div class="comment_text"><p>Thanks Ray! I have heard about ICE before, but i read somewhere about a "special server" needed and therefore never tried it.</p><p>Now i just setup a subdomain and start playing with it. Is ICE only available in english? A german interface would be nice.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715604">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715604">5</a> by Raymond Camden
		posted on 5/20/2009 at 3:00 PM
		</div>
		<div class="comment_text"><p>Patrick: No idea on language. Sorry. :)</p></div>
	</div>
</div>
		