
<div class="comment" id="c_1713666655">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666655">1</a> by Josh Nathanson
		posted on 6/8/2007 at 2:49 AM
		</div>
		<div class="comment_text"><p>Now if they would just add a link to the left menu, where they have all the other languages, people might actually be able to find it.  WTF??</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666642">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666642">2</a> by Sam Farmer
		posted on 6/8/2007 at 3:29 AM
		</div>
		<div class="comment_text"><p>Congrats on all your hard work, Ray.  Great news.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666657">3</a> by Jay
		posted on 6/8/2007 at 3:44 AM
		</div>
		<div class="comment_text"><p>Waahooooo Ray's Coldfusion crusader gang!</p><p>Lemme at em uncle scoob, lemme at em!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666653">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666653">4</a> by Raymond Camden
		posted on 6/8/2007 at 4:32 AM
		</div>
		<div class="comment_text"><p>Josh - they know of the missing link. It will get fixed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666656">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666656">5</a> by Pragnesh Vaghela
		posted on 6/8/2007 at 6:56 AM
		</div>
		<div class="comment_text"><p>Great work Ray. Congrats</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666664">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666664">6</a> by Mark Drew
		posted on 6/8/2007 at 10:55 AM
		</div>
		<div class="comment_text"><p>Shall we hire Chris Cornell to sing "You know my CF Name!" for us?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666658">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666658">7</a> by ziggy
		posted on 6/8/2007 at 11:02 AM
		</div>
		<div class="comment_text"><p>&gt;&gt;I bugged Yahoo about this and when they finally came back to me and asked me to write it up</p><p>This is why Adobe CF support is a joke. Why in the world do they not have someone who works on issues like this all over the net? They should hire you to work for CF and get their act together.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666665">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666665">8</a> by Wayne Putterill
		posted on 6/8/2007 at 1:14 PM
		</div>
		<div class="comment_text"><p>Quick heads up, the "how to make a Yahoo! Web Service request" link at the top of the "Parse Yahoo! Web Service" page goes to the PHP version.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666663">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666663">9</a> by Brian Swartzfager
		posted on 6/8/2007 at 4:03 PM
		</div>
		<div class="comment_text"><p>Wayne's right:  it's the first link on this page:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fdeveloper.yahoo.com%2Fcoldfusion%2Fhowto-parseRestCF.html%3AwMyPiC1E_aN104mKL8Ae_NoVkoQ&amp;cuid=3321886" rel="nofollow noopener" title="http://developer.yahoo.com/coldfusion/howto-parseRestCF.html">http://developer.yahoo.com/...</a></p><p>Following the link takes you to Yahoo's missing page notice.</p><p>Still, this is all really cool.  Thanks for doing this Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666661">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666661">10</a> by James, F.E.
		posted on 6/8/2007 at 6:13 PM
		</div>
		<div class="comment_text"><p>Thanks for getting this put together Ray. It is appreciated.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666662">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666662">11</a> by Frank Hipolito
		posted on 6/8/2007 at 7:20 PM
		</div>
		<div class="comment_text"><p>Well Done.<br>I'm looking forward to using them.<br>Keep up the great work!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666659">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666659">12</a> by Josh Nathanson
		posted on 6/8/2007 at 8:24 PM
		</div>
		<div class="comment_text"><p>Link is still missing from the left menu, but at least there's a nice paragraph on the Dev Center home page about the new addition.</p><p>Yeah, Adobe should hire you Ray.  The ColdFusion community would have even LESS visibility if it wasn't for you.  Thanks for everything.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666666">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666666">13</a> by Raymond Camden
		posted on 6/8/2007 at 8:28 PM
		</div>
		<div class="comment_text"><p>My Yahoo contacts knows about the left hand link. It _will_ be fixed - there is just something else going on (unrelated) that is delaying it - but trust me - it will go in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666645">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666645">14</a> by Patrick Whittingham
		posted on 6/8/2007 at 9:28 PM
		</div>
		<div class="comment_text"><p>good job Raymond....:)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666646">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666646">15</a> by Frank Hipolito
		posted on 6/8/2007 at 10:26 PM
		</div>
		<div class="comment_text"><p>The install docs all reference your <a href="http://disq.us/url?url=http%3A%2F%2Fcamdenfamily.com%3AwTisx5fv2XwC3bFwuiKCun0fT3w&amp;cuid=3321886" rel="nofollow noopener" title="camdenfamily.com">camdenfamily.com</a> info</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666647">16</a> by Raymond Camden
		posted on 6/8/2007 at 10:39 PM
		</div>
		<div class="comment_text"><p>Frank, I sent in the text before I moved.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666650">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666650">17</a> by Andrew S
		posted on 6/12/2007 at 4:25 AM
		</div>
		<div class="comment_text"><p>You're fighting the good fight Ray.  Keep it up!  Now all the rest of us in the community need to do whatever we can to keep this momentum.</p><p>Thanks Again!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666648">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666648">18</a> by John
		posted on 6/12/2007 at 5:18 AM
		</div>
		<div class="comment_text"><p>Great stuff Ray, Yay :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666756">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666756">19</a> by sean
		posted on 6/12/2007 at 9:24 AM
		</div>
		<div class="comment_text"><p>Rock on good work!. Cant wait to put to put this to work on my TravelLogix Reservation booking system.</p><p>Let me know if need some help!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666761">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666761">20</a> by Gary Gilbert
		posted on 6/12/2007 at 5:19 PM
		</div>
		<div class="comment_text"><p>Nice going Ray!</p><p>Momentum steadily increasing, just wish CF use was a bit broader in Mainland Europe, specifically Germany.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666763">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666763">21</a> by Simon Whatley
		posted on 7/5/2007 at 2:04 AM
		</div>
		<div class="comment_text"><p>I have to reiterate every CF developer's support of this step to get ColdFusion onto the Yahoo developer network and to thank you in facilitating the process.</p><p>With the release of CF8, and the integration of YUI amongst other great additions, CF can go stratospheric.</p><p>Two things I ask, 1) can we get a menu link on the Yahoo Developer Network to the ColdFusion pages; and 2) can we have more CF/Flex events in Europe, you guys in the US have a near monopoly on them!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713666762">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713666762">22</a> by Raymond Camden
		posted on 7/5/2007 at 3:11 AM
		</div>
		<div class="comment_text"><p>1) This is a known issue. The link was supposed to be up there already, but... It should be there soon.</p><p>2) Many conferences are done by the community. You should consider doing one yourself. :)</p></div>
	</div>
</div>
		