
<div class="comment" id="c_1713650823">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713650823">1</a> by Jen
		posted on 3/17/2006 at 2:53 AM
		</div>
		<div class="comment_text"><p>Great presentation, Ray! Thanks so much for your time. Hoping to catch the full version at CFUnited this summer!</p></div>
	</div>
</div>
		