
<div class="comment" id="c_1713726857">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726857">1</a> by ppshein
		posted on 10/15/2010 at 9:35 AM
		</div>
		<div class="comment_text"><p>Can I migrate MangoBlog to BlogCFC? If say "Yap", where can I find information for that?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726865">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726865">2</a> by Raymond Camden
		posted on 10/15/2010 at 4:23 PM
		</div>
		<div class="comment_text"><p>You can, but it involves migrating the DB manually. You may want to check this entry: <a href="http://disq.us/url?url=http%3A%2F%2Fnil.checksite.co.uk%2Findex.cfm%2F2010%2F1%2F27%2FA-Return-to-BlogCFC%3AMbK8eCj2q4v4nD90grqJw5EhUx8&amp;cuid=3321886" rel="nofollow noopener" title="http://nil.checksite.co.uk/index.cfm/2010/1/27/A-Return-to-BlogCFC">http://nil.checksite.co.uk/...</a> and see if it helps.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726861">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726861">3</a> by ppshein
		posted on 10/19/2010 at 7:57 AM
		</div>
		<div class="comment_text"><p>BlogCFC can support Railo? Because, my blog is based on Railo hosting.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726860">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726860">4</a> by Raymond Camden
		posted on 10/19/2010 at 3:53 PM
		</div>
		<div class="comment_text"><p>It should be 100% CF7 compat, so as long as Railo is, it isn't a problem.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726863">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726863">5</a> by Joe Brislin
		posted on 10/22/2010 at 1:02 AM
		</div>
		<div class="comment_text"><p>Thought you might want to know that the mobile version of your blog does not work on the Blackberry browser. Whenever you click on a blog post link, the browser opens the blog post for a brief second and then closes and returns you to the home screen.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726866">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726866">6</a> by Raymond Camden
		posted on 10/22/2010 at 1:04 AM
		</div>
		<div class="comment_text"><p>Yeah, this is the third report I've gotten. I'm going to remove the BB from the list of browsers "auto pushed" to mobile.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726862">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726862">7</a> by Raymond Camden
		posted on 10/22/2010 at 1:29 AM
		</div>
		<div class="comment_text"><p>Joe, I've pushed the change here. If you can confirm it works for you (and by works I mean you won't get the mobile version), then I can push it over to BlogCFC mainline.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726868">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726868">8</a> by ppshein
		posted on 10/22/2010 at 6:00 AM
		</div>
		<div class="comment_text"><p>@Ray,</p><p>Mobile version doesn't work when I access <a href="http://disq.us/url?url=http%3A%2F%2Fwww.ppshein.net%2FBlogCFC%2Fclient%2Findex.cfm%3Ah17ZS36beFd4CcaEG4TlG7GAgdE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.ppshein.net/BlogCFC/client/index.cfm">http://www.ppshein.net/Blog...</a> with my iPhone.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726867">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726867">9</a> by Raymond Camden
		posted on 10/22/2010 at 7:24 AM
		</div>
		<div class="comment_text"><p>Can you please describe how it doesn't work?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726876">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726876">10</a> by ppshein
		posted on 10/23/2010 at 4:33 AM
		</div>
		<div class="comment_text"><p>When I access with iPhone's Safari, normal browser version come out instead of Mobile version.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fimg707.imageshack.us%2Fimg707%2F6434%2Fphotoai.png%3ABXQo_czLzZbXNaGfkSq3w5x14l4&amp;cuid=3321886" rel="nofollow noopener" title="http://img707.imageshack.us/img707/6434/photoai.png">http://img707.imageshack.us...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726856">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726856">11</a> by ppshein
		posted on 10/23/2010 at 1:05 PM
		</div>
		<div class="comment_text"><p>Hi,</p><p>I've finally migrated to blogCFC and mobile version is fine now. Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726854">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726854">12</a> by Raymond Camden
		posted on 10/23/2010 at 5:05 PM
		</div>
		<div class="comment_text"><p>Woot. As an FYI, there are 2 bugs:</p><p>1) It pushes Blackberry to mobile and the BB doesn't like the mobile. Next update will change this.</p><p>2) If a blog entry has a download, you can't see it from mobile.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726852">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726852">13</a> by Joe Brislin
		posted on 10/25/2010 at 5:08 PM
		</div>
		<div class="comment_text"><p>Ray,<br>Sorry the comments were getting sent to my spam folder so I just saw this. I tried it on my BB again and it was still pushing it to the mobile site. I cleared my browser cache to make sure it wasn't that but still got sent to the mobile version. Let me know if there is anything else you need me to try.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726851">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726851">14</a> by Raymond Camden
		posted on 10/27/2010 at 11:11 AM
		</div>
		<div class="comment_text"><p>Can you tell me what your user agent string is?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726853">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726853">15</a> by Joe Brislin
		posted on 10/27/2010 at 7:02 PM
		</div>
		<div class="comment_text"><p>BlackBerry9630/5.0.0.975 Profile/MIDP-2.1 Configuration/CLDC-1.1 VendorID/105</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713726855">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713726855">16</a> by Raymond Camden
		posted on 11/1/2010 at 6:02 PM
		</div>
		<div class="comment_text"><p>Please try again. The issue was MIDP in your UA string. I now have code that says if you find blackberry at all, deny.</p></div>
	</div>
</div>
		