
<div class="comment" id="c_1713740909">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740909">1</a> by jD
		posted on 5/4/2012 at 6:19 PM
		</div>
		<div class="comment_text"><p>Raymond,</p><p>   This is awesome congrats!...<br>It took very-very short time in get publish.</p><p>Thank you<br>jD @ <a href="http://disq.us/url?url=http%3A%2F%2Fpragmatikroo.blogspot.com%3AUzr7qCHI1Hcsbp6jF_axxafbofI&amp;cuid=3321886" rel="nofollow noopener" title="http://pragmatikroo.blogspot.com">http://pragmatikroo.blogspo...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740894">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740894">2</a> by RogerTheGeek
		posted on 5/4/2012 at 6:31 PM
		</div>
		<div class="comment_text"><p>I didn't see the link, then realized that Ghostery wipes JS widgets out. I'll look on Amazon. Usually, the blockers are really nice in eliminating stuff. It really made me realize how many pages depend on JS for a lot of functionality.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740910">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740910">3</a> by Jaana Gilbert
		posted on 5/4/2012 at 7:52 PM
		</div>
		<div class="comment_text"><p>I tried to get it from the Packt site link. I selected the print + eBook and the price was suppose to be $39.95 or similar, but in the cart it was $50+. Needless to say I didn't purchase it from there. Until they get that fixed, I won't be buying it from them :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740911">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740911">4</a> by Raymond Camden
		posted on 5/4/2012 at 7:55 PM
		</div>
		<div class="comment_text"><p>Weird. Did you try their support form?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740908">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740908">5</a> by Jaana Gilbert
		posted on 5/4/2012 at 7:59 PM
		</div>
		<div class="comment_text"><p>It's correct now. The 85% discount is showing on the eBook now. The total including shipping for $70 was a bit too much to swallow :) I'm placing the order for it now that the pricing is correct.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740913">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740913">6</a> by Raymond Camden
		posted on 5/4/2012 at 8:05 PM
		</div>
		<div class="comment_text"><p>And as always... be critical. Be honest. I know both Andy and I wanted to make something that was useful,helpful, etc. If I have failed in that respect, I want to know.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740915">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740915">7</a> by Jaana Gilbert
		posted on 5/4/2012 at 8:09 PM
		</div>
		<div class="comment_text"><p>No problem. I known to be painfully direct :D</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740912">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740912">8</a> by DH House
		posted on 5/5/2012 at 7:08 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Is this going to be released for Kindle?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740914">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740914">9</a> by Jaana Gilbert
		posted on 5/5/2012 at 7:18 AM
		</div>
		<div class="comment_text"><p>@DH House<br>You can download the eBook to Kindle and other eBook readers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740897">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740897">10</a> by John Hofmann
		posted on 5/7/2012 at 2:44 AM
		</div>
		<div class="comment_text"><p>Nice book Ray and so far so good. I have always liked your writing stye. It is very personal and seems to be directed right at me. Thanks for all you do for the community.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740895">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740895">11</a> by Mikel
		posted on 5/8/2012 at 5:36 PM
		</div>
		<div class="comment_text"><p>It is still showing as pre-order only :(</p><p>This title will be released on July 17, 2012</p><p>Oh well I'm ordering anyway!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740896">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740896">12</a> by Raymond Camden
		posted on 5/8/2012 at 5:41 PM
		</div>
		<div class="comment_text"><p>Mikel, I heard from one of the folks at Pakt. They put in the change about 2 days ago, and supposedly it takes 4-5 days to process. So the right date should be there real soon now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740899">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740899">13</a> by Prad
		posted on 5/10/2012 at 5:00 AM
		</div>
		<div class="comment_text"><p>I had similar issues with Packt's promo system when they recently offered 3 ebooks for $19.99. Strangely! I was being overcharged and was also charged for delivery when I added a discounted offer to a month long Packtlib subscription on top of ebooks. Packt have been having problems with their cart system especially with discount coupons since they rolled out their new Drupal Site. I have had problems before and they have always refunded the excess. Though they have been slow with refund recently and I had to contact them twice, but they were responsive to my emails within 24 hours. So I guess we should not worry about Packt overcharging if you really want discounted books and happy to spend time (though annoying) emailing them the problem. They do care about their niche customers.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740898">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740898">14</a> by Mikel
		posted on 5/26/2012 at 12:15 AM
		</div>
		<div class="comment_text"><p>Got my book today.  It is so well written that I may task my 11 year old with working her way through it and learning something really worthwhile!</p><p>My evil secret is that I can then ask her to help me with projects :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740900">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740900">15</a> by Raymond Camden
		posted on 5/26/2012 at 12:16 AM
		</div>
		<div class="comment_text"><p>Wow, that's an incredible compliment. Thank you.</p></div>
	</div>
</div>
		