
<div class="comment" id="c_1713656906">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656906">1</a> by Freddys Garcia
		posted on 8/30/2006 at 7:32 PM
		</div>
		<div class="comment_text"><p>Is it being recorded Ray?  I won't be able to stop by tonight, but would love to see what I missed out on.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656910">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656910">2</a> by Raymond Camden
		posted on 8/30/2006 at 7:46 PM
		</div>
		<div class="comment_text"><p>It will be recorded. The URL for that will be available tomorrow.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656915">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656915">3</a> by Michael Brennan-White
		posted on 8/30/2006 at 10:05 PM
		</div>
		<div class="comment_text"><p>Does it require us to pre-register.</p><p>If so, I didn't see a link.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656911">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656911">4</a> by Raymond Camden
		posted on 8/30/2006 at 11:18 PM
		</div>
		<div class="comment_text"><p>Everone is allowed in.</p><p>Except you.</p><p>Just teasing. :) You can come in now if you want.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656912">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656912">5</a> by Teddy R Payne
		posted on 8/31/2006 at 12:27 AM
		</div>
		<div class="comment_text"><p>Did I see an invitation to heckle? *ears perk up*</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656913">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656913">6</a> by Raymond Camden
		posted on 8/31/2006 at 12:31 AM
		</div>
		<div class="comment_text"><p>Only on even numbered minutes that are divisible by 3.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656914">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656914">7</a> by Ken Auenson
		posted on 8/31/2006 at 3:12 AM
		</div>
		<div class="comment_text"><p>Ray:<br>Check out my mad photoshop skillz...<br><a href="http://disq.us/url?url=http%3A%2F%2Fauenson.com%2Frandom%2FRay_FlavaFlav_Camden.jpg%3APeyKATtqDh-aFgY9aSNTohvt5Y4&amp;cuid=3321886" rel="nofollow noopener" title="http://auenson.com/random/Ray_FlavaFlav_Camden.jpg">http://auenson.com/random/R...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656917">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656917">8</a> by Sam
		posted on 8/31/2006 at 5:58 PM
		</div>
		<div class="comment_text"><p>And the URL to the recorded version is ... tada! ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656918">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656918">9</a> by Raymond Camden
		posted on 8/31/2006 at 6:04 PM
		</div>
		<div class="comment_text"><p>Coming very soon...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656916">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656916">10</a> by Josen Ruiseco
		posted on 9/1/2006 at 7:32 PM
		</div>
		<div class="comment_text"><p>Just posting to get notified of when the recording is made available...</p><p>Josen</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713656919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713656919">11</a> by Raymond Camden
		posted on 9/1/2006 at 7:54 PM
		</div>
		<div class="comment_text"><p>Done, see newest blog entry. Sorry for the delay!</p></div>
	</div>
</div>
		