
<div class="comment" id="c_1713665177">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665177">1</a> by Lola LB
		posted on 5/15/2007 at 5:16 AM
		</div>
		<div class="comment_text"><p>Is there a way to subscribe without having to have a Google account?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665186">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665186">2</a> by Raymond Camden
		posted on 5/15/2007 at 5:18 PM
		</div>
		<div class="comment_text"><p>Not sure actually. Try it and let us know. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665165">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665165">3</a> by Lola LB
		posted on 5/15/2007 at 5:38 PM
		</div>
		<div class="comment_text"><p>Here's the answer - send a "subscribe" email to model-glue-subscribe@googlegroups.com.  You will then be sent an email with a link to confirm your subscription.</p></div>
	</div>
</div>
		