
<div class="comment" id="c_1713660960">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660960">1</a> by todd sharp
		posted on 1/3/2007 at 12:17 AM
		</div>
		<div class="comment_text"><p>I may have to go to California for work that week, but if I don't have to go count me in (if i do go the agenda is 7a-7p everyday so I won't be able to make it).</p><p>PS - where did you go to make the logo?  I was just trying to find that site yesterday.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660953">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660953">2</a> by todd sharp
		posted on 1/3/2007 at 12:20 AM
		</div>
		<div class="comment_text"><p>I'm an idiot - nevermind - it says it right in the logo. :(</p><p>And to think that i searched your site for that logo specifically yesterday and didn't notice it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660962">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660962">3</a> by Blaine
		posted on 1/3/2007 at 4:08 AM
		</div>
		<div class="comment_text"><p>I'm in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660958">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660958">4</a> by Michael De Jonghe
		posted on 1/3/2007 at 5:09 AM
		</div>
		<div class="comment_text"><p>Count me in too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660959">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660959">5</a> by Robert Owen
		posted on 1/3/2007 at 6:35 PM
		</div>
		<div class="comment_text"><p>See you there</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660961">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660961">6</a> by Phillip Senn
		posted on 1/4/2007 at 3:10 AM
		</div>
		<div class="comment_text"><p>Number one groupie :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660964">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660964">7</a> by Mark Holm
		posted on 1/4/2007 at 10:45 PM
		</div>
		<div class="comment_text"><p>I'm in too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660966">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660966">8</a> by Dan O&amp;aposKeefe
		posted on 1/5/2007 at 6:16 AM
		</div>
		<div class="comment_text"><p>I'll be there</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660967">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660967">9</a> by Ed Lamp
		posted on 1/8/2007 at 3:56 AM
		</div>
		<div class="comment_text"><p>Count me in</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660968">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660968">10</a> by Scott P
		posted on 1/8/2007 at 6:54 AM
		</div>
		<div class="comment_text"><p>I'll be there.</p></div>
	</div>
</div>
		