
<div class="comment" id="c_1713746093">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713746093">1</a> by Mikel
		posted on 4/19/2013 at 6:04 PM
		</div>
		<div class="comment_text"><p>Ha!  I was just having this discussion with a co-worker and was trying to find a list of some of the more tasty highlights and in rolls your email!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713746097">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713746097">2</a> by Raymond Camden
		posted on 4/19/2013 at 6:07 PM
		</div>
		<div class="comment_text"><p>Your coworker called me last night. We planned this. THE WORLD REVOLVES AROUND YOU!!!!!!!!!!!!!!!!!</p><p>;)</p><p>(Sorry - long week!)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713746098">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713746098">3</a> by Edward Rynearson
		posted on 4/19/2013 at 7:46 PM
		</div>
		<div class="comment_text"><p>The other day a co-worker asked me what software I was using and I told them "Coldfusion Builder" and he said to me, "do people still use Coldfusion?" &gt; I smiled and nodded &gt; I am not hot shot developer which is one of the reasons I have stuck with Coldfusion so long &gt; It makes me look good &gt; I really appreciate the the work you are doing Ray and hope to meet you someday</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713746100">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713746100">4</a> by Raymond Camden
		posted on 4/19/2013 at 7:47 PM
		</div>
		<div class="comment_text"><p>I'll be at cfObjective in a few weeks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713746099">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713746099">5</a> by Mikel
		posted on 4/19/2013 at 9:19 PM
		</div>
		<div class="comment_text"><p>Thanks Ray it is about time that someone noticed (or your +1 spell resistance check failed)....now if only the rest of the world would fall under my evil spell.</p></div>
	</div>
</div>
		