
<div class="comment" id="c_3320838203">
	<div>
		<img src="https://disqus.com/api/users/avatars/phillipsenn.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3320838203">1</a> by Phillip Senn
		posted on 5/23/2017 at 4:40 PM
		</div>
		<div class="comment_text"><p>I think you could do something with Dünyayı Kurtaran Adam.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3320993088">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3320993088">2</a> (In reply to <a href="#c_3320838203">#1</a>) by Raymond Camden
		posted on 5/23/2017 at 5:59 PM
		</div>
		<div class="comment_text"><p>Sorry what?</p></div>
	</div>
</div>
		
<div class="comment" id="c_3328448328">
	<div>
		<img src="https://disqus.com/api/users/avatars/loige.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3328448328">3</a> by Luciano Mammino
		posted on 5/28/2017 at 9:21 AM
		</div>
		<div class="comment_text"><p>Haha this is very funny! Well done Raymond also for creating a tutorial out of it!</p></div>
	</div>
</div>
		