
<div class="comment" id="c_1713620156">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620156">1</a> by M@ Bourke
		posted on 8/20/2005 at 10:23 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>key to google ad success is to not have them in a place that they are anooying to the user.<br>I personally find if they appear in the middle of the sites main content I simply right click them and hit "block Iframe" and it removes the ads for good.</p><p>As a friendly tip I believe your ads would be better on the right hand column and not in the middle of the page.</p><p>thoughts ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620159">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620159">2</a> by Raymond Camden
		posted on 8/20/2005 at 6:31 PM
		</div>
		<div class="comment_text"><p>Heh, I actually do have ads in the right col, they are just on the home page only. I think main ad is in a good place, after the "primary" content, and before the comments.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620161">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620161">3</a> by Emmet
		posted on 8/20/2005 at 11:21 PM
		</div>
		<div class="comment_text"><p>I aggree with Ray.  I make a substantial ammount off of Adsense on a travel site I operate.  After trying every position imaginable they are now at the top of the page below the graphic header.  I make twice what I made in other positions and my traffic is no less than what it was before.</p><p>Adsense content is the least obtrusive of all ads.  I dont feel guilty in the slightest about any possible annoyance they may cause.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713620162">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620162">4</a> by M@ Bourke
		posted on 8/21/2005 at 6:24 AM
		</div>
		<div class="comment_text"><p>HI ray, sorry never scrolled down far enough to see the ads on right,</p><p>sure ads in centre anooying position may work but in the long run when everyoneh as ad blockers installed in there browser I think it may back fire, but then again personal websites are all about personal choices so I guess where you place your ads is up to your self.</p><p>M@</p></div>
	</div>
</div>
		