
<div class="comment" id="c_1713660485">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660485">1</a> by D K
		posted on 12/19/2006 at 10:48 AM
		</div>
		<div class="comment_text"><p>this is a great start for it. I'm just scratching the surface of Flex after how many years. This is just what I need to dig into!</p><p>p.s. Ray are you ever gonna make up that CF u.g. security presentation that was cancelled, or did I miss it!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660478">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660478">2</a> by Raymond Camden
		posted on 12/19/2006 at 5:28 PM
		</div>
		<div class="comment_text"><p>The CFJUG starts up next year. In January.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660494">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660494">3</a> by Lola LB
		posted on 12/19/2006 at 6:34 PM
		</div>
		<div class="comment_text"><p>Maybe they'll do the same thing for ColdFusion?  Hope springs eternal . . . :-(</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660488">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660488">4</a> by D K
		posted on 12/19/2006 at 6:52 PM
		</div>
		<div class="comment_text"><p>@Lola - the <a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusioncookbook.com%2F%3AlL2VL-ho2ukJ85ThcaG2_qYNkKQ&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusioncookbook.com/">http://www.coldfusioncookbo...</a> already has over 100 entries and is a great resource. I'm not sure how much use its getting at the moment, I don't recall many entries being added lately =\</p><p>@Ray - glad to hear it. I really enjoyed the previous one I watched and was anxious to see the security one :P</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660501">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660501">5</a> by Raymond Camden
		posted on 12/19/2006 at 7:07 PM
		</div>
		<div class="comment_text"><p>DK - we typically add an entry or so a week. It is slow - but it grows. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660497">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660497">6</a> by Lola LB
		posted on 12/20/2006 at 7:06 PM
		</div>
		<div class="comment_text"><p>I'm talking about printed books.  I don't always want to take my laptop into certain rooms, if you know what I mean.  ;-) (Matter of fact, you're asking for disaster if you're using your laptop in a small room with lots of water!)  I'm hoping that O'Reilly will at least update their CF titles when Scorpio comes out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660496">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660496">7</a> by Raymond Camden
		posted on 12/20/2006 at 7:09 PM
		</div>
		<div class="comment_text"><p>Oh, you can always use the PDF from ColdFusion Cookbook.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660499">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660499">8</a> by Jason Calleiro
		posted on 12/29/2006 at 4:09 AM
		</div>
		<div class="comment_text"><p>Just wanted to let you guys know we are developing a social network that the whole user admin side is being developed in flex.</p></div>
	</div>
</div>
		