
<div class="comment" id="c_1713715886">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715886">1</a> by Ahmad
		posted on 6/2/2009 at 5:18 PM
		</div>
		<div class="comment_text"><p>Funny you mention the OO stuff considering Marc Funaro's post recently which I believe you've seen..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715880">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715880">2</a> by Raymond Camden
		posted on 6/2/2009 at 5:23 PM
		</div>
		<div class="comment_text"><p>Yes, I've definitely seen it. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715888">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715888">3</a> by William Bowen
		posted on 6/2/2009 at 8:02 PM
		</div>
		<div class="comment_text"><p>The main pain of being a CF developer has nothing to do with the coding itself but constantly defending it against the verbal assault of colleagues and managers.</p><p>In fact, the shop here is moving completely to .NET because the decision makers claim "ColdFusion is dead and does not integrate with Sharepoint." I showed them direct evidence to the contrary, but fighting perception is hard and this attitude is constantly reinforced by other non-CF professionals and various magazines/reports. Non-technical people will always think they know what's best based on reading a handful of journals.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715882">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715882">4</a> by Raymond Camden
		posted on 6/2/2009 at 8:04 PM
		</div>
		<div class="comment_text"><p>William, this is an excellent point, but really belongs on their blog though so they can take your feedback. I'm just the messenger here. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715884">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715884">5</a> by William Bowen
		posted on 6/2/2009 at 8:06 PM
		</div>
		<div class="comment_text"><p>Yeah, I realized immediately after I posted. Just a gut reaction based on some recent developments, thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715881">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715881">6</a> by Jeff Gladnick
		posted on 6/3/2009 at 12:34 AM
		</div>
		<div class="comment_text"><p>Honestly, I think one of the most effective things you can teach new developers is how to incorporate some really basic search engine optimization.  I've gotten really into this in the past 6 months, and about 80% of it can be explained in 30 minutes or less.  No matter how great your site is, if no one uses it, who cares if its OO or not.  On one of the applications I tend, just making some basic changes in Model-glue to the event names and adding some automatic metadata population boosted traffic by like 25-30% (traffic was relatively low).  This isn't hard to do, and more CF developers should at least know the SEO basics</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715890">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715890">7</a> by Raymond Camden
		posted on 6/3/2009 at 12:38 AM
		</div>
		<div class="comment_text"><p>&lt;cf_gentlenudge&gt; Jeff, interesting idea here - but can you please post to the blog entry for cfhour?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715885">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715885">8</a> by Chris Mallinson
		posted on 6/3/2009 at 1:23 AM
		</div>
		<div class="comment_text"><p>Ray, I can't believe you just leaked the &lt;cf_gentlenudge&gt; tag.  CF9 is still under NDA.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713715865">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713715865">9</a> by Raymond Camden
		posted on 6/3/2009 at 1:25 AM
		</div>
		<div class="comment_text"><p>Well, yesterday I leaked the <a href="http://disq.us/url?url=http%3A%2F%2Fmakebeerwithcf.riaforge.org%3ASohpnyw4PSbdG4XE5r25Bf7Zvfg&amp;cuid=3321886" rel="nofollow noopener" title="makebeerwithcf.riaforge.org">makebeerwithcf.riaforge.org</a> project, so just call me the Instagator.</p></div>
	</div>
</div>
		