
<div class="comment" id="c_2453922269">
	<div>
		<img src="https://disqus.com/api/users/avatars/simonreimler.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2453922269">1</a> by Simon Grimm
		posted on 1/12/2016 at 6:59 PM
		</div>
		<div class="comment_text"><p>Awesome tutorial. Reminds me that I wanted to create a blogpost on the creator as well, seems to be quite useful by now. And the completely random use of Star Wars API makes this tutorial really great :D</p><p>One very very little thing... afaik controller names in Angular should be starting with a capital letter!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2453925909">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2453925909">2</a> (In reply to <a href="#c_2453922269">#1</a>) by Raymond Camden
		posted on 1/12/2016 at 7:01 PM
		</div>
		<div class="comment_text"><p>Good point. I'm just getting 'comfortable' with Angular, not quite at the 'following best practices' part. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_2455990109">
	<div>
		<img src="https://disqus.com/api/users/avatars/jpfaraco.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2455990109">3</a> by João Faraco
		posted on 1/13/2016 at 9:04 PM
		</div>
		<div class="comment_text"><p>Love this! I'm getting started with Angular and this tut was great to see a simple practical application using a live API.</p><p>One little thing I noticed was the key for the opening crawl -- correct is "opening_crawl", instead of "crawl" ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_2456001149">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2456001149">4</a> (In reply to <a href="#c_2455990109">#3</a>) by Raymond Camden
		posted on 1/13/2016 at 9:11 PM
		</div>
		<div class="comment_text"><p>Thanks - should be right in the repo (should be anyway).</p></div>
	</div>
</div>
		
<div class="comment" id="c_2456655571">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_IttULKzJnU.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2456655571">5</a> (In reply to <a href="#c_2456001149">#4</a>) by mayoralito
		posted on 1/14/2016 at 6:18 AM
		</div>
		<div class="comment_text"><p>Hi, nice tutorial and explanation. Thanks for sharing your experience. </p></div>
	</div>
</div>
		
<div class="comment" id="c_2480384886">
	<div>
		<img src="https://disqus.com/api/users/avatars/mathiasbanda.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2480384886">6</a> by Mathias Banda
		posted on 1/27/2016 at 9:02 AM
		</div>
		<div class="comment_text"><p>Hey Raymond, I played with the stars wars app and it works great on windows devices. The android version just doesn't seem to retrieve data from the swapi server though works with hard-coded data. Any clues anyone? I have made sure the internet permissions are all enabled</p></div>
	</div>
</div>
		
<div class="comment" id="c_2480951219">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2480951219">7</a> (In reply to <a href="#c_2480384886">#6</a>) by Raymond Camden
		posted on 1/27/2016 at 3:53 PM
		</div>
		<div class="comment_text"><p>Check the console (Chrome Remote Debug) - do you see an error?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2673556619">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_Uy7oePNoo6.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2673556619">8</a> by ABA
		posted on 5/13/2016 at 12:38 PM
		</div>
		<div class="comment_text"><p>Thanks for the tutorial.<br>I’d like to know how I can do to upgrade my app easily.</p><p>I have built an app V1with Ionic Creator with a single page, and exported it in ZIP file. Then I have added the javascript code for the controllers, and done some modifications in<br>HTML part. It works fine.</p><p>Now, I want to add a 2nd page, with Ionic Creator again.  But I don’t want to lose the code of my controllers, neither my HTML modifications.</p><p>What is the best way to do that?</p><p>Is it possible, for instance, to import my app in Ionic Creator, including my modifications?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2673665236">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2673665236">9</a> (In reply to <a href="#c_2673556619">#8</a>) by Raymond Camden
		posted on 5/13/2016 at 1:49 PM
		</div>
		<div class="comment_text"><p>As far as I know, this is not supported. You could use IC to design the page and then get the output for just that view, but you can't import, nor can you easily bring in an update into your existing app. You would need to do it carefully.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2724850745">
	<div>
		<img src="https://disqus.com/api/users/avatars/brandecho.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2724850745">10</a> by brandecho
		posted on 6/11/2016 at 11:58 AM
		</div>
		<div class="comment_text"><p>Great tutorial! 2 questions... <br>1. Instead of an ionic list component, can the same apply to an ionic card component with dynamic data?<br>2. Instead of the link going to a details page with a paragraph component, can the dynamic data be displayed using the cells component?</p><p>Also, would be great if there was a tutorial on doing the same and using a WordPress JSON API endpoint?</p><p>Thanks again for an awesome tutorial.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2724876321">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2724876321">11</a> (In reply to <a href="#c_2724850745">#10</a>) by Raymond Camden
		posted on 6/11/2016 at 12:27 PM
		</div>
		<div class="comment_text"><p>1) Anything is possible really. I know it sounds kinda lame to say that, but really - you can use any UI item that makes sense for your app.</p><p>2) I don't know what the cells component is - but it's the same thing really.</p><p>3) As for the WP API, again, possible. It's just another API. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_3190385540">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_GDGO3DD4MT.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3190385540">12</a> by Web Expert
		posted on 3/7/2017 at 7:05 AM
		</div>
		<div class="comment_text"><p>Great guide<br>I have question<br>how could edit route.js and app.js and index.html on ionic creator?</p></div>
	</div>
</div>
		
<div class="comment" id="c_3190606750">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3190606750">13</a> (In reply to <a href="#c_3190385540">#12</a>) by Raymond Camden
		posted on 3/7/2017 at 12:18 PM
		</div>
		<div class="comment_text"><p>I haven't worked on Creator since their most recent updates which allow a much greater level of editing, even the JS files. I believe this may be supported - best thing to do is try it.</p></div>
	</div>
</div>
		