
<div class="comment" id="c_2388785057">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_9O9QkwKCu0.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2388785057">1</a> by Justin Cook
		posted on 12/2/2015 at 2:45 PM
		</div>
		<div class="comment_text"><p>Raymond, Do you think that Adobe is moving more towards design and multimedia and away from application development tools?  Maybe I'm wrong, but it sure seems like the priority is shifting that way.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2388793233">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2388793233">2</a> (In reply to <a href="#c_2388785057">#1</a>) by Raymond Camden
		posted on 12/2/2015 at 2:50 PM
		</div>
		<div class="comment_text"><p>Well, they have always had a huge investment in design. The Edge stuff was great imo because it appealed to *both* design and dev.</p></div>
	</div>
</div>
		