
<div class="comment" id="c_1713734110">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734110">1</a> by Brian Swartzfager
		posted on 7/11/2011 at 12:39 AM
		</div>
		<div class="comment_text"><p>Your review of "The City &amp; The City" introduced me to China Miéville, and I agree that he's a really unique writer and his books can be challenging reads.  I was thinking about picking up "Embassytown":  might do that later this summer after getting through "A Dance with Dragons"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734111">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734111">2</a> by Pete
		posted on 10/9/2012 at 4:11 PM
		</div>
		<div class="comment_text"><p>I bought both these books a year ago based on this post. Only just got round to reading Robopocalypse, and I can't put it down, it's brilliant. I wish I'd read it sooner.</p><p>The way it's written reminds me of "A record of the year of infection", the way it's pieced together.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713734115">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713734115">3</a> by Raymond Camden
		posted on 10/9/2012 at 5:44 PM
		</div>
		<div class="comment_text"><p>They are making a movie out of it and I hope they do it justice.</p></div>
	</div>
</div>
		