
<div class="comment" id="c_1713676250">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676250">1</a> by James Allen
		posted on 1/15/2008 at 4:19 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>In your version do you have missing diagrams on pages: 10 and 14? I noticed a few spelling mistakes as well so wasn't sure if an early version got published by mistake.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676266">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676266">2</a> by Raymond Camden
		posted on 1/15/2008 at 4:21 AM
		</div>
		<div class="comment_text"><p>I see it as well. I don't think it's an early version - just a simple mistake. It happens. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676256">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676256">3</a> by James Allen
		posted on 1/15/2008 at 4:42 AM
		</div>
		<div class="comment_text"><p>Very true..</p><p>You can just imagine it though can't you.. The time taken for it all to be proof read, prepared, checked over and over until the final version as ready to go to press..<br>Then someone forgets to insert those two diagrams they 'would get to'.. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676259">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676259">4</a> by Brian Swartzfager
		posted on 1/15/2008 at 5:17 AM
		</div>
		<div class="comment_text"><p>The composition of the photo looks fine.  I think all you need is a brighter flash...as the old Macromedia folks used to say, "you can never have too much Flash".  :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676254">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676254">5</a> by Lance
		posted on 1/15/2008 at 5:32 AM
		</div>
		<div class="comment_text"><p>I got mine today, too!  What a coincidence!  Congrats, Ray!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676253">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676253">6</a> by Todd Rafferty
		posted on 1/15/2008 at 6:36 AM
		</div>
		<div class="comment_text"><p>Somehow I got book 3 before you did. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676255">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676255">7</a> by Raymond Camden
		posted on 1/15/2008 at 6:56 AM
		</div>
		<div class="comment_text"><p>@Brian - Heh, I got my wife a SLR. I need to start using that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676258">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676258">8</a> by Brian Swartzfager
		posted on 1/15/2008 at 5:29 PM
		</div>
		<div class="comment_text"><p>My wife's been the CHP (Chief House Photographer) since she got her digital SLR back in 2006.  She got a large flash add-on for it for Christmas and it's really an improvement over the built-in flash:  definitely a recommended add-on if you're taking a lot of indoor pictures.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676252">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676252">9</a> by Lola LB
		posted on 1/15/2008 at 6:32 PM
		</div>
		<div class="comment_text"><p>Congratulations!  And I'm seeing volume 1 and 2 at local bookstores as well.  Now . . . how about "Head Start ColdFusion"?  ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676257">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676257">10</a> by Lola LB
		posted on 1/15/2008 at 6:33 PM
		</div>
		<div class="comment_text"><p>That should be "Head First ColdFusion" . . .</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676262">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676262">11</a> by Raymond Camden
		posted on 1/15/2008 at 7:15 PM
		</div>
		<div class="comment_text"><p>@Brian -I got my wife a nice Canon, with no add ons yet. I figured we would start simple. I need to start reading the manual as I REALLY want to get better at photography.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676260">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676260">12</a> by Michael White
		posted on 1/15/2008 at 8:27 PM
		</div>
		<div class="comment_text"><p>On-camera flash sucks hard so I avoid it like the plague. I have a Nikon D200 and just got a new flash with bracket, wireless remote, etc. and let me tell you, "real" Flash photography is a whole new world. Oh, yeah, I ordered volume 3 from Amazon a few days ago... but I haven't finished volume two yet anyway</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676261">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676261">13</a> by JackWill01
		posted on 12/15/2010 at 3:16 PM
		</div>
		<div class="comment_text"><p>pic looks good I got my copy today have to start reading today any suggestions before I start ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676263">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676263">14</a> by Raymond Camden
		posted on 12/15/2010 at 5:50 PM
		</div>
		<div class="comment_text"><p>Nothing outside of ensuring you already have COldFusion installed. :)</p></div>
	</div>
</div>
		