
<div class="comment" id="c_1713737975">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737975">1</a> by Phillip Senn
		posted on 1/7/2012 at 10:24 PM
		</div>
		<div class="comment_text"><p>There's just so much to JavaScript - like all these date functions.  Another thing is that it's weird how db.transaction has an error callback followed by a success callback, while executeSql has a success followed by error.<br>So many examples on the net use anonymous functions, you've made it more clear by using named functions.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737976">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737976">2</a> by Raymond Camden
		posted on 1/7/2012 at 10:37 PM
		</div>
		<div class="comment_text"><p>re: date functions<br>Well, it doesn't seem like a lot of code to me, but obviously, that's just my opinion</p><p>re:event handler order<br>I agree completely. Not quite sure why PhoneGap made that decision. I'm guessing just a mistake.</p><p>re:named handlers<br>I go back and forth. I'm still figuring out the best way to write db-intensive PG apps.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737977">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737977">3</a> by Phillip Senn
		posted on 1/8/2012 at 1:05 AM
		</div>
		<div class="comment_text"><p>I've tried using jQuery.Deferred() with resolve and reject here:<br><a href="http://disq.us/url?url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F8748990%2Fjquery-deferred-no-promises%3ADWgjvinJGZC7ggvrbe8N7J8VpTA&amp;cuid=3321886" rel="nofollow noopener" title="http://stackoverflow.com/questions/8748990/jquery-deferred-no-promises">http://stackoverflow.com/qu...</a></p><p>Someone mentioned the Step framework, which looks promising<br><a href="http://disq.us/url?url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F8583774%2Fis-there-a-way-to-sequentially-execute-statements-in-javascript%3ANnywHI_GapOJ9JKAvrJWfS1Kn5A&amp;cuid=3321886" rel="nofollow noopener" title="http://stackoverflow.com/questions/8583774/is-there-a-way-to-sequentially-execute-statements-in-javascript">http://stackoverflow.com/qu...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737980">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737980">4</a> by Raj
		posted on 6/7/2014 at 10:44 PM
		</div>
		<div class="comment_text"><p>Hi</p><p>I have a small problem with WebSql /IndexedDB.</p><p>In My database, i have latitude and longitude.</p><p>I want to display all the stations near by with in 10 miles .</p><p>I am using WebSql.</p><p>Can you please provide me any solution ?</p><p>Thanks<br>R</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737979">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737979">5</a> by Raymond Camden
		posted on 6/7/2014 at 10:49 PM
		</div>
		<div class="comment_text"><p>There is a standard way of doing this with SQL - just Google. Whether it will work in SQLite is another story of course. You would need to test.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737981">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737981">6</a> by Raj
		posted on 6/7/2014 at 10:52 PM
		</div>
		<div class="comment_text"><p>Hi Friend,</p><p>It is not working, i don't think trigonometric functions are available for sq-lite.</p><p>Do you have any suggestion for me?</p><p>i have search in google but unable to find the solution.</p><p>Thanks<br>R</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737982">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737982">7</a> by Raymond Camden
		posted on 6/7/2014 at 10:56 PM
		</div>
		<div class="comment_text"><p>What about the suggestion here: <a href="http://disq.us/url?url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F2628876%2Ftrigonometric-functions-in-sqlite-in-iphone-sdk%3ANNPtsO57lFCBWWtEGeyR9q0BjSA&amp;cuid=3321886" rel="nofollow noopener" title="http://stackoverflow.com/questions/2628876/trigonometric-functions-in-sqlite-in-iphone-sdk">http://stackoverflow.com/qu...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737978">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737978">8</a> by Raj
		posted on 6/7/2014 at 11:08 PM
		</div>
		<div class="comment_text"><p>I Am using WebSql,</p><p>I am developing an mobile aplication using Jquery mobile.</p><p>Wil this work with this?</p><p>Sorry for asking such questions, I am new to this area</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737983">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737983">9</a> by Raymond Camden
		posted on 6/8/2014 at 12:15 AM
		</div>
		<div class="comment_text"><p>Are you asking about what I linked to? I don't know - it was a suggestion. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737992">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737992">10</a> by dina salah
		posted on 7/7/2014 at 7:21 PM
		</div>
		<div class="comment_text"><p>Hello,<br>I got log error <br>(23) Not authorized</p><p>In which cases I got this error?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737994">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737994">11</a> by Raymond Camden
		posted on 7/7/2014 at 7:28 PM
		</div>
		<div class="comment_text"><p>@dina: Show me where I can run this online to test and I'll try to help.</p></div>
	</div>
</div>
		