
<div class="comment" id="c_1713670343">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713670343">1</a> by John
		posted on 8/4/2011 at 3:01 AM
		</div>
		<div class="comment_text"><p>This link doesn't work.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713670335">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713670335">2</a> by Raymond Camden
		posted on 8/4/2011 at 4:40 AM
		</div>
		<div class="comment_text"><p>Um, ok. This blog entry is nearly 4 years old. Things change. ;) His new blog is at <a href="http://disq.us/url?url=http%3A%2F%2Fsamfarmer.com%2Fblog%3AJ19R1nkbNIGbQuSw9HrVwvX8SPg&amp;cuid=3321886" rel="nofollow noopener" title="samfarmer.com/blog">samfarmer.com/blog</a>, you can search for it there.</p></div>
	</div>
</div>
		