
<div class="comment" id="c_1714083331">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083331">1</a> by Robert Zehnder
		posted on 7/8/2014 at 5:00 PM
		</div>
		<div class="comment_text"><p>Looks awesome, Ray.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083336">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083336">2</a> by Salvatore fusto
		posted on 7/8/2014 at 6:53 PM
		</div>
		<div class="comment_text"><p>+1</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083340">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083340">3</a> by Raymond Camden
		posted on 7/11/2014 at 1:58 AM
		</div>
		<div class="comment_text"><p>Support for adding plugins and removing contacts is in. Roughly 60% of the work for it is there. You can't search yet, so you need to know the exact ID. For removing, it works, but doesn't handle the case where you try to remove X and Y needed it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083337">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083337">4</a> by Adrian Perez
		posted on 7/21/2014 at 12:33 PM
		</div>
		<div class="comment_text"><p>That's an interesting idea, I'll take a look at it. It will probably come in handy and I could contribute to it :)</p></div>
	</div>
</div>
		