
<div class="comment" id="c_1713676785">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676785">1</a> by Javier Julio
		posted on 2/6/2008 at 2:46 AM
		</div>
		<div class="comment_text"><p>I'm amazed this does not have a comment! Shame on us New Yorkers for not picking it up. I'm glad you are coming out next week! We are looking forward to having you present. Ben and Clark have done an amazing job running the user group so I'm sure it'll go real well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676773">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676773">2</a> by Raymond Camden
		posted on 2/6/2008 at 3:26 AM
		</div>
		<div class="comment_text"><p>Heh, nice to know _someone_ in NYC cares. ;) I just wish I was staying longer.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676786">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676786">3</a> by Javier Julio
		posted on 2/6/2008 at 5:07 AM
		</div>
		<div class="comment_text"><p>It's sad I'm the only one. :) I'll be seeing Ben and Clark tonight so I'll make sure to let them know. Trust me they are very excited to have you present next week. We had an awesome turn out last week. Definitely had to be around 25+. So expect a great audience!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676787">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676787">4</a> by Peter Bell
		posted on 2/7/2008 at 8:57 PM
		</div>
		<div class="comment_text"><p>Well, I'll certainly be coming along. Although if you're using Kurt as a role model, I may sit in the back, be very quiet when you speak and bring a kevlar vest along :-&gt;</p><p>Ping me offline if you're interested in grabbing a bite to eat before the preso. We could get some people together if you were free . . .</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676790">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676790">5</a> by Raymond Camden
		posted on 2/7/2008 at 9:49 PM
		</div>
		<div class="comment_text"><p>I'll be working with Clark before hand, but I believe we are all going out after the meeting.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676788">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676788">6</a> by Peter Bell
		posted on 2/7/2008 at 9:56 PM
		</div>
		<div class="comment_text"><p>Cool! C u then. Safe flight!</p></div>
	</div>
</div>
		