
<div class="comment" id="c_1713672638">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672638">1</a> by John Paul Ashenfelter
		posted on 10/1/2007 at 6:52 PM
		</div>
		<div class="comment_text"><p>If you're going to the trouble of using Lucene, you probably want to look at *Solr* -- which is a RESTful wrapper around Lucene that makes it dead simple to use. It speaks HTML, JSON, etc and removes a lot of the hassle of managing Lucene.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672641">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672641">2</a> by Joseph Lamoree
		posted on 10/23/2007 at 2:24 PM
		</div>
		<div class="comment_text"><p>Hi Ray.</p><p>I wrote the code on CFLucene a *long* time ago. There are lots of areas that need improvement, but I haven't been active on it. I would be interested to see what you do with Lucene and ColdFusion.</p><p>-joseph</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672643">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672643">3</a> by Raymond Camden
		posted on 10/23/2007 at 6:17 PM
		</div>
		<div class="comment_text"><p>I've got some sample code ready - just not posted yet.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672642">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672642">4</a> by Raymond Camden
		posted on 10/25/2007 at 10:16 PM
		</div>
		<div class="comment_text"><p>Guys, please see:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Findex.cfm%2F2007%2F10%2F24%2FLucene-Update%3AbZ0OCElCnH-2wHME58kfYGOdwfY&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/index.cfm/2007/10/24/Lucene-Update">http://www.coldfusionjedi.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672640">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672640">5</a> by barry.b
		posted on 11/30/2007 at 8:42 AM
		</div>
		<div class="comment_text"><p>looks like the CFLucene project site has an expired domain.</p><p>I was just after seeing how people have wrapped CF around Lucerne.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672644">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672644">6</a> by Raymond Camden
		posted on 11/30/2007 at 7:25 PM
		</div>
		<div class="comment_text"><p>Barry, have you looked at my Seeker project?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672647">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672647">7</a> by Jeff
		posted on 12/2/2007 at 2:11 AM
		</div>
		<div class="comment_text"><p>Ray, is there a way to get the indexed data for a single file back.  So lets say i run cf_index on test.txt.  Is there a way to grab what lucene indexed for test.txt back as a variable so CF can play with it?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713672639">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713672639">8</a> by Raymond Camden
		posted on 12/3/2007 at 9:17 PM
		</div>
		<div class="comment_text"><p>I do not think so. If the Lucene API supports this, it is something I could add to my code. Note that I only learned a tiny bit about Lucene.</p></div>
	</div>
</div>
		