
<div class="comment" id="c_3191347757">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3191347757">1</a> by Robert Zehnder
		posted on 3/7/2017 at 8:12 PM
		</div>
		<div class="comment_text"><p>Congrats Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_3191971817">
	<div>
		<img src="https://disqus.com/api/users/avatars/dotnetkow.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3191971817">2</a> by Matt Netkow, Ionic Team
		posted on 3/8/2017 at 2:31 AM
		</div>
		<div class="comment_text"><p>congrats!  bought! You've got great content here so happy to pay it forward. Also, I looked into Netlify because of you.. and it's great! I'll be moving my blog over to a static site soon, so the book's timing is perfect. I'm thinking Hugo + Netlify.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3191974406">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3191974406">3</a> (In reply to <a href="#c_3191971817">#2</a>) by Raymond Camden
		posted on 3/8/2017 at 2:33 AM
		</div>
		<div class="comment_text"><p>Thanks Matt - be sure to let me know what you think when done, bad and good. I know both Brian and I want to keep the book updated.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3191974504">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3191974504">4</a> (In reply to <a href="#c_3191347757">#1</a>) by Raymond Camden
		posted on 3/8/2017 at 2:33 AM
		</div>
		<div class="comment_text"><p>Thanks. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_3195251062">
	<div>
		<img src="https://disqus.com/api/users/avatars/dotnetkow.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3195251062">5</a> (In reply to <a href="#c_3191974406">#3</a>) by Matt Netkow, Ionic Team
		posted on 3/9/2017 at 9:29 PM
		</div>
		<div class="comment_text"><p>so far, so good! I'm migrating from Tumblr (ha!) to Hugo... spent way too much time trying to find Tumblr export options, only to have the book point me to Hugo's migration tools. Brilliant!</p></div>
	</div>
</div>
		