
<div class="comment" id="c_1713722276">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722276">1</a> by Andrew Scott
		posted on 3/2/2010 at 9:04 AM
		</div>
		<div class="comment_text"><p>It should be noted that this is one approach, however the best approach would be to use the line debugger and look at the url variable in all its glory there.</p><p>There is also a hidden gem, that while line debugging you can switch over to the Debug Output Buffer. Select the Server output Buffer and watch the request build up as well.</p><p>So in some cases, if you do a dump here you don't need to write it to a file. You can view it in the IDE as well.</p><p>I think the line debugger doesn't get enough attention, it beats the cfdumps hands down for me.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722277">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722277">2</a> by Raymond Camden
		posted on 3/2/2010 at 9:30 AM
		</div>
		<div class="comment_text"><p>I know I'm in the minority - but I don't like using the debugger. It just doesn't seem to work well for me. On the flip side, I like the debugger in Flex. Meh. To each their own.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713722278">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713722278">3</a> by Sean Henderson
		posted on 3/3/2010 at 12:13 AM
		</div>
		<div class="comment_text"><p>Thanks.  Just loaded up CF9/CFB on my machine today and this tip was useful.</p></div>
	</div>
</div>
		