
<div class="comment" id="c_1713740581">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740581">1</a> by Raymond Camden
		posted on 4/20/2012 at 2:01 AM
		</div>
		<div class="comment_text"><p>By the way - here is a good presentation on JavaScript templating engines. Lots of options:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.slideshare.net%2Fgarann%2Fusing-templates-to-achieve-awesomer-architecture%3A-e8Faa8U7rsPRmv2_nbmsTNyspE&amp;cuid=3321886" rel="nofollow noopener" title="http://www.slideshare.net/garann/using-templates-to-achieve-awesomer-architecture">http://www.slideshare.net/g...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740583">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740583">2</a> by Adrian J. Moreno
		posted on 4/20/2012 at 4:15 AM
		</div>
		<div class="comment_text"><p>We just started talking about Handlebars, plus you answered the question, "where can I find a comic book database?" for me.</p><p>2-for-1!</p><p>Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740582">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740582">3</a> by Raymond Camden
		posted on 4/20/2012 at 5:24 AM
		</div>
		<div class="comment_text"><p>I wrote this post just for you. Honest. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740585">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740585">4</a> by existdissolve
		posted on 4/20/2012 at 7:14 AM
		</div>
		<div class="comment_text"><p>This is really cool, and it's nice to see a pretty intuitive convention for templating. I also like the JSON/P integration :)</p><p>Just curious, but have you played around with the templating in ExtJS ever?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740584">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740584">5</a> by William Ukoh
		posted on 4/20/2012 at 12:32 PM
		</div>
		<div class="comment_text"><p>Thanks for the post</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740586">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740586">6</a> by Roberto
		posted on 4/20/2012 at 12:36 PM
		</div>
		<div class="comment_text"><p>Spry was too cool to survive? :-)<br>thanks ray :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740587">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740587">7</a> by Raymond Camden
		posted on 4/20/2012 at 3:30 PM
		</div>
		<div class="comment_text"><p>@Exitdissolve: No - I'm not much of a fan of Ext. It is -very- powerful, but I don't like _how_ it works if that makes sense.</p><p>@Roberto: Heh, well, it was a great effort. If you ever look at Angular, it is similar (although Angular has gone far further).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740588">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740588">8</a> by Manithan
		posted on 4/20/2012 at 5:13 PM
		</div>
		<div class="comment_text"><p>i have used handlebars little bit and i liked it. now i like AngularJS which comes with everything the main part i like about AngularJS templates is that it has two way binding which makes life lot easier. After played lot with other templates Angular is the one got in to me and it is all HTML</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740589">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740589">9</a> by Kevin C.
		posted on 4/20/2012 at 5:18 PM
		</div>
		<div class="comment_text"><p>Demos don't appear to be working for me.  Firebug showing different errors for each one.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740590">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740590">10</a> by Raymond Camden
		posted on 4/20/2012 at 5:25 PM
		</div>
		<div class="comment_text"><p>Kevin - I see that. Give me a sec and I'll fix it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740591">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740591">11</a> by Raymond Camden
		posted on 4/20/2012 at 5:30 PM
		</div>
		<div class="comment_text"><p>Heh, interestingly enough - given a div with id X, Chrome allows for</p><p>X.innerHTML = "...";</p><p>whereas Firefox does not. I just fixed it - and made it "more proper" by doing</p><p>document.querySelector("#X").innerHTML = "...";</p><p>Thanks for the report, Kevin.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740592">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740592">12</a> by Phillip Senn
		posted on 4/20/2012 at 6:34 PM
		</div>
		<div class="comment_text"><p>I am assuming you have decided to use vanilla JavaScript so as not to be tied to a particular library.  I chose jQuery because Internet Explorer requires attachEvent('onclick'...) instead of AddEventListener('click'...).  My feeling is that if JavaScript libraries had not been written, then everyone would have to write their own because you sure don't want to put an if/then block around every time you declare an event.</p><p>I pulled up your example in IE9 and it didn't work using (Alt+9) or (Alt+8).<br>It goes without saying that the only time I pull up Internet Explorer is just to see how my users would see it.<br>But JavaScript being so brittle is why it's frustrating - you get something that works, and then it doesn't work in another environment.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740594">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740594">13</a> by Raymond Camden
		posted on 4/20/2012 at 6:43 PM
		</div>
		<div class="comment_text"><p>I choose not to use jQuery in these demos just because I'm trying to do more things on my own. I recognize that it will not always be cross-browser compatible. Frankly - I'm ok with that for demos. I do want Chrome/Firefox to work, but everything else I'm not so concerned with.</p><p>I'm not against libraries like jQuery. I love jQuery. At the same time, I'm trying to improve my JavaScript skills so I'm trying to do more on my own without the training wheels of jQuery.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740597">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740597">14</a> by Phillip Senn
		posted on 4/20/2012 at 7:03 PM
		</div>
		<div class="comment_text"><p>Hmmm...  That's a bit of a conflict.  Are you posting the blog entry for the readers or yourself?  I know the answer is "a little of both".  That you often refer back to previous blog posts or have even posted some things for the purpose of writing it down.  But if you have to make disclaimers like "This works for all the standard browsers, but might not work once you deploy to production", then that's doing a bit of a disservice to your readership.</p><p>I want to argue again the idea that it's a crutch.  The fact is that JavaScript is broken.  CSS is broken too as far I know.  Developers are wasting too much time with polyfills and shims and hacks to get around browser inconsistencies.  Don't think of it as a crutch.  Just think of it as a couple of routine you may have written yourself that say something like "If (this feature is support) { use this feature } else { use this polyfill or shim or hack }</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740596">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740596">15</a> by Raymond Camden
		posted on 4/20/2012 at 7:18 PM
		</div>
		<div class="comment_text"><p>We will have to agree to disagree. I think a demo not working in IE is not a disservice to my readers. A demo is not a production site with hours of QA and UX testing. A demo is just that - a demo. If you view my blog entries as something that is always 'production ready', then I think you are reading way too much into what should be just simple examples. Frankly, I don't want that kind of pressure when I blog.</p><p>As for 'crutch' - I was perhaps being too strong. There are things I use jQuery for that I can do easily myself. The biggest one being $("...") for example. Ditto for the jsonp support which wasn't difficult at all. I'm not arguing against using jQuery. I'm simply saying you don't have to use it all the time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740600">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740600">16</a> by Adrian J. Moreno
		posted on 4/20/2012 at 7:29 PM
		</div>
		<div class="comment_text"><p>"But JavaScript being so brittle is why it's frustrating - you get something that works, and then it doesn't work in another environment."</p><p>Hang on, there's a typo:</p><p>"But Internet Explorer being so brittle is why it's frustrating - you get something that works, and then it doesn't work in another environment."</p><p>There you go. :P</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740598">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740598">17</a> by Brad Newman
		posted on 4/20/2012 at 9:36 PM
		</div>
		<div class="comment_text"><p>Ray,  I had no clue about templating engines.. Thanks for the post.. Or, maybe not as I will be consumed with research for the next few days. ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740599">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740599">18</a> by GMS
		posted on 4/25/2012 at 9:35 AM
		</div>
		<div class="comment_text"><p>With the irony that coldfusion is a template engine, aside.  Templating engines are best way to improve your code's readbility and maintainability.  We use another take on mustache called Goatee [<a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fowenallenaz%2FGoatee%3AB9bQaspz_lYoD2eWewDWtR3Z2WQ&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/owenallenaz/Goatee">https://github.com/owenalle...</a>].  The advantage of this system is you can reuse templates to be used from the Javascript implementation or in Coldfusion. If anyone is interested in VIMEO tutorial let me know</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740601">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740601">19</a> by Adrian J. Moreno
		posted on 4/27/2012 at 3:09 AM
		</div>
		<div class="comment_text"><p>Working this into an internal application. Ridiculously simple.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740606">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740606">20</a> by Phillip Senn
		posted on 5/1/2012 at 7:52 PM
		</div>
		<div class="comment_text"><p>Darn it!  I had this working relatively quickly but then I lost it (now it's not working).  So, if I SELECT from an html5 openDatabase, then I get a result which has result.rows.item(0), result.rows.item(1), etc.</p><p>So how do I call mustache again?<br>I've tried:</p><p>template(result);<br>template(result.rows);<br>template(result.rows.item);</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740604">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740604">21</a> by Raymond Camden
		posted on 5/1/2012 at 7:56 PM
		</div>
		<div class="comment_text"><p>html5 openDatabase? I don't know what that is. Do you mean WebSQL? If so - the Handlebars may not like the form of the data. You may want to rewrite it as a simple array of structs and pass that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740605">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740605">22</a> by Phillip Senn
		posted on 5/1/2012 at 9:25 PM
		</div>
		<div class="comment_text"><p>Here is my <a href="http://disq.us/url?url=http%3A%2F%2Fjsfiddle.net%2FPhillipSenn%2FGUGjS%2F%3AsxM6T8R_CP-8wWVHIFYXCrSZxAE&amp;cuid=3321886" rel="nofollow noopener" title="http://jsfiddle.net/PhillipSenn/GUGjS/">http://jsfiddle.net/Phillip...</a> where I drop, create, insert, select and (try to) display the result from the select.</p><p>Maybe I have to do some kind of $.makeArray or something.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740607">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740607">23</a> by Raymond Camden
		posted on 5/1/2012 at 10:23 PM
		</div>
		<div class="comment_text"><p>No idea what makeArray is - but - remember KISS. I'd just make a new array (var data = []), and loop over your SQL results and add them manually. Then pass data to handlebars.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740609">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740609">24</a> by Phillip Senn
		posted on 5/1/2012 at 11:50 PM
		</div>
		<div class="comment_text"><p>OK, yeah, that helped me getting it to work right.<br><a href="http://disq.us/url?url=http%3A%2F%2Fjsfiddle.net%2FPhillipSenn%2FGUGjS%2F2%2F%3AQ9jbRYndSBvkH4nK4BHZoEmf3Q4&amp;cuid=3321886" rel="nofollow noopener" title="http://jsfiddle.net/PhillipSenn/GUGjS/2/">http://jsfiddle.net/Phillip...</a></p><p>Although I'm not happy with having to loop over the result because I have a sneaking suspicion that it's not required, but it does work.</p><p>I really appreciate it!  <br>Thank you very much!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740714">25</a> by Raymond Camden
		posted on 5/1/2012 at 11:53 PM
		</div>
		<div class="comment_text"><p>Glad you got it!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740717">26</a> by stegoste
		posted on 5/5/2012 at 1:35 AM
		</div>
		<div class="comment_text"><p>I have one website about &lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.medialinkwirelessnrouter.net%3AEHr_OCYKgqAp_t9R9K47zOHoQuY&amp;cuid=3321886" rel="nofollow noopener" title="http://www.medialinkwirelessnrouter.net">http://www.medialinkwireles...</a>"&gt;medialink wireless n router&lt;/a&gt; and I would like to try handlebars, but I'm not sure if I will succeed because the site is developed in wordpress...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740710">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740710">27</a> by Raymond Camden
		posted on 5/5/2012 at 1:40 AM
		</div>
		<div class="comment_text"><p>You would need to edit the code I assume.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740712">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740712">28</a> by phani kiran.M
		posted on 11/20/2013 at 7:32 PM
		</div>
		<div class="comment_text"><p>hi all,<br>I just started working now on handlebars.I m facing problem while compiling handlebar template file into .js with minified version file,The newly crerated file is starting  '!' symbol it is observed after opening the file , the newly created js file which browser is not <a href="http://disq.us/url?url=http%3A%2F%2Faccepting.how%3AvBfM9ap7yupn3sHNkZULfVUs4ko&amp;cuid=3321886" rel="nofollow noopener" title="accepting.how">accepting.how</a> can i fix this issue in 64-bit machine.can anyone help me on this.</p><p>Regards,<br>phanikiran</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740713">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740713">29</a> by Raymond Camden
		posted on 11/21/2013 at 2:24 AM
		</div>
		<div class="comment_text"><p>Not sure what to suggest here. When I did my tests with Handlebars I didn't try minimizing the compiled templates. I'd try their Google group (pretty sure they have one).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740709">30</a> by prad
		posted on 12/14/2013 at 11:10 PM
		</div>
		<div class="comment_text"><p>Hi am working on a application, where server is giving me response of type float i.e xxx.yy I need to display this xxx.yy as  xxxhyy</p><p>example: from server response----&gt;112.45<br>               output should be----------&gt;112h45</p><p>How do i do this please help me</p><p>thanks in advance....</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740716">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740716">31</a> by Raymond Camden
		posted on 12/15/2013 at 12:29 AM
		</div>
		<div class="comment_text"><p>You need a block helper. See: <a href="http://disq.us/url?url=http%3A%2F%2Fhandlebarsjs.com%2Fblock_helpers.html%3AGSg4W4rMDXqt9n2BXtZuklDEsbk&amp;cuid=3321886" rel="nofollow noopener" title="http://handlebarsjs.com/block_helpers.html">http://handlebarsjs.com/blo...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740711">32</a> by siva
		posted on 1/15/2014 at 5:15 PM
		</div>
		<div class="comment_text"><p>in ie8 handle bar js is not working</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713740715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713740715">33</a> by Raymond Camden
		posted on 1/15/2014 at 5:25 PM
		</div>
		<div class="comment_text"><p>From what I can see, it should work in IE8. Can you please specify what error you are getting? This may be an issue for the Handlebars team though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2290430089">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2290430089">34</a> by sakthi
		posted on 10/5/2015 at 8:51 AM
		</div>
		<div class="comment_text"><p>Hi I am new for this, how to prepare popup window login form with validation? anybody having sample code.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2290491192">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2290491192">35</a> (In reply to <a href="#c_2290430089">#34</a>) by Raymond Camden
		posted on 10/5/2015 at 10:13 AM
		</div>
		<div class="comment_text"><p>This question doesn't really apply to the article, does it? You can find a simple popup/modal code in Bootstrap.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2411937313">
	<div>
		<img src="https://disqus.com/api/users/avatars/marklottes.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2411937313">36</a> by Mark Lottes
		posted on 12/16/2015 at 3:17 AM
		</div>
		<div class="comment_text"><p>Thank you so much. Exceptional write up. I have literally read over a dozen articles today looking for examples and your is the only one that has been helpful. Great job.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2412395733">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2412395733">37</a> (In reply to <a href="#c_2411937313">#36</a>) by Raymond Camden
		posted on 12/16/2015 at 12:50 PM
		</div>
		<div class="comment_text"><p>This is an old post, but I'm glad it was helpful. As an FYI, I have an entire course on client-side templating for sale on <a href="http://disq.us/url?url=http%3A%2F%2Foreilly.com%3A9KII0OPSYjLzZzyrdhTcJspyiHA&amp;cuid=3321886" rel="nofollow noopener" title="oreilly.com">oreilly.com</a>. You can get to it from the "About Me" link above.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3515661895">
	<div>
		<img src="https://disqus.com/api/users/avatars/everbarbero.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3515661895">38</a> by Echeban
		posted on 9/13/2017 at 4:16 PM
		</div>
		<div class="comment_text"><p>How can I use handlebarsjs to emulate the most basic feature of ASP Master Pages, just to have a common Header, Footer, and Menu for all pages?</p></div>
	</div>
</div>
		
<div class="comment" id="c_3518860867">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3518860867">39</a> (In reply to <a href="#c_3515661895">#38</a>) by Raymond Camden
		posted on 9/15/2017 at 3:01 PM
		</div>
		<div class="comment_text"><p>Well keep in mind Handlbars can be used in two contexts - either in the client side as I described here or on the server side with Node. On the client-side, what you describe doesn't really make sense. On the server side, you could use layouts with Handlebars and get the behavior you want.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3954126825">
	<div>
		<img src="https://disqus.com/api/users/avatars/stepankolomiets.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3954126825">40</a> by Stepan  Kolomiets
		posted on 6/21/2018 at 9:49 AM
		</div>
		<div class="comment_text"><p>Hi guys, I need your advice. If, for example, I have 5 sections where I should include header which is the same, should I use Handlebars or there are other better solutions to keep up with DRY rule?</p></div>
	</div>
</div>
		
<div class="comment" id="c_3954293208">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3954293208">41</a> (In reply to <a href="#c_3954126825">#40</a>) by Raymond Camden
		posted on 6/21/2018 at 12:55 PM
		</div>
		<div class="comment_text"><p>I'm not 100% sure I understand what you are asking. Handlebars lets you define, and reuse, a template. So that header you defined could be a template used in multiple places. Look at Partials, for example.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3955001379">
	<div>
		<img src="https://disqus.com/api/users/avatars/stepankolomiets.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3955001379">42</a> (In reply to <a href="#c_3954293208">#41</a>) by Stepan  Kolomiets
		posted on 6/21/2018 at 8:27 PM
		</div>
		<div class="comment_text"><p>Thanks, it's exactly what I'm looking for!</p></div>
	</div>
</div>
		