
<div class="comment" id="c_1713664447">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664447">1</a> by Ryan Guill
		posted on 4/26/2007 at 4:00 PM
		</div>
		<div class="comment_text"><p>I am still trying to process this, and what it really means.  Is this really a good thing?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664436">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664436">2</a> by Joe Mastroianni
		posted on 4/26/2007 at 6:13 PM
		</div>
		<div class="comment_text"><p>Exactly. What does this mean for deployment costs?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664448">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664448">3</a> by Raymond Camden
		posted on 4/26/2007 at 7:45 PM
		</div>
		<div class="comment_text"><p>Let me start off by saying that I am not an Open Source Zealot. I think OS is "nice" (shoot, I share all of my work), but I don't get political about it. To me - it is one more attribute like cost, platform support, etc. So to me it is good in that it opens up the code base to support from the world. How much contributions come in is totally up in the air. Maybe none. But it can't hurt.</p><p>Joe - not quite sure what you mean. It certainly won't increase the cost to deploy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664451">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664451">4</a> by Joe Mastroianni
		posted on 4/26/2007 at 8:01 PM
		</div>
		<div class="comment_text"><p>I guess I meant development and deployment costs. FlexBuilder is 500.00. Other components from Adobe also cost money. I take those will most likely not be open sourced?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664449">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664449">5</a> by Nat Papovich
		posted on 4/26/2007 at 8:25 PM
		</div>
		<div class="comment_text"><p>You can check out the FAQ Ray points to, but it appears that Adobe will continue to charge for Flex Builder ($500+) along with Flex Data Services ($$$). They're basically open-sourcing everything they currently give away for free. They'll also continue to offer everything under a commercial (supported) license, similar to, say MySQL.</p><p>Ray, they've mentioned that it'll be under the Mozilla umbrella so chances are slim for a home at RIAForge.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664452">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664452">6</a> by TJ Downes
		posted on 4/26/2007 at 10:00 PM
		</div>
		<div class="comment_text"><p>Nat, they actually are using the Mozilla license, that's it. The project will not be under the umbrella of Mozilla and will stay under Adobe's wing. So it could end up on RIAForge, but I suspect Adobe will host the project themselves.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664450">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664450">7</a> by Raymond Camden
		posted on 4/26/2007 at 10:02 PM
		</div>
		<div class="comment_text"><p>Don't forget though that there is a free, limit throughput, version of FDS, and you don't _need_ FlexBuilder to write Flex apps.</p></div>
	</div>
</div>
		