
<div class="comment" id="c_1713664521">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664521">1</a> by Dave Shuck
		posted on 4/27/2007 at 8:46 PM
		</div>
		<div class="comment_text"><p>I sure wish they had a Linux client.  I wonder if that is in the works.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713664498">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713664498">2</a> by Russ Johnson
		posted on 4/30/2007 at 7:06 AM
		</div>
		<div class="comment_text"><p>The Mac beta is working nicely for simple backups. No support for adding rules to your backup sets as of yet though, that kind of sucks. Also support for external drives is shoddy at best. I pointed a backup set to my music collection on my external 250GB Western Digital MyBook drive and it only found 68 files out of 14,000. Not a very good backup.</p><p>On a brighter note, I sent an email to support about the issues I was having with the external drive and they repsonded quickly and asked me for copies of several log files in helping to debug the issue.</p><p>I know its beta and Im planning to continue my subscription for several months in hopes they get these bugs worked out.</p></div>
	</div>
</div>
		