
<div class="comment" id="c_1713614915">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614915">1</a> by Peter Tilbrook
		posted on 9/14/2003 at 10:16 AM
		</div>
		<div class="comment_text"><p>Check out <a href="http://disq.us/url?url=http%3A%2F%2Fwww.yahoo.com.au%3AHhn_bHFKpOxAggD4o-41qj971j4&amp;cuid=3321886" rel="nofollow noopener" title="www.yahoo.com.au">www.yahoo.com.au</a> then. They are using FlashCom to good effect!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614918">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614918">2</a> by PaulH
		posted on 9/14/2003 at 10:49 AM
		</div>
		<div class="comment_text"><p>while i know you're wildly popular, can you be making enough advert money to put you in the faustian category? ie, is it worth it?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614923">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614923">3</a> by Raymond Camden
		posted on 9/15/2003 at 8:16 PM
		</div>
		<div class="comment_text"><p>It is earning money. Right now I don't for hosting, but I'd like to recoup some cost in case I do have to start paying. So - are the ads bad or good, or do you just ignore em?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614917">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614917">4</a> by PaulH
		posted on 9/15/2003 at 8:37 PM
		</div>
		<div class="comment_text"><p>glad to hear you're making money, another reason i guess for me to implement your blog &amp; get the heck off blogspot ;-) i still can't see you in the faust category when google's talking about 20 million page views before they'll customize their ads.</p><p>the ads are hard to ignore but run-of-the-mill as far as content (ditto for the blogspot ones which are googlized as well)--yes i actually read them. i don't guess they are any worse than anything else out there and its your blog after all.</p><p>so, no you're not seling out. the ads i guess are morally neutral.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614924">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614924">5</a> by Jacob Reider
		posted on 9/16/2003 at 3:08 PM
		</div>
		<div class="comment_text"><p>Ray - I took your lead and put ads on my blog as well.  I put them on the archive pages rather than the top page - so visitors to the main page at <a href="http://disq.us/url?url=http%3A%2F%2Fwww.docnotes.net%3AWrLKRrLXNr4yqzAx-7PGM45U7rA&amp;cuid=3321886" rel="nofollow noopener" title="www.docnotes.net">www.docnotes.net</a> won't see them (my loyal readers?!) but anyone coming to an individual post as indexed by a search engine will see the ads.  You are right (and I am surprised) .. this earns money rather quickly.  In 12 hours I've made $5.  Not gonna get rich .. but it'll pay for the blog hosting.  My wife congratulated me on the big earnings:  "if you google yourself all day, maybe you could quite one of yor jobs!"  She's so witty.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614920">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614920">6</a> by Angus McLaren
		posted on 9/18/2003 at 3:01 PM
		</div>
		<div class="comment_text"><p>But why would they accept you as an potential ad deliverer? Your site sucks and everything else you ever said about CFMX is so out of date it isn't funny.</p><p>You can't drive for shit and blame others for your misdemeanors. I mean what gives?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614919">7</a> by Raymond Camden
		posted on 9/18/2003 at 4:55 PM
		</div>
		<div class="comment_text"><p>Well, Angus, can you please tell me what content is out of date? I obviously disagree with you about the site sucking - and driving skills (by the way, I wasn't driving during the accident, and the police agreed with us that it was the other driver's fault), but I take seriously your comment about the content. If you could point to where I'm out of date, I'd appreciate it. Of course, a blog evolves over time. An entry from last year can't be faulted for being out of date.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614927">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614927">8</a> by Sam
		posted on 9/19/2003 at 12:19 AM
		</div>
		<div class="comment_text"><p>Can you customize the adds at all, to make the colors more compatible with your site?  Peter Hall mentioned on his blog he was looking at customizable ads once, not from google though.  Matt Liotta has ads on his site and theyre right at the top--very annoying.  I never noticed yours.  :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713614926">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713614926">9</a> by Raymond Camden
		posted on 9/19/2003 at 11:38 PM
		</div>
		<div class="comment_text"><p>Yes, you can customize the colors. I love green which is why I chose the scheme. Of course, I can't design for crap.</p></div>
	</div>
</div>
		