
<div class="comment" id="c_2549728730">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2549728730">1</a> by David McCan
		posted on 3/3/2016 at 5:56 PM
		</div>
		<div class="comment_text"><p>Congrats!  glhf</p><p>Enjoy your blog posts.  Thanks for sharing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2549807550">
	<div>
		<img src="https://disqus.com/api/users/avatars/rszehnder.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2549807550">2</a> by Robert Zehnder
		posted on 3/3/2016 at 6:33 PM
		</div>
		<div class="comment_text"><p>Congrats brother!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2549951640">
	<div>
		<img src="https://disqus.com/api/users/avatars/therealdanvega.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2549951640">3</a> by Dan Vega
		posted on 3/3/2016 at 7:46 PM
		</div>
		<div class="comment_text"><p>So cool...Congrats on the new position Ray!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2559301537">
	<div>
		<img src="https://disqus.com/api/users/avatars/Frondor.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2559301537">4</a> by Frondor
		posted on 3/9/2016 at 5:34 AM
		</div>
		<div class="comment_text"><p>I'm looking forward to read more blog post about LoopBack and its best practices! Keep it up!</p></div>
	</div>
</div>
		