
<div class="comment" id="c_1713615006">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615006">1</a> by Todd
		posted on 10/15/2003 at 7:40 PM
		</div>
		<div class="comment_text"><p>You mean this 40 gig ipod? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615011">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615011">2</a> by Todd
		posted on 10/15/2003 at 7:40 PM
		</div>
		<div class="comment_text"><p>er.. oops: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.web-rat.com%2FDownloads%2Fipod%2F%3AGPZcEvxHAYg7c3Q7iHlqB5XDI7s&amp;cuid=3321886" rel="nofollow noopener" title="http://www.web-rat.com/Downloads/ipod/">http://www.web-rat.com/Down...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615003">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615003">3</a> by Raymond Camden
		posted on 10/15/2003 at 8:00 PM
		</div>
		<div class="comment_text"><p>Hell yes. So, I just know your tired of your own blog and want to use mine - and you want to send me a new 40 gig IPod. Go ahead. Now. Please.</p><p>(Can't blame me for trying, eh? ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615017">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615017">4</a> by Todd
		posted on 10/15/2003 at 8:25 PM
		</div>
		<div class="comment_text"><p>Heh. :)  It is sweet.  My only complaint about it is battery life.  It's very dumb in terms of charging.  Example, it's fully charged, you take it out of the cradel and then put it back in because you forgot to sync something?  It now thinks it needs to charge again and you have to wait until it says it's fully charged again (Well, you don't have to, but still).  S'kind of stupid that way, not sure why.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615013">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615013">5</a> by Todd
		posted on 10/17/2003 at 1:34 AM
		</div>
		<div class="comment_text"><p>BTW, Ray.. when someone does donate the iPod to you.  Don't bother installing musicmatch.  iTunes for windows was just released today... great software, go use it instead. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615014">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615014">6</a> by Kyle
		posted on 10/25/2003 at 6:40 AM
		</div>
		<div class="comment_text"><p>Hello,Raymond Camden<br>I used your blog to build my blog,but it's troble to show chinese when I use rss reader to read my rss,I can't find where need modify,May you help me ? thank's a lot !!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615015">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615015">7</a> by adf
		posted on 11/1/2003 at 5:31 AM
		</div>
		<div class="comment_text"><p>still have (?????????) chinese problem ?</p></div>
	</div>
</div>
		