
<div class="comment" id="c_1714080395">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080395">1</a> by Kevin Jones
		posted on 10/25/2013 at 9:04 PM
		</div>
		<div class="comment_text"><p>Great session Ray on Solr @ CF Summit</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080387">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080387">2</a> by Raymond Camden
		posted on 10/25/2013 at 9:05 PM
		</div>
		<div class="comment_text"><p>Thank you.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080408">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080408">3</a> by Raymond Camden
		posted on 10/25/2013 at 9:17 PM
		</div>
		<div class="comment_text"><p>FYI, this site is using DisMax now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080414">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080414">4</a> by Ritesh Upadhyay
		posted on 1/4/2014 at 2:15 PM
		</div>
		<div class="comment_text"><p>How can i implimented dismaxparse in php+solr guide me</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714080410">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080410">5</a> by Raymond Camden
		posted on 1/4/2014 at 7:27 PM
		</div>
		<div class="comment_text"><p>I don't use PHP. The presentation described here is entirely about Solr and ColdFusion.</p></div>
	</div>
</div>
		