
<div class="comment" id="c_2867219097">
	<div>
		<img src="https://disqus.com/api/users/avatars/brad_wood.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867219097">1</a> by Brad Wood
		posted on 8/30/2016 at 3:24 PM
		</div>
		<div class="comment_text"><p>Thanks for the post Ray.  Brew is supposed to have the latest version, but they require you to submit a pull request to their repo every time you release a new version.  Here is the pull where they supposedly updated to 3.2.0.  I'll follow up and have someone on our end with a Mac give it a test. <a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2FHomebrew%2Fhomebrew-core%2Fpull%2F3303%3AS9Xy9ImEkbIMxh0qXM4ZeL4U5Nw&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/Homebrew/homebrew-core/pull/3303">https://github.com/Homebrew...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_2867237760">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867237760">2</a> (In reply to <a href="#c_2867219097">#1</a>) by Raymond Camden
		posted on 8/30/2016 at 3:35 PM
		</div>
		<div class="comment_text"><p>(I said this on Slack, but thought it might be useful to repeat here.)</p><p>So I know for another project, they recommend running brew update first. So their docs show:</p><p>brew update &amp;&amp; brew install hugo</p><p>Would that have helped here?</p></div>
	</div>
</div>
		
<div class="comment" id="c_2867241485">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_A5TH4jvN3p.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867241485">3</a> by Andrew Dixon
		posted on 8/30/2016 at 3:37 PM
		</div>
		<div class="comment_text"><p><a data-dsq-mention="cfjedimaster:disqus" href="https://disqus.com/by/cfjedimaster/" rel="nofollow noopener" title="https://disqus.com/by/cfjedimaster/">Raymond Camden</a> Can't believe I'm forgettable!!! :-(</p></div>
	</div>
</div>
		
<div class="comment" id="c_2867242199">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867242199">4</a> (In reply to <a href="#c_2867241485">#3</a>) by Raymond Camden
		posted on 8/30/2016 at 3:37 PM
		</div>
		<div class="comment_text"><p>Heh, sorry, and THANK YOU!</p></div>
	</div>
</div>
		
<div class="comment" id="c_2867298176">
	<div>
		<img src="https://disqus.com/api/users/avatars/neokoenig.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867298176">5</a> by Tom King
		posted on 8/30/2016 at 4:08 PM
		</div>
		<div class="comment_text"><p>Check out the stuff server.json gives you too: I have preset port numbers, custom url rewriting etc all setup, and I just need to do `start` to kick it all off. Awesome things.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2867321603">
	<div>
		<img src="https://disqus.com/api/users/avatars/brad_wood.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867321603">6</a> (In reply to <a href="#c_2867237760">#2</a>) by Brad Wood
		posted on 8/30/2016 at 4:21 PM
		</div>
		<div class="comment_text"><p>Probably.  I'll be honest, I don't have a Mac so I've never used Brew!  If they cache that data locally then I could see it being the case of an outdated local cache.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2867447123">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2867447123">7</a> (In reply to <a href="#c_2867298176">#5</a>) by Raymond Camden
		posted on 8/30/2016 at 5:29 PM
		</div>
		<div class="comment_text"><p>Dude, yeah, I forgot to mention this in my post, but that's *another* issue that came up based on my friend's need and was another reason I needed to leave Express. I can't believe CB supports it, and thank you for bringing it up!</p></div>
	</div>
</div>
		