
<div class="comment" id="c_1713736040">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736040">1</a> by Brian Swartzfager
		posted on 10/22/2011 at 12:01 AM
		</div>
		<div class="comment_text"><p>Ray, one question: since the Flex/AIR stuff is packaged into the .apk file, does that mean you could deploy Android apps based on 4.6 code today (as in, there's nothing that needs to be updated on the handset/Android OS side for the 4.6 stuff to work)?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736043">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736043">2</a> by Raymond Camden
		posted on 10/22/2011 at 12:14 AM
		</div>
		<div class="comment_text"><p>My understanding is that the AIR stuff _can_ be packaged in, not "is" packaged in. So I _may_ be able to ship this now. Still gonna wait though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736042">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736042">3</a> by Richard Turner-Jones
		posted on 10/22/2011 at 3:04 AM
		</div>
		<div class="comment_text"><p>Windows "wingdings" font capital N is a skull and cross bones.<br>Type it in Fireworks, under the Text menu select "Convert to Paths" and there you have a vector skull.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713736041">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713736041">4</a> by Raymond Camden
		posted on 10/22/2011 at 8:45 PM
		</div>
		<div class="comment_text"><p>omg that's cool. Never used Fireworks believe it or not. ;)</p></div>
	</div>
</div>
		