
<div class="comment" id="c_2443699883">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_XULXbZ1faV.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2443699883">1</a> by Justin James
		posted on 1/7/2016 at 1:10 AM
		</div>
		<div class="comment_text"><p>Guess I have been lucky to not have gotten bit by this.  Good info to know though.  Going to add this to my list of things to remember.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2559863232">
	<div>
		<img src="https://disqus.com/api/users/avatars/nncl.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2559863232">2</a> by Cauê Almeida
		posted on 3/9/2016 at 2:51 PM
		</div>
		<div class="comment_text"><p>Simple and so useful. Thanksss</p></div>
	</div>
</div>
		
<div class="comment" id="c_2615265068">
	<div>
		<img src="https://disqus.com/api/users/avatars/webchi.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2615265068">3</a> by webchi
		posted on 4/9/2016 at 10:58 PM
		</div>
		<div class="comment_text"><p>Thanks. Loose half an hour before found your post with how to fix this.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2767567622">
	<div>
		<img src="https://disqus.com/api/users/avatars/obedm503.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2767567622">4</a> by obedm503
		posted on 7/6/2016 at 3:32 AM
		</div>
		<div class="comment_text"><p>Great, solved my problem. Interestingly enough the view-title with a scope property worked fine when two views shared the same controller (like a list of films view, and a detail view for a clicked film). But for performance reasons I decided to give the details view it's own controller, and it broke. But this solved it. Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_2787028096">
	<div>
		<img src="https://disqus.com/api/users/avatars/erikig.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2787028096">5</a> by RagnarDanneskjöld
		posted on 7/16/2016 at 8:45 PM
		</div>
		<div class="comment_text"><p>Thanks for this, I wish it was a little better documented.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2890207025">
	<div>
		<img src="https://disqus.com/api/users/avatars/rinogo.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2890207025">6</a> by rinogo
		posted on 9/12/2016 at 11:22 PM
		</div>
		<div class="comment_text"><p>Thank you so much!  I burned several hours on this one... I chalked it up to my newb-level Angular/Ionic skills, but no matter what I tried (isolated scope, inherited scope, delays before setting the value, etc.), I couldn't get it to work reliably.  The "delayed set" approach worked, but is obviously a huge hack.  Good to know* it's just another quirk in the Angular/Ionic environment.  (*I wish I understood what *exactly* was going on, though!  Possible idea for a follow-up post, maybe?... :) )</p></div>
	</div>
</div>
		
<div class="comment" id="c_2890365707">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2890365707">7</a> (In reply to <a href="#c_2890207025">#6</a>) by Raymond Camden
		posted on 9/13/2016 at 1:20 AM
		</div>
		<div class="comment_text"><p>You are most welcome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3135331725">
	<div>
		<img src="https://disqus.com/api/users/avatars/bsquochoainew.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3135331725">8</a> by Trần Quốc Hoài (new 2015)
		posted on 2/3/2017 at 6:53 AM
		</div>
		<div class="comment_text"><p>i'm still checking your solution. Maybe it's working for my project. Thank you so much. If there is something happened i will inform with you. Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_3266815466">
	<div>
		<img src="https://disqus.com/api/users/avatars/prafullagarwal.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3266815466">9</a> by Prafull agarwal
		posted on 4/21/2017 at 12:20 PM
		</div>
		<div class="comment_text"><p>We are also facing this issue and your above resolution don't works for me!!!<br>After lots of hours we find we add a extra template in same ionic HTML via script tag ng/template this causes blocker to ionic header updating.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3268158619">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3268158619">10</a> (In reply to <a href="#c_3266815466">#9</a>) by Cristiano
		posted on 4/22/2017 at 5:20 AM
		</div>
		<div class="comment_text"><p>Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3335076554">
	<div>
		<img src="https://disqus.com/api/users/avatars/CapnHammered.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3335076554">11</a> by Danny Battison
		posted on 6/1/2017 at 1:13 PM
		</div>
		<div class="comment_text"><p>I've just come across this and you saved me a headache.  Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_3335088505">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3335088505">12</a> (In reply to <a href="#c_3335076554">#11</a>) by Raymond Camden
		posted on 6/1/2017 at 1:22 PM
		</div>
		<div class="comment_text"><p>You are most welcome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3357039491">
	<div>
		<img src="https://disqus.com/api/users/avatars/georgesimonk.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3357039491">13</a> by George Simon K
		posted on 6/13/2017 at 6:23 AM
		</div>
		<div class="comment_text"><p>Thank you very much for this post. This was helpful</p></div>
	</div>
</div>
		
<div class="comment" id="c_3603827254">
	<div>
		<img src="https://disqus.com/api/users/avatars/disqus_Wz1gV30H2j.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3603827254">14</a> by Gil Santos
		posted on 11/7/2017 at 1:04 AM
		</div>
		<div class="comment_text"><p>Very helpful. Thank you so much!</p></div>
	</div>
</div>
		