
<div class="comment" id="c_1713620157">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713620157">1</a> by Harry Fear
		posted on 8/21/2005 at 3:30 PM
		</div>
		<div class="comment_text"><p>No chance sane people would unsubscribe....we love CFLib!</p></div>
	</div>
</div>
		