
<div class="comment" id="c_1713721908">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721908">1</a> by Jason Brookins
		posted on 2/9/2010 at 7:53 PM
		</div>
		<div class="comment_text"><p>I, for one, would love to see this in RIAForge. I'm just now getting into FW/1, so this would be a time-saver.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721911">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721911">2</a> by Zarko
		posted on 2/9/2010 at 8:25 PM
		</div>
		<div class="comment_text"><p>This could be extended over time, so thumbs up for riaforge.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721917">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721917">3</a> by Joe Brislin
		posted on 2/9/2010 at 9:52 PM
		</div>
		<div class="comment_text"><p>I think skeletons are useful no matter what type of framework that you're using. It always gives you a clean slate to start with and helps speed up development. I would also love to see this in RIAForge.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721916">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721916">4</a> by Dan Vega
		posted on 2/9/2010 at 11:05 PM
		</div>
		<div class="comment_text"><p>I always wondered how I could use the project create event, great example!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721919">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721919">5</a> by John Allen
		posted on 2/10/2010 at 12:16 AM
		</div>
		<div class="comment_text"><p>Great example.</p><p>This post is ALSO cool cause it mentions FW/1, and FW/1  ROCKS!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721918">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721918">6</a> by Dan Fredericks
		posted on 2/10/2010 at 2:32 AM
		</div>
		<div class="comment_text"><p>I like it...of course if you cf9 at a remote server, you have to create it locally, then copy it to your cf9 server...it beats remembering all the folders and files.<br>I was wondering why you did not include the org/framework.cfc folder into your install?<br>Did you not do this because that folder should be created outside your framework and just extend to it?</p><p>thanks for this CFB extension.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721922">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721922">7</a> by Gary Funk
		posted on 2/10/2010 at 2:49 AM
		</div>
		<div class="comment_text"><p>FW/1 is the first framework I have seriously worked with. I picked it because I got in on the ground floor and am learning along with everyone else.</p><p>Honestly Ray, this extension will help me use FW/1 more, which I view as good.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713721924">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713721924">8</a> by Raymond Camden
		posted on 2/10/2010 at 2:57 AM
		</div>
		<div class="comment_text"><p>@Dan: I made the assumption that you had already "installed" the FW/1 framework (I hate to say install when its all of one file ;).</p></div>
	</div>
</div>
		