
<div class="comment" id="c_3336493077">
	<div>
		<img src="https://disqus.com/api/users/avatars/simevidas.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3336493077">1</a> by Šime Vidas
		posted on 6/2/2017 at 4:32 AM
		</div>
		<div class="comment_text"><p>The issue seems to already have been fixed in Firefox Nightly (I noticed because that’s my default browser 😎). Maybe it was a temporary regression.</p><p>Regarding the element in general, I’m betting on web components. Hopefully, Firefox and Edge will add support for the v1 APIs by this time next year. A <code>&lt;data-list&gt;</code> custom element could provide a consistent UI and UX out of the box.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3336927750">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3336927750">2</a> (In reply to <a href="#c_3336493077">#1</a>) by Raymond Camden
		posted on 6/2/2017 at 1:12 PM
		</div>
		<div class="comment_text"><p>Interesting. It looked like something planned for me, but yea, as I said, with them already nicely limiting the size, it didn't make sense.</p></div>
	</div>
</div>
		