
<div class="comment" id="c_1713744699">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744699">1</a> by MD
		posted on 2/25/2013 at 11:59 PM
		</div>
		<div class="comment_text"><p>Hi and thanks for talk.<br>I have a question about &lt;iframe&gt; elements. We load some content in a ifram that include some JavaScripts code which send a request to a the server and receive the respond. if we monitor the network send and receive requests with something like chrome DevTools, can we see network activities of ifame content? Or just main page network activities can be seen?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744704">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744704">2</a> by Raymond Camden
		posted on 2/26/2013 at 12:21 AM
		</div>
		<div class="comment_text"><p>I don't know.... but... silly question. Why not just test it? If you already have this, just use the Chrome Dev Tools and look. :) It should take you 2 seconds to test, right?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744703">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744703">3</a> by Ty Whalin
		posted on 2/26/2013 at 7:38 PM
		</div>
		<div class="comment_text"><p>Joined you on Twitter, one closer to that 5000 mark.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744709">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744709">4</a> by Raymond Camden
		posted on 2/26/2013 at 7:52 PM
		</div>
		<div class="comment_text"><p>5002 and now. ;) Not sure what that gets me, but...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744710">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744710">5</a> by Tushar Bhaware
		posted on 2/27/2013 at 9:56 AM
		</div>
		<div class="comment_text"><p>nice presentation ... learn a quite a bit ... Thanks :)</p></div>
	</div>
</div>
		