
<div class="comment" id="c_1713744642">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744642">1</a> by ron
		posted on 2/11/2013 at 8:34 PM
		</div>
		<div class="comment_text"><p>I've been out the job market for a long time -- but this is the first I've ever seen an ad for a              union programming job.  I would think that someone with that skill set could do a whole lot better than $57K anyway. <br>Thanks for sharing!</p></div>
	</div>
</div>
		