
<div class="comment" id="c_1714082608">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714082608">1</a> by Gustavo Denis
		posted on 4/24/2014 at 9:36 PM
		</div>
		<div class="comment_text"><p>great! :D</p></div>
	</div>
</div>
		
<div class="comment" id="c_2163223478">
	<div>
		<img src="https://disqus.com/api/users/avatars/futuredve.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2163223478">2</a> by FUTURED∆VE
		posted on 7/29/2015 at 2:17 PM
		</div>
		<div class="comment_text"><p>Hi Raymond thanks for your work! <br>How do you limit the number of projects to load? <br>On the previous version it was a handcoded line in one of the arrays but I can't work it out in this version. Thanks man</p></div>
	</div>
</div>
		
<div class="comment" id="c_2163248022">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2163248022">3</a> (In reply to <a href="#c_2163223478">#2</a>) by Raymond Camden
		posted on 7/29/2015 at 2:31 PM
		</div>
		<div class="comment_text"><p>It looks like it isn't supported in either of the getProjects methods. It would be easy to add I think. You can file an issue, but I really don't work w/ Behance anymore now that I'm no longer at Adobe.</p></div>
	</div>
</div>
		
<div class="comment" id="c_2163347137">
	<div>
		<img src="https://disqus.com/api/users/avatars/futuredve.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_2163347137">4</a> (In reply to <a href="#c_2163248022">#3</a>) by FUTURED∆VE
		posted on 7/29/2015 at 3:27 PM
		</div>
		<div class="comment_text"><p>cool man thanks for the reply</p></div>
	</div>
</div>
		