
<div class="comment" id="c_1713733302">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733302">1</a> by James Edmunds
		posted on 6/17/2011 at 1:23 AM
		</div>
		<div class="comment_text"><p>I love CFLib and still use it regularly!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733291">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733291">2</a> by Krish
		posted on 6/18/2011 at 1:01 AM
		</div>
		<div class="comment_text"><p>We have an urgent opening for “Cold Fusion Developer ” Rochester ,MN 12 months project. Please review the job requirements and let me know if anybody interested, Please respond with your .doc RESUME to krish@compusoft<a href="http://disq.us/url?url=http%3A%2F%2F-is.com%3AEpwVmiI8H-7MqO8TmaGIZ3yUx6c&amp;cuid=3321886" rel="nofollow noopener" title="-is.com">-is.com</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713733303">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713733303">3</a> by Raymond Camden
		posted on 6/18/2011 at 1:03 AM
		</div>
		<div class="comment_text"><p>Krish, I was going to delete this comment as spam, but since it is for a CF developer I will not. But - your comment is not appropriate here. There are other places to post job openings.</p></div>
	</div>
</div>
		