
<div class="comment" id="c_1713652339">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652339">1</a> by Brian Rinaldi
		posted on 4/25/2006 at 5:40 PM
		</div>
		<div class="comment_text"><p>We moved everything to swfobject <a href="http://disq.us/url?url=http%3A%2F%2Fblog.deconcept.com%2Fswfobject%2F%3ADzUpVexUcqFioaN9tcteSQBIIIM&amp;cuid=3321886" rel="nofollow noopener" title="http://blog.deconcept.com/swfobject/">http://blog.deconcept.com/s...</a> which worked great as well.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652340">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652340">2</a> by Raymond Camden
		posted on 4/25/2006 at 5:43 PM
		</div>
		<div class="comment_text"><p>I've heard good things about it as well. I'm not using it, but I think a coworker is.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652316">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652316">3</a> by Ryan Guill
		posted on 4/25/2006 at 6:00 PM
		</div>
		<div class="comment_text"><p>Hey ray, does this work for flash forms as well?  If so, Im not sure how you would implement it...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652334">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652334">4</a> by Chris Charlton
		posted on 4/25/2006 at 6:05 PM
		</div>
		<div class="comment_text"><p>Yes, pretty simple.  :) The free extension from Adobe adds a Publishing (HTML) template and a Command (to ask where to save the JS include file). So, yes, pretty simple.</p><p>I see FlashObject, er now, SWFobject (SWFo) has an update as well. I really, really like how SWFo handles FlashParams. Adobe's solution isn't bad, but I like to parse in params with server-side code and Adobe's solution for FlashParams seems arcane for now. For now.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652333">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652333">5</a> by Raymond Camden
		posted on 4/25/2006 at 6:12 PM
		</div>
		<div class="comment_text"><p>Ryan, no, it is not for Flash Forms or CFCHART. Adobe is working on that though.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652335">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652335">6</a> by Kyle Hayes
		posted on 4/25/2006 at 7:09 PM
		</div>
		<div class="comment_text"><p>Apple implemented javascript code and functions for embedding quicktime as well.<br><a href="http://disq.us/url?url=http%3A%2F%2Fwww.apple.com%2Fquicktime%2Ftutorials%2Fembed.html%3AKKUSLA-btsrMcnKNA7QmR8uuRNA&amp;cuid=3321886" rel="nofollow noopener" title="http://www.apple.com/quicktime/tutorials/embed.html">http://www.apple.com/quickt...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652336">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652336">7</a> by Rob Gonda
		posted on 4/26/2006 at 3:30 AM
		</div>
		<div class="comment_text"><p>I'll second FlashObject / SWFObject ... I started using it recently and it's working like a charm.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652337">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652337">8</a> by Bjorn Jensen
		posted on 4/26/2006 at 11:09 AM
		</div>
		<div class="comment_text"><p>But does it work with javascript disabled ?<br>NoScript is the 2nd most popular extension for firefox at the moment, and as a NoSCript user I have to say it's bliss. I'm already blocking flash, but I can enable it with a click, however if javascript is used to generate the flash, I'll probably never see it and just move on to another site.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652338">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652338">9</a> by Raymond Camden
		posted on 4/26/2006 at 2:40 PM
		</div>
		<div class="comment_text"><p>It does not work with JS disabled. I believe the Adobe site mentions that in the noscript you can use the 'old' object/embed stuff so that at least they _get_ the flash, but just have to click first.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652341">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652341">10</a> by PaulC
		posted on 4/26/2006 at 11:05 PM
		</div>
		<div class="comment_text"><p>As infuriating as this situation is because of Eolas, I have to call shenanigans in part on Adobe.</p><p>MS announced this change months ago, patches for CF should have been ready to go, and I didn't even hear about the revised Flash publish templates until I saw it on John Dowdell's blog days after the IE patch was released.</p><p>Not to nitpick too hard, but I didn't see any kind of statement from Adobe on the lawsuit either. I know companies like to avoid getting sued, but I think developers would feel better if mama bear flashed her teeth at Mike Doyle.</p><p>Especially after &lt;a href="<a href="http://disq.us/url?url=http%3A%2F%2Fwww.eweek.com%2Farticle2%2F0%2C1895%2C1944867%2C00.asp%3AckKp4l9eco11x3J0TNuCFpzMc8E&amp;cuid=3321886" rel="nofollow noopener" title="http://www.eweek.com/article2/0,1895,1944867,00.asp">http://www.eweek.com/articl...</a>" target="_blank&gt;these comments from Eolas COO Mark Swords.<br>&lt;/a&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652322">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652322">11</a> by J
		posted on 6/30/2006 at 5:14 AM
		</div>
		<div class="comment_text"><p>I can't get FlashVars to work in IE6 or Firefox 1.5.0 and when I searched adobe flash forum for 'active AND content AND FlashVars' I found posts mentioning that FlashVars doesn't work.  What browser are you using?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652323">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652323">12</a> by Greg H
		posted on 7/27/2006 at 8:15 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>In a comment above 3 months ago, responding to Ryan's question about an Active Content fix for "Flash Forms or CFCHART" you wrote "Adobe is working on that".</p><p>Have you heard if Adobe has released a fix?  I checked the CF 7.0.2 updater and do not see it called out specifically.</p><p>Thanks,</p><p>g</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652319">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652319">13</a> by Raymond Camden
		posted on 7/27/2006 at 8:19 PM
		</div>
		<div class="comment_text"><p>It is there.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652321">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652321">14</a> by Z
		posted on 8/28/2008 at 6:27 PM
		</div>
		<div class="comment_text"><p>This article saved my sanity.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652342">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652342">15</a> by DJ
		posted on 10/24/2008 at 10:24 PM
		</div>
		<div class="comment_text"><p>I know this is an old article so I apologize for reopening.</p><p>The AC_FL_Runcontent works great for FF 3 but IE will load my swf but not play it (background shows but nothing else) as soon as i put in 'FlashVars','xmlfile=#imageXML#&amp;xmlfiletype=Default',</p><p>Anyone have any ideas as to why or how to fix?</p><p>Thanks!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713652343">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713652343">16</a> by Raymond Camden
		posted on 10/25/2008 at 12:35 AM
		</div>
		<div class="comment_text"><p>What is #imagexml#? It doesn't have a space in it, does it?</p></div>
	</div>
</div>
		