
<div class="comment" id="c_1713665074">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665074">1</a> by collin
		posted on 5/13/2007 at 5:39 AM
		</div>
		<div class="comment_text"><p>thanks for all of the great projects!</p><p>I just wanted to comment that viva pinata IS weird, one of my favorite shows with my daughter though. the reference gave me good chuckle! for anyone who hasn't seen it, get up early on saturday and stick around for some ninja turtles.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665072">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665072">2</a> by Lola LB
		posted on 5/13/2007 at 2:54 PM
		</div>
		<div class="comment_text"><p>Try this - <a href="http://disq.us/url?url=http%3A%2F%2Fwww.actualtechnologies.com%2Fmacodbcnews.php%3A5JzAHZzgCwvBSc2srRIH2OyLTOo&amp;cuid=3321886" rel="nofollow noopener" title="http://www.actualtechnologies.com/macodbcnews.php">http://www.actualtechnologi...</a></p><p>It's the only one I know of that has drivers to allow you to access Access databases (pun not intended).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665069">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665069">3</a> by Michael White
		posted on 5/14/2007 at 6:47 PM
		</div>
		<div class="comment_text"><p>you have probably answered this a thousand times, but what is the best way to migrate all my old data (from version 2.06) to the new version? I am using a microsoft SQL database.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665067">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665067">4</a> by Raymond Camden
		posted on 5/14/2007 at 6:54 PM
		</div>
		<div class="comment_text"><p>The readme.txt file is your friend. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665058">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665058">5</a> by Michael White
		posted on 5/14/2007 at 6:55 PM
		</div>
		<div class="comment_text"><p>by the way, I currently have NO tables that start with "lh_"</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665071">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665071">6</a> by Raymond Camden
		posted on 5/14/2007 at 6:59 PM
		</div>
		<div class="comment_text"><p>Rename them to have lh_ in front. This was done to help LHP not conflict with other systems. My other apps use a dynamic prefix. I may add that to LHP later on.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665068">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665068">7</a> by Michael White
		posted on 5/14/2007 at 7:08 PM
		</div>
		<div class="comment_text"><p>Thanks Ray, that will teach me for skipping versions...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665075">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665075">8</a> by Colter
		posted on 6/28/2007 at 10:39 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>First, thanks for all your future forward work, it helps keep my ColdFusion code forever moving.</p><p>Next, I have searched to see if you have posted this anywhere but have you been able to get around to updating LightHouse JSON with Spry 1.5?</p><p>Thanks,<br>Colter</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665080">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665080">9</a> by Raymond Camden
		posted on 7/1/2007 at 6:21 AM
		</div>
		<div class="comment_text"><p>No, but it will be in the next update.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665070">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665070">10</a> by Steve Glachan
		posted on 7/2/2007 at 11:44 AM
		</div>
		<div class="comment_text"><p>Hi Ray,</p><p>Your install instructions were great by the way. I am having a slight problem running the application however.</p><p>The mail server I have set in CF Admin validates fine but when I try to run Lighthouse Pro Element (my first attempt at running it) I receive the following error:</p><p>MAILSERVER is undefined in APPLICATION. <br>The error occurred in D:\Content\WWWRoot\lighthousepro\Application.cfc: line 273</p><p>It does not seem to matter if I leave the mail server related fields blank or filled in the defaults.cfm file</p><p>Please let me know your thoughts ... even if it means telling me I've done something stupidly wrong :-p</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665073">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665073">11</a> by Steve Glachan
		posted on 7/2/2007 at 11:48 AM
		</div>
		<div class="comment_text"><p>PS.</p><p>Sorry for any confusion ... I have no idea where the word "Element" came from in my above post! ("Lighthouse Pro Element")... I just meant Lighthouse Pro 2.4 :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665079">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665079">12</a> by Raymond Camden
		posted on 7/2/2007 at 3:39 PM
		</div>
		<div class="comment_text"><p>Please update to the latest version. An update was released around noon on July 1, 2007.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665076">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665076">13</a> by Mingo Hagen
		posted on 7/9/2007 at 2:07 PM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>Thanks for updating! I was wondering if you could help me with this error i'm getting:</p><p>Caught exception in JSONDataSet.loadDataIntoDataSet: SyntaxError: missing ] after element list</p><p>I'm only getting it with one Project, so I assume it's an unescaped ']' or something.</p><p>The error occurs at /project_view.cfm</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665083">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665083">14</a> by Raymond Camden
		posted on 7/9/2007 at 4:26 PM
		</div>
		<div class="comment_text"><p>Use Firebug and show me how the data was returned please.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665082">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665082">15</a> by Kevin Penny
		posted on 7/11/2007 at 8:52 PM
		</div>
		<div class="comment_text"><p>Hey Ray - Thanks for putting this out there as open source - <br>I'm planning on adding an 'Excel Document' Upload/import of Issues into the Project for the Lighthouse application.  So you can upload an excel document with 'Issues' in it that will prepopulate the Project.  We need this as with a part of our company that have a checklist of 40 items that they do each time with each new client - and want to use this to track them.  Just thought I'd let you know - once its complete I can give you the source code for it - in case you want to built it into your release (origionally might be strictly sql server compat, but I can dumb it down once I get into it likely)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665078">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665078">16</a> by Raymond Camden
		posted on 7/11/2007 at 10:10 PM
		</div>
		<div class="comment_text"><p>Sure Kevin, send it on over.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665081">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665081">17</a> by Kevin Penny
		posted on 7/13/2007 at 8:54 PM
		</div>
		<div class="comment_text"><p>I sent over the update lighthousepro with he excel import ability - hope you got it ok and find it to your liking.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665060">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665060">18</a> by Rudi Shumpert
		posted on 8/8/2007 at 6:18 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Do you happen to know if anyone has installed LightHouse on BlueDragon?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665059">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665059">19</a> by Raymond Camden
		posted on 8/8/2007 at 6:22 PM
		</div>
		<div class="comment_text"><p>No. I do intend to support BD - I just don't always have the time to test. :(</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665063">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665063">20</a> by Railgun
		posted on 1/14/2010 at 12:49 AM
		</div>
		<div class="comment_text"><p>Was Comment 13 by Mingo Hagen every addressed? I have the same problem with LH v2.4.7.  We're trying to upgrade to the latest now to see if it gets fixed.  It happens in both IE 7 and FF3.5.  I have a latop and desktop, only happens on the desktop for the same LH account.  Even though my project has 2 issues, they don't show up at the project level (same .cfm as mentioned above) and ALL the debug info is dumped in the response including my LH ID and PW.  The issues are in the DB.  I even get emailed about them, but they will never display and I get the Caught exception in JSONDataSet.loadDataIntoDataSet it what looks like a debugging window.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665062">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665062">21</a> by Raymond Camden
		posted on 1/14/2010 at 12:54 AM
		</div>
		<div class="comment_text"><p>I don't remember if he followed up with me post-comment. If you get it after updating, please email me directly so we can work it out.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665065">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665065">22</a> by Peter Tanswell
		posted on 5/14/2013 at 9:06 AM
		</div>
		<div class="comment_text"><p>Hi there</p><p>Have been trying to get Lighhouse pro working but to no avail.</p><p>I followed all the steps but still no success.</p><p>Wondering if someone might be able to have a quick look and advise what I have missed so that I can get the application running.</p><p>I keep on getting an error Could not find the included template /ModelGlue/gesture/ModelGlue.cfm</p><p>I would really like to get this application working properly so any assistance that can be given would be greatly appreciated.</p><p>Thanks in advance.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713665066">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713665066">23</a> by Raymond Camden
		posted on 5/14/2013 at 2:46 PM
		</div>
		<div class="comment_text"><p>Do you have a CF mapping for ModelGlue?</p></div>
	</div>
</div>
		