
<div class="comment" id="c_1714080331">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714080331">1</a> by Raymond Camden
		posted on 10/16/2013 at 6:16 PM
		</div>
		<div class="comment_text"><p>I've got a rough draft of the second version with a render function built in as well. Again - the thinking being that you may not want to use JS to draw out your crap.</p></div>
	</div>
</div>
		