
<div class="comment" id="c_1713714388">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714388">1</a> by todd sharp
		posted on 4/2/2009 at 5:28 PM
		</div>
		<div class="comment_text"><p>It helped me the other day when we talked on IM.  Thanks yo.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713714395">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714395">2</a> by Dan G. Switzer, II
		posted on 4/2/2009 at 6:21 PM
		</div>
		<div class="comment_text"><p>Enabling multiline is another option that can help things out. It'll alternate labels between two rows which can help squeeze more labels on a chart.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713714394">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714394">3</a> by Dan Wilson
		posted on 4/2/2009 at 6:34 PM
		</div>
		<div class="comment_text"><p>Here's another way to work out the skiplabels feature.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.nodans.com%2Findex.cfm%2F2008%2F12%2F4%2FI-searched-and-found-CFSearching%3A0HByajjOb9kD0Uopq5mz1Rq0Jzw&amp;cuid=3321886" rel="nofollow noopener" title="http://www.nodans.com/index.cfm/2008/12/4/I-searched-and-found-CFSearching">http://www.nodans.com/index...</a></p><p>In my case, the number of labels to skip totally depended on runtime conditions.</p><p>DW</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713714396">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714396">4</a> by Edward Beckett
		posted on 4/2/2009 at 6:40 PM
		</div>
		<div class="comment_text"><p>Hmmm ...</p><p>It would be really cool to see BlogCFC/stats.cfm updated with some snazzy CFChart action ...</p><p>:)</p><p>Feature Request?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713714399">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714399">5</a> by Raymond Camden
		posted on 4/2/2009 at 6:42 PM
		</div>
		<div class="comment_text"><p>When it comes to stats in BlogCFC, my thinking was to actually kill the current stats, which is a public list of tables, and replace it with an admin only stats tool that is MUCH deeper.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713714397">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713714397">6</a> by Gary Gilbert
		posted on 4/2/2009 at 11:59 PM
		</div>
		<div class="comment_text"><p>@Ray,</p><p>The skip labels feature is really great for statistics where you only want to show Q1 through Q4 but want to include the points on the graph for all 12 months.  Or for stock charts where you show daily points but only labels for each month.</p></div>
	</div>
</div>
		