
<div class="comment" id="c_1713743420">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743420">1</a> by Josh Slebodnik
		posted on 10/12/2012 at 11:38 PM
		</div>
		<div class="comment_text"><p>Thanks for the blog post Raymond! I also found another solution. If you use Yahoo Pipes, you can create a pipe of an iCal feed, and it can actually convert it into an RSS feed link!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713743417">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713743417">2</a> by Raymond Camden
		posted on 10/12/2012 at 11:38 PM
		</div>
		<div class="comment_text"><p>That is damn slick. I used Yahoo Pipes a few years back and it was a cool technology, I didn't know it supported iCal parsing though. Slick.</p></div>
	</div>
</div>
		