
<div class="comment" id="c_1713744095">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744095">1</a> by Joe Brislin
		posted on 12/5/2012 at 2:27 AM
		</div>
		<div class="comment_text"><p>For informational purposes, the name Big Lick comes from the original of Roanoke, VA. <a href="http://disq.us/url?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FRoanoke%2C_Virginia%3AO-DEMx4Q-8ECL2TWY-H2I0Hsr-4&amp;cuid=3321886" rel="nofollow noopener" title="http://en.wikipedia.org/wiki/Roanoke,_Virginia">http://en.wikipedia.org/wik...</a></p><p>Of course, it also helps that it's a really stinking funny name.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744100">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744100">2</a> by Phillip Senn
		posted on 12/5/2012 at 3:38 AM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFrench_Lick%2C_Indiana%3Au8yos-PVPh6uXmUm7FtP3EdcyuU&amp;cuid=3321886" rel="nofollow noopener" title="http://en.wikipedia.org/wiki/French_Lick,_Indiana">http://en.wikipedia.org/wik...</a></p></div>
	</div>
</div>
		