
<div class="comment" id="c_1713744079">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744079">1</a> by Peter Tilbrook
		posted on 12/5/2012 at 8:12 AM
		</div>
		<div class="comment_text"><p>Got a version of it working well here:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fweb2.clubgroup.com.au%2F_Virtual%2Flocations.clubgroup.com.au%2F%3AfsZzt0WyvNtEXtjOnDDOyhOIF44&amp;cuid=3321886" rel="nofollow noopener" title="http://web2.clubgroup.com.au/_Virtual/locations.clubgroup.com.au/">http://web2.clubgroup.com.a...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744080">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744080">2</a> by Raymond Camden
		posted on 12/5/2012 at 8:15 AM
		</div>
		<div class="comment_text"><p>So where do I send the invoice? ;)</p><p>Sooooo happy to see someone actually using my code. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744082">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744082">3</a> by Peter Tilbrook
		posted on 12/5/2012 at 1:40 PM
		</div>
		<div class="comment_text"><p>If you view the source code I added credit to you there. :)</p><p>All my sites are coming from a database so need tweaking. Also added custom addtions like URL, phone and email addresses.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744086">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744086">4</a> by Peter Tilbrook
		posted on 12/13/2012 at 2:28 PM
		</div>
		<div class="comment_text"><p>Has a proper sub-domain now.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Flocations.clubgroup.com.au%2F%3AWV2N2QnpSglJbZNk2T2Alx7eRmg&amp;cuid=3321886" rel="nofollow noopener" title="http://locations.clubgroup.com.au/">http://locations.clubgroup....</a></p><p>Tip find CLub Lime Kaleen. Drag "street view man" onto it. I found this out myself by accident!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744085">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744085">5</a> by Raymond Camden
		posted on 12/13/2012 at 8:58 PM
		</div>
		<div class="comment_text"><p>Slick. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744081">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744081">6</a> by Peter Tilbrook
		posted on 12/14/2012 at 1:33 AM
		</div>
		<div class="comment_text"><p>OK so I have Sat mode on by default. Looking through the Google API docs can't find a way to turn on street labels by default. Any ideas?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744084">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744084">7</a> by Raymond Camden
		posted on 12/14/2012 at 1:55 AM
		</div>
		<div class="comment_text"><p>I'm sure there is a way. Do what I'd do - check the docs. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744083">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744083">8</a> by dmitry
		posted on 2/25/2013 at 8:36 PM
		</div>
		<div class="comment_text"><p>I want to separate concerns and put html for popup window in a template. Is it possible to pass javascript template variable to google maps info window content? I tried code below but my mustache.js template was not rendered. var template = $('#infowindow').html(); var contentHtml = Mustache.to_html(template, data); var infowindow = new google.maps.InfoWindow({<br>		    			content: contentHtml<br>					});</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744089">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744089">9</a> by Raymond Camden
		posted on 2/25/2013 at 8:54 PM
		</div>
		<div class="comment_text"><p>It should be possible. Try doing a console.log on contentHtml. Most likely you broke it there since InfoWindow is just taking the HTML.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744087">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744087">10</a> by denis
		posted on 4/25/2013 at 3:13 AM
		</div>
		<div class="comment_text"><p>I got it!  I created an app like this, but i'd like to use a combobox instead of a checkbox, i'm trying to make this. Maybe in jquery i can resolve this?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744088">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744088">11</a> by Raymond Camden
		posted on 4/25/2013 at 5:30 PM
		</div>
		<div class="comment_text"><p>Sure, it shouldn't be difficult.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744091">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744091">12</a> by Ari
		posted on 5/18/2013 at 5:23 PM
		</div>
		<div class="comment_text"><p>I’m trying to modify your example to be able to use large dynamic lists as opposed to a small static one.</p><p>Could you give me a heads-up as to how I would go about using your example to handle, let’s say 1000 item list instead of 4? Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744090">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744090">13</a> by Raymond Camden
		posted on 5/18/2013 at 6:51 PM
		</div>
		<div class="comment_text"><p>I haven't used a thousand or so, but I do know there is documentation about handling large data sets. I'd recommend going to their docs and looking around for it. If I remember right, there was a way to make the map smart enough to render some items only when you've zoomed in enough - thereby making the map less complex.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744093">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744093">14</a> by Ari
		posted on 5/18/2013 at 7:24 PM
		</div>
		<div class="comment_text"><p>Thanks for the quick response Raymond.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744092">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744092">15</a> by Ashraf ali
		posted on 10/18/2013 at 5:04 PM
		</div>
		<div class="comment_text"><p>Hello Raymond,<br>i want to show some places like hospital,restaurant,shops etc through dropdown (&lt;select&gt;&lt;/select&gt;) where user can select there choice whether they are looking for the defind destinations so what i want to show them the markers when there are the output.</p><p>for eg:if person choose restaurant  in map it shows the all the restaurant within the map with markers.</p><p>i think you can understand me what i am asking for.</p><p>please revert me back ASAP</p><p>thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744094">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744094">16</a> by Raymond Camden
		posted on 10/18/2013 at 5:54 PM
		</div>
		<div class="comment_text"><p>What you want is - pretty much - exactly what my demo does. But instead of checkboxes it is driven by a select field. It should take just a few minutes to modify my demo.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744104">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744104">17</a> by robi
		posted on 10/18/2013 at 6:39 PM
		</div>
		<div class="comment_text"><p>Ashraf,</p><p> Ray is not your servant or slave. Asking him to revert back to you ASAP is incredibly rude. If it was me I would have simply ignored you. Ray... thanks for all you do for helping lots of folks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744102">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744102">18</a> by Balaji
		posted on 10/24/2013 at 4:44 PM
		</div>
		<div class="comment_text"><p>Thanks Ray for the wonderful blog. Really useful. i am using your code as well.Need some help, If i want to write automation - test script i.e - To assert one of the markers displayed correctly on the map for the given lat &amp; lon.</p><p>Is there a way for selenium talk to the DOM and assert the Markers on the map?</p><p>Thanks again in advance<br>Balaji</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744101">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744101">19</a> by Raymond Camden
		posted on 10/24/2013 at 5:19 PM
		</div>
		<div class="comment_text"><p>Hmm, that's a fascinating question. So obviously Google Maps is doing *something* to the DOM, but I don't think it is something you can rely on. What I mean is - they may add the marker with class "gmEpicMarker", and then one day switch to "gmEpicCoolMarker". Your test can't rely on Google to always use the same DOM manipulation to get the job done.</p><p>Therefore - I think the answer is no - you can't - but I'd love to be proven wrong here.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744106">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744106">20</a> by Steve Spittell
		posted on 3/18/2014 at 3:21 PM
		</div>
		<div class="comment_text"><p>Is there a way to have the var data [ ] pull from a xml file ?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744103">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744103">21</a> by Raymond Camden
		posted on 3/18/2014 at 3:53 PM
		</div>
		<div class="comment_text"><p>Yes. Or JSON.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744105">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744105">22</a> by wj
		posted on 3/23/2014 at 10:01 AM
		</div>
		<div class="comment_text"><p>Hi, it is possible to populate the data in the static array (var data) from database?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744107">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744107">23</a> by Raymond Camden
		posted on 3/23/2014 at 3:20 PM
		</div>
		<div class="comment_text"><p>Yes!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744110">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744110">24</a> by wj
		posted on 3/24/2014 at 4:23 PM
		</div>
		<div class="comment_text"><p>Sorry for late reply. I am using php in the javascript to read from database. But the problem is I could not format the code to the form like the var data above. Using the php code in the var data will 'break' the structure. Is there any way to format it? Thanks.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744109">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744109">25</a> by Raymond Camden
		posted on 3/24/2014 at 4:27 PM
		</div>
		<div class="comment_text"><p>You need to output the data in a form that JS can read - JSON. I'm sure PHP has some library (or even built in support) to make that easy.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744108">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744108">26</a> by Anders Stentebjerg
		posted on 3/26/2014 at 5:57 PM
		</div>
		<div class="comment_text"><p>Great read.  [… I know it is old]<br>Would it be possible to combine this with <a href="http://disq.us/url?url=http%3A%2F%2Fjsfiddle.net%2FukW2C%2F3%2F%3AEnpfreCJQ8SEpM-ly98p8gE0-Yg&amp;cuid=3321886" rel="nofollow noopener" title="http://jsfiddle.net/ukW2C/3/">http://jsfiddle.net/ukW2C/3/</a><br>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713744111">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713744111">27</a> by Raymond Camden
		posted on 3/26/2014 at 6:21 PM
		</div>
		<div class="comment_text"><p>Your fiddle demonstrates a 2 column list where you can filter based on a match on any side. Can it be combined? Sure.</p></div>
	</div>
</div>
		