
<div class="comment" id="c_1713738093">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738093">1</a> by Misty
		posted on 1/16/2012 at 11:11 PM
		</div>
		<div class="comment_text"><p>Well, I have only Windows 7 Ultimate and Any Guidence on Phonecap usage so the code to be build can be deployed on any Mobile Device will be nice..</p><p>Please guide Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738095">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738095">2</a> by Raymond Camden
		posted on 1/16/2012 at 11:13 PM
		</div>
		<div class="comment_text"><p>I do PhoneGap development all the time. Before answering though, have you followed their Getting Started guide? It walks you through the entire process.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738088">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738088">3</a> by Misty
		posted on 1/16/2012 at 11:33 PM
		</div>
		<div class="comment_text"><p>No, I have not went to that stuff yet, Can you give a Link for this <br>Thanks</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738089">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738089">4</a> by dave
		posted on 1/17/2012 at 12:17 AM
		</div>
		<div class="comment_text"><p>Misty,</p><p>Google is your friend.. or is should be.<br>Pet peeve alert. Someone on a discussion expects you to go do a google and paste the link.<br>C'mon, search for the getting started link before asking. Just sayin'.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738086">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738086">5</a> by Raymond Camden
		posted on 1/17/2012 at 12:18 AM
		</div>
		<div class="comment_text"><p>I hate to be a jerk about this, but did you go to the PhoneGap web site? The Getting Started guide is listed on the top level nav under Developers. It's also on the home page by "Learn." I want to help - but you really need to do a bit of checking yourself first.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738091">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738091">6</a> by Misty
		posted on 1/17/2012 at 2:44 PM
		</div>
		<div class="comment_text"><p>Thanks @dave and @ray..</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738090">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738090">7</a> by Pete
		posted on 1/17/2012 at 5:49 PM
		</div>
		<div class="comment_text"><p>Misty, this should help:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Flmgtfy.com%2F%3Fq%3Dphonegap%2Bgetting%2Bstarted%3AKFPoxHWsNWQb6PfB2Y5mlrNQZRM&amp;cuid=3321886" rel="nofollow noopener" title="http://lmgtfy.com/?q=phonegap+getting+started">http://lmgtfy.com/?q=phoneg...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738094">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738094">8</a> by Pete
		posted on 1/17/2012 at 5:53 PM
		</div>
		<div class="comment_text"><p>Actually on a serious note though, have you ever thought about doing native Objective-C coding? Or the pros/cons between that and PhoneGap</p><p>I couldn't decide between PhoneGap and Objective-C, and decided that PhoneGap might be a bit limiting with the devices features, it was also a year ago so it was all still a bit new and scary for me.</p><p>But having seen all the awesome stuff you've done I sort of regret my decision.</p><p>It'll be a long while before I'm as good at Objective-C as I am at coding in HTML + JS.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738092">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738092">9</a> by Raymond Camden
		posted on 1/17/2012 at 6:57 PM
		</div>
		<div class="comment_text"><p>I would certainly not say you should regret learning Objective-C. If you know both, you are going to be extremely valuable.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738096">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738096">10</a> by Simon Romanski
		posted on 1/18/2012 at 1:00 AM
		</div>
		<div class="comment_text"><p>Pete, that <a href="http://disq.us/url?url=http%3A%2F%2Flmgtfy.com%3AWr-Wbk71D9HM1GPZM0MbWxwjb70&amp;cuid=3321886" rel="nofollow noopener" title="lmgtfy.com">lmgtfy.com</a> (let me google that for you) link was awesomely appropriate. I've never seen that before... easy one to remember too. Made me chuckle...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738097">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738097">11</a> by Phillip Senn
		posted on 1/19/2012 at 2:16 AM
		</div>
		<div class="comment_text"><p>It's a bit intimidating to publish an app in the Apple app store - I have yet to do it.  We have the developer's license, and have found out that you can publish a BTB app so that it is only available to your customers.  <br>Some people see it as a negative to where you have to get Apple's permission, but you can see it as a positive as well.  They have high standards and aren't going to let just any application on their devices.  So for $99 you have a quality control team.</p><p>I told my son four years ago when he entered college that what he'd be working on hadn't been invented yet.  Guess what he's working on now?  The iPad and XCode.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738098">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738098">12</a> by Pete
		posted on 1/19/2012 at 3:00 AM
		</div>
		<div class="comment_text"><p>It is a pain getting something in the app store... but it is the most relieving feeling when it gets accepted.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713738099">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713738099">13</a> by Henry Cox
		posted on 1/21/2012 at 7:21 AM
		</div>
		<div class="comment_text"><p>Hello,<br>Just wondering if anyone has tried running MAC Lion or Leopard on PC or VM? If so, can you link to resources. <br>Thanks<br>Henry</p></div>
	</div>
</div>
		