
<div class="comment" id="c_1713685657">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685657">1</a> by salvatore fusto
		posted on 9/11/2008 at 5:40 PM
		</div>
		<div class="comment_text"><p>a superXL for me?<br>salvatore</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685668">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685668">2</a> by Katie
		posted on 9/11/2008 at 6:21 PM
		</div>
		<div class="comment_text"><p>humpf , am i the only 5ft coldfuson developer then? I'll wear it as a dress :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685665">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685665">3</a> by Raymond Camden
		posted on 9/11/2008 at 6:22 PM
		</div>
		<div class="comment_text"><p>@katie - while I tend to hog the CF shirts, you wouldn't believe how many tech shirts my kids have. My daughter can easily wear most as a dress. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685671">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685671">4</a> by katie
		posted on 9/11/2008 at 7:05 PM
		</div>
		<div class="comment_text"><p>TBH im abit miffed that Coldfusion 9 is in the pipelines already, I only convinced my boss to let us upgrade to a host with Coldfusion 8 yesterday, im always a step behind!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685670">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685670">5</a> by FOF
		posted on 9/11/2008 at 8:17 PM
		</div>
		<div class="comment_text"><p>Is this really the best design they can come up with???</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.justanaverageyo.com%2Findex.cfm%2F2008%2F9%2F11%2Fcoldfusion-9-shirt%3AUbmhRIXPKsJIUxYWdw25fRR4TZA&amp;cuid=3321886" rel="nofollow noopener" title="http://www.justanaverageyo.com/index.cfm/2008/9/11/coldfusion-9-shirt">http://www.justanaverageyo....</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685675">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685675">6</a> by Dave
		posted on 9/11/2008 at 8:32 PM
		</div>
		<div class="comment_text"><p>Are there any tidbits of information on what's coming in CF9?  New features, changes, etc?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685673">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685673">7</a> by Raymond Camden
		posted on 9/11/2008 at 8:35 PM
		</div>
		<div class="comment_text"><p>Here: <a href="http://disq.us/url?url=http%3A%2F%2Fwww.coldfusionjedi.com%2Findex.cfm%2F2008%2F6%2F18%2FCFUNITED-08-Opening-Keynote%3AAlNxmR_qzwjSqSaE1KgmLAdsp2E&amp;cuid=3321886" rel="nofollow noopener" title="http://www.coldfusionjedi.com/index.cfm/2008/6/18/CFUNITED-08-Opening-Keynote">http://www.coldfusionjedi.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685676">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685676">8</a> by Michael DeJonghe
		posted on 9/11/2008 at 10:58 PM
		</div>
		<div class="comment_text"><p>They should have partnered with Old Spice for their centaur campaign. "I'm two things... a CF programmer and a smart shopper."</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685674">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685674">9</a> by Mary Jo
		posted on 9/13/2008 at 7:08 PM
		</div>
		<div class="comment_text"><p>I can pick up your amazingly big head for 20 dollars? Awesome!</p><p>Hey, they may know developers...but they obviously don't know that women use CF too! :-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685677">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685677">10</a> by Mark Phillips
		posted on 9/15/2008 at 5:36 PM
		</div>
		<div class="comment_text"><p>Ray,  thanks for the shout-out.</p><p>@Michael -I was thinking the same thing: )  I guess this is the year of the Centaur.</p><p>@Mary Jo -we'll be adding a small to our next order of inventory.  If you're interested in getting one, please email me at mark at vertabase dot com.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685678">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685678">11</a> by Mary Jo Sminkey
		posted on 9/15/2008 at 10:51 PM
		</div>
		<div class="comment_text"><p>@Mark - well I was kind of joking, but in seriousness the issue for a lot of us girls is not just size, but the lack of fit. I generally will only wear a Ladies style t-shirt except as a nightshirt (have enough freebie shirts for this use, ha!) I have to envy those girls that can be at a computer all day and keep their sexy figures...I personally need all the help I can get from what I wear! :-) I had to agree with FOF as well, the design doesn't do much for me, if I am going to spread some CF love, it needs to be a shirt that someone other than me will actually be able to get "CF" out of.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685681">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685681">12</a> by Mark Phillips
		posted on 9/17/2008 at 8:15 AM
		</div>
		<div class="comment_text"><p>@Mary Jo -I wanted to stay clear of actually using ColdFusion since its a registered trademark of Adobe's.</p><p>As far as other ideas, would you prefer a logo just in the right hand pocket type of approach?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713685680">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713685680">13</a> by Mark Phillips
		posted on 9/17/2008 at 8:16 AM
		</div>
		<div class="comment_text"><p>^ left side pocket</p></div>
	</div>
</div>
		