
<div class="comment" id="c_1713728366">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713728366">1</a> by SuperAlly
		posted on 12/14/2010 at 1:33 AM
		</div>
		<div class="comment_text"><p>Thanks Ray.<br>Time zones make my head hurt and I missed it!</p></div>
	</div>
</div>
		