
<div class="comment" id="c_1713676681">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676681">1</a> by joel
		posted on 1/30/2008 at 1:53 AM
		</div>
		<div class="comment_text"><p>You can also, of course, save the xml as a separate file and reference it in the style attribute to apply the same styles to multiple charts.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676683">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676683">2</a> by Raymond Camden
		posted on 1/30/2008 at 1:59 AM
		</div>
		<div class="comment_text"><p>Yep - and you could get fancy. You could create an XML block for left aligned - note the differences - and generate the XML on the fly to go back and forth.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676684">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676684">3</a> by Joshua
		posted on 2/26/2008 at 12:04 AM
		</div>
		<div class="comment_text"><p>Hey Ray,</p><p>Where could one find this Chart Editor that you speak of?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676682">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676682">4</a> by Raymond Camden
		posted on 2/26/2008 at 12:06 AM
		</div>
		<div class="comment_text"><p>Under your coldfusion folder, charting, webcharts.bat.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676685">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676685">5</a> by Joshua
		posted on 2/26/2008 at 12:12 AM
		</div>
		<div class="comment_text"><p>Thanks I found it after reading the docs a little more carefully. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676687">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676687">6</a> by jeff
		posted on 2/26/2008 at 3:40 AM
		</div>
		<div class="comment_text"><p>Is this a CF8 only thing?  When I try to pass a string to the style attribute, I get an error: "The system cannot find the file specified".</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713676686">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713676686">7</a> by Raymond Camden
		posted on 2/26/2008 at 3:46 AM
		</div>
		<div class="comment_text"><p>Nope, CF7 added it. Don't forget the PDF reference manual shows the history of tags back to MX.</p></div>
	</div>
</div>
		