
<div class="comment" id="c_1713623244">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623244">1</a> by Jeff
		posted on 12/3/2005 at 6:25 AM
		</div>
		<div class="comment_text"><p>I don't get it in the slightest.</p><p> Is "Beware, I Hunger" a quote from something?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623225">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623225">2</a> by Che
		posted on 12/3/2005 at 7:06 AM
		</div>
		<div class="comment_text"><p>Umm, Yes... its what the "sinister" voice says to the game player during game play. Ray, correct me if I'm wrong...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623242">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623242">3</a> by Raymond Camden
		posted on 12/3/2005 at 8:36 AM
		</div>
		<div class="comment_text"><p>You are right Che.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713623246">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713623246">4</a> by Emmet
		posted on 12/3/2005 at 11:40 PM
		</div>
		<div class="comment_text"><p>If you were an early adopter of the original xbox you might remember the controllers.  They were enourmous.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.penny-arcade.com%2Fcomic%2F2001%2F11%2F28%3AUK7cRPcE5459nJdvWztVf7Ey9lc&amp;cuid=3321886" rel="nofollow noopener" title="http://www.penny-arcade.com/comic/2001/11/28">http://www.penny-arcade.com...</a></p></div>
	</div>
</div>
		