
<div class="comment" id="c_1713660302">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660302">1</a> by Edward T
		posted on 12/15/2006 at 5:41 PM
		</div>
		<div class="comment_text"><p>Swift recovery, Ray!<br>/ejt</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660319">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660319">2</a> by John Barrett
		posted on 12/15/2006 at 5:45 PM
		</div>
		<div class="comment_text"><p>Hi Ray,<br>I wish you a speedy recovery!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660313">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660313">3</a> by Phillip Senn
		posted on 12/15/2006 at 8:15 PM
		</div>
		<div class="comment_text"><p>I've been waiting for Ray to be drugged so I can tell the world:<br>Ray Camden stole one of my ideas!<br>;-)<br>Speedy recovery Ray.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660317">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660317">4</a> by Ben Nadel
		posted on 12/16/2006 at 8:45 AM
		</div>
		<div class="comment_text"><p>Enjoy the down time. Crash on the couch and watch some Lost reruns :) Good luck.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660320">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660320">5</a> by John Farrar
		posted on 12/16/2006 at 9:44 AM
		</div>
		<div class="comment_text"><p>Seriously Ray... hope this doesn't turn into one of your rolling blogs about how some institution just couldn't get it right. We want you to stay active in the picture rather than taking a few months helping the get things right! Seriously hope simple stays simple for you! (And it's OK with me if your not religious, but will make a request on your behalf just the same.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713660323">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713660323">6</a> by Raymond Camden
		posted on 12/16/2006 at 8:24 PM
		</div>
		<div class="comment_text"><p>I'm feeling better today. Just took a pain pill though so I'm getting ready to get loopy. ;) Thanks for the prayers John, it is appreciated.</p></div>
	</div>
</div>
		