
<div class="comment" id="c_1713667717">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667717">1</a> by Andy Matthews
		posted on 6/21/2007 at 8:57 PM
		</div>
		<div class="comment_text"><p>Ray...no examples?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667721">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667721">2</a> by Raymond Camden
		posted on 6/21/2007 at 9:26 PM
		</div>
		<div class="comment_text"><p>Well, there is sample code. YOu mean an online example?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667716">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667716">3</a> by Daniel Budde II
		posted on 6/22/2007 at 3:19 AM
		</div>
		<div class="comment_text"><p>Do you have something you specifically need to know how to do?  Maybe I could give you a hand.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667722">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667722">4</a> by Andy Matthews
		posted on 6/22/2007 at 5:13 PM
		</div>
		<div class="comment_text"><p>Nothing specific...just wondering is all. Ray's usually really good about showing examples, so I was just curious.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667718">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667718">5</a> by Raymond Camden
		posted on 6/22/2007 at 5:22 PM
		</div>
		<div class="comment_text"><p>This was a 100% guest post, so I didn't do a demo. Sorry. :) Of course, you can always try this yourself. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667714">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667714">6</a> by Daniel Budde II
		posted on 6/22/2007 at 7:12 PM
		</div>
		<div class="comment_text"><p>I should have a new project up on RIAForge in a couple of weeks that will have an example of this.  When I do and as long as I remember to come back and comment it, I will supply a link and the name of the project.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667719">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667719">7</a> by Daniel Budde
		posted on 8/10/2007 at 11:21 PM
		</div>
		<div class="comment_text"><p>A quick clarification.</p><p>The classes actually are:</p><p>yuimenu - any yui menu div<br>yuimenuitem - any yui menu list-item<br>yuimenubar - Only a yui horizontal menu div<br>yuimenubaritem - Only a yui menu list-item under a horizontal menu bar</p><p>The other two classes were accurate.  My solution worked under beta, but doesn't appear to work completely on CF8 official release.  Like I said, when I finish my project, hopefully I will post it back here.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667723">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667723">8</a> by Chris Walker
		posted on 3/28/2008 at 5:13 PM
		</div>
		<div class="comment_text"><p>Ray,&lt;br&gt;<br>&lt;br&gt;<br>CFMenu is great.  But when you combine it with another flex function like cfgrid, the menu drops down behind the grid.  Is there anyway to fix this? I've searched far and wide for the solution but can't find it.&lt;br&gt; <br>&lt;br&gt;<br>I might need to drop cfmenu in our new Flex-y application.  Say it ain't so Shane, 'er Ray, say it ain't so!&lt;br&gt;<br>&lt;br&gt;<br>Chris</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667715">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667715">9</a> by Raymond Camden
		posted on 3/28/2008 at 5:38 PM
		</div>
		<div class="comment_text"><p>You got me on that one. Can you try changing the z-index?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667720">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667720">10</a> by Ritesh Sanan
		posted on 6/6/2008 at 5:12 PM
		</div>
		<div class="comment_text"><p>So what's the class to change the hover BG color for the Li?<br>Can some one point it out ...I've tried a few combinations ..but can't hit the nail</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667711">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667711">11</a> by Christopher Walker
		posted on 6/6/2008 at 5:48 PM
		</div>
		<div class="comment_text"><p>I found the answer to my z-index issue 2 posts back.  Check it out here.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fwww.shareddynamics.com%2Findex.cfm%2F2008%2F3%2F28%2FTrouble-Getting-CFMENU-to-Open-Over-Flash-CFFORM-zindex%3ASZqAq0Gj3E00ohCrxh4hB7ytxrY&amp;cuid=3321886" rel="nofollow noopener" title="http://www.shareddynamics.com/index.cfm/2008/3/28/Trouble-Getting-CFMENU-to-Open-Over-Flash-CFFORM-zindex">http://www.shareddynamics.c...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667713">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667713">12</a> by Webster Maposa
		posted on 7/1/2009 at 2:43 PM
		</div>
		<div class="comment_text"><p>Thanks Ray. Your code helped me a lot to apply the CSS on CFMenu. My biggest problem is, it looks like there is compatibility issues for your code with IE7. I do not want the submenuindicator to be visible but this code only works on IE6 but does not on work on IE7 and Firefox 3.0.11. Does anyone have a suggestion on this one?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713667730">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713667730">13</a> by Jon Cavanaugh
		posted on 9/30/2011 at 8:18 PM
		</div>
		<div class="comment_text"><p>Thank you Ray for this post! With a bit of reading and testing I fixed a z-index issue by adding my own CSS below the closing head tag.</p></div>
	</div>
</div>
		