
<div class="comment" id="c_1713675388">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675388">1</a> by Kyle Dodge
		posted on 12/10/2007 at 10:41 PM
		</div>
		<div class="comment_text"><p>Nice find Ray! Could be a good alternative to cfchart for me</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675379">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675379">2</a> by Steve Walker
		posted on 12/10/2007 at 10:53 PM
		</div>
		<div class="comment_text"><p>Although I haven't done it yet, CF8 allows flash charts to be embedded into a pdf (cfdocument).</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675391">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675391">3</a> by Raymond Camden
		posted on 12/10/2007 at 10:58 PM
		</div>
		<div class="comment_text"><p>I believe that is a document mistake. I remember trying it during my blog posts on CF8 PDF stuff and it did not work. (Again, I "believe". Call it 90% certain.)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675387">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675387">4</a> by Emmet
		posted on 12/10/2007 at 11:12 PM
		</div>
		<div class="comment_text"><p>A good reason NOT to use cfchart indeed.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675382">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675382">5</a> by Raul Riera
		posted on 12/11/2007 at 12:18 AM
		</div>
		<div class="comment_text"><p>From your 3 examples I can tell that Google's chart does indeed apply X coordinate labels to all bars, is this because the width is larger, or in fact is better than CF by NOT making those labels disappear?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675390">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675390">6</a> by Dan Russell
		posted on 12/11/2007 at 12:22 AM
		</div>
		<div class="comment_text"><p>This thing is great!</p><p>Here's my meme-friendly attempt at it:  <a href="http://disq.us/url?url=http%3A%2F%2Ftinyurl.com%2F2j227d%3AeEZJwnBTPPcge0jrSDwgTEGOmO4&amp;cuid=3321886" rel="nofollow noopener" title="http://tinyurl.com/2j227d">http://tinyurl.com/2j227d</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675385">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675385">7</a> by Raymond Camden
		posted on 12/11/2007 at 12:24 AM
		</div>
		<div class="comment_text"><p>Raul, I'm a bit confused by your q. Are you asking how it applied the labels for the xaxis? I set them. I also set the bar width. Why does CF 'hide' labels? It does the best it can I guess with the width. I set the width of my chart until it was wide enough to hold it all. The Google charts definitely require you to work with them a bit more.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675392">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675392">8</a> by Raul Riera
		posted on 12/11/2007 at 12:32 AM
		</div>
		<div class="comment_text"><p>Yeah, what I meant was, since CF tries to fit it (if it doesnt  succeed it will hide it) will google do this as well? or will they fit in the label doing whatever it takes? (because when the charts are totally dynamic, manually setting the width and height is not that good an idea (I think)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675389">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675389">9</a> by Raymond Camden
		posted on 12/11/2007 at 12:40 AM
		</div>
		<div class="comment_text"><p>No, if things are tight, text will overwrite each other. I had to play with the total width and bar width a bit. Then again, I'd rather have it all show up then some randomly drop off. I've never liked that about cfchart.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713675400">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713675400">10</a> by Justin Carter
		posted on 12/11/2007 at 3:20 AM
		</div>
		<div class="comment_text"><p>I've been tinkering with the Google Chart API for a Vista gadget that I've made for tracking download quota usage for my ISP... It seems to work great, although it doesn't include as much detail as I'd like, for example values next to each data item on the chart.</p><p>Here's a sample screeny of how I'm currently using it:<br><a href="http://disq.us/url?url=http%3A%2F%2Fimg142.imageshack.us%2Fimg142%2F8517%2Fnephewgraph2cv3.jpg%3AbGtctVEDoyHfYkzKZUkN_KcxXNQ&amp;cuid=3321886" rel="nofollow noopener" title="http://img142.imageshack.us/img142/8517/nephewgraph2cv3.jpg">http://img142.imageshack.us...</a></p><p>Great for apps where ColdFusion can't be used :)</p></div>
	</div>
</div>
		