
<div class="comment" id="c_1714083981">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083981">1</a> by Šime Vidas
		posted on 9/19/2014 at 4:28 AM
		</div>
		<div class="comment_text"><p>Interesting how in Firefox/Android, the list shows up immediately (when clicking on the field) and is visible at all times (as long as the field is focused). Even when scrolling the page (swiping up/down), the list is hidden during the scroll and then redrawn immediately after the scroll ends. I think I like Firefox's behavior better.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714083979">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714083979">2</a> by Raymond Camden
		posted on 9/19/2014 at 6:05 AM
		</div>
		<div class="comment_text"><p>Dang, I'm ashamed to say I didn't even think about Firefox - thanks for reporting on that.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3254066379">
	<div>
		<img src="https://disqus.com/api/users/avatars/chiptoll.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3254066379">3</a> by Chip Toll
		posted on 4/13/2017 at 10:59 AM
		</div>
		<div class="comment_text"><p>Are there any iPad browsers that currently support a datalist? The caniuse page seems to indicate the only option that works are Android and Android Chrome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_3254087982">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_3254087982">4</a> (In reply to <a href="#c_3254066379">#3</a>) by Raymond Camden
		posted on 4/13/2017 at 11:24 AM
		</div>
		<div class="comment_text"><p>If CanIUse says it, it's typically right. :\</p></div>
	</div>
</div>
		