
<div class="comment" id="c_1713658178">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658178">1</a> by todd sharp
		posted on 10/12/2006 at 6:09 PM
		</div>
		<div class="comment_text"><p>Nov 1 works for me.  Even though these are more geared towards beginners, I feel like I pick up something new every time.</p><p>P.S.  I found a site the other day that let me walk right in with a foo' or '1' = '1 password.  Absolutely horrible.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658189">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658189">2</a> by yanni
		posted on 10/12/2006 at 6:14 PM
		</div>
		<div class="comment_text"><p>To be quite honest, when I saw the word, "JUG", jedi user group wasn't the first thought that crossed my mind ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658191">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658191">3</a> by Gary Funk
		posted on 10/13/2006 at 5:35 AM
		</div>
		<div class="comment_text"><p>I'll vote yes for both meetings. I came in late last time.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658197">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658197">4</a> by DLL
		posted on 10/13/2006 at 12:57 PM
		</div>
		<div class="comment_text"><p>I missed the first meeting, and since I live in the UK, I was planning to listen to the recording, so I vote for a re-run.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658196">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658196">5</a> by Phillip Senn
		posted on 10/17/2006 at 10:09 PM
		</div>
		<div class="comment_text"><p>I am RSVPing.  I came in late as well.</p><p>Q: Does it make sense to do the following in Application.cfc:</p><p>Since there is no init function being called, why not call it yourself?<br>&lt;cfcomponent output="false"&gt;<br>&lt;cfset Init('myApplicationName')&gt;</p><p>&lt;cffunction name="Init" output=False returntype="void"&gt;<br>&lt;cfargument name="AppName"&gt;<br>&lt;cfset <a href="http://disq.us/url?url=http%3A%2F%2Fthis.name%3AEm-S9q6F4e-8KUeib7Eeo3ysjlY&amp;cuid=3321886" rel="nofollow noopener" title="this.name">this.name</a> = arguments.AppName&gt;<br>...<br>&lt;/cffunction&gt;<br>...<br>&lt;/cfcomponent&gt;</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658195">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658195">6</a> by Raymond Camden
		posted on 10/17/2006 at 11:08 PM
		</div>
		<div class="comment_text"><p>I don't yet have 5 RSVPs for tomorrow - so I'm on the edge. I have 3 it seems...</p><p>Ok.. I'll do it - but I'm going to have to have a hard cut off at 6, ie, I may not stick around for questions as much as I normally would. That ok?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713658198">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713658198">7</a> by Dan O&amp;aposKeefe
		posted on 10/18/2006 at 9:21 PM
		</div>
		<div class="comment_text"><p>RSVP for one</p></div>
	</div>
</div>
		