
<div class="comment" id="c_4922091200">
	<div>
		<img src="https://disqus.com/api/users/avatars/danskaggs.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4922091200">1</a> by Dan Skaggs
		posted on 5/21/2020 at 12:37 PM
		</div>
		<div class="comment_text"><p>I recently went through the same thing and have been really enjoying the development experience with WSL 2 and VS Code remote editing. The one thing I haven't figure out yet is how to back up those files in the WSL file system. Most of the work I do in there is attached to Git repos, but not everything. At this point I've not been able to find a good way to backup that stuff. I think I'm going to try to install Duplicati inside the Linux distro (I use it for backup for all my other machines) and see if that works. Is that something you've looked into at all?</p></div>
	</div>
</div>
		
<div class="comment" id="c_4922136231">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4922136231">2</a> (In reply to <a href="#c_4922091200">#1</a>) by Raymond Camden
		posted on 5/21/2020 at 1:20 PM
		</div>
		<div class="comment_text"><p>Nope. My plan is to use GitHub for everything *except* a folder I called testingzone where I put misc crap I'm ok with losing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4984916005">
	<div>
		<img src="https://disqus.com/api/users/avatars/bobclingan.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4984916005">3</a> by Bob Clingan
		posted on 7/9/2020 at 1:33 AM
		</div>
		<div class="comment_text"><p>I'm creating a new Angular app using the terminal (set to use wsl) inside of Visual Code. Its sooooo slow... its currently pointed to /mnt/c/...</p><p>Ray - somewhere I feel like I read you made a comment related to this being slow and alternative, but I can't recall where I saw it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4984921566">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4984921566">4</a> (In reply to <a href="#c_4984916005">#3</a>) by Raymond Camden
		posted on 7/9/2020 at 1:39 AM
		</div>
		<div class="comment_text"><p>Yep - stop using /mnt and stick to the Ubuntu file system only.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4987200348">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4987200348">5</a> (In reply to <a href="#c_4984916005">#3</a>) by Raymond Camden
		posted on 7/10/2020 at 8:31 PM
		</div>
		<div class="comment_text"><p>query - did you recently post a reply to my last comment and delete it? I got the email, but don't see it.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4987208925">
	<div>
		<img src="https://disqus.com/api/users/avatars/bobclingan.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4987208925">6</a> (In reply to <a href="#c_4987200348">#5</a>) by Bob Clingan
		posted on 7/10/2020 at 8:38 PM
		</div>
		<div class="comment_text"><p>Yes- I started to ask another question and realized the answer was in the article, duh!</p></div>
	</div>
</div>
		
<div class="comment" id="c_4987236684">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4987236684">7</a> (In reply to <a href="#c_4987208925">#6</a>) by Raymond Camden
		posted on 7/10/2020 at 9:01 PM
		</div>
		<div class="comment_text"><p>Heh no worries!</p></div>
	</div>
</div>
		