
<div class="comment" id="c_1714081855">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081855">1</a> by Sean Coyne
		posted on 2/21/2014 at 9:10 PM
		</div>
		<div class="comment_text"><p>Responses are logged to console so open it to see results...</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fjsfiddle.net%2Fseancoyne%2F5NcDq%2F1%2F%3ALoLoUmqbBZvponidOXThsq0PrWo&amp;cuid=3321886" rel="nofollow noopener" title="http://jsfiddle.net/seancoyne/5NcDq/1/">http://jsfiddle.net/seancoy...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081868">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081868">2</a> by Raymond Camden
		posted on 2/21/2014 at 9:13 PM
		</div>
		<div class="comment_text"><p>Nice. To be picky, I don't like the outputs in the rollDice func. It should be returning results to the caller instead.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081869">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081869">3</a> by Sean Coyne
		posted on 2/21/2014 at 9:13 PM
		</div>
		<div class="comment_text"><p>Yeah, not exactly "production ready" code.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081866">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081866">4</a> by Raymond Camden
		posted on 2/21/2014 at 9:14 PM
		</div>
		<div class="comment_text"><p>Btw - no offense made. In general, I like to nit pick the submissions. Totally arbitrary of course. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081873">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081873">5</a> by Sean Coyne
		posted on 2/21/2014 at 9:15 PM
		</div>
		<div class="comment_text"><p>None taken at all.  Was fun to write.  Hadn't generated a random number, as simple as it is, in JS before.  Just never had a need I guess.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081876">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081876">6</a> by Danny Scott
		posted on 2/21/2014 at 9:28 PM
		</div>
		<div class="comment_text"><p>Super quick and dirty<br><a href="https://disq.us/url?url=https%3A%2F%2Fgist.github.com%2Fdannyrscott%2F9137416%3ApANeCilzlKlBJUdDalgHY9tvIkQ&amp;cuid=3321886" rel="nofollow noopener" title="https://gist.github.com/dannyrscott/9137416">https://gist.github.com/dan...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081870">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081870">7</a> by Raymond Camden
		posted on 2/21/2014 at 9:34 PM
		</div>
		<div class="comment_text"><p>Nice - any reason you didn't use JSBin? (I ask because I keep going back and forth on whether I like them. I find them awkward at times.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081879">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081879">8</a> by Raymond Camden
		posted on 2/21/2014 at 9:35 PM
		</div>
		<div class="comment_text"><p>Oh - I see you called it Node Roller - so the assumption was back end perhaps?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081878">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081878">9</a> by Danny Scott
		posted on 2/21/2014 at 9:38 PM
		</div>
		<div class="comment_text"><p>Yeah, quick and dirty so I just went with the back-end.</p><p>I'm in the same boat as you when it comes to JSBin...cool mostly but akward</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081881">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081881">10</a> by Michael Schmidt
		posted on 2/21/2014 at 10:59 PM
		</div>
		<div class="comment_text"><p>Here is my attempt it is very ugly and doesn't handle a case of the minimum number of sides a dice can have i assumed that number of sides and number of dice had to be more then zero</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081852">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081852">11</a> by Michael Schmidt
		posted on 2/21/2014 at 10:59 PM
		</div>
		<div class="comment_text"><p>I forgot the link <br><a href="http://disq.us/url?url=http%3A%2F%2Fjsbin.com%2Fmofuqina%2F9%2Fedit%3A5YzfIAMDqJju_vmKenkt0qz0MoM&amp;cuid=3321886" rel="nofollow noopener" title="http://jsbin.com/mofuqina/9/edit">http://jsbin.com/mofuqina/9...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081850">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081850">12</a> by Sean Walsh
		posted on 2/22/2014 at 12:42 AM
		</div>
		<div class="comment_text"><p>Quick and dirty in Groovy: <a href="https://disq.us/url?url=https%3A%2F%2Fgist.github.com%2Fs992%2F9141872%3AIexsW-jOGATbWjj2lsufwy4ZO0E&amp;cuid=3321886" rel="nofollow noopener" title="https://gist.github.com/s992/9141872">https://gist.github.com/s99...</a></p><p>I wasn't sure if a roll result could be negative (e.g. 1d6-20), so I just let it happen.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081857">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081857">13</a> by Raymond Camden
		posted on 2/22/2014 at 12:58 AM
		</div>
		<div class="comment_text"><p>Fascinating. I learned Groovy years ago, but haven't used it - I forget how nice it is.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081853">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081853">14</a> by Sean Walsh
		posted on 2/22/2014 at 1:17 AM
		</div>
		<div class="comment_text"><p>I'm still very much in the early stages of learning Groovy (read: that code could probably be way better), but it's been a blast so far! Really fun language to code in.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081854">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081854">15</a> by Jared
		posted on 2/22/2014 at 3:13 AM
		</div>
		<div class="comment_text"><p>Some regular expression fun with JavaScript. I bet there are some edge cases it misses, but it works pretty well.</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fjsbin.com%2Fbogolewa%2F5%2Fedit%3Ax8H7ljQgSTx2uSc0hgsfmEXPCks&amp;cuid=3321886" rel="nofollow noopener" title="http://jsbin.com/bogolewa/5/edit">http://jsbin.com/bogolewa/5...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_1714081856">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1714081856">16</a> by AXL
		posted on 2/22/2014 at 6:52 PM
		</div>
		<div class="comment_text"><p><a href="http://disq.us/url?url=http%3A%2F%2Fpastebin.com%2FKmwb3dMZ%3AVLgrm7uYS51ruVsp0BZj16USZd4&amp;cuid=3321886" rel="nofollow noopener" title="http://pastebin.com/Kmwb3dMZ">http://pastebin.com/Kmwb3dMZ</a></p><p>Can't wait for the warm weather ^^;</p></div>
	</div>
</div>
		