
<div class="comment" id="c_1713727839">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727839">1</a> by RogerTheGeek
		posted on 11/24/2010 at 5:11 AM
		</div>
		<div class="comment_text"><p>Who could possibly miss that line up? I'll start now figuring out how to convert CST to EST. I wonder if anything serious will be talked about or whether y'all will talk about video games and SciFi the whole time. Actually, that doesn't sound too bad. Either way, I'll be there if possible.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727845">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727845">2</a> by Mark Mandel
		posted on 11/24/2010 at 8:34 AM
		</div>
		<div class="comment_text"><p>For those not in the US:<br><a href="http://disq.us/url?url=http%3A%2F%2Fpermatime.com%2FCST6CDT%2F2010-12-08%2F11%3A00%3ARTNIGzLl-aKLIvsSRW2Im-hb94U&amp;cuid=3321886" rel="nofollow noopener" title="http://permatime.com/CST6CDT/2010-12-08/11:00">http://permatime.com/CST6CD...</a></p><p>Should help with the time conversion a lot.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727837">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727837">3</a> by Craig M. Rosenblum
		posted on 11/24/2010 at 6:55 PM
		</div>
		<div class="comment_text"><p>Added to my google calendar, and I am ready for some holiday uber aweness...</p><p>cf 4 life...</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727834">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727834">4</a> by Raymond Camden
		posted on 11/24/2010 at 8:51 PM
		</div>
		<div class="comment_text"><p>Added to the list:<br>Rob Brooks-Bilson<br>Brian Kotek</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727838">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727838">5</a> by Tim Cunningham
		posted on 11/24/2010 at 9:30 PM
		</div>
		<div class="comment_text"><p>Ray,</p><p>Two things: <br>1. Can we submit questions prior to the panel?<br>2. Will the questions be somewhat moderated?</p><p>I can imagine if you have a lot of attendees and no preset topic, getting anything answered in any organized manner may be the hardest part of the experience.</p><p>Just curious.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727841">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727841">6</a> by Raymond Camden
		posted on 11/24/2010 at 10:13 PM
		</div>
		<div class="comment_text"><p>And now: Andy Mathews</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727842">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727842">7</a> by Raymond Camden
		posted on 11/24/2010 at 10:35 PM
		</div>
		<div class="comment_text"><p>And now: Andy Allan</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727840">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727840">8</a> by Tom Jenkins
		posted on 11/25/2010 at 2:06 AM
		</div>
		<div class="comment_text"><p>Awesome line up Ray :D</p><p>... but not quite as awesome as Robocop on a freakin unicorn!!!!!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713727843">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713727843">9</a> by Raymond Camden
		posted on 11/25/2010 at 4:33 AM
		</div>
		<div class="comment_text"><p>@Tim: I'd rather you just hold on to em for now. Yes, we will be moderating.</p></div>
	</div>
</div>
		