
<div class="comment" id="c_4430689871">
	<div>
		<img src="https://disqus.com/api/users/avatars/nathanstrutz.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4430689871">1</a> by Nathan Strutz
		posted on 4/20/2019 at 1:13 AM
		</div>
		<div class="comment_text"><p>I started playing with the embedded editor. It's pretty good, snappy updates, fun to toy around with, even on this chromebook. Nice!</p></div>
	</div>
</div>
		
<div class="comment" id="c_4478211540">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4478211540">2</a> by Amr Essam
		posted on 5/27/2019 at 3:09 AM
		</div>
		<div class="comment_text"><p>Hi Raymond, this is Amr. I created vgauge. Thank you so much for including it in your blog. :)</p></div>
	</div>
</div>
		
<div class="comment" id="c_4478644773">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4478644773">3</a> (In reply to <a href="#c_4478211540">#2</a>) by Raymond Camden
		posted on 5/27/2019 at 1:59 PM
		</div>
		<div class="comment_text"><p>You are most welcome.</p></div>
	</div>
</div>
		
<div class="comment" id="c_4495100446">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4495100446">4</a> (In reply to <a href="#c_4478644773">#3</a>) by Amr Essam
		posted on 6/9/2019 at 6:17 AM
		</div>
		<div class="comment_text"><p>I've taken your feedback into account, and I've created support for script tag include.<br>Please take a look :)<br>[here](<a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Famroessam%2Fvgauge%29%3ASNeRl_6buHrst4yYfT_6J-oOXno&amp;cuid=3321886" rel="nofollow noopener" title="https://github.com/amroessam/vgauge)">https://github.com/amroessa...</a> and<br>[here](<a href="https://disq.us/url?url=https%3A%2F%2Fcodesandbox.io%2Fs%2Fvgauge-browser-include-32hxf%29%3AC5TChi8iMLPhByfc01-r72A84qM&amp;cuid=3321886" rel="nofollow noopener" title="https://codesandbox.io/s/vgauge-browser-include-32hxf)">https://codesandbox.io/s/vg...</a></p></div>
	</div>
</div>
		
<div class="comment" id="c_4495391993">
	<div>
		<img src="https://disqus.com/api/users/avatars/cfjedimaster.jpg" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_4495391993">5</a> (In reply to <a href="#c_4495100446">#4</a>) by Raymond Camden
		posted on 6/9/2019 at 2:50 PM
		</div>
		<div class="comment_text"><p>Very nice - thank you for thinking of those users who want the simpler route!</p></div>
	</div>
</div>
		