
<div class="comment" id="c_1713737914">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737914">1</a> by Mike
		posted on 1/3/2012 at 9:29 PM
		</div>
		<div class="comment_text"><p>10 bucks! that's a deal killer sorry :)  If only SF was not 500 miles away.. any chance it will come to LA any time soon?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737916">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737916">2</a> by Raymond Camden
		posted on 1/3/2012 at 9:34 PM
		</div>
		<div class="comment_text"><p>Well, it is a user group thing, so if there is a LA UG, and you guys want me, and my boss approves, I can go there too.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713737915">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713737915">3</a> by Raymond Camden
		posted on 1/5/2012 at 7:13 PM
		</div>
		<div class="comment_text"><p>I will NOT be speaking on PhoneGap! Sorry folks. It's jQuery Mobile. Here's more info:</p><p><a href="http://disq.us/url?url=http%3A%2F%2Fmobiletabletpublishing.eventbrite.com%3A7eV3pcT0CV295ndpktwn5TOX4Jw&amp;cuid=3321886" rel="nofollow noopener" title="http://mobiletabletpublishing.eventbrite.com">http://mobiletabletpublishi...</a></p></div>
	</div>
</div>
		