
<div class="comment" id="c_1713677181">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677181">1</a> by chad
		posted on 2/20/2008 at 7:19 AM
		</div>
		<div class="comment_text"><p>Way to go Mike!</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677199">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677199">2</a> by Mike Benner
		posted on 2/20/2008 at 7:14 PM
		</div>
		<div class="comment_text"><p>Thanks, it is amazing what happens when you stop eating junk (it was very tough to throw out those Girl Scout Cookies that just arrived) at the desk while you are working and actually force yourself to go to the gym.</p><p>Ray, thanks for this.  It was the motivation I needed and I feel better today than I have in a long time.</p></div>
	</div>
</div>
		