
<div class="comment" id="c_1713677196">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677196">1</a> by Steve &amp;aposCutter&amp;apos Blades
		posted on 2/20/2008 at 2:35 AM
		</div>
		<div class="comment_text"><p>That pesky Emmet guy, he's always finding something....;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713677182">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713677182">2</a> by Emmet
		posted on 2/20/2008 at 9:05 PM
		</div>
		<div class="comment_text"><p>I thought i would win an award or something.</p></div>
	</div>
</div>
		