
<div class="comment" id="c_1713742901">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742901">1</a> by Simon MacDonald
		posted on 9/13/2012 at 7:39 AM
		</div>
		<div class="comment_text"><p>Glad you could re-purpose my post for your site. Seriously folks we want to help you but you make it hard sometimes.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742890">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742890">2</a> by Brian W.
		posted on 9/13/2012 at 7:50 PM
		</div>
		<div class="comment_text"><p>Great post guys - but no mention of Firebug/Console Ray? I know that you hate it when people ask Ajax based questions without telling you what console is saying. ;-)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713742904">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713742904">3</a> by Raymond Camden
		posted on 9/13/2012 at 8:08 PM
		</div>
		<div class="comment_text"><p>To me, that falls within the 'Provide Details' part above. And it also falls into the general lack of understanding that a lot of people have concerning JavaScript and Web Development. Which then leads me to the my debugging JS/Web talk I've given a few times now. :)</p></div>
	</div>
</div>
		