
<div class="comment" id="c_1713615317">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615317">1</a> by Daniel Dura
		posted on 1/22/2004 at 6:26 AM
		</div>
		<div class="comment_text"><p>Nice solution!</p><p>But even more important, where did your wife get the calandar... sounds like a lot of fun.</p></div>
	</div>
</div>
		