
<div class="comment" id="c_1713615592">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615592">1</a> by Nathan Dintenfass
		posted on 4/23/2004 at 3:57 AM
		</div>
		<div class="comment_text"><p>What would the duration of the contract work be?  Full time only?</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615594">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615594">2</a> by Raymond Camden
		posted on 4/23/2004 at 3:37 PM
		</div>
		<div class="comment_text"><p>I believe it is full time only - but I'm not 100% sure. Ping the email address as I said in the post. ;)</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615595">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615595">3</a> by Marcos Placoná
		posted on 4/23/2004 at 7:07 PM
		</div>
		<div class="comment_text"><p>Is it a job inside the enterprise? Coukd I work at home remotely?</p><p>Regards,</p><p>Marcos Placoná</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615593">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615593">4</a> by Raymond Camden
		posted on 4/23/2004 at 7:41 PM
		</div>
		<div class="comment_text"><p>Please post to the email address.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615598">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615598">5</a> by Ian Sheridan
		posted on 4/24/2004 at 3:22 AM
		</div>
		<div class="comment_text"><p>heh I did the challenge because I'm strange</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615596">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615596">6</a> by Nathan Dintenfass
		posted on 4/24/2004 at 4:07 AM
		</div>
		<div class="comment_text"><p>Heh, glad I'm not the only one ;)</p><p>I'm a sucker for that kind of thing.</p></div>
	</div>
</div>
		
<div class="comment" id="c_1713615599">
	<div>
		<img src="//a.disquscdn.com/1611874952/images/noavatar32.png" class="comment_author_profile_pic">
	</div>
	<div>
		<div class="comment_header">
		Comment <a href="#c_1713615599">7</a> by Ian Sheridan
		posted on 4/24/2004 at 4:23 AM
		</div>
		<div class="comment_text"><p>well I finished it but it's a little slow I have to speed it up. I used a funky technique to do it but I don't what to mess up the challenge for other freaks like me.</p></div>
	</div>
</div>
		